### ISSUE TITLE
Finding offsets in Unity games with Metadata v22

### ISSUE THREAD

**Issue by evildog1** [Perfare/Il2CppDumper#1]
Most games with metadata v22 no longer have unk offsets (R0, and R1) and auto mode does not work on obfuscated games
Can you explain where can i find another offsets?

**Comment by Perfare** [comment]
I don't know what the 'obfuscated' is
If possible, please upload the file

**Comment by evildog1** [comment]
Obfuscated means they have removed all strings from the .so file which makes us harder to find il2cpp::vm::MetadataCache::Register but i already found it using hex searching.

Unfortinately there are no unk offsets, and auto mode didn't work either
![image](https://cloud.githubusercontent.com/assets/8687585/21850499/282389aa-d80b-11e6-8c6e-6baf0e3ca245.png)

Here is the file http://usersdownload.com/?op=upload_result&st=OK&fn=tvuo406mxtd4

**Comment by Perfare** [comment]
R0=R12 + R2 = 0xFFFFF334 + _GLOBAL_OFFSET_TABLE_
R1 + R2 = 0x22B60 + _GLOBAL_OFFSET_TABLE_, This is a pointer to the value of R1
I submit the new code should be able to work in some obfuscated games
In addition, the file you uploaded seems to be different from your screenshot, new code no work in this files

**Comment by evildog1** [comment]
Oh thanks. I just lack of ARM knowledge
It seems that you look in another instruction. Can you tell me where should i find offstes manually?

In this file, I just search hex 18 30 9F E5 02 10 91 E7 and I will be able to find sub_14675E0

**Comment by Perfare** [comment]
I've told you how to calculate the offstes
If you don't understand, you can try right click on the loc_146760C- Create function

**Comment by evildog1** [comment]
Sorry, i'm not good in math

**Comment by Hamzahacker** [comment]
Obfuscated means they have removed all strings from the .so file which makes us harder to find il2cpp::vm::MetadataCache::Register but i already found it using hex searching.

Unfortinately there are no unk offsets, and auto mode didn't work
image

Here is the file http://usersdownload.com/?op=upload_result&st=OK&fn=tvuo406mxtd4

how you find it using hex searching

**Comment by Hamzahacker** [comment]
il2cpp::vm::MetadataCache::Register how to find this function using hex searc plz answer and any other trick
