### ISSUE TITLE
Metadata file supplied is not a supported version[16]

### ISSUE THREAD

**Issue by ada1016** [Perfare/Il2CppDumper#10]
Downloaded Il2CppDumper v0.4 @ http://pan.baidu.com/s/1bpKQ5Uv#list/path=%2F

The data I am trying to get a hand with 
https://drive.google.com/file/d/0B5w-PkG-Uyi7eVN1ZXJsQWxBNTA/view?usp=sharing

I try to run with these metadata and binary (from iOS)

Metadata file supplied is not a supported version[16]
at Il2CppDumper.Program.Main(String[] args)

But I thought 16 is supported ?

1
--
if (version != 16 && version != 20 && version != 21 && version != 22 && version != 23)
  | throw new Exception($"ERROR: Metadata file supplied is not a supported version[{version}].");

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper/releases

**Comment by ada1016** [comment]
thanks, I am sorry for this silly question. I tried to use the latest.  (Il2CppDumper-v1.0.13) on https://drive.google.com/file/d/0B5w-PkG-Uyi7eVN1ZXJsQWxBNTA/view?usp=sharing

I got another error

ERROR: Unable to process file automatically, try to use manual mode.
  at Il2CppDumper.Program.Main(String[] args] in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:;line 39

The binary I attach is a Unity project on iOS..

**Comment by Perfare** [comment]
use manual mode, #7 #9

**Comment by ada1016** [comment]
Perfare, thank you. i followed the suggestion, also google some more alternative, but still failed to find the offset,, can you please help me understand where I missed?.
in this binary, the InitFunc_1 didn't really say anything so I folllowed to InitFunc_1_0 & sub_100CBEC68, but they does not seem to be the right unk address...


__text:0000000100CBEC68 ; =============== S U B R O U T I N E =======================================
__text:0000000100CBEC68
__text:0000000100CBEC68
__text:0000000100CBEC68 sub_100CBEC68                           ; DATA XREF: InitFunc_1_0+10o
__text:0000000100CBEC68                 ADRP            X0, #unk_101FF4C80@PAGE
__text:0000000100CBEC6C                 ADD             X0, X0, #unk_101FF4C80@PAGEOFF
__text:0000000100CBEC70                 ADRP            X1, #dword_101F51EB8@PAGE
__text:0000000100CBEC74                 ADD             X1, X1, #dword_101F51EB8@PAGEOFF
__text:0000000100CBEC78                 B               sub_100CBEC7C
__text:0000000100CBEC78 ; End of function sub_100CBEC68
__text:0000000100CBEC78
__text:0000000100CBEC7C
__text:0000000100CBEC7C ; =============== S U B R O U T I N E =======================================
__text:0000000100CBEC7C
__text:0000000100CBEC7C ; Attributes: thunk
__text:0000000100CBEC7C
__text:0000000100CBEC7C sub_100CBEC7C                           ; CODE XREF: sub_100CBEC68+10j
__text:0000000100CBEC7C                 B               sub_101AC3D88
__text:0000000100CBEC7C ; End of function sub_100CBEC7C
__text:0000000100CBEC7C
__text:0000000100CBEC80
__text:0000000100CBEC80 ; =============== S U B R O U T I N E =======================================
__text:0000000100CBEC80
__text:0000000100CBEC80
__text:0000000100CBEC80 InitFunc_1_0                            ; CODE XREF: InitFunc_1j
__text:0000000100CBEC80                 MOV             X2, #0
__text:0000000100CBEC84                 MOV             W3, #0
__text:0000000100CBEC88                 ADRP            X0, #unk_1021A05F2@PAGE
__text:0000000100CBEC8C                 ADD             X0, X0, #unk_1021A05F2@PAGEOFF
__text:0000000100CBEC90                 ADR             X1, sub_100CBEC68
__text:0000000100CBEC94                 NOP
__text:0000000100CBEC98                 B               sub_101AB9FB0
__text:0000000100CBEC98 ; End of function InitFunc_1_0
__text:0000000100CBEC98
__text:0000000100CBEC9C
__text:0000000100CBEC9C ; =============== S U B R O U T I N E =======================================
__text:0000000100CBEC9C
__text:0000000100CBEC9C ; Attributes: thunk
__text:0000000100CBEC9C
__text:0000000100CBEC9C                 EXPORT InitFunc_1
__text:0000000100CBEC9C InitFunc_1                              ; DATA XREF: __mod_init_func:0000000101F22468o
__text:0000000100CBEC9C                 B               InitFunc_1_0
__text:0000000100CBEC9C ; End of function InitFunc_1
__text:0000000100CBEC9C

**Comment by Perfare** [comment]
> __text:0000000100CBEC68 ADRP X0, #unk_101FF4C80@PAGE
__text:0000000100CBEC6C ADD X0, X0, #unk_101FF4C80@PAGEOFF
__text:0000000100CBEC70 ADRP X1, #dword_101F51EB8@PAGE
__text:0000000100CBEC74 ADD X1, X1, #dword_101F51EB8@PAGEOFF

101FF4C80 and 101F51EB8

**Comment by ada1016** [comment]
ha ha.. i think I made myself looked so dump here.. I swear that i tried those two yesterday but not work.. guess I made some typo there. 

But it worked!  Thank you so much !
