### ISSUE TITLE
Dumps many duplicates when method names are obfuscated

### ISSUE THREAD

**Issue by HailOdin** [Perfare/Il2CppDumper#100]
This might be because of obfuscation but as you can see many addresses are the same and dumper could remove those.

![image](https://user-images.githubusercontent.com/3116731/52523941-871cb480-2c97-11e9-8730-8693357a9fbb.png)

**Comment by Perfare** [comment]
Please upload binary file and global-metadata.dat

**Comment by Thorusus** [comment]
https://drive.google.com/file/d/1MNqn499uamhjBkdCz-XxRhf4IpoFjtw9/view?usp=sharing

**Comment by Perfare** [comment]
I checked the file and thought it was affected by the obfuscator, but the Il2CppDumper had no way to remove them.
