### ISSUE TITLE
Dumping does not work with x86 binaries that have a version >= 2018.3

### ISSUE THREAD

**Issue by BowDown097** [Perfare/Il2CppDumper#101]
Title says it all. This is what happens every time I try. None of the Auto modes work.
![image](https://user-images.githubusercontent.com/42720004/52525280-ff658480-2c5b-11e9-9a76-000d568a8544.png)

**Comment by Perfare** [comment]
Please upload binary file and global-metadata.dat

**Comment by BowDown097** [comment]
https://drive.google.com/open?id=1V8mReCFng1__TOhEFADbT9I1FjVApMgO
https://drive.google.com/open?id=1T6xM7Qv-cjQMbdYof17hCNhv8WdlGDR8
