### ISSUE TITLE
Add support Nintendo Switch Metadata/NSO files

### ISSUE THREAD

**Issue by Glitchware** [Perfare/Il2CppDumper#103]
Does not work on nintendo switch metadata/nso files.

**Comment by Perfare** [comment]
Can you upload some example files to me?

**Comment by Tek9x** [comment]
This is from the game Farm Together for the switch

Global Metadata
[here](https://nofile.io/f/0ZGuEdky6BJ/global-metadata.dat)

NSO File
[here](https://nofile.io/f/N6EO5kFGB0Y/main)

Information about NSO format
[here](https://switchbrew.org/wiki/NSO)

**Comment by Glitchware** [comment]
> Can you upload some example files to me?

@Tek9x beat me to it!

**Comment by Perfare** [comment]
done.

**Comment by Tek9x** [comment]
@Perfare awesome!
