### ISSUE TITLE
Can't use this mode  to process file…… unity是2018.3，使用4.2.1选则yes后仍然提示这个，dat和so都没有加密

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#104]
所有模式都会失败,麻烦大佬了。
[FKJY.zip](https://github.com/Perfare/Il2CppDumper/files/2887377/FKJY.zip)

**Comment by 350030173** [comment]
![image](https://user-images.githubusercontent.com/20263746/56857009-28173380-699a-11e9-8f7b-707d4aecf960.png)
