### ISSUE TITLE
Mac os version

### ISSUE THREAD

**Issue by pirocoptero** [Perfare/Il2CppDumper#105]
Please, have a mac version?

**Comment by sterling0x1** [comment]
It runs fine in wine.

**Comment by Perfare** [comment]
There is currently no mac version.

**Comment by HimiGame** [comment]
i find the mac version by moder, check  link:
https://platinmods.com/threads/il2cppdumper-cli-compiled-for-macos-and-linux.89608/

**Comment by HimiGame** [comment]
补充一个mac/linux下载地址：
链接: https://pan.baidu.com/s/1iEgjX6hOtpAoVgc6-3bpng  密码: 82qj

**Comment by noasoso** [comment]
https://dl.sbenny.com/folder/1270/Il2CppDumper_CLI
