### ISSUE TITLE
Ghidra

### ISSUE THREAD

**Issue by sterling0x1** [Perfare/Il2CppDumper#106]
This might be early to ask, but tomorrow Ghidra (free disassembler by NSA) will be released. As it supports scripting, will you consider updating the script to Ghidra so we can reverse unity games using the new disassembler?

**Comment by Perfare** [comment]
I will try to support Ghidra.

**Comment by sterling0x1** [comment]
nice :) 
if not Ghidra, you could perhaps take radare2 GUI - Cutter in consideration. its free and quite capable of reversing iOS binaries. I'm not trying to be very needy, just looking into free methods of reversing. 
No rush and thanks for considering support for other free tools :)

**Comment by fantasyz** [comment]
FYI, i found a script already doing that.

https://gist.github.com/KenjiroIchise/ed69cf6abf0a886302adf2a39f06d066

However, I tried and the function address seems incorrect. 
Not sure if exported script.py is incorrect or i config Ghidra wrong. (Don't have IDA so can't compare)

**Comment by Perfare** [comment]
@fantasyz Thanks for the information provided. I will try to finish this work in the near future.

**Comment by worawit** [comment]
I create ghidra script that read from script.py output

https://gist.github.com/worawit/c8788723a667f990ba9aebe9d69f2fc4

I think my script is easy to be modified for this project

**Comment by masagrator** [comment]
Script is not working anymore with il2cppdumper newer than 4.6.0. With and without fix.

> Traceback (most recent call last):
>   File "C:\Users\Marek\ghidra_scripts\ildumper_script_reader.py", line 68, in <module>
>     res = globals()['do_'+name.replace('.', '_')](arg1, arg2)
> KeyError: 'do_idc_set_cmt'

> Traceback (most recent call last):
>   File "C:\Users\Marek\ghidra_scripts\ildumper_script_reader.py", line 68, in <module>
>     res = globals()['do_'+name.replace('.', '_')](arg1, arg2.replace(' ', '-'))
> KeyError: 'do_idc_set_cmt'

**Comment by masagrator** [comment]
https://gist.github.com/masagrator/f21a0bb7b882b509c34beba7d2258b5d

Script working with 5.0.4. It's using hack avoiding new function - idc.set_cmt

**Comment by kulfix** [comment]
hey, i am a little new to ghidra and python. how can i run this script? when trying from comand line i got : 
PS C:\code> python .\ildumper_script_reader.py
Traceback (most recent call last):
  File ".\ildumper_script_reader.py", line 2, in <module>
    import ghidra.program.model.symbol.SourceType
ImportError: No module named ghidra.program.model.symbol.SourceType
PS C:\code>

pip install ghidra 

give nothing. 
could you give some tip ?

**Comment by Perfare** [comment]
Ghidra script has been completed and the MakeFunction part has been improved.

**Comment by WimpyMistake** [comment]
anybody able to make the script works in cutter.re?
