### ISSUE TITLE
ERROR: Some errors in dumping

### ISSUE THREAD

**Issue by ZahirSher** [Perfare/Il2CppDumper#108]
![untitled](https://user-images.githubusercontent.com/8087235/53808653-cf28b180-3f8d-11e9-94fe-8539ba6f3b8e.png)

**Metadata & Binary:** https://www92.zippyshare.com/v/oVtJYQNb/file.html

**Comment by Perfare** [comment]
This game Unity version should greater than or equal to 2018.3 .When asked "Is the Unity version greater than or equal to 2018.3?", please select yes.
