### ISSUE TITLE
Where does the methodCount variable come from in PlusSearch.cs?

### ISSUE THREAD

**Issue by Ben3874** [Perfare/Il2CppDumper#110]
I cannot for the life of me figure where it comes from.
I would've though it'd come from pMetadataHdr.methodsCount/sizeof(Il2CppMethodDefinition) but they're different values.

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper/blob/be89ac9debb383f85b8ec45e7b10976f503899e2/Il2CppDumper/Program.cs#L182
