### ISSUE TITLE
scripts.py not working in IDA for NSO files?

### ISSUE THREAD

**Issue by Tek9x** [Perfare/Il2CppDumper#114]
#103 scripts.py does not seem to be populating in IDA at all, even though the file did get generated.

[scripts.py](https://nofile.io/f/Tp0Yx47zOHW/script.py)
[main.nso](https://nofile.io/f/Yp21FJOcDG5/main)
[global meta data](https://nofile.io/f/KSqVbwFEhxa/global-metadata.dat)

i did wait for IDA to finish decompiling to run script.py.

is it working atm, or is that not a feature that works with NSO.

i am using the NSO Loader for IDA by reswitched
https://github.com/reswitched/loaders

**Comment by Mila432** [comment]
the loader messes up the addresses 
use the clean method

https://github.com/Mila432/switch_rom_hacking#uncompressing-main-recommended

**Comment by Tek9x** [comment]
> 
> 
> the loader messes up the addresses
> use the clean method
> 
> https://github.com/Mila432/switch_rom_hacking#uncompressing-main-recommended

@Mila432 Great, Thank you. I do get one error "GOT section overlaps and might be corrupt. GOT entries will not be renamed." is this normal.
