### ISSUE TITLE
还没发布到release里，到这里下载https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

### ISSUE THREAD

**Issue by zellfy** [Perfare/Il2CppDumper#116]
还没发布到release里，到这里下载https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

_Originally posted by @Perfare in https://github.com/Perfare/Il2CppDumper/issues/115#issuecomment-476144327_

大佬能加个好友吗，我的QQ是114277199，拜托了，有点事情想跟您咨询。

**Comment by Perfare** [comment]
Il2CppDumper相关问题可以直接在这里提问，其他问题不接受私下咨询.
