### ISSUE TITLE
Please I have a problem with the dumper

### ISSUE THREAD

**Issue by jogosunlimited** [Perfare/Il2CppDumper#117]
I'm getting an error after I dumper a game.
Cs line 195
Cs line 95

I try everything don't work.

Error in Il2cppDumper.program.Init(Byte[ ] il2cppdumper, byte [ ] metadatabytes in c: \projects\il2cppdumper\Il2cppdumper\program.cs line .....

**Comment by Perfare** [comment]
Please upload binary file and global-metadata.dat
