### ISSUE TITLE
Metadata registration offset obfuscated

### ISSUE THREAD

**Issue by ElliotRobot20** [Perfare/Il2CppDumper#118]
![119B847B-9072-4FDF-B147-178028466E66](https://user-images.githubusercontent.com/28879469/55683885-d4717700-5912-11e9-8a00-55e364700fd1.jpeg)

Many apps are obfuscating the metadata registration offset like the screenshot. Anyway we can get around this?

**Comment by Perfare** [comment]
If the auto mode does not work, you can upload the file to me.

**Comment by ElliotRobot20** [comment]
Hi Perfare,
Auto mode doesnt work.

Here is the files:
https://we.tl/t-8K9mBaTw5L

This is applicable for multiple games.
This was the old way:
__text:0000000103B46250
__text:0000000103B46250                 STP             X29, X30, [SP,#-0x10+var_s0]!
__text:0000000103B46254                 MOV             X29, SP
__text:0000000103B46258                 ADRP            X0, #unk_1053756A8@PAGE
__text:0000000103B4625C                 ADD             X0, X0, #unk_1053756A8@PAGEOFF
__text:0000000103B46260                 ADRP            X1, #unk_1054FAB48@PAGE
__text:0000000103B46264                 ADD             X1, X1, #unk_1054FAB48@PAGEOFF

Now they are using a constant value instead of a Memory pointer for the metadata registration
(files attached)

__text:000000010140016C                 ADRP            X0, #unk_106F25D10@PAGE
__text:0000000101400170                 ADD             X0, X0, #unk_106F25D10@PAGEOFF
__text:0000000101400174                 MOV             X1, #0xB544
__text:0000000101400178                 MOVK            X1, #0xA4DD,LSL#16
__text:000000010140017C                 MOVK            X1, #0xA9C,LSL#32
__text:0000000101400180                 MOVK            X1, #0x7CBA,LSL#48

unk_106F25D10 is the CodeRegistration Offset
Metadata Registration is constant: 0x7CBA0A9CA4DDB544 and not memory pointer
