### ISSUE TITLE
尝试过全部的模式了

### ISSUE THREAD

**Issue by aiwobazou** [Perfare/Il2CppDumper#119]
version : unity 2018.3.3
ida 在 il2cpp 里面没有搜索到 il2cpp::vm::MetadataCache::Register相关。
检查了libunity.so一下，发行il2cpp好像是在so里面完成的初始化等各种操作
[signed int __fastcall sub_64160C(int  @a1)] @fbarriga @iBotPeaches @dogtopus @Perfare 
所以dump出来的文件全部是报错信息或者直接dump失败.

文件链接:链接：
https://pan.baidu.com/s/10C2Gis_AwZBwWUygISsh0Q 
提取码：sjeb 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Perfare** [comment]
测试过了，正常工作
