### ISSUE TITLE
Il2cppdumper

### ISSUE THREAD

**Issue by thienha1** [Perfare/Il2CppDumper#12]
I tried to dump with your software but it force close after 1.Auto 2.Manual although never press 1 or 2!! And i don't see dump.cs be created!!!

**Comment by ZahirSher** [comment]
!!! 

Chill out dude, this type of messages are what irritates creators the most

**Comment by thienha1** [comment]
What are you talking about??

**Comment by Perfare** [comment]
I don't think it will happen
