### ISSUE TITLE
希望大佬帮忙看一下这个问题，谢谢啦

### ISSUE THREAD

**Issue by ZHOOOOOU** [Perfare/Il2CppDumper#121]
文件不会直接在这里发，传到蓝奏云了https://www.lanzous.com/i3qtj5c
出现问题描述如下
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\Users\Administrator\Deskt
op\Il2CppDumper-master\Il2CppDumper\Program.cs:行号 134
如果可以解决的话，联系qq945323477一定有偿，谢谢啦

**Comment by Perfare** [comment]
测试过了，正常工作
