### ISSUE TITLE
IDA查看的函数跟dnSpy查看DummyDll内的函数对应不上

### ISSUE THREAD

**Issue by jim1019** [Perfare/Il2CppDumper#122]
4.2.5 4.4.2都测试过，结果是一样的
Unity版本是2018.3.5f1
选择第4种模式才能正常导出，通过ida执行script.py查看函数，发现ida内查看的函数逻辑跟DummyDll对应的函数逻辑是对应不上的，比如函数参数就对应不上，可以肯定是完全对应不上。

dll内的部分脚本：
// Token: 0x060000CF RID: 207 RVA: 0x00002384 File Offset: 0x00000584
[Address(RVA = "0x3AEDC8", Offset = "0x3AEDC8")]
Token，RID，RVA，File Offset，Offset 求教一下这几个参数的含义是什么？

[so_metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3072250/so_metadata.zip)

**Comment by Perfare** [comment]
根据你的描述我认为你想说的是函数地址不对，但是根据你贴出的位于0x3AEDC8的GameRunning()我检查过并没有什么问题
上面一栏注释是dnspy的自带内容，你可以选择关闭，RVA是虚地址偏移，Offset是物理地址偏移

**Comment by jim1019** [comment]
ida:
int __fastcall GameManager__GameRunning(int a1)
{
  int result; // r0

  result = *(_DWORD *)(a1 + 164);
  if ( result != 1 )
    result = 0;
  return result;
}

dump.cs
public bool GameRunning();

感谢回复，造成我提出这个问题的疑惑是dump.cs（或者说是dll）没有参数，ida上是有参数的，是否是我的理解出现偏差了？
