### ISSUE TITLE
macho64解析出错

### ISSUE THREAD

**Issue by C4nf3ng** [Perfare/Il2CppDumper#123]
提交之前, 请先使用[latest build](https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts)版本

- Il2CppDumper版本
4.4.2
- 目标Unity版本

- 问题描述
已经砸壳的ios游戏 解析可执行文件出错 本来想编译调试下但是源码vs2015编译报错
Is the Unity version greater than or equal to 2018.3?
1.Yes 2.No
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadUInt32()
   在 Il2CppDumper.Macho64..ctor(Stream stream, Single version, Int64 maxMetadataUsages) 位置 C:\projects\il2cppdumper\Il2CppDumper\Macho64.cs:行号 25
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 187
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 87
- 上传可执行文件和global-metadata.dat
链接: https://pan.baidu.com/s/1R6E0rsEe4mOwUjBItPX9NA 提取码: yk3u

**Comment by Perfare** [comment]
文件损坏，请先保证能用ida打开

**Comment by C4nf3ng** [comment]
大佬我错了 是filezilla从mbp向win传文件时候丢了几kb 麻烦大佬了
