### ISSUE TITLE
Unity 2019.1

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#124]
提交之前, 请先使用[latest build](https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts)版本

- Il2CppDumper版本
Il2CppDump 4.4.2
- 目标Unity版本
2019.1.0f2
- 问题描述
无法完成dump工作。
Is the Unity version greater than or equal to 2018.3?
1.Yes  2.No
Initializing metadata...
System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
      在 System.ThrowHelper.ThrowKeyNotFoundException<>
      在 System.Collections.Generic.Dictionary'2.get_Item<TKey key>
      在 IlCppDumper.Metadata.ProcessingMetadataUsage<> 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 150
      在 IlCppDumper.Metadata..ctor<Stream stream, Single version> 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 72
      在 IlCppDumper.Program.Init<Byte[] il2cppBytes, Byte[] metadataBytes> 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 116
      在 IlCppDumper.Program.Main<String[] args> 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 87
Press any key to exit...
- 上传可执行文件和global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3099904/global-metadata.zip)
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/3099910/libil2cpp.zip)

**Comment by Perfare** [comment]
elf arm已支持。
