### ISSUE TITLE
ERROR: Can't use this mode to process file, try another mode.

### ISSUE THREAD

**Issue by HxBreak** [Perfare/Il2CppDumper#125]
提交之前, 请先使用[latest build](https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts)版本

- Il2CppDumper版本 

v4.4.2

- 目标Unity版本

 未知，两种情况都测试过了

- 问题描述

目标so文件架构为v8a，尝试过多种模式，均无法提取出method信息

- 上传可执行文件和global-metadata.dat
[metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3099990/metadata.zip)

**Comment by HxBreak** [comment]
软件下载地址 https://www.greplay.com/info/11917.html?tdsourcetag=s_pcqq_aiomsg

**Comment by Perfare** [comment]
![QQ截图20190421175007](https://user-images.githubusercontent.com/12952226/56468367-ed733f80-645d-11e9-9a20-6d694acbba51.png)
