### ISSUE TITLE
无法生成DUMP文件

### ISSUE THREAD

**Issue by moonsun1234** [Perfare/Il2CppDumper#127]
提交之前, 请先使用[latest build](https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts)版本

- Il2CppDumper版本
Il2CppDumper-v4.5.0

- 目标Unity版本
2019.1

- 问题描述
选用2019.1 unity版本可以Initializing metadata成功，但是所有模式都试验过，无法生成DUMP文件，提示 ERROR: Can't use this mode to process file, try another mode.    CodeRegistration和MetadataRegistration为0 。

- 上传可执行文件和global-metadata.dat

[file.zip](https://github.com/Perfare/Il2CppDumper/files/3115453/file.zip)

**Comment by HxBreak** [comment]
ok, 感谢回馈




------------------ 原始邮件 ------------------
发件人: "moonsun1234"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 下午2:30
收件人: "Perfare/Il2CppDumper"<Il2CppDumper@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Perfare/Il2CppDumper] 无法生成DUMP文件 (#127)




提交之前, 请先使用latest build版本
  
 
Il2CppDumper版本
 Il2CppDumper-v4.5.0
 
 
 
目标Unity版本
 2019.1
 
 
 
问题描述
 选用2019.1 unity版本可以Initializing metadata成功，但是所有模式都试验过，无法生成DUMP文件，提示 ERROR: Can't use this mode to process file, try another mode.    CodeRegistration和MetadataRegistration为0 。
 
 
 
上传可执行文件和global-metadata.dat
 
  
file.zip

**Comment by Perfare** [comment]
#124

**Comment by Perfare** [comment]
elf arm已支持。
