### ISSUE TITLE
Error : Index was outside the bound of the array.

### ISSUE THREAD

**Issue by Hisenberg19** [Perfare/Il2CppDumper#130]
Hello, I was unable to create dump and python script file. I have tried the latest il2cpp dumper and previous versions as well using all the modes, I had even tried 'unity metadata loader' but it all failed. Can anyone please help?
- Il2CppDumper version:
  4.5.5
- Target Unity version:
  5.6, 2017.1
- Describe the issue:
I have added screenshots about the error am getting-
![Capture1](https://user-images.githubusercontent.com/50170704/57026741-16fb4a80-6c58-11e9-92f8-45b1c2a3b4bd.JPG)
![Capture2](https://user-images.githubusercontent.com/50170704/57026748-1ebaef00-6c58-11e9-9170-6309cb7a6b22.JPG)
- Upload executable file and global-metadata.dat:
  Il2cpp file - [https://www.mediafire.com/file/jb7bgb9bfjdjln0/libil2cpp.so/file](url)
  global - metadata - [https://www.mediafire.com/file/n224ej2nh8ncvnj/global-metadata.dat/file](url)
  It created a short dump file - [https://www.mediafire.com/file/wpobsi3gl98bd7g/dump.cs/file](url)

**Comment by Perfare** [comment]
Wrong Unity version.

**Comment by Hisenberg19** [comment]
Can you please tell me where to find this unity version? I have tried to input version 5.6 and also 2017.1 but both failed.

**Comment by Hisenberg19** [comment]
> 
> 
> Wrong Unity version.

Can you please tell me where to find this unity version? I have tried to input version 5.6 and also 2017.1 but both failed.

**Comment by Hisenberg19** [comment]
I found it and it was wrong unity version as you said. Thank you.

**Comment by LaxusiC** [comment]
@Hisenberg19 I'm getting the same issue, how do you find the correct version of unity?

**Comment by Hisenberg19** [comment]
@LaxusiC I was too not able to figure out the correct method but I kept trying putting every versions of unity, luckily 2018.3 worked for me. You can try too. Just use one unit after decimal point. The unity versions: [https://unity3d.com/get-unity/download/archive](url)
