### ISSUE TITLE
PC, 64 bit dumping

### ISSUE THREAD

**Issue by zanzan13531** [Perfare/Il2CppDumper#136]
- Il2CppDumper version
v4.5.8

- Target Unity version
2018.3

- Describe the issue
I tried auto mode, which doesn't work, so I then tried manual, but I don't know what to put for the input CodeRegistration and input MetadataRegistration fields. An online guide told me to look for a function called InitFunc, but I can't find that in ida. I'm running windows 8.1, on a 64 bit computer.

- Upload executable file and global-metadata.dat
https://drive.google.com/open?id=1Aphcp5Vb6R7_2ym33SGYu2VW1djiOHz6

**Comment by Perfare** [comment]
This file is processed normally, without any problems.
