### ISSUE TITLE
2019.3.5 无法完成dump工作

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#137]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper 4.5.8
- 目标Unity版本
2019.3.5
- 问题描述
无法完成dump工作。
try another mode.
- 上传可执行文件和global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3180527/global-metadata.zip)
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/3180528/libil2cpp.zip)

**Comment by Perfare** [comment]
Auto模式不支持2019，请使用Manual模式
