### ISSUE TITLE
Unity Version

### ISSUE THREAD

**Issue by KingKong5147** [Perfare/Il2CppDumper#139]
Hi ,

Thanks for your awesome tool :)
Now the issue I’m having is I can’t seem to find the unity version to use the tool where would I find this in iOS???......

**Comment by LaxusiC** [comment]
I would like to know too????

**Comment by DrkArrow19** [comment]
Same here as well.

**Comment by qorn** [comment]
This might help 
https://www.andnixsh.com/2019/05/how-to-get-unity-version-from-any-asset.html
