### ISSUE TITLE
Auto mode can't deal. How to find addresses manually?

### ISSUE THREAD

**Issue by fattakhovmarat** [Perfare/Il2CppDumper#14]
Tried to dump these: https://drive.google.com/drive/folders/0B9E0BjdgxRlzUlNya1ZhQzFOcW8?usp=sharing

Could not handle to get addresses manually. Tried to find bytes  { 0x55, 0x89, 0xE5, 0x53, 0x83, 0xE4, 0xF0, 0x83, 0xEC, 0x20, 0xE8, 0x00, 0x00, 0x00, 0x00, 0x5B }. Can you point me an instruction please?

**Comment by Perfare** [comment]
Sorry, because there are too many cases, please depend on yourself
