### ISSUE TITLE
What did you compile to get 8 byte values on your Il2CppMetadataRegistration class?

### ISSUE THREAD

**Issue by Ben3874** [Perfare/Il2CppDumper#143]
I've tried compiling for windows store and the PC platform with IL2CPP, but every time I try to compile, I get the following struct in my il2cpp-class-internals.h.

`typedef struct Il2CppMetadataRegistration
{
	int32_t genericClassesCount;
	Il2CppGenericClass* const * genericClasses;
	int32_t genericInstsCount;
	const Il2CppGenericInst* const * genericInsts;
	int32_t genericMethodTableCount;
	const Il2CppGenericMethodFunctionsDefinitions* genericMethodTable;
	int32_t typesCount;
	const Il2CppType* const * types;
	int32_t methodSpecsCount;
	const Il2CppMethodSpec* methodSpecs;
	FieldIndex fieldOffsetsCount;
	const int32_t** fieldOffsets;
	TypeDefinitionIndex typeDefinitionsSizesCount;
	const Il2CppTypeDefinitionSizes** typeDefinitionsSizes;
	const size_t metadataUsagesCount;
	void** const* metadataUsages;
} Il2CppMetadataRegistration;`

Except, I have noticed, that the struct that is in my games il2cpp-class-internals.h. should be something like this

`typedef struct Il2CppMetadataRegistration
{
	int64_t genericClassesCount;
	Il2CppGenericClass* const * genericClasses;
	int64_t genericInstsCount;
	const Il2CppGenericInst* const * genericInsts;
	int64_t genericMethodTableCount;
	const Il2CppGenericMethodFunctionsDefinitions* genericMethodTable;
	int64_t typesCount;
	const Il2CppType* const * types;
	int64_t methodSpecsCount;
	const Il2CppMethodSpec* methodSpecs;
	FieldIndex fieldOffsetsCount;
	const int32_t** fieldOffsets;
	TypeDefinitionIndex typeDefinitionsSizesCount;
	const Il2CppTypeDefinitionSizes** typeDefinitionsSizes;
	const size_t metadataUsagesCount;
	void** const* metadataUsages;
} Il2CppMetadataRegistration;`

I just want to know if I'm compiling the games incorrectly or if you just looked at the hex values and figure it out.

Edit: Sorry for the struct looking terrible, Github doesn't like formatting

**Comment by Perfare** [comment]
About the compilation problem of il2cpp, you should go to the Unity community to ask questions instead of here.
