### ISSUE TITLE
I can't dump

### ISSUE THREAD

**Issue by Arsenal88** [Perfare/Il2CppDumper#145]
hey 

I can't dumb il2cpp
This message appears to me
<img width="673" alt="33" src="https://user-images.githubusercontent.com/51047081/59459542-51dacb80-8e1d-11e9-8b6f-361dd0f6861c.PNG">

I used Il2CppDumper-v4.5.8
Input unity version:
2018.3

this is global-metadata
https://www58.zippyshare.com/v/ltycLyuh/file.html

this is libil2cpp
https://www116.zippyshare.com/v/QdeOijh9/file.html

Thanks in advance

**Comment by Perfare** [comment]
Wrong Unity version.
