### ISSUE TITLE
Unable to dump ios binary

### ISSUE THREAD

**Issue by Smethan** [Perfare/Il2CppDumper#147]
- Il2CppDumper version: 4.5.11

- Target Unity version: 2018.2.5f1

- Describe the issue: I get an "ERROR: Can't use this mode to process file, try another mode." no matter what mode I try. I have tried manual mode with little success, couldn't find the offsets above the InitFunc_. The file opens fine and even find all objc functions in IDA, only have problems with il2cppDumper

- Upload executable file and global-metadata.dat:
binary: https://mega.nz/#!jTBRTQiB!lkMyIz9Uvj9-1dcJLO_nSiJLBrfpHqrntnu6ACrBa9U
global-metadata: https://mega.nz/#!CD4wnSqT!Paxe5GNdP0DnoOBB7rSbO0U86aUDf0EGJqR9gGgs-fk

**Comment by Perfare** [comment]
Data is destroyed or encrypted.
![QQ截图20190615113630](https://user-images.githubusercontent.com/12952226/59546538-dafb1b00-8f61-11e9-8b08-4f29a34c822c.png)
