### ISSUE TITLE
About the latest version Il2CppDumper-v4.5.11

### ISSUE THREAD

**Issue by Arsenal88** [Perfare/Il2CppDumper#148]
I used the latest version which you released yesterday
Its bad news for me about Auto mode not working on unity version 2019 or above 
So bro would you mind told me how can you manual mode?
need to codeRegistration 
really want your help

Thanks 

<img width="677" alt="3" src="https://user-images.githubusercontent.com/51047081/59557565-5ea61d80-8fdd-11e9-91c9-aee931bd89ea.PNG">

**Comment by mikieribeiroaptoide** [comment]
Here you go: https://platinmods.com/threads/manually-dump-il2cpp-unity-2019-x-x-on-android-games.67593/
