### ISSUE TITLE
exporting interfaces

### ISSUE THREAD

**Issue by nicoschmitt** [Perfare/Il2CppDumper#15]
Did you had a look at exporting interfaces?
I tried to dump interface and types implementing interfaces but with no luck so far

**Comment by Perfare** [comment]
You mean like this part below?
```csharp
public sealed class Int32 : ValueType, IFormattable, IConvertible, IComparable, IComparable`1<int>, IEquatable`1<int> // TypeDefIndex: 5
```

**Comment by nicoschmitt** [comment]
Yes. You mean you do it already?

Sent from Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by Perfare** [comment]
I think it should be all right 44e3a26c6ed00075e5a0ce621d60112a27c678e0

**Comment by nicoschmitt** [comment]
Nice, I'll have a look!

**Comment by nicoschmitt** [comment]
Thanks, it works fine. 
I don't know how I came up with that but my code was way more complicated, and obviously didn't work...
