### ISSUE TITLE
ERROR: Some errors in dumping

### ISSUE THREAD

**Issue by TunahanB** [Perfare/Il2CppDumper#151]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version = 4.5.11

- Target Unity version - I just write the latest unity version 5.6.7

- Describe the issue 
![image](https://user-images.githubusercontent.com/52636879/60773714-fc3ec980-a111-11e9-876f-765984179e07.png)

- Upload executable file and global-metadata.dat (https://iosddl.net/bf7f8e3fd0dfed61/dumperror.zip)

**Comment by Perfare** [comment]
Wrong Unity version.
