### ISSUE TITLE
ERROR : cannot find coderegistraion ! 

### ISSUE THREAD

**Issue by komik8** [Perfare/Il2CppDumper#153]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 4.5.11

- Target Unity version 2018.3 / 2018.4 / 2019.1

- Describe the issue
![image](https://user-images.githubusercontent.com/52743858/60963712-2081ec80-a344-11e9-84a1-1c6b6c85124c.png) 
 cannot find coderegistration
it's auto plus
then if 2019.1 this happen:
![image](https://user-images.githubusercontent.com/52743858/60964196-465bc100-a345-11e9-8e3c-b2b237706a2c.png)

- Upload executable file and global-metadata.dat
https://mega.nz/#!U5Z1VCAQ!Ph3If75bNLkIFDNHiV4ncaCM1X41vwEDmiaHRnCwkLI   >>libil2cpp
https://mega.nz/#!poJFzSJT!DvYu3WkG9wzlhYR9uCedlr5HFB6wy2qMjHJu2mxFBmg    >>global metadata

**Comment by Perfare** [comment]
Protected file
