### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element on PSVita ELF

### ISSUE THREAD

**Issue by KuromeSan** [Perfare/Il2CppDumper#154]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version v4.5.11

- Target Unity version 5.3.5p6

- Describe the issue 

This is a .elf for a PSVita game (Nep*Nep Connect Chaos Champerru)
i did vita-unmake-fself on it to get the .elf back from SELF and it still doesn't work giving
an error

the vita uses standard ARM9 .ELF files ulbeit packed into there fancy "SELF" format generally, but it doesnt work on the unpacked version either

i tried all modes none of which work.

```
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Initializing il2cpp file...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Elf..ctor(Stream stream, Single version, Int64 maxMetadataUsages) in C:\projects\il2cppdumper\Il2CppDumper\Elf.cs:line 77
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 209
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 87
Press any key to exit...
```

- Upload executable file and global-metadata.dat

[Modules.zip](https://github.com/Perfare/Il2CppDumper/files/3386120/Modules.zip)

**Comment by Perfare** [comment]
This converted elf is not standard, difficult to debug, and will not consider support.

**Comment by KuromeSan** [comment]
pfft ill fix it myself then >_>

btw~ 

```
SCE ELFs use a different relocation format from standard ELFs. The relocation entries
are in two different format, either an 8 byte “short” entry or a 12 byte “long” entry. 
```

``dynamic_table = ReadClassArray<Elf32_Dyn>(pt_dynamic.p_offset, pt_dynamic.p_filesz / 8u);``
