### ISSUE TITLE
Can't Dump 

### ISSUE THREAD

**Issue by Chensem** [Perfare/Il2CppDumper#156]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version  
4.5.11 or 4.5.8 (all failed)

- Target Unity version 
2018.01
- Describe the issue
can't dump
- Upload executable file and global-metadata.dat
https://mega.nz/#!emwDyCRA
![image](https://user-images.githubusercontent.com/27469499/61371693-f5f5dd80-a8c7-11e9-9dd0-7689d7e3bee8.png)

maybe i get the known version of unity , can you tell me the rigth way to detect the version . and i also see a segement named ill2cpp , i did't see it before , thank for you help :)

**Comment by Perfare** [comment]
https://www.andnixsh.com/2019/05/how-to-get-unity-version-from-any-asset.html
