### ISSUE TITLE
RVA in dump.cs is VA

### ISSUE THREAD

**Issue by Ben3874** [Perfare/Il2CppDumper#157]
In the dump.cs files, all the methods labeled as "RVA" are the VA's, not the RVA's

**Comment by Perfare** [comment]
If you refer to the PE format, all addresses will have a base address equal to the ImageBase attribute in the PE header.

**Comment by Ben3874** [comment]
Virtual Addresses do not have their Base Address subtracted, but Relative Virtual Addresses do.

From https://docs.microsoft.com/en-us/windows/win32/debug/pe-format:
"Relative virtual address. In an image file, the address of an item after it is loaded into memory, with the base address of the image file subtracted from it"
"virtual address. Same as RVA, except that the base address of the image file is not subtracted."

**Comment by Perfare** [comment]
So what do you want to express?
I have already told you that if it is pe format, the output address will be added with ImageBase, you can think of it as a bug, but only when it is in pe format.

**Comment by Ben3874** [comment]
Yeah, for PE format its a bug. Do other formats treat RVA's differently?

**Comment by Perfare** [comment]
But when parsing in ida, it will also load the file into ImageBase, dump.cs will let the user directly locate the function in ida. When you need a real rva address, you only need to subtract the value of ImageBase.

**Comment by Perfare** [comment]
I found that I made a mistake in the past, and I'm very sorry about that. I have refactored the relevant code, and will now output both RVA and VA when the file exists in imageBase.
