### ISSUE TITLE
Can't dump !

### ISSUE THREAD

**Issue by Chensem** [Perfare/Il2CppDumper#158]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

    v4.5.11
- Target Unity version

    2018.4
- Describe the issue
![image](https://user-images.githubusercontent.com/27469499/61535611-46ef0880-aa65-11e9-8f24-3ffc85609587.png)

    i am reversing a game ,  the unity version is 2018.4. and i have two apk of this game. One is from third platform (Mi application shopping), the other is from official website , one can dump (Mi application shopping) , but the other can't dump. i tried manual mode , but it did't work . I can't find the magic on the official application.
![image](https://user-images.githubusercontent.com/27469499/61535464-efe93380-aa64-11e9-8c58-8d70e60363ba.png) the unity version is right . now i don't know how to solve this question

- Upload executable file and global-metadata.dat
    https://mega.nz/#!KzQEiSgJ

**Comment by Perfare** [comment]
你mega并没有给秘钥，另外根据你的描述基本可以判断有保护

**Comment by Chensem** [comment]
> 你mega并没有给秘钥，另外根据你的描述基本可以判断有保护

C42Legh3kyHCRNsKjLfnr9tmkye2N15syf6HTW8gBI0

**Comment by Perfare** [comment]
腾讯mtp
