### ISSUE TITLE
help me dump arm64 binary in iOS?

### ISSUE THREAD

**Issue by kuteteen** [Perfare/Il2CppDumper#16]
I have a binary ios with 2 arm7 and arm64 codes. I've done auto dump and the result is dump of arm7. I want to have dump of arm64 then i need to do?

**Comment by ZahirSher** [comment]
You will need to thin your binary. Remove the armv7 portion of the binary.

- Copy your binary to your iDevice (**/var/mobile/**)
- Open Terminal app
- login as root ( **su** -> **alpine** )
- locate to the binary location ( **cd /var/mobile** )
- type:
`lipo (binaryname) -thin arm64 -o (newbinaryname)`

use the newbinary to decrypt.

**Comment by nicoschmitt** [comment]
7zip can do it also. You don't even need a mac.

**Comment by Perfare** [comment]
You can do as ZahirSher says first
I will try to add option to support dump arm7 and arm64 code from Fat Macho

**Comment by kuteteen** [comment]
thanks all.

**Comment by Perfare** [comment]
supported
