### ISSUE TITLE
无法Dump --> ERROR: Can't use this mode to process file, try another mode

### ISSUE THREAD

**Issue by zcadqewxs** [Perfare/Il2CppDumper#160]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper v4.5.11

- 目标Unity版本
2017.4

- 问题描述
三个模式都试过，还是无法Dump
![il2cpp-dump](https://user-images.githubusercontent.com/17941731/62200291-0f1a8600-b3c0-11e9-9d49-328d867bc398.PNG)

- 上传可执行文件和global-metadata.dat
https://send.firefox.com/download/d4031ba686bd60ce/#47AsoJzsrOGvQGhNo48wgg

**Comment by Perfare** [comment]
有壳
