### ISSUE TITLE
无法Dump --> ERROR: Can't use this mode to process file, try another mode

### ISSUE THREAD

**Issue by MasterThrone** [Perfare/Il2CppDumper#161]
- Il2CppDumper版本
Il2CppDumper-v4.5.11
- 目标Unity版本
2017.4.18f1
- 问题描述
三个模式都试过，还是无法Dump
- 上传可执行文件和global-metadata.dat
https://drive.google.com/file/d/1naIdGnhM7mCA8lxhiuHs8pfz1U9QzndR/view?usp=sharing

**Comment by Perfare** [comment]
有壳
