### ISSUE TITLE
Extract information from only global-metadata.dat file

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Perfare/Il2CppDumper#162]
In some cases (like WebGL Unity games) there is no executable binary. Having an option to generate dummy DLLs and extract strings from just a global-metadata.dat would be very helpful in these cases.

**Comment by Perfare** [comment]
Cannot create DummyDLL by relying solely on global-metadata.dat.

**Comment by HoLLy-HaCKeR** [comment]
There is probably other information to extract, like strings or type info. Anything would be better than nothing.

**Comment by Perfare** [comment]
In my opinion, even WebGL must have a file similar to an executable file.
Only the metadata file can only get the name information of the type, method and field.
