### ISSUE TITLE
Unity Version missing

### ISSUE THREAD

**Issue by PiotrKFtw** [Perfare/Il2CppDumper#164]
I use the latest il2cppdumper.
It cannot auto-dump 2019.2.0

[gameassembly.zip](https://github.com/Perfare/Il2CppDumper/files/3478496/gameassembly.zip)

[metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3478498/metadata.zip)

**Comment by Perfare** [comment]
Auto mode cannot work in versions above 2019.
