### ISSUE TITLE
ERROR: Can't use this mode to process file, try another mode

### ISSUE THREAD

**Issue by nevercoldl** [Perfare/Il2CppDumper#166]
- Il2CppDumper 4.5.11

- 目标Unity版本 2018.2.7f

- 闪耀暖暖的so和global-metadata.dat用所有的自动模式都无法生成文件，而且用ida查看so文件也找不到与metadata相关的函数，所以也无法手动的找到偏移

- metadata https://pan.baidu.com/s/1VWJOvnmqKhKUkYl1wSm9vA
so https://pan.baidu.com/s/1QSoXcDAvs1zGjYUVtAsi8A

//在您的博客好像找到了您的qq，看您的空间在玩这个，希望在破解游戏过程中能得到你的帮助

**Comment by Perfare** [comment]
请先脱壳
另外你明显找错qq了，我并没有玩这个游戏
