### ISSUE TITLE
Need help on IL2CPP for Windows (Win10 Store)

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/Il2CppDumper#167]
I already got into the filesystem of the game and dumped the DummyDLLs with the Auto (Plus) setting, but what is the game executable (Windows' version of LibIL2CPP.so) to disassemble to relate to them and the scripts? I see GameAssembly.dll and Angry Birds Friends.exe, I for sure know its one of those as the others relate to the Unity engine alone, I'm doing GameAssembly.dll right now, is that correct? Thanks so much. I have all the game files relating to the assembly and the metadata itself.

[ABFRIENDS_WIN10_DUMMYDLLS_SCRIPTS.zip](https://github.com/Perfare/Il2CppDumper/files/3494413/ABFRIENDS_WIN10_DUMMYDLLS_SCRIPTS.zip)
[global-metadata.dat.txt](https://github.com/Perfare/Il2CppDumper/files/3494415/global-metadata.dat.txt)
[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/3494759/GameAssembly.zip)

Game: Angry Birds Friends
Source: Microsoft Store
IL2CPPDumper Version: v4.5.11
Unity Version: 2018.4.0.f1

**Comment by LolHacksRule** [comment]
Anything helpful please?

**Comment by AndnixSH** [comment]
GameAssembly.dll is the Il2Cpp. I had tried it on one of Steam game and it worked

**Comment by LolHacksRule** [comment]
Thank you.

**Comment by LolHacksRule** [comment]
Thank you.
