### ISSUE TITLE
针对global-metadata的新加密方式?

### ISSUE THREAD

**Issue by kotoricon** [Perfare/Il2CppDumper#168]
使用Il2CppDumper-v4.5.11 dump某游戏时出现

> 
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Program.Dump() 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 257
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 89
> 

unity版本2018.3   上个版本未出现该错误
把so丢进ida又可以直接分析，请问是加密了还是有其它问题？

**Comment by Perfare** [comment]
请使用问题模板重新提交问题
