### ISSUE TITLE
Detected this may be a dump file. If not, it must be protected

### ISSUE THREAD

**Issue by nik2143** [Perfare/Il2CppDumper#169]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 4.5.11

- Target Unity version: 2018.3

- Describe the issue: 
When i try to use this tool I get the message 
Detected this may be a dump file. If not, it must be protected.
Input dump address:

- Upload executable file and global-metadata.dat
il2cpp: https://mega.nz/#!VIx0waaR!m8RW8P0tDp2kKIDyOlF3neSoNK6cZ6_0uxCVzKLf7wQ
global-metadata.dat: https://mega.nz/#!pJhWAYAJ!swhz3n9Odc_UgcHw1q2zvycMN3TtjXP_pbyHgzm97HQ

**Comment by hamidali6449** [comment]
Same problem unity version 2019.1 can't get metadata registration code and say enter dump code please anyone can't explain how to get metadata registration manually thanks!

**Comment by masagrator** [comment]
Read readme. It's not supporting auto for Unity 2019. So it's not a bug, but not implemented function.

**Comment by nik2143** [comment]
I know but my problem is with unity 2018.3

**Comment by Perfare** [comment]
> Detected this may be a dump file. If not, it must **be protected**.

The prompt has clearly told you that this is a protected file.

**Comment by vikarihonest** [comment]
for il2cppdumper that need input address from maps of game
with perm r-xp it will dump fully (depend on addr) , beacuse it protected.
