### ISSUE TITLE
Cant get it to work with unity 2019.2.0f1 

### ISSUE THREAD

**Issue by trash-code** [Perfare/Il2CppDumper#170]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version latest

- Target Unity version 2019.2.0f1

- Describe the issue

I have reversed the coderegistration and metadataregistration values but i keep getting can't use this mode to process file error. the code registration is at 0x1D1FF10 and metadata registration is at 0x1D27640 but it keeps giving the error cant use this mode but as you can see the executable isnt encrypted.

[Metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3535685/Metadata.zip)

- Upload executable file and global-metadata.dat

**Comment by hamidali6449** [comment]
Tell me game name I will give u dump file

**Comment by trash-code** [comment]
I am trying to make a dump for rust

**Comment by Perfare** [comment]
You entered the wrong pointer address.
By the way, the 2019 version is currently supported.
