### ISSUE TITLE
unity 5.6 error dump 

### ISSUE THREAD

**Issue by kuteteen** [Perfare/Il2CppDumper#171]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本

- 目标Unity版本

- 问题描述

- 上传可执行文件和global-metadata.dat

Exception of type 'System.Exception' was thrown.
ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.FormGUI.A(Object , DoWorkEventArgs )
----------------------------
link: https://www.dropbox.com/s/wtc51ndlhs2gjz0/vuonggiavinhdieu.zip?dl=0

**Comment by Perfare** [comment]
#128
