### ISSUE TITLE
Extract data to machine readable format

### ISSUE THREAD

**Issue by wwhurley** [Perfare/Il2CppDumper#172]
Is it possible to add the ability to write extracted data to JSON or some other machine readable format in addition to the C# code?

**Comment by Perfare** [comment]
Can you give an example of the output format details? I don't have any idea about output json or other formats.

**Comment by wwhurley** [comment]
Sure. So in addition to the output in the dump.cs file that looks like:

```
// Namespace: Microsoft.Win32
[ComVisibleAttribute] // RVA: 0x6C2C38 Offset: 0x6C2C38
public static class Registry // TypeDefIndex: 4
{
        // Fields
        public static readonly RegistryKey ClassesRoot; // 0x0

        // Methods
        private static void .cctor(); // RVA: 0x2683AB4 Offset: 0x2683AB4
}
```
have something that's like:

```
[{
  "namespace": "Microsoft.Win32",
  "class": {
  	"attributes": ["static", "public"],
	"RVA": "0x6C2C38",
	"offset": "0x6C2C3",
	"name": "Registry",
	"fields": [{
	  "attributes": ["public", "static", "readonly"],
	  "type": "RegistryKey",
	  "name": "ClassesRoot",
	  "offset": "0x0"
	}],
	"methods": [{
	  "attributes": ["private", "static"],
	  "return": "void",
	  "name": ".cctor",
	  "RVA": "0x2683AB4",
	  "offset": "0x2683AB4"
	}]
  }
}]
```

**Comment by Perfare** [comment]
Sorry to reply to you so late, I have no intention of implementing this feature after considering it. I think json is not suitable for c #, like generic classes and generic instances are not suitable for json expression. If you want to get reusable data for development, I recommend doing it on the generated DummyDll (cecil)
