### ISSUE TITLE
Cant get it to work with unity 2019.1.8f1

### ISSUE THREAD

**Issue by XieZuoBao** [Perfare/Il2CppDumper#173]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
4.6.0
- Target Unity version
2019.1.8f1
- Describe the issue
I have reversed the coderegistration and metadataregistration values but i keep getting can't use this mode to process file error.
- Upload executable file and global-metadata.dat

[Demo.zip](https://github.com/Perfare/Il2CppDumper/files/3583446/Demo.zip)
![1](https://user-images.githubusercontent.com/31207002/64421109-66082f00-d0d3-11e9-8d5a-a6741e04606a.png)
![2](https://user-images.githubusercontent.com/31207002/64421114-686a8900-d0d3-11e9-974a-301d807eaad9.png)
![3](https://user-images.githubusercontent.com/31207002/64421119-6acce300-d0d3-11e9-961d-5856faced397.png)
![4](https://user-images.githubusercontent.com/31207002/64421129-6f919700-d0d3-11e9-98a0-583001270e84.png)

**Comment by masagrator** [comment]
Why not use Auto(Plus), when 4.6.0 added support for 2019?

**Comment by XieZuoBao** [comment]
I just use the Auto (Plus) mode.Then I got an error.

**Comment by Perfare** [comment]
Protected file.

**Comment by XieZuoBao** [comment]
> 
> 
> Protected file.

I used the shell detection tool to detect il2cpp.so, which is not protected by encryption. Is the global-metadata.dat file protected by shells?
