### ISSUE TITLE
所有mode都提示Can't use this mode to process file, try another mode.

### ISSUE THREAD

**Issue by tzwsoho** [Perfare/Il2CppDumper#176]
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Initializing il2cpp file...
Applying relocations...
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.Exception: ERROR: Can't use this mode to process file, try another mode.

   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 249
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 87
Press any key to exit...

希望作者大佬可以帮忙解决，谢谢！
[NinjaMustDie3_Official.zip](https://github.com/Perfare/Il2CppDumper/files/3598533/NinjaMustDie3_Official.zip)

**Comment by Perfare** [comment]
加壳文件
