### ISSUE TITLE
[ERROR] Can't use this mode to process file, try another mode. 

### ISSUE THREAD

**Issue by mgurbuz06** [Perfare/Il2CppDumper#177]
Input Unity version:
2019.1
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Initializing il2cpp file...
Applying relocations...
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 249
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 87
Press any key to exit...

How this have to work ?

libil2cpp.so and global-metadata.dat in zip file.

[Files.zip](https://github.com/Perfare/Il2CppDumper/files/3608599/Files.zip)

**Comment by HarukaMomono** [comment]
> Input Unity version:
> 2019.1
> Initializing metadata...
> Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
> Initializing il2cpp file...
> Applying relocations...
> Searching...
> CodeRegistration : 0
> MetadataRegistration : 0
> System.Exception: ERROR: Can't use this mode to process file, try another mode.
> at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 249
> at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 87
> Press any key to exit...
> 
> How this have to work ?
> 
> libil2cpp.so and global-metadata.dat in zip file.
> 
> [Files.zip](https://github.com/Perfare/Il2CppDumper/files/3608599/Files.zip)

protected files

**Comment by mgurbuz06** [comment]
But it works in version 4.5.11.

**Comment by Perfare** [comment]
Protected files. It can't work in any version.

**Comment by AdamAzote** [comment]
@Perfare With wich tool they protect files ?
I have the same problem with this files
[files.zip](https://github.com/Perfare/Il2CppDumper/files/3618611/files.zip)

**Comment by HarukaMomono** [comment]
> @Perfare With wich tool they protect files ?
> I have the same problem with this files with 2018.4.8 unity version
> [files.zip](https://github.com/Perfare/Il2CppDumper/files/3618611/files.zip)

It looks like protected by Themida.

**Comment by AdamAzote** [comment]
And there is no way to decompile it ?

**Comment by mgurbuz06** [comment]
@HarukaMomono  
How did you know you were protected with Themida?
