### ISSUE TITLE
i can not dump this il2cpp

### ISSUE THREAD

**Issue by litefish** [Perfare/Il2CppDumper#180]
- Target Unity version:   2019.1.8f1

when i dump this file with error:
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) 位置 I:\dev\Unity3D\Il2CppDumper\Il2CppDumper\Program.cs:行号 249
   在 Il2CppDumper.Program.Main(String[] args) 位置 I:\dev\Unity3D\Il2CppDumper\Il2CppDumper\Program.cs:行号 87

please help me.

[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/3624211/libil2cpp.zip)

**Comment by Perfare** [comment]
Protected file.
