### ISSUE TITLE
[Question] How to get proper address to function runtime?

### ISSUE THREAD

**Issue by PiotrKFtw** [Perfare/Il2CppDumper#181]
I'm trying to do a method call so i created C++ Dynamic link library, wrote basic stuff like create thread and initialization and i run into a problem. When I was trying to get correct address for a method "UnityEngine.Time.get_Time()" i was getting either pointer to place that doesn't exist or in a place that wasn't even function, resulting in game crash .
The code:
`typedef float (*get_timef)();`
`get_timef get_Time;`
First try:
`get_Time = gameAssemblyAddr + RVA`
`cout << get_Time << endl;`
`cout << get_Time() << endl;`
Second try:
`get_Time = gameAssemblyAddr + Offset`
`cout << get_Time << endl;`
`cout << get_Time() << endl;`
also tried doing type casting but nothing worked.
Does anyone have an idea how to get correct address to that function?

**Comment by Perfare** [comment]
I think you are working on PC format. In PC format, RVA will add the value of Optional Header - ImageBase, 32bit is 0x10000000 and 64bit is 0x180000000, the rva in dump.cs minus the above value should work.

**Comment by PiotrKFtw** [comment]
> I think you are working on PC format. In PC format, RVA will add the value of Optional Header - ImageBase, 32bit is 0x10000000 and 64bit is 0x180000000, the rva in dump.cs minus the above value should work.

Thanks
