### ISSUE TITLE
Offsets of properties

### ISSUE THREAD

**Issue by njbrown09** [Perfare/Il2CppDumper#182]
Im using this to develop a trainer currently. My issue is getting offsets of certain values. The dump is great about showing me offsets of fields, but some classes like Transform only give me properties without offsets.

**Comment by Perfare** [comment]
Because they don't use their own fields to store values, go to their get and set methods to see what they are.

**Comment by njbrown09** [comment]
Not entirely sure what you mean. Are you referencing this?

Im trying to get the position of a Vector3.

// Methods
	public Vector3 get_position(); // RVA: 0x181011B10 Offset: 0x1010910

Is this offset something i can just read the memory from?

**Comment by Perfare** [comment]
You need to have a pointer to the Transform you want to get, then call the function at (gameAssembly module base address + 0x1011B10) address, function declaration is get_position(void* transform), then you will get the value of position, which is a pointer to a Vector3 structure.

**Comment by njbrown09** [comment]
Hmm okay. Im using an external program and just RPM/WPM so i guess im not going to be able to get that data.

**Comment by njbrown09** [comment]
Is there a way to figure out the pure offset or the value behind the property? 99% of the properties im trying to get have no logic, they are literally just "return _privateVersionOfTheProperty"
