### ISSUE TITLE
None of the automatic modes work.

### ISSUE THREAD

**Issue by lrh3370** [Perfare/Il2CppDumper#183]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v4.6.0

- Target Unity version
2018.4.9f1

- Describe the issue
Cannot use any automatic mode

CodeRegistration : 0
MetadataRegistration : 0
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 249
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 87

- Upload executable file and global-metadata.dat
[Files.zip](https://github.com/Perfare/Il2CppDumper/files/3646630/Files.zip)

**Comment by morelli690** [comment]
https://www.unknowncheats.me/forum/general-programming-and-reversing/355005-il2cppdumper-tutorial-finding-coderegistration-metadataregistration.html#post2584934

**Comment by lrh3370** [comment]
Thanks! That worked.
