### ISSUE TITLE
马里奥赛车dump报错

### ISSUE THREAD

**Issue by xxzzddxzd** [Perfare/Il2CppDumper#184]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue
 
- Il2CppDumper版本
4.6.0
- 目标Unity版本
2017.4.3f1
- 问题描述
解密iOS版本的马里奥赛车时报错
- 上传可执行文件和global-metadata.dat
[global-metadata.dat.zip](https://github.com/Perfare/Il2CppDumper/files/3651105/global-metadata.dat.zip)
主程文件过大这里发不了，可以加q或邮箱吗

**Comment by xxzzddxzd** [comment]
[xaa.zip](https://github.com/Perfare/Il2CppDumper/files/3651165/xaa.zip)
[xab.zip](https://github.com/Perfare/Il2CppDumper/files/3651171/xab.zip)
[xac.zip](https://github.com/Perfare/Il2CppDumper/files/3651174/xac.zip)
[xad.zip](https://github.com/Perfare/Il2CppDumper/files/3651186/xad.zip)
[xae.zip](https://github.com/Perfare/Il2CppDumper/files/3651187/xae.zip)
分段压缩的，主程序已上传

**Comment by Perfare** [comment]
不要分开发，不行就传百度云或者其他网盘

**Comment by xxzzddxzd** [comment]
链接:https://pan.baidu.com/s/1_bhhE9RRpO6DIhI7TkAi9Q  密码:t8ka
请查收

**Comment by Perfare** [comment]
![QQ截图20190928025203](https://user-images.githubusercontent.com/12952226/65794554-f8fc2c80-e19a-11e9-9257-26693f819cb8.png)
数据有问题，推测是砸壳有误
