### ISSUE TITLE
所有模式都使用了，未dump下来

### ISSUE THREAD

**Issue by hjes** [Perfare/Il2CppDumper#185]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
4.6
- 目标Unity版本
2018.4.3f1
- 问题描述
所有模式都试过，dump不下来
- 上传可执行文件和global-metadata.dat
https://www.lanzous.com/i6fu8od

**Comment by morelli690** [comment]
https://www.unknowncheats.me/forum/general-programming-and-reversing/355005-il2cppdumper-tutorial-finding-coderegistration-metadataregistration.html#post2584934

**Comment by Perfare** [comment]
已加壳
