### ISSUE TITLE
Missing offsets of abstract methods 

### ISSUE THREAD

**Issue by lyndmi** [Perfare/Il2CppDumper#186]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version:
4.6.0

- Target Unity version:
2017.4

- Describe the issue
Dumper is not able to dump offsets of abstract methods, returning -1

![image](https://user-images.githubusercontent.com/24647715/66034652-f0448700-e509-11e9-8325-a16ecbd6b950.png)

- Upload executable file and global-metadata.dat
[il2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/3680481/il2cpp.zip)

**Comment by Perfare** [comment]
This is the basic c# knowledge, the abstract method is an unimplemented method.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/abstract
