### ISSUE TITLE
生成得script.py 不支持IDA7.4

### ISSUE THREAD

**Issue by dlnn** [Perfare/Il2CppDumper#189]
新的IDC API https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

替换成
def SetString(addr, comm):
	global index
	name = "StringLiteral_" + str(index);
	ret = idc.set_name(addr, name, SN_NOWARN)
	idc.set_cmt(addr, comm, 0)
	index += 1

def SetMethod(addr, name):
	i = 0
	ret = idc.set_name(addr, name, SN_NOWARN)
	if ret == 0:
		new_name = name + '_' + str(addr)
		ret = idc.set_name(addr, str(new_name), SN_NOWARN)

def MakeFunction(start, end):
	if GetFunctionAttr(start, FUNCATTR_START) == 0xFFFFFFFF:
		ida_funcs.add_func(start, end)
	else:
		idc.SetFunctionEnd(start, end)
就好了

**Comment by Perfare** [comment]
感谢提醒

**Comment by Perfare** [comment]
已更新，顺带改进了一下脚本
