### ISSUE TITLE
Can't get memory dump file to work

### ISSUE THREAD

**Issue by jacobsorrell** [Perfare/Il2CppDumper#191]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v4.6.0

- Target Unity version
2018.2.15f1

- Describe the issue
I tried all methods on regular "libil2cpp.so", but they all failed. Advanced mode gave me registration points but it still failed.
![error1](https://user-images.githubusercontent.com/50650501/67586584-4a490d00-f795-11e9-989d-417baadd68f5.png)

So I tried a memory dump from GameGuardian. I hopefully picked the right memory file & dump address, but now it can't find the Registration points, and fails.
![error](https://user-images.githubusercontent.com/50650501/67586476-0fdf7000-f795-11e9-851a-bf7e1649ee13.png)

The game is Ulala, https://apkpure.com/ulala-idle-adventure/com.xdg.and.wll. Can you help me?

- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/3772864/files.zip)

**Comment by Perfare** [comment]
Your maps file tells you that libil2cpp.so is at 0x08000000, but the file you selected is start from 0x04000000, so you need to cut dump file at 0x08000000 - 0x04000000.

**Comment by jacobsorrell** [comment]
That worked! I manually entered the 08000000 address into game guardian and I was able to dump the file 👍 

![success](https://user-images.githubusercontent.com/50650501/67614693-c0d12380-f804-11e9-9072-9a2e190f24ca.png)
