### ISSUE TITLE
Dump offsets without dummy dll generation

### ISSUE THREAD

**Issue by Symbai** [Perfare/Il2CppDumper#192]
Would this be possible to add? This would allow removing mono cecil as reference let us skip this dummy dll step completely which currently takes 2/3 of overall time.

Also an option to skip certain modules would be nice to lower performance footprint. Most standard unity dlls for example are not required to dump most of the time.

**Comment by Perfare** [comment]
I don't think it will take much time. From my experience, generating dummy dll will not exceed ten seconds in total.
Please use config.json to control this behavior.
