### ISSUE TITLE
Why Field no Offset when dump from dump.so?

### ISSUE THREAD

**Issue by ngoalong123** [Perfare/Il2CppDumper#193]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 4.6.0

- Target Unity version: All version

- Describe the issue: Why Field no Offset when dump from dump.so?

IMG dll from libil2cpp-dump.so: https://i.imgur.com/CwYcYJS.png
IMG dll from libil2cpp-normal.so: https://i.imgur.com/94TkJVh.png

**Comment by Perfare** [comment]
This has nothing to do with whether it is a dump, libil2cpp will not contain all the FieldOffset information, some will be generated at runtime, such as generic classes.

**Comment by ngoalong123** [comment]
> This has nothing to do with whether it is a dump, libil2cpp will not contain all the FieldOffset information, some will be generated at runtime, such as generic classes.

Is there any way to get Offsets. I really need it?

**Comment by Perfare** [comment]
Maybe it will be added in the future, but this is not a small project, accuracy is also difficult to verify.

**Comment by ngoalong123** [comment]
> Maybe it will be added in the future, but this is not a small project, accuracy is also difficult to verify.

Thank you so much

**Comment by Perfare** [comment]
Fixed a bug that could cause this problem, Please download the latest version.
