### ISSUE TITLE
无法DUMP国服公主连接

### ISSUE THREAD

**Issue by EtherealAO** [Perfare/Il2CppDumper#197]
- Il2CppDumper版本
4.7.0
- 目标Unity版本
2017.4
- 问题描述
用gameguardian dump出libil2cpp.so，并参照https://floe-ice.cn/archives/96 进行修复&DUMP，所有模式都无法正常使用(ERROR: Can't use this mode to process file, try another mode.)
也参照过https://bbs.pediy.com/thread-192874.htm 进行修复，同样无法dump
- 上传可执行文件和global-metadata.dat
原包https://pkg.biligame.com/games/gzljReDive_2.4.3.1101_20191101_064553_885d3.apk
dump出的未经修改的https://pan.baidu.com/s/1y4kL3QsSe3einhzvv6w17g 提取码: gwrj

**Comment by Perfare** [comment]
第一个浮冰的教程有点老了，我已经修改了处理dump so的逻辑，至于第二篇修复section其实是没有任何用处的。
首先下载4.7.1版，这个版本Auto和Auto(Plus)都能处理这个文件
Auto：
从源so文件复制elf_header以及program_header_table，就这个so而言，长度为0x120，然后就可以用Il2CppDumper载入了
Auto(Plus)：
从源so文件复制elf_header以及program_header_table，长度为0x120，然后修改属性为RX和RW的loadable segment将起始地址全填为0，长度填为so的大小，用Il2CppDumper载入后可以用Auto(Plus)暴力搜索出指针地址

**Comment by lyndmi** [comment]
Mine still fail to dump, auto and auto (plus) didn't work. Can you check this file? https://anonfile.com/haEfx9A8n3/dump_orig_zip
And by Start address, do you mean VIRTUAL_ADDRESS?

**Comment by codingEnzo** [comment]
Il2CppDumper版本
4.7.1
目标Unity版本
2017.4
问题描述
按照上述方法无法dump
上传可执行文件和global-metadata.dat
原包https://pkg.biligame.com/games/gzljReDive_2.4.3.1101_20191101_064553_885d3.apk
dump出的未经修改的链接: https://pan.baidu.com/s/1k5f38SvNhwG7eJe9Y3ZCWg 提取码: 77vu
