### ISSUE TITLE
Some confused problems

### ISSUE THREAD

**Issue by Chensem** [Perfare/Il2CppDumper#198]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
the latest
- Target Unity version
2017.4.32f1
- Describe the issue

I have met a binary that has been protect , with keywors libNetHTProtect.so .
and no important functions in original libil2cpp.so . so i analyze the .init_array . i find a function like decrypt function . it has memcpy function . so i think this function is a decrypt function . so i tried to dump the memory use ida.
![image](https://user-images.githubusercontent.com/27469499/68488218-88f3c280-027f-11ea-83c2-729e60602d02.png)
![image](https://user-images.githubusercontent.com/27469499/68488204-81341e00-027f-11ea-8f0a-119e49ac9183.png)
i dumped the memory from 0xc2e94000 to 0xc6a36000.
![image](https://user-images.githubusercontent.com/27469499/68488233-97da7500-027f-11ea-99b4-42659a0b41fd.png)
i use xxd tool and i find the ELF's head's infomation has been removed.
![image](https://user-images.githubusercontent.com/27469499/68488354-d2dca880-027f-11ea-99a6-77471c8dee19.png)
and luckily i find this blog https://floe-ice.cn/archives/96 , it has the same situation like this .

with moidy headers and pht and the virtual addr . 

i build the bird 
![image](https://user-images.githubusercontent.com/27469499/68489265-bc375100-0281-11ea-8c20-f5c61f4285bc.png)
and use the auto dump and get the infomation below.
![image](https://user-images.githubusercontent.com/27469499/68489367-ed178600-0281-11ea-8223-02453adebd27.png)
![image](https://user-images.githubusercontent.com/27469499/68489422-03bddd00-0282-11ea-98e8-77726d54af1f.png)
and get the bytecode .  this is not neccessery , copy the bytecode in blog just ok. then search these hex bytes in ida . with the result below.
![image](https://user-images.githubusercontent.com/27469499/68519865-c03d9000-02ce-11ea-85a7-82348e768ee7.png)
![image](https://user-images.githubusercontent.com/27469499/68519902-ec591100-02ce-11ea-9dda-b0bdad4a3891.png)
the value is too small at C68374EC , so i can't calculate the addr of metadataRegistration . 
![image](https://user-images.githubusercontent.com/27469499/68519955-43f77c80-02cf-11ea-8dc4-7ce2aea8312c.png)
but i find the offset of metadataRegistration and codeRegistration is 56 . 
![image](https://user-images.githubusercontent.com/27469499/68519981-70ab9400-02cf-11ea-87dd-60dbc6d5f6a6.png)
so i get the metadataRegistration . it's addr is 
![image](https://user-images.githubusercontent.com/27469499/68520061-eadc1880-02cf-11ea-9681-07fdbd49d08e.png)
![image](https://user-images.githubusercontent.com/27469499/68520072-f92a3480-02cf-11ea-8df4-8d4d1e2602ba.png)
but , but , it failed . i don't know what't wrong. wish you can help me.

- Upload executable file and global-metadata.dat
https://mega.nz/#!Wr4HDCLC  the original il2cpp.so
https://mega.nz/#!S2ZTzKJD the so i dumped
https://mega.nz/#!OjRzzA7R the metadata

**Comment by Perfare** [comment]
#197
