### ISSUE TITLE
Access Static Class Values

### ISSUE THREAD

**Issue by PiotrKFtw** [Perfare/Il2CppDumper#199]
Let's say il2cpp dumper dumped fully static class Profile
```
public static class Profile
{
    [FieldOffset("0x8")]
    public static string Name;
}
```
How do I get address to values from that static class or how do i ``typeof(Profile)``?
```String* name = (String*)(StaticProfileAddress? + 0x8)```

**Comment by Perfare** [comment]
Look at script.py to find something like "Class${namespace}{classname}"

**Comment by PiotrKFtw** [comment]
> Look at script.py to find something like "Class${namespace}{classname}"

Yes but that points to nowhere because the string size is over 3 million or it simply crashes game.
```
String* name = (String*)((*(DWORD*)(gameAssHandle + (Class_Profile - imageBase32) + 92) + 0x8);
cout << name->size << endl;
```
