### ISSUE TITLE
Offset off by 1

### ISSUE THREAD

**Issue by nicoschmitt** [Perfare/Il2CppDumper#2]
Thanks for you work. I'm using part of you logic for iOS in a similar project of mine, and at the end it seems the method offset are off by 1.

I'm wondering if it has something to do with the "-1" you have here: https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Macho.cs#L70.

However, offset I found are 1 bigger, not 1 lower from the correct ones...

**Comment by Perfare** [comment]
In Mach-O, the methon pointer address is always +1, I think this is not much affected so I don't handle it.
You can make all the elements -1 in methodPointers and customAttributeGenerators If you want the right address

**Comment by nicoschmitt** [comment]
ok, good to know thanks
