### ISSUE TITLE
Il2cpp Replica of Nested classes

### ISSUE THREAD

**Issue by PiotrKFtw** [Perfare/Il2CppDumper#201]
i got class
```
class GUILayoutGroup
{
    class LayoutCache
    {
    }
}
```
in normal C# i would do ``GUILayoutGroup.LayoutCache``
but what do i input to ``il2cpp_class_from_name`` to get that class?

**Comment by Perfare** [comment]
If you want to create an instance of a class, using ```il2cpp_runtime_class_init(Il2CppClass* klass)```, The pointer to Il2CppClass can be found in script.py like ```Class${namespace}{classname}```

**Comment by PiotrKFtw** [comment]
> If you want to create an instance of a class, using `il2cpp_runtime_class_init(Il2CppClass* klass)`, The pointer to Il2CppClass can be found in script.py like `Class$GUILayoutGroup.LayoutCache`

``GUILayout.LayoutCache`` Doesn't work in ``il2cpp_class_from_name``.

**Comment by Perfare** [comment]
```il2cpp_class_from_name``` function prototype is ```Il2CppClass* il2cpp_class_from_name(const Il2CppImage* image, const char* namespaze, const char *name)```, confirm that you provided the correct parameters.

**Comment by PiotrKFtw** [comment]
> `il2cpp_class_from_name` function prototype is `Il2CppClass* il2cpp_class_from_name(const Il2CppImage* image, const char* namespaze, const char *name)`, confirm that you provided the correct parameters.

Confirmed.

**Comment by Perfare** [comment]
I can't help you more, but I think the ```Class$GUILayoutGroup.LayoutCache``` address in script.py is the pointer to the Il2CppClass you want.

**Comment by Perfare** [comment]
I haven't received your reply in a week. I think you have solved this problem. If you have other questions, you can reopen it or create a new one. I will answer you within the scope of my ability.
