### ISSUE TITLE
ERROR: Some errors in dumping

### ISSUE THREAD

**Issue by a-ahmed** [Perfare/Il2CppDumper#203]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
5.0.0
- Target Unity version
2018.1
- Describe the issue
I got the following error

Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Searching...
CodeRegistration : 1499190
MetadataRegistration : 14991d8
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate script...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.ScriptGenerator.WriteScript(StreamWriter writer, Config confi
g) in C:\projects\il2cppdumper\Il2CppDumper\ScriptGenerator.cs:line 21
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp) in C:\projects
\il2cppdumper\Il2CppDumper\Program.cs:line 277
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2Cp
pDumper\Program.cs:line 87
Press any key to exit...

I tried all other mode but without success

[so_meta.zip](https://github.com/Perfare/Il2CppDumper/files/3852701/so_meta.zip)

- Upload executable file and global-metadata.dat

**Comment by Perfare** [comment]
Unable to reproduce this error, this file can be processed normally.

**Comment by a-ahmed** [comment]
What mode did you used? I used "2" again also I am using windows7

**Comment by a-ahmed** [comment]
I works now!!,, wondering what was wrong, sorry, and thanks for help, greetings!
