### ISSUE TITLE
Please Help Me Fix It

### ISSUE THREAD

**Issue by ngoalong123** [Perfare/Il2CppDumper#204]
this global-metadata.dat not encrypted it only changed header. And how to fix it? thank you so much.

- Upload executable file and global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/3853826/global-metadata.zip)

**Comment by Perfare** [comment]
As long as the format of global-metadata.dat is not a standard format, it can be considered encrypted and does not solve any problems with encryption.
