### ISSUE TITLE
No Values

### ISSUE THREAD

**Issue by brunovarelaAptoide** [Perfare/Il2CppDumper#208]
- Il2CppDumper version
latest
- Target Unity version
2019.2

- Describe the issue
I can see all the classes and fields but no values.

- Upload executable file and global-metadata.dat

**Comment by Perfare** [comment]
Can't understand what you're talking about.

**Comment by brunovarelaAptoide** [comment]
In the generated dump you can get the the variables names but how can I get the variable values?
Example:
private static byte[] data; // 0x58F8 -> how can I get the value of this variable?

**Comment by Perfare** [comment]
View the code of the .cctor function of the static class.

**Comment by Perfare** [comment]
I don't know if you want to get the value at runtime or something else, you need to describe your problem in detail.

**Comment by brunovarelaAptoide** [comment]
The information we get on the dumper file is:
- Methods,Classes,Variables Name,Offsets etc.

Besides this information can we get the variables value on the execution of the dumper?

Thank you for your answers btw.

**Comment by Perfare** [comment]
I think you lack some knowledge, the value of variables can be changed at runtime, they may not have a fixed value.

**Comment by brunovarelaAptoide** [comment]
You're right, the value can change, however I'm interested in the value that is assigned in compile time to specific variables. Am I able to obtain that using your tool?

**Comment by Perfare** [comment]
Go to the .cctor function of the static class to see the value of the variable initialization.

**Comment by brunovarelaAptoide** [comment]
What do you mean by the static class? the Dump.cs?We have this in the dumper file:

	private static byte[] data; // 0x58F8
	public static readonly bool IsPopulated; // 0xC0000

	// Methods
	public static byte[] Data(); // RVA: 0x1024964 Offset: 0x1024964
	public void .ctor(); // RVA: 0x1024B28 Offset: 0x1024B28
	private static void .cctor(); // RVA: 0x1024B54 Offset: 0x1024B54

Is this .cctor() ?

**Comment by Perfare** [comment]
Yes
If you write code like this
```
static class Test
{
    private static byte[] data = new byte[] { 0x0 };
}
```
After compiling its actual code is
```
static class Test
{
    private static byte[] data;

    private static void .cctor()
    {
        data = new byte[] { 0x0 };
    }
}
```
So you need to view the .cctor code of the static class to get its initialization value

**Comment by brunovarelaAptoide** [comment]
The problem is how can I find .cctor() code?

**Comment by Perfare** [comment]
Use ida or other decompiler.
