### ISSUE TITLE
王者榮耀

### ISSUE THREAD

**Issue by cctgapp** [Perfare/Il2CppDumper#210]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
5.0.4
- 目标Unity版本
5.6
- 问题描述
遊戲為王者榮耀
Auto模式都失敗，嘗試手動模式不會找。
- 上传可执行文件和global-metadata.dat
檔案太大無法上傳，請到以下連結下載：
https://drive.google.com/file/d/1QVUjqFmU37c8Zzv1fNPYIGCcJkx2R0UJ/view?usp=sharing

**Comment by 2689480146** [comment]
手动模式也不行的，同样会失败

**Comment by Perfare** [comment]
王者荣耀修改了il2cpp格式，请自行解决

**Comment by enjoyMiracle** [comment]
android 版本的能够dump 出来， ios的不行
