### ISSUE TITLE
Doesn't work with wine anymore on linux

### ISSUE THREAD

**Issue by werererer** [Perfare/Il2CppDumper#213]
- Il2CppDumper version: 5.0.4

- Target: any unity version

- the program freezes after entering the unity version. I tried it with wine and wine staging on archlinux & different games 

example files: 
[files.zip](https://github.com/Perfare/Il2CppDumper/files/3964252/files.zip)

**Comment by Perfare** [comment]
I'm sorry this program is just a PC program. I haven't tested it in other environments and can't guarantee normal operation.

**Comment by toluschr** [comment]
> I'm sorry this program is just a PC program. I haven't tested it in other environments and can't guarantee normal operation.

It works fine for me on Linux. Just [install dotnet-core](https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh
) and run the application using `dotnet Il2CppDumper.dll`

**Comment by Mr-Precise** [comment]
(note)
Debian 10 / Ubuntu 20.04,  Mono 6.12
https://www.mono-project.com/download/nightly/
sudo apt install mono-complete
Il2CppDumper.exe run as Mono-Runtime...
works good
