### ISSUE TITLE
DUMMYDLL ERROR

### ISSUE THREAD

**Issue by RevealedSoulEven** [Perfare/Il2CppDumper#214]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 5.0.4

- Target Unity version 2019.0.2

- Describe the issue whenever i dunno using il2cpp dumper it can't create dummy dll! Trying with garena free fire

- Upload executable file and global-metadata.dat

**Comment by Perfare** [comment]
You did not upload executable file and global-metadata.dat
