### ISSUE TITLE
ERROR: Metadata file supplied is not valid metadata file.

### ISSUE THREAD

**Issue by Symbai** [Perfare/Il2CppDumper#216]
- Il2CppDumper version `5.0.4`
- Target Unity version  `2018.3.11`
- Describe the issue:
After selecting GameAssembly.dll and metadata file from a Windows game it immediately throws an exception: `"ERROR: Metadata file supplied is not valid metadata file."` at `Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp)`

[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/4008254/GameAssembly.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4008256/global-metadata.zip)

**Comment by zakoh99** [comment]
bro do you know how can I find dump address?

**Comment by Symbai** [comment]
Nvm saw the readme says this error should not be reported..
