### ISSUE TITLE
How can I find dump Address

### ISSUE THREAD

**Issue by zakoh99** [Perfare/Il2CppDumper#217]
![Capture](https://user-images.githubusercontent.com/59339458/71559641-a6812380-2a9b-11ea-8a44-79fb1860341f.PNG)

- Il2CppDumper version -> Il2CppDumper v5.0.4

- Target Unity version -> 2017.4.23f1

- Describe the issue -> it asked to Input dump address,  how can I find it

- Upload executable file and global-metadata.dat - > https://easyupload.io/by6jr3

**Comment by Perfare** [comment]
View the dumped folder and you will see a *-maps.txt file. Open and find the 'libil2cpp' line.

**Comment by zakoh99** [comment]
There is no dumped folder and *-maps.txt file , can u show me how can I find dumped folder via pic ? Sorry bro I know I'm stupid

**Comment by Perfare** [comment]
I know from your description that this is not a dumped so file, the program has obviously prompted you that if it is not a dumped file, it is a protected file.
