### ISSUE TITLE
某游dump不完整

### ISSUE THREAD

**Issue by kotoricon** [Perfare/Il2CppDumper#219]
版本5.0.4

目标版本5.6.7

已确定是MTP壳，dump出bin后进行操作手动输入地址虽然工具提示dump成功，其实全是没用的地方关键部分全部无法dump。
已确定dat未加密或修改
[MobileFile.zip](https://github.com/Perfare/Il2CppDumper/files/4009591/MobileFile.zip)

**Comment by Perfare** [comment]
如果程序运行没有报错，dump.cs就是全部内容了，如果你说找不到你想要的东西，应该你自己解决，跟本程序无关
