### ISSUE TITLE
Can't dump 64-bit binary using auto mode (iOS)

### ISSUE THREAD

**Issue by evildog1** [Perfare/Il2CppDumper#22]
Dumping 32-bit works but not 64-bit, I got this error. I tried to dump other iOS il2cpp games but same issue.
I can't do manual mode because i don't know where to find offsets in 64-bit binary

Link to binary file: http://www.mediafire.com/file/um78d8285govpg9/iosbinary.zip
```
ERROR: Unable to process file automatically, try to use manual mode.
   ved Il2CppDumper.Program.Main(String[] args) i C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linje 88
Press any key to exit...
```

**Comment by Perfare** [comment]
see https://github.com/Perfare/Il2CppDumper/issues/9#issuecomment-311943859
I have to say, these same questions will make me feel that adding auto feature is a bad decision
#19 #18 #9 #7

**Comment by evildog1** [comment]
Oh well but put that infomation in README, because not everyone will read into closed issues.

**Comment by Perfare** [comment]
I added a new auto model, now can handle some couldn't handled file, including this one you uploaded.
