### ISSUE TITLE
Unable to use with specific game

### ISSUE THREAD

**Issue by cra0kalo** [Perfare/Il2CppDumper#221]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper-v5.0.4
- Unknown?

- Describe the issue
Unable to process this with the latest version, it might be packed or encrypted 

- Upload executable file and global-metadata.dat
https://drive.google.com/open?id=1qXDKOJCKGtgf_P58pAL65tnhD2mCMMRI

**Comment by Perfare** [comment]
When you select a file, the program will tell you if the file is protected.
