### ISSUE TITLE
Problem with auto modes

### ISSUE THREAD

**Issue by Xrom666** [Perfare/Il2CppDumper#223]
Hi!
Il2CppDumper version 5.0.4
Target Unity version 2018.4
Describe the issue: all automated extraction modes failed with this error
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   в Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String
stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp) в C:\projects\il2
cppdumper\Il2CppDumper\Program.cs:line 261
   в Il2CppDumper.Program.Main(String[] args) в C:\projects\il2cppdumper\Il2CppD
umper\Program.cs:line 85
[files.zip](https://github.com/Perfare/Il2CppDumper/files/4112158/files.zip)

**Comment by Perfare** [comment]
Please give me the full Unity version like '2018.4.16f1'

**Comment by Xrom666** [comment]
> Please give me the full Unity version like '2018.4.16f1'

2018.4.0f1

**Comment by Perfare** [comment]
global-metadata.dat and il2cpp.so do not match, please make sure you select the correct global-metadata.dat, otherwise global-metadata.dat has been modified.
