### ISSUE TITLE
Protected File?

### ISSUE THREAD

**Issue by PhoenixICE** [Perfare/Il2CppDumper#225]
Hi,

Input Unity version:
2017.4.35f1
Initializing metadata...
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file is protected.

Just curious what are you suppose to do when it requires you to find .init_proc - you can find it in ida but I couldn't find any information on what to do when you find it.

If you need the files:

2017.4.35f1
[il2cpp-ark.7z](https://drive.google.com/file/d/1OOI54d6MOJhgxncGHd4ZangOgKDthDvE/view?usp=sharing)

**Comment by Perfare** [comment]
This just reminds you that Il2CppDumper found .init_proc in the executable file, 99% of the files containing this feature have been protected.
If you want to bypass protection you can use a gameguardian dump .so file and then use Il2CppDumper to process it.
