### ISSUE TITLE
Code and matadata registration are not found in binary file

### ISSUE THREAD

**Issue by AndnixSH** [Perfare/Il2CppDumper#226]
- Il2CppDumper version: 5.0.4

- Target Unity version: 5.6.3p4

- Describe the issue: Tried both auto and auto plus, both failed.

```
Initializing metadata...
Initializing il2cpp file...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   ved Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp) i C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linje 261
   ved Il2CppDumper.Program.Main(String[] args) i C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linje 85
Press any key to exit...
```

I tried manual way, searched byte patteren `88 12 40 F9 00 01 3F D6 88 06 40 F9` and xrefs to locate them but the offsets are missing 

This video explains all. Left side is this binary and right side is other game with 5.6.4.p4 version
https://streamable.com/5v73y

![image](https://user-images.githubusercontent.com/40742924/73598932-4bc96480-453e-11ea-910e-9b5fdfd13290.png)

- Upload executable file and global-metadata.dat
Binary file is iOS executeable and is decrypted
https://drive.google.com/file/d/1NEbd8K8Mb1HPFpJ9uWsrWrmZKyMRArWU/view

**Comment by Perfare** [comment]
The game modified the il2cpp format, it will not be supported. #210

**Comment by AndnixSH** [comment]
So how can I figure it out the custom il2cpp format?

**Comment by Perfare** [comment]
I don't work on ios so I don't know if it works.
On Android, you can hook the basic functions of il2cpp like "il2cpp_class_from_name" "il2cpp_class_get_method_from_name" to get the information you want.

**Comment by anish23884** [comment]
at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration,

**Comment by anish23884** [comment]
ERROR: This file may be protected.
Il2Cpp Version: 23
Searching...
CodeRegistration : 32b74bc
MetadataRegistration : 32b74f4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration)
