### ISSUE TITLE
Generation of Headers for IDA

### ISSUE THREAD

**Issue by CheatBoss** [Perfare/Il2CppDumper#227]
Header generation will be a useful feature for analyzing applications. I tried to implement this myself, but I don’t know how to implement generic types and getting array sizes.
I found a program that generates headers from data obtained at runtime but it is very difficult to use.
https://github.com/tacesrever/Il2CppParser
Is it possible to recreate something similar to this using data from global-metadata and binary?

**Comment by Perfare** [comment]
I have actually completed a similar project, but I have not released it for the following reasons:

1. Static fields are pointers and are assigned at runtime, cannot define it when using the same Il2CppClass as the base class. Unless I define a separate Il2CppClass base class for each class, but this will cause too much data. The project you mentioned does not deal with it too and does not output any static field information.
2. The ida script generated by Il2CppDumper already contains enough information, compared with the project you mentioned, it just lacks the definition of non-static fields, but Il2CppDumper also output the field offset. It ’s just that you can’t directly see what fields in ida, you need to confirm in dump.cs.

I am currently adding new feature to Il2CppDumper, and may release it when I am done.

> I don’t know how to implement generic types and getting array sizes
Sorry i didn't understand your question, please elaborate and let me know what you want to do

**Comment by CheatBoss** [comment]
C# generics - https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/


They can be implemented in C++ headers:
![example](https://user-images.githubusercontent.com/17236577/74098994-6607d180-4b40-11ea-82ce-9245a1f23280.png)
but IDA does not support C++ headers.
I already found a solution for this, need to find all uses of the generic class and create a structs for each type:
![IDASolution](https://user-images.githubusercontent.com/17236577/74100745-d9670e80-4b53-11ea-9bdf-a6e92bd069f0.PNG)



Sorry, I made a mistake with arrays, I forgot that the array in IL2CPP is an independent object and they have a fixed size in the struct

**Comment by Perfare** [comment]
Il2cpp does not use C ++ templates to handle generic classes, it also creates a separate structure for each generic instance. After all, there are many differences between c++ templates and c # generics.
By the way, I have plans to release this feature in the near future, although there are still some problems with static variables and other things

**Comment by Perfare** [comment]
I have released Il2CppDumper v6.0.0 and implemented this feature, and solved the static fields problem mentioned earlier.
But there are still some minor problems
* Only support 22 ~ 24.2 version, below version 22, il2cpp significantly changed the Il2CppClass structure, because the version is too old and no longer planned to be implemented.
* The array type will only be output as Il2CppArray. I need to take a moment to think about how to deal with it.
