### ISSUE TITLE
Cant use auto mode

### ISSUE THREAD

**Issue by qwAAQ** [Perfare/Il2CppDumper#228]
I'm trying to dump but says auto mode can't be used

Unity version: 2018.4.2f1
It however differs across the resource files.

[files](https://mega.nz/#!IktQjKJA!0oflFYJj6XSInq-fztlW_5u_fPYbscDw209MI3Xd-JQ)

**Comment by Perfare** [comment]
Pc game executable file is `GameAssembly.dll` or `*Assembly.dll`, not .exe file

**Comment by qwAAQ** [comment]
Ahh ok thanks, it worked.
