### ISSUE TITLE
ghidra.py chokes

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#229]
- Il2CppDumper 5.1.0

- Unity version: 2018.4

- ghidra.py script is very slow, uses many CPU resources for nothing

I have tried it on Ghidra 9.1.1 with Ash of Gods Switch game. Ida.py has 24 MB.
After 5 hours it still didn't finish job.
I have edited old script to include your functions with main function untouched and it works as intented - in one minute everything is done.
https://gist.github.com/masagrator/f21a0bb7b882b509c34beba7d2258b5d

**Comment by Perfare** [comment]
Your script doesn't handle MakeFunction. If you don't want this feature, you can modify `config.json` set `MakeFunction` to false, will be exactly the same as your script.

**Comment by therealchjones** [comment]
In my cursory testing, it appears that it's the getFunctionAfter call that's causing excessive delays on large programs. Attempting to modify to mitigate.
