### ISSUE TITLE
ll2CppDumper Manual Mode

### ISSUE THREAD

**Issue by KingKong5147** [Perfare/Il2CppDumper#23]
Hi just seeing if you can supply a guide for using in manual mode? , the picture supplied does not show clearly how to use. Obviously you need an address as a pointer tried on a few different games with no success . Please and thank you

**Comment by KingKong5147** [comment]
I can supply a binary and metadata for example if you would like?

**Comment by KingKong5147** [comment]
http://iosddl.net/c2ae6f34e3f50f08/l.zip

Here you go

**Comment by Perfare** [comment]
The format of file is very special, I don't think it's significant to research this format

**Comment by KingKong5147** [comment]
I can understand that but is there a way to find the pointer ?

**Comment by Perfare** [comment]
May have. But I didn't research the file, I can't help you.

**Comment by KingKong5147** [comment]
Awesome 👏 make a program that does half a job 👏👏

**Comment by Perfare** [comment]
A good news, I added a new auto model, now we can get CodeRegistration in version 16.
I tested the files you provided and get these
32bit:
CodeRegistration : 25e9ddc
64bit:
CodeRegistration : 102c63180
In 32bit, go to offset 25e9ddc in IDA then we can see a function reference it
> __const:025E9DDC unk_25E9DDC     DCB 0x10                ; DATA XREF: sub_D7F7AE+12
go to sub_D7F7AE and then we'll see

> __text:00D7F7AE sub_D7F7AE                              ; DATA XREF: InitFunc_6_0+14o
__text:00D7F7AE                 MOV             R1, #(off_25C7080 - 0xD7F7BE)
__text:00D7F7B6                 MOVW            R0, #(:lower16:(unk_25E9DDC - 0xD7F7C4))
__text:00D7F7BA                 ADD             R1, PC ; off_25C7080
__text:00D7F7BC                 MOVT.W          R0, #(:upper16:(unk_25E9DDC - 0xD7F7C4))
__text:00D7F7C0                 ADD             R0, PC ; unk_25E9DDC
__text:00D7F7C2                 LDR             R1, [R1] ; unk_262EF74
__text:00D7F7C4                 B.W             sub_D7F7C8
262EF74 is MetadataRegistration
Use manual mode and input 25E9DDC, 262EF74, dump will succeed.

**Comment by KingKong5147** [comment]
This with arm64 support ?

**Comment by Perfare** [comment]
It can be supported, even though I haven't tested it.
You just have to look at what I do, and you can easily get the MetadataRegistration in 64 bits.
And I think this issue has been solved, I'll close it.
