### ISSUE TITLE
TypeError: add(): 1st arg can't be coerced to long

### ISSUE THREAD

**Issue by RayFirefist** [Perfare/Il2CppDumper#231]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
5.1.0 and 5.0.4

- Target Unity version
2019.1

- Describe the issue

I tried to load the ghidra.py script with the generated ida.py/script.py and when I reached the end I got this exception

(10715886541006636002L, '0x94B67A08AA1703E2') # this line is printed by an edit of mine
Traceback (most recent call last):
  File "/Users/admin/ghidra_scripts/ghidra.py", line 73, in <module>
    res = globals()['do_'+name.replace('.', '_')](arg1, arg2.replace(' ', '-'))
  File "/Users/admin/ghidra_scripts/ghidra.py", line 48, in do_MakeFunction
    addr2 = _convert_arg_addr(arg2)
  File "/Users/admin/ghidra_scripts/ghidra.py", line 19, in _convert_arg_addr
    raise e
TypeError: add(): 1st arg can't be coerced to long

- Upload executable file and global-metadata.dat
https://drive.google.com/open?id=1GhGLnKsz57aQJ78vu6KBjRPqDAkfOvTo # iOS Decrypted bin
https://drive.google.com/file/d/1jkYF-tCu6zxvMuqVGzK8qhMB6ZhUAZ1W # its global-metadata.dat

**Comment by Perfare** [comment]
This is a very special case for this file, edit ida.py to remove the last two MakeFunction codes.

**Comment by Perfare** [comment]
Rewritten ghidra script, please use latest version.

**Comment by Perfare** [comment]
In addition, when using Ghidra, it is recommended to set the `MakeFunction` in config.json to false
