### ISSUE TITLE
Auto mode not working (particular iOS app)

### ISSUE THREAD

**Issue by Noel-K** [Perfare/Il2CppDumper#232]
- Il2CppDumper version
5.1.0
5.0.4

- Target Unity version
2019.3.0f6

- Describe the issue
Auto mode not working.
Same as #210?

5.1.0:   Search failed
```
Initializing metadata...
Initializing il2cpp file...
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: シーケンスに、一致する要素は含まれてません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   場所 Il2CppDumper.Macho64.Search() 場所 C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:行 144
   場所 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp) 場所 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行 249
ERROR: An error occurred while processing.
```

5.0.4:  Can't use auto mode.
```
Initializing metadata...
Initializing il2cpp file...
Searching...
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   場所 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp) 場所 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行 261
   場所 Il2CppDumper.Program.Main(String[] args) 場所 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行 85
```
- Upload executable file and global-metadata.dat
https://drive.google.com/file/d/1-504AvGP3usI9xiGPlh9yDS5jT76M0aP/view
The file contains decrypted binary and global-metadata.dat

**Comment by Perfare** [comment]
You selected the wrong executable file

**Comment by Noel-K** [comment]
Thank you, 
but no other executable file in app root directory.
 * The file in zip file was renamed. [EternalOfficial] was original.

This app is not a official release but a TestFlight app.
It may be related to the problem, but I don't know...

**Comment by Perfare** [comment]
I don't know how you do it. On ios, usually use some tools such as [Clutch](https://github.com/KJCracks/Clutch) or [frida-ios-dump](https://github.com/AloneMonkey/frida-ios-dump) to get the decrypted ipa package, and then decompress it to get the executable file and global-metadata.dat.
