### ISSUE TITLE
show is wrong meta file 

### ISSUE THREAD

**Issue by daiviswang** [Perfare/Il2CppDumper#234]
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 111
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 73
Press any key to exit...

是不是因为metadata 被更改了？

**Comment by Perfare** [comment]
是的
