### ISSUE TITLE
Modified il2cpp structure.

### ISSUE THREAD

**Issue by TrueLecter** [Perfare/Il2CppDumper#235]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.0.1

- Target Unity version: Not sure, but AssetStudio shows for game assets 2018.4.16f1

- Describe the issue: 
![image](https://user-images.githubusercontent.com/5520406/75462212-94810b80-598c-11ea-90fc-dadb7de7da8a.png)

Tried with both x86 and arm libraries. Generated dump.cs contains some classes/structures, but their names are seem to be clipped: 
![image](https://user-images.githubusercontent.com/5520406/75462663-3c96d480-598d-11ea-92f4-784d5e318719.png)

- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/4262608/files.zip)

**Comment by Perfare** [comment]
I think libil2cpp.so does not match global-metadata.dat, please make sure these two files come from the same installation package

**Comment by TrueLecter** [comment]
Here is the apk what I'm trying to dump from: https://apkpure.com/crusaders-quest/com.nhnent.SKQUEST/download?from=details

Both those files are from this apk. libil2cpp.so is from lib/x86 folder and global-metadata.dat is from assets/bin/Data/Managed/Metadata/

**Comment by Perfare** [comment]
Got it, i will check it.

**Comment by Perfare** [comment]
I checked it and was sure the game modified the il2cpp structure.

**Comment by TrueLecter** [comment]
Any chance you can help me with dumping? Or point a direction where I can try investigating?

**Comment by bastiflew** [comment]
Same issue with RAID Shadow Legends with v6.0.2, was working fine with v5.2.6

**Comment by Perfare** [comment]
@bastiflew Thanks for your feedback, this is not the same bug, I have fixed it in 6.0.3.

**Comment by TrueLecter** [comment]
If you can link me dumping instructions, I can try dumping library from memory and try il2cpp dump again.

**Comment by Perfare** [comment]
@TrueLecter Sorry to reply you so late. Sorry i only know one solution, if you are good at Android injection and C programming, you can use il2cpp export functions such as `il2cpp_class_get_method_from_name `to get the data you want at runtime.

**Comment by TrueLecter** [comment]
Do you have any more info regarding this function? Or may be some useful resources regarding it?

**Comment by Perfare** [comment]
They are all exported functions of libil2cpp.so, You can find more complete function information in `il2cpp-api-functions.h`, `il2cpp-api-functions.h` exists in the Unity installation package.

**Comment by HimekoEx** [comment]
func `DO_API(const MethodInfo*, il2cpp_class_get_methods, (Il2CppClass * klass, void* *iter));`
