### ISSUE TITLE
Getting asset encryption keys from a il2cpp game?

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/Il2CppDumper#24]
Hello Perfare, I could not figure out any way to contact you other than an issue here. I'm looking to get the aes encryption keys they use to decrypt oggs and other assets in Super Mario Run. I noticed its a il2cpp game and tried everything possible to find them but could not.
An example of an encrypted file is here: https://download-cdn-supermariorun.akamaized.net/native/e07e1191b490a31c/3.0.1/raw/RawSound/DeALProject.json
And one of the encrypted OGG: https://download-cdn-supermariorun.akamaized.net/native/e07e1191b490a31c/3.0.1/raw/RawSound/sound/BGM/Athletic_RB_32.ogg

il2cppdumper dumped things like get_OggEncryptionAesKey but I cannot figure out how to actually get the key it refers to?

**Comment by KingKong5147** [comment]
He has a website https://www.perfare.net/ try him there . I'm still waiting for my issue to be resolved :(

**Comment by evildog1** [comment]
It's a custom encryption by Nintendo. It have nothing to do with il2cpp

**Comment by Perfare** [comment]
I think you should put this question to the hacking forum, so that other people can help you.
