### ISSUE TITLE
Problem with dump file

### ISSUE THREAD

**Issue by den2412** [Perfare/Il2CppDumper#240]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
latest - 6.0.3
- Target Unity version
2018.4.12f1
- Describe the issue
The libil2cpp file is protected. I made a memory dump, but it says that the file is not supported, although it gives a version of metadata 24,1
- Upload executable file and global-metadata.dat
[Files.zip](https://github.com/Perfare/Il2CppDumper/files/4297899/Files.zip)

**Comment by Perfare** [comment]
Copy missing headers from source file to dumped file.
![QQ截图20200306195801](https://user-images.githubusercontent.com/12952226/76081848-fa9d0c80-5fe4-11ea-9c4f-8314dc90c44d.png)
Then use the latest 6.1 version to load.
