### ISSUE TITLE
Can't use auto mode

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#241]
- Il2CppDumper version: 6.1.0

- Target Unity version: 2019.2.4f1

- Describe the issue: "Can't use auto mode to process file, try manual mode."
Executable is not protected

- Upload executable file and global-metadata.dat
[Files.zip](https://github.com/Perfare/Il2CppDumper/files/4299467/Wanderlust.zip)

**Comment by Perfare** [comment]
Updated, please use new version 6.1.1.
