### ISSUE TITLE
Output directory CMD parameter

### ISSUE THREAD

**Issue by LGLTeam** [Perfare/Il2CppDumper#242]
Not an issue. I'm requesting a feature to be able to set output directory in the CMD parameter like `Il2CppDumper.exe <executable-file> <global-metadata> <output-directory>`

**Comment by AlexZonov** [comment]
Really need!)

**Comment by LGLTeam** [comment]
Yeah!

**Comment by Perfare** [comment]
Added.

**Comment by palapapa** [comment]
I specified the output directory but the files are still generated in the current working directory. Version 6.7.25

**Comment by Tey** [comment]
The output directory argument is ignored if the specified output directory does not exist. It would be better that the tool creates the directory if it does not exist yet.
