### ISSUE TITLE
Combat Of Hero iOS 0.1.34 format changed

### ISSUE THREAD

**Issue by cctgapp** [Perfare/Il2CppDumper#243]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.1.1
- Target Unity version
2018.4
- Describe the issue
Since version 0.1.34, the file global-metadata.dat is gone and instead the file game.dat appear, rename it to global-metadata.dat but still fail.
![il2cpp](https://user-images.githubusercontent.com/45614763/76155744-58d40780-612b-11ea-93e2-b840fb7095e6.JPG)

- Upload executable file and global-metadata.dat
[international.zip](https://github.com/Perfare/Il2CppDumper/files/4302759/international.zip)
[game.dat.zip](https://github.com/Perfare/Il2CppDumper/files/4302757/game.dat.zip)

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#common-errors
