### ISSUE TITLE
il2cpp.h can contain multiple fields with the same name

### ISSUE THREAD

**Issue by mid-kid** [Perfare/Il2CppDumper#244]
IDA doesn't like it when multiple struct fields have the same name, even if the types are different. This is simple to fix manually but I'd have the dumper generate different names for these.

**Comment by mid-kid** [comment]
Also `float near;` and `float far;` are apparently abstract declaration.s

**Comment by Perfare** [comment]
> IDA doesn't like it when multiple struct fields have the same name, even if the types are different. This is simple to fix manually but I'd have the dumper generate different names for these.

Normally the field with the same name will be processed. If you still encounter it, please upload executable file and global-metadata.dat.

> Also float near; and float far; are apparently abstract declarations, which are rejected by IDA as well.

Sorry i didn't understand what you were talking about.

**Comment by mid-kid** [comment]
This was encountered with the latest version (v6.1.1), where it generated a structure like this:
```
struct UINamingWonderMail_o {
	UINamingWonderMail_c *klass;
	void *monitor;
	intptr_t Object_m_CachedPtr;
	int32_t syncCount_;
	CommonScreen_o* commonScreenNaming_;
	bool bCancel_;
	System_String_o* rtnText;
	int32_t actionType;
	FiniteStateMachine_UINaming__UINaming_States__o* FSM;
	UINaming_NamingEnterTextWindow_o* UINaming_namingEnterTextWindow_;
	bool bEnd_;
	FiniteStateMachine_UINamingPasswordOld__UINaming_States__o* new_FSM;
	UINamingPasswordOld_NamingPasswordEnterTextWindow_o* UINamingPasswordOld_namingPasswordEnterTextWindow_;
	FiniteStateMachine_UINamingWonderMail__UINaming_States__o* new_FSM;
	UINamingWonderMail_NamingMailEnterTextWindow_o* namingMailEnterTextWindow_;
};
```
This structure contains `new_FSM` twice, which IDA doesn't accept.

> Sorry i didn't understand what you were talking about.

I mean that IDA doesn't accept `float near;` and `float far;` in a structure, because `near` and `far` are reserved names.

**Comment by Perfare** [comment]
I have modified the field processing logic of the same name, and added `near` and `far` to the keyword filtering, please try version 6.1.2.
Also, I can’t determine which keywords are reserved names. If you encounter them, welcome feedback to me.

**Comment by mid-kid** [comment]
`bool flat` is another one.

**Comment by Perfare** [comment]
I have added this keyword. I will close this issue, if you have other questions please open a new issue.
