### ISSUE TITLE
Unhandled C++ exception when use Hexrays with ida_with_struct.py

### ISSUE THREAD

**Issue by JustDragon** [Perfare/Il2CppDumper#246]
- Il2CppDumper version: 6.1.2
- Target Unity version: 2018.4.14f1
- Describe the issue: I'm using IDA 7.2. When I use ida_with_struct.py, I see a lot of apply_type failed in log. If I go to a random function, for example: 0x0362339C. Then I press F5, click on sub_3634850(12266), it will has error Unhandled C++ exception: Unknown exception and close IDA.
I see this error in log too https://imgur.com/a/PwgB1BK
`apply_type failed: 0x362550cL void UnityEngine_CloudBuild_MiniJSON_Json_Serializer__SerializeArray (UnityEngine_CloudBuild_MiniJSON_Json_Serializer_o* this, System_Collections_IList_o* anArray);
apply_type failed: 0x362518cL void UnityEngine_CloudBuild_MiniJSON_Json_Serializer__SerializeString (UnityEngine_CloudBuild_MiniJSON_Json_Serializer_o* this, System_String_o* str);
apply_type failed: 0x3625dd4L void UnityEngine_CloudBuild_MiniJSON_Json_Serializer__SerializeOther (UnityEngine_CloudBuild_MiniJSON_Json_Serializer_o* this, Il2CppObject* value);`

- Upload executable file and global-metadata.dat: https://mega.nz/#!uJU3CSKI!mcLsGq9KwQefxMWd_PTPDLVRhckmbjlI5MY4brh9iwc

**Comment by Perfare** [comment]
`apply_type failed` can be ignored.
I tested both ida 7.0 and 7.4 without encountering this problem.
I noticed that you are using ida 7.2. If you are using a leaked version of ida 7.2, you should know that the leaked version of the Hex-Rays Decompiler plugin for ida 7.2 does not include the arm and x86 versions. If your ida 7.2 includes the arm version, it must be copied from the 7.0 version. However, the 7.0 version of the plugin will cause many problems in 7.2. My suggestion is to stop using the 7.2 version.
