### ISSUE TITLE
protected file

### ISSUE THREAD

**Issue by JustDragon** [Perfare/Il2CppDumper#247]
- Il2CppDumper version: 6.1.4
- Target Unity version: 2018.4.14f1
- Describe the issue: With version 6.0.3, I can dump this file, but for later version, including 6.1.4, when dump it will ask for Input dump address, I enter 0, then it show error

> Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Detected this may be a dump file. If not, it must be protected.
Input dump address:
0
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Elf.Search()
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp)
ERROR: An error occurred while processing.
Press any key to exit...

- Upload executable file and global-metadata.dat: https://mega.nz/#!iU03BJJQ!A5MChwdELmeHYJH57_13baZrcrP0GE_dP7Y1H-dgsnA
Thank you!

**Comment by JustDragon** [comment]
I use 6.0.3 version to dump but have another error. All StringLiteral can't xref. I think the issue because the lib is encrypted. Can you suggest which section I need to fix to make this StringLiteral work? Thank you!

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

**Comment by JustDragon** [comment]
Sorry it seem you misunderstood my question. Using Il2CppDumper v6.0.3, I can dump this libil2cpp I uploaded. But other later version like Il2CppDumper v6.1.4 can't dump it. Anyways, here is the dumped version of libil2cpp with GameGuardian if you need it https://mega.nz/#!LMk0wQ4J!vhlx7wZt-eXB5mfIzvPV2G9gnTxn-bqkAqo1ll90YCU

**Comment by Perfare** [comment]
I did not mistake anything, this file is 100% protected.
This is the 6.0.3 log you posted.

> Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
**_ERROR: This file may be protected._** <- Did you see it?

Even if you can successfully dump using 6.0.3, you can't see any code in ida, unless you use GameGuardian to dump.

**Comment by JustDragon** [comment]
What I want to report is: with 6.0.3 I can successfully dump it. Later version can't dump. I don't report about problem not see code in IDA, I can take care of that.

**Comment by Perfare** [comment]
If there is no code, ida impossible to xref StringLiteral.
I don't know why you have to wonder why 6.0.3 can dump. For this kind of protected file, it doesn't make sense to dump before removing the protection. 
This is a logical error in 6.0.3, causing it to bypass the protection detection of Il2CppDumper, for protected files, prompt and prevent dump is the correct way.

**Comment by JustDragon** [comment]
Anyways, here is the dumped version of libil2cpp with GameGuardian https://mega.nz/#!LMk0wQ4J!vhlx7wZt-eXB5mfIzvPV2G9gnTxn-bqkAqo1ll90YCU
With this dumped libil2cpp, no Il2cppDumper can success dump it. Can you please fix this?

**Comment by Perfare** [comment]
You did not provide a dump address of libil2cpp.so.

**Comment by JustDragon** [comment]
Thank you! I solved problem now.

**Comment by siyu644321** [comment]
can you tell me how can you solved this problem ? Thank you !
