### ISSUE TITLE
分享一个踩坑经历

### ISSUE THREAD

**Issue by qiankanglai** [Perfare/Il2CppDumper#248]
(也许可以补充到README) 希望帮到遇到类似问题的朋友

Il2CppDumper生成的DummyDll配合uTinyRipper使用时候，应该使用net46而不是netcoreapp3.1模式。因为后者生成的dll会在AssemblyReference里指向一个System.Private.CoreLib

这样就导致uTinyRipper在Resolve Core Lib时候指向这个而非mscorlib，带来System.String等类型Resolve失败...(查了一小时的血泪

**Comment by Perfare** [comment]
这种情况大概uTinyRipper也是.net core版本就没啥问题，所以win下还是用.net framework版本吧
