### ISSUE TITLE
Backwards IDA scripts compatibility

### ISSUE THREAD

**Issue by artemking4-Projects** [Perfare/Il2CppDumper#249]
Currently, automatically generated scripts dont support old versions of IDA, such as 6.8.
Could you do some tweaking/make 2 types of scripts for old and new ida versions?

You can find some useful info on that here:
https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

**Comment by JustDragon** [comment]
+1 for this too. IDA 6.8 seem the most stable version.

**Comment by Perfare** [comment]
I actually don’t think there is a need to support 6.8.
7.0 has been completely leaked, and all aspects of 7.0 are better than 6.8, especially support for the new version of the compiler.

**Comment by artemking4-Projects** [comment]
As i will need to update my IDA, i cant use my old idb databases after this. I will use a newer one in future, but i still have some databases on the old version

**Comment by Perfare** [comment]
Sorry I don’t have the idea of being compatible with the lower version of ida. In addition, the leaked ida 7.0 has generally been applied with compatibility patches, it allows ida to load a lower version of the databases.
