### ISSUE TITLE
Create c++ header files with all structs and function defenitions

### ISSUE THREAD

**Issue by artemking4-Projects** [Perfare/Il2CppDumper#251]
As the title says. Basically just generate a simple sdk that can be used in a standard c++ environment. Would be really useful. I may also contribute/make this by myself and make a pull request.

**Comment by Perfare** [comment]
Did not understand what you mean, the current Il2CppDumper would have generated a c header file "il2cpp.h"

**Comment by artemking4-Projects** [comment]
Yes it would. Indeed, its not enough. What about also exporting address offsets?

**Comment by Perfare** [comment]
They exist in script.json, please load them into ida using ida_with_struct.py.
