### ISSUE TITLE
IDA Pro 7.0 apply type failed

### ISSUE THREAD

**Issue by PiotrKFtw** [Perfare/Il2CppDumper#252]
I'm using: Latest IL2CPPDumper version.
How to recreate:
Open any GameAssembly.dll in ida and apply the ida_with_struct.py
Result:
![image](https://user-images.githubusercontent.com/33489788/76883690-d3fc9280-687c-11ea-9075-8224aeb9b2ad.png)
It happens for every type

**Comment by Perfare** [comment]
Execute the script after the ida analysis is completed. In addition, apply type failed errors can be ignored. I will comment out this log in the next version.
