### ISSUE TITLE
Set function and variable types in ida

### ISSUE THREAD

**Issue by artemking4-Projects** [Perfare/Il2CppDumper#253]
Set function prototypes as they are in the recovered dll (for an example).
Same with variables.

**Comment by Perfare** [comment]
I think you are saying "ida_with_struct.py".

**Comment by artemking4-Projects** [comment]
Probably. It just doesnt work with my current ida version

**Comment by Perfare** [comment]
Sorry I don’t have the idea of being compatible with the lower version of ida. If you have other questions, you can open a new issue.
