### ISSUE TITLE
i cant run the script.py in IDA

### ISSUE THREAD

**Issue by mareyole** [Perfare/Il2CppDumper#254]
hello
i need some help to run script.py in IDA
the Il2CppDumper-v4.2.3 script in run normal on my IDA
but the Il2CppDumper-v5.xx > v6 i cant run there script
can you give me some info how to make the script works
 my ida is 6.8
thank you have nice day

**Comment by Perfare** [comment]
Does not support ida 6.8, please use version 7.0 and above.
#249
