### ISSUE TITLE
死循环导致调用栈溢出

### ISSUE THREAD

**Issue by whklhh** [Perfare/Il2CppDumper#258]
- Il2CppDumper版本
v6.1.4

- 目标Unity版本
2017.4.30f1

- 问题描述
Dumping开始后产生了StackOverflow异常。
调试了一下看到是il2cppExecutor.cs中的第82行死循环了，
因为il2Cpp.Types[metadata.typeDefs[**il2CppType**.data.klassIndex].declaringTypeIndex] == **il2CppType**， 导致死循环调用GetTypeName。

- 上传可执行文件和global-metadata.dat
[compass_il2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4375087/compass_il2cpp.zip)

感谢作者~

**Comment by Perfare** [comment]
明显是数据有问题，请使用gg重新dump

**Comment by whklhh** [comment]
重新Dump后仍然存在这个问题_(:_」∠)_
游戏使用了MTP加固，GG使用无保护后可以打开游戏，但是在游戏界面中Dump出来的libil2cpp.so就还是这个样子..
可能是魔改或者运行时解密吗？
对unity没什么了解还希望作者大佬有空的话能多指点一下囧，谢谢

**Comment by whklhh** [comment]
翻你的博客发现有个评论里提到了也是这个错误，然后他自己回复了一下原来是global-metadata错了
然后我自省了一下想起来游戏有更新过，metadata也变了……
orz打扰了，感谢！
