### ISSUE TITLE
Process is terminated due to StackOverflowException.

### ISSUE THREAD

**Issue by thaipokecard** [Perfare/Il2CppDumper#259]
Thank you for providing the tool.

While I tried to test the tool on Japanese games UNI'S ON AIR, I encountered the following error.

> Initializing metadata...
> Metadata Version: 24.1
> Initializing il2cpp file...
> Applying relocations...
> Il2Cpp Version: 24.1
> Searching...
> CodeRegistration : 0
> MetadataRegistration : 0
> CodeRegistration : 2093348
> MetadataRegistration : 2093380
> Dumping...
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> ERROR: Some errors in dumping
> 
> Process is terminated due to StackOverflowException.

I uploaded .so file and meta file for reference. Il2CppDumper-v6.1.4
https://drive.google.com/open?id=1OM7hLQIt81CsJaOmtZS-HskORsFQLSw3
https://drive.google.com/open?id=1lO73pnqHQdOK7yoP1440UxtRdHL7LTdu

**Comment by Perfare** [comment]
I tested 1.7.1 everything works fine, please confirm that the two files are from the same version.
