### ISSUE TITLE
Unable to process [32Bit Binary][Auto]

### ISSUE THREAD

**Issue by CrazyHater** [Perfare/Il2CppDumper#26]
so, i have the latest version, the .20

error code

ERROR: Unable to process file automatically, try to use manual mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 88
Press any key to exit...

**Comment by CrazyHater** [comment]
thanks in advance! I'm trying to dump a iOS binary, game :- CSR 2. have tried both 32/64 doesn't work on auto,
Neither does the binary successfully load in IDA so i could do manual

**Comment by Perfare** [comment]
> try to use manual mode

**Comment by Perfare** [comment]
> Unable to process file automatically, **_try to use manual mode_**.
