### ISSUE TITLE
 Cannot edit methods, classes in extracted dll files

### ISSUE THREAD

**Issue by teamjrmods** [Perfare/Il2CppDumper#260]
Hello, 
**for what reason can not edit the code of the extracted dll?**

When editing shows me this message..

**the predefined type 'system.object' is not defined or imported**

- Although adding a simple space shows me this error, that is, I cannot modify the code

I use the dnSpy decompiler

**Comment by MrIkso** [comment]
lol, do not edit dump dll files

**Comment by Perfare** [comment]
It's just a fake dll, there is no code in it, why should you edit it?
