### ISSUE TITLE
Error: Index was outside the bounds of array

### ISSUE THREAD

**Issue by yodo226** [Perfare/Il2CppDumper#261]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: v6.1.4

- Target Unity version: 2019.1.14f1 (how do i specify unity version to target in Il2CppDumper?)

- Describe the issue: Errors in dumping and System.IndexOutOfRangeException: Index was outside the bounds of the array

- Upload executable file and global-metadata.dat (Download is below the pictures)

<img width="872" alt="Capture1" src="https://user-images.githubusercontent.com/20930076/77664863-c8fedc00-6fb9-11ea-8b14-f0169b13e5a7.PNG">
<img width="725" alt="Capture4" src="https://user-images.githubusercontent.com/20930076/77665186-47f41480-6fba-11ea-8811-f9f5ee7cbe52.PNG">
<img width="731" alt="Capture2" src="https://user-images.githubusercontent.com/20930076/77664873-cb613600-6fb9-11ea-8854-2e7997aa8feb.PNG">
<img width="720" alt="Capture3" src="https://user-images.githubusercontent.com/20930076/77664882-cd2af980-6fb9-11ea-90c4-305d8c322d4f.PNG">

[executablefile+globalmetadata.zip](https://github.com/Perfare/Il2CppDumper/files/4388131/executablefile%2Bglobalmetadata.zip)

**Comment by Perfare** [comment]
In my opinion, this global-metadata.dat has been modified/encrypted.
