### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by armbandito** [Perfare/Il2CppDumper#262]
Note: if you do not provide all of the following information I will directly ignore and close this issue

_- Il2CppDumper version_
    **Il2CppDumper v6.1.4**
_- Target Unity version_
    **2019.2.11f1**

_- Describe the issue_
    **get the ERROR: Can't use auto mode to process file, try manual mode.**

_- Upload executable file and global-metadata.dat_
    **[Among Us.zip](https://github.com/Perfare/Il2CppDumper/files/4388916/Among.Us.zip)**

**Comment by Perfare** [comment]
#228
