### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException error on Panzer Dragoon

### ISSUE THREAD

**Issue by staringstar** [Perfare/Il2CppDumper#263]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.1.4

- Target Unity version: 2019.3.0f3. Game is Panzer Dragon Remake.

- Describe the issue: So after giving main and gloabal-metadata.dat to Il2CppDumper, it gives an error whn it tries to generate script and the result is a script.json file, a stringliteral.json file and a dump.cs file. It works in version 6.1.1.
Full output:
`Initializing metadata...
Metadata Version: 24,2
Initializing il2cpp file...
Il2Cpp Version: 24,2
Searching...
CodeRegistration : 369bfc8
MetadataRegistration : 369cf20
Dumping...
Done!
Generate script...
System.Collections.Generic.KeyNotFoundException: La clé donnée était absente du dictionnaire.
   à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary``2.get_Item(TKey key)
   à Il2CppDumper.ScriptGenerator.RecursionStructInfo(StructInfo info)
   à Il2CppDumper.ScriptGenerator.WriteScript(Config config)
   à Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp)
   à Il2CppDumper.Program.Main(String[] args)
Press any key to exit...`

- Link to main executable for switch and global-metadate.dat: https://drive.google.com/open?id=1uLgEx_weeSMbD3V4Dx0S_qjsrGsP7lfJ

**Comment by Perfare** [comment]
Fixed, download the last build version from here https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

**Comment by staringstar** [comment]
Thanks!
