### ISSUE TITLE
System.IndexOutOfRangeException: 索引超出了数组界限。

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#265]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper v6.1.4
- 目标Unity版本
2019.3.0a12
arm64-v8a
- 问题描述
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 1d27980
MetadataRegistration : 1d281e0
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistrat
ion)
   在 Il2CppDumper.Il2Cpp.AutoInit(UInt64 codeRegistration, UInt64 metadataRegis
tration)
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metada
ta& metadata, Il2Cpp& il2Cpp)
ERROR: An error occurred while processing.
Press any key to exit...

我自己找了下CodeRegistration是1d27970，旧版本也试了一下好像也不行，有空看一下吧~
- 上传可执行文件和global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4401322/global-metadata.zip)
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4401325/libil2cpp.zip)

**Comment by Perfare** [comment]
Fixed in 4cddf5de8b4f8cc4a599045046e2d949c6d7ca8d
