### ISSUE TITLE
WHY CAN'T DUMP FREE FIRE?

### ISSUE THREAD

**Issue by madamdroid** [Perfare/Il2CppDumper#266]
![image](https://user-images.githubusercontent.com/44340008/78131698-af401780-7445-11ea-9b72-09c3c1e64344.png)

How to fix it?

name: free fire game

**Comment by madamdroid** [comment]
i want dump.cs and Dummydll

But very hard to get this:(
please help me:(

https://www.apkmirror.com/apk/garena-international-i-private-limited/garena-free-fire/garena-free-fire-1-46-0-release/garena-free-fire-winterlands-1-46-0-android-apk-download/download/

thank you ^^

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

**Comment by madamdroid** [comment]
> https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

but, where dummydll?
