### ISSUE TITLE
System.invalidoperationexception: Sequence contains no elements

### ISSUE THREAD

**Issue by BMD4E** [Perfare/Il2CppDumper#268]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.1.8

- Target Unity version:  2018.4.9f1 

- Describe the issue: Can't dump. I tried dump from memory but it does not ask for input address

- Upload executable file and global-metadata.dat
https://drive.google.com/file/d/1ZlphE2kr110f4qAt6ePq477CtoFTlME_/view

**Comment by Perfare** [comment]
This is a relatively rare kind of protection, I need to consider whether to add support.

**Comment by BMD4E** [comment]
Ok, it would be great to support for those who do not have knowledge breaking protection. In most cases, its fine to hook even the game is protected

**Comment by Perfare** [comment]
I rechecked the game and I noticed that this problem only occurs on 32-bit, dump files under 64 can run normally.
As 32-bit is about to be phased out, I no longer consider supporting 32-bit encryption.
