### ISSUE TITLE
Which offsets should i use for manual dump in metadata v24

### ISSUE THREAD

**Issue by evildog1** [Perfare/Il2CppDumper#27]
I tried many ways to dump in different offsets but not working.
I also tried to dump my own il2cpp game uses latest il2cpp version but not working.
`il2cpp::vm::MetadataCache::Register` looks different. Which offset should i use for manual dump?
![image](https://user-images.githubusercontent.com/8687585/32135695-a3f77352-bc03-11e7-99d2-143ff908d9ea.png)

**Comment by Perfare** [comment]
You need to find function name is `il2cpp_codegen_register` that are call the
`il2cpp::vm::MetadataCache::Register` function.
Also, do you test the new auto model?

**Comment by evildog1** [comment]
I found _Z27s_Il2CppCodegenRegistrationv but the R0 and R1 offsets I have given, does not work
Both auto mode and advanced auto mode does not work
```
ERROR: Unable to process file automatically, try to use other mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 93
Press any key to exit...
```
Here is my il2cpp files if you want to take a look. 100% clean project, no protections.
[New Unity Project 1.zip](https://github.com/Perfare/Il2CppDumper/files/1425292/New.Unity.Project.1.zip)

**Comment by Perfare** [comment]
All pointer addresses in this file are initialized only after loading, so the program is unable to process this dynamic type of file.
For example, in IDA, you can see the hex on 0x7AE198 is `30 D2 79 00`, but if you open the file in the hex editor, You can only see `00 00 00 00` at this address.

**Comment by evildog1** [comment]
So how do i do now?
I tried to save raw data including loaded bytes from IDA and dump it but still failure. This kind of infomation is new for me

**Comment by loveezu** [comment]
I have encountered the same problem, the three models are tried, can not determine the CodeRegistration and MetadataRegistration pointer address(the reason), but also you provide[New Unity Project 1.zip](https://github.com/Perfare/Il2CppDumper/files/1425292/New.Unity.Project.1.zip), and I encountered the same problem, there is no solution, the ELF file structure  and is not very familiar with.
![image](https://user-images.githubusercontent.com/11979349/32261587-93208a28-bf0a-11e7-94a9-e0e36bb0a4f4.png)

**Comment by evildog1** [comment]
yeah seems like Unity is trying hard to crack down Il2CppDumper

**Comment by Perfare** [comment]
I first encountered this type of file, I can only provide some possible suggestions. 
Try running game and dump whole il2cpp.so from memory.

**Comment by kbpsmp3** [comment]
Is there a solution yet? i have the same problem and i really want to mod rpg games so badly. please provide solutions. you are the boss

**Comment by Perfare** [comment]
@kbpsmp3 @loveezu 
Can you give me the download address of the game? I'm going to do research

**Comment by kbpsmp3** [comment]
this game https://play.google.com/store/apps/details?id=com.ubisoft.runeguard&hl=en

**Comment by Perfare** [comment]
@kbpsmp3 @evildog1 
I noticed that these .so method symbol have not been removed, we can search method name on IDA without relying on Il2CppDumper.

**Comment by evildog1** [comment]
Huh, didn't know that. I was about to dump il2cpp.so but i just waited for solutions. Thanks lol

**Comment by kbpsmp3** [comment]
me too. will look into methods in ida pro. many thanks boss

**Comment by Perfare** [comment]
@evildog1 @loveezu @zoanthropy I've added support for these redirection file, It's can dump now.

**Comment by evildog1** [comment]
That sounds cool, i will try it
