### ISSUE TITLE
dump完毕 自动关闭程序

### ISSUE THREAD

**Issue by Upfunny** [Perfare/Il2CppDumper#270]
使用命令行dump完成后，会提示press any key to exit
可否加入一个参数 在dump完成后 直接关闭程序 不再等待输入

**Comment by HarukaMomono** [comment]
> 使用命令行dump完成后，会提示press any key to exit
> 可否加入一个参数 在dump完成后 直接关闭程序 不再等待输入

【技巧向】我是在他运行的时候就多按一下任意键，然后结束时它就会一闪而过了

**Comment by Upfunny** [comment]
> 【技巧向】我是在他运行的时候就多按一下任意键，然后结束时它就会一闪而过了
我是想做自动化Mod，在python调用Il2CppDumper完成dump后，进程就停了
需要按任意键才会继续进行，所以想问能否加入自动关闭的参数，dump完直接关闭，这样python就能继续执行了

**Comment by Upfunny** [comment]
我是想做自动化Mod，在python调用Il2CppDumper完成dump后，进程就停了
需要按任意键才会继续进行，所以想问能否加入自动关闭的参数，dump完直接关闭，这样python就能继续执行了

**Comment by Perfare** [comment]
已添加
