### ISSUE TITLE
Question: How does the 2019 code registration plus search work?

### ISSUE THREAD

**Issue by DannyParker0001** [Perfare/Il2CppDumper#272]
I dont get what the bytes "featureBytes2019" represent and why scanning for them works...
https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Utils/PlusSearch.cs#L344

**Comment by Perfare** [comment]
This is a string `mscorlib.dll`, is the moduleName of the first Il2CppCodeGenModule.

**Comment by DannyParker0001** [comment]
Thanks, that clears it up.
