### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by mxwsxr** [Perfare/Il2CppDumper#274]
- Il2CppDumper version: 24

- Target Unity version: 2018.2.11f1

- Describe the issue: Trying to dump binary file(from .ipa to use in IDA Pro) and global-metadata file. Didn't work for me with the following error: **_ERROR: An error ocurred while processing._**

![Screenshot_2](https://user-images.githubusercontent.com/18013347/78502234-5da6ce00-7760-11ea-9cfe-15104b016b00.jpg)

Global-Metadata File: [global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4434237/global-metadata.zip)

Executable File: [https://drive.google.com/open?id=117F7ApdHPGeRwGPscYL26iun_tuOl82B](url)

**Comment by Perfare** [comment]
This ipa is not decrypted and cannot be used.
![QQ截图20200406001227](https://user-images.githubusercontent.com/12952226/78503787-5f41b780-779b-11ea-9e03-db66e76323af.png)

**Comment by mxwsxr** [comment]
How can I decrypt the file?
