### ISSUE TITLE
question about protected file

### ISSUE THREAD

**Issue by tahooo39** [Perfare/Il2CppDumper#275]
so after i dump the il2copp from memory and get all classes and functions then how to modify the protected file with hex editor any idea cause it is protected

**Comment by rafaelfernandesx** [comment]
> 
> 
> so after i dump the il2copp from memory and get all classes and functions then how to modify the protected file with hex editor any idea cause it is protected

how you do the dump? you used the il2cppdumper same?

**Comment by tahooo39** [comment]
> > so after i dump the il2copp from memory and get all classes and functions then how to modify the protected file with hex editor any idea cause it is protected
> 
> how you do the dump? you used the il2cppdumper same?

i dumped with game guardian the range addresses of the library

**Comment by MrPictYT-art** [comment]
> so after i dump the il2copp from memory and get all classes and functions then how to modify the protected file with hex editor any idea cause it is protected

No Need To Use Hex Editor, Since you dump from memory the il2cpp already unprotected, you just need loaded in Il2cpp Dumper

**Comment by mrcas** [comment]
> 
> 
> > so after i dump the il2copp from memory and get all classes and functions then how to modify the protected file with hex editor any idea cause it is protected
> 
> No Need To Use Hex Editor, Since you dump from memory the il2cpp already unprotected, you just need loaded in Il2cpp Dumper

His mean that after using II2cppdumper, get all files. But when we find the offset to patch, how can we patch it? Because the il2cpp.so file is protected. Can we patch directly to original .so file?

**Comment by mrcas** [comment]
Please. Help us!

**Comment by tahooo39** [comment]
> Please. Help us!

i guess you cant but you must make a shared library .so with mono loader and load it into game process and call functions from there

**Comment by mrcas** [comment]
Thanks my friend, i see and i also though same with you.

**Comment by Perfare** [comment]
Using VirtualApp or Riru to modify libil2cpp.so at runtime, you need to have certain C programming knowledge, I will not do too much introduction here, please rely on your own.
