### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by creatorss** [Perfare/Il2CppDumper#279]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本 6.2.1

- 目标Unity版本 

- 问题描述
`Initializing metadata...`
`Metadata Version: 24`
`Initializing il2cpp file...`
`Applying relocations...`
`WARNING: find JNI_OnLoad`
`ERROR: This file may be protected.`
`Il2Cpp Version: 24`
`Searching...`
`CodeRegistration : 0`
`MetadataRegistration : 0`
`ERROR: No symbol is detected`
`ERROR: Can't use auto mode to process file, try manual mode.`
`Input CodeRegistration:`
- 上传可执行文件和global-metadata.dat
链接：https://pan.baidu.com/s/1eWntR4iGMSv-gUrh_94-bw 
提取码：nlnq

**Comment by Perfare** [comment]
> WARNING: find JNI_OnLoad
-> ERROR: This file may be protected.
