### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by anhdd143** [Perfare/Il2CppDumper#28]
I can not dump this data
" metadata file supplied is not valid metadata file " with v24 (  
because new  global-metadata)
https://drive.google.com/file/d/1WsLbiH55UZv_VS-txJt1llgjUkpK6Dpx/view?usp=sharing

**Comment by Perfare** [comment]
The reason is 

>metadata file supplied is not valid metadata file

 no new format

**Comment by anhdd143** [comment]
can you update new format ? , thanks you

**Comment by Perfare** [comment]
I don't know what you're talking about, there's no new format for metadata.
