### ISSUE TITLE
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。

### ISSUE THREAD

**Issue by K7cl** [Perfare/Il2CppDumper#280]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.2.1（非netcore）
- 目标Unity版本
2018.4.15f1
- 问题描述
Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Detected this may be a dump file.
Input dump address or input 0 to force continue:
cbd95000
Il2Cpp Version: 24.1
Searching...
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadUInt32()
   在 Il2CppDumper.PlusSearch.FindCodeRegistration32Bit() 位置 C:\projects\il2cppdumper\Il2CppDumper\Utils\PlusSearch.cs:行号 194
   在 Il2CppDumper.Elf.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount) 位置 C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf.cs:行号 175
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 174
ERROR: An error occurred while processing.
Press any key to exit...
- 上传可执行文件和global-metadata.dat
https://oss.k7cl.com/file.zip
其中dump.bin是我自己尝试修改的dump文件 删去了libil2cpp文件前后的其他内容
也附了maps和修改之前GG导出的源文件
global-metadata.dat和libil2cpp.so是apk解压出来的源文件。
GitHub上的6.2.1和另一个平台下载的6.2.3都试了，不太行。麻烦了，谢谢！

**Comment by Perfare** [comment]
不要裁减后面的内容

**Comment by K7-Lenovo** [comment]
> 不要裁减后面的内容

您的意思是GG导出的bin只删去il2cpp之前的无关内容，之后的不删？

**Comment by K7-Lenovo** [comment]
> 不要裁减后面的内容

非常感谢指导，成功了，只裁剪GG导出so之前的无关部分即可，之后的保留。

**Comment by mitiandashuaibi** [comment]
兄弟,我dump出来的bin有很多个怎么办, 你遇到过没
