### ISSUE TITLE
Accessing Function Contents

### ISSUE THREAD

**Issue by TORCommunity** [Perfare/Il2CppDumper#281]
Hello,
I've generated the Dummy DLL containing Assembly-Csharp.dll from and APK's libil2cpp.so and global-metadata, and I'm able to view function names and their RVA, offset, and VA by opening the .dll in dnSpy, dotPeek, IDA etc., however the function body is empty of code:

In previous versions of the APK, before they started using libil2cpp.so, the function looked something like this:

```
public static float GetBasicStatStepValue(float step)
  {
    int num1 = Mathf.Clamp(Mathf.FloorToInt(step), -6, 6);
    float num2 = (float) Mathf.Abs(num1);
    if (num1 > 0)
      return (float) ((4.0 + (double) num2) / 4.0);
    return num1 < 0 ? (float) (4.0 / (4.0 + (double) num2)) : 1f;
  }
```

In the libil2cpp version, it looks like this (dnSpy):

```
// Token: 0x06000819 RID: 2073 RVA: 0x00003D50
 File Offset: 0x00001F50
[Address(RVA = "0xD91510", Offset = "0xD91510", VA = "0xD91510")]
public static float GetBasicStatStepValue(float step)
{
	return 0f;
}
```

And in IDA Pro:

```
  .method public static hidebysig float32 GetBasicStatStepValue(float32 step)
  {
    .maxstack 1
    .locals (float32 V0)
  .custom instance void [Il2CppDummyDll]Il2CppDummyDll.AddressAttribute::.ctor() = (
   01 00 03 00 53 0E 03 52 56 41 08 30 78 44 39 31
   35 31 30 53 0E 06 4F 66 66 73 65 74 08 30 78 44
   39 31 35 31 30 53 0E 02 56 41 08 30 78 44 39 31
   35 31 30) // ....S..RVA.0xD91510S..Offset.0xD91510S..VA.0xD91510
ldloca.s 0
initobj  [mscorlib]System.Single
ldloc.0
ret
  }
```

Am I missing something? I've tried opening the offset listed in the HxD hex editor, but I just see this:

![hexedit](https://user-images.githubusercontent.com/11221452/80637334-d716a100-8a2c-11ea-942b-1d35280c6cd9.png)

Any help is much appreciated!

**Comment by MrPictYT-art** [comment]
I think you should use Offser value not an a RVA value

**Comment by Perfare** [comment]
It's just a dummy dll, does not contain any method body. You need to use ida to load libil2cpp.so to view.
