### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by RedKage** [Perfare/Il2CppDumper#282]
Can't use auto mode to process file, try manual mode

- Il2CppDumper version
Il2CppDumper-v6.2.1
Il2CppDumper-netcore-v6.2.1

- Target Unity version
?

- Describe the issue
`Il2CppDumper.exe "RotMG Exalt.exe" "global-metadata.dat"`
> Initializing metadata...
> Metadata Version: 24.2
> Initializing il2cpp file...
> Il2Cpp Version: 24.2
> Searching...
> CodeRegistration : 0
> MetadataRegistration : 0
> ERROR: Can't use auto mode to process file, try manual mode.
> Input CodeRegistration:

- Upload executable file and global-metadata.dat
[rotmg_exalt_x33.0.1.zip](https://github.com/Perfare/Il2CppDumper/files/4558055/rotmg_exalt_x33.0.1.zip)

**Comment by heinrich5991** [comment]
Try throwing the game dll at it, it worked for me (in a different game).

**Comment by RedKage** [comment]
Dude, you were right!
Dumping GameAssembly.dll works!

And the result for this game are yummy .net code ... eheh
