### ISSUE TITLE
Cannot get all strings on IDA 7.2

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/Il2CppDumper#284]
- Il2CppDumper version: 6.2.1

- Target Unity version: 2018.2.14.f1

- Describe the issue: I'm trying to disassemble a game's ARM64 lib (don't have at the moment, ask if needed), I used both ida.py and ida_with_struct.py on the dumped script but no strings from it get into IDA aside from the strings already present in the lib, I also get apply type failed so many times. Any advice or I should downgrade to IDA 7.0?

- Upload executable file and global-metadata.dat:
https://we.tl/t-xRDNYxGo4Z (ARMV7, expires in a week)
[global-metadata.dat.txt](https://github.com/Perfare/Il2CppDumper/files/4582870/global-metadata.dat.txt)

**Comment by masagrator** [comment]
For me also it's not working from when script.json was introduced on IDA 7.0 and 7.2 ARMv8A
Tried before and after analysis

**Comment by LolHacksRule** [comment]
Doubt the lib is obfuscated, il2cppdumper said it might since it couldn't find JNI_OnLoad...

**Comment by LolHacksRule** [comment]
https://we.tl/t-Ynp4UL97sN (ARM64 lib, expires in a week)

**Comment by LolHacksRule** [comment]
Downgrading to 7.0 helped on fixing apply type failed errors, will report again when something else happens.

**Comment by LolHacksRule** [comment]
None of the strings from the dumped script don't get in 7.0... Assembly names do though...

**Comment by LolHacksRule** [comment]
Strings actually did but again, they aren't strings in the strings window...

**Comment by Perfare** [comment]
ida script does not make string display in ida's string window, because it does not exist in so.

**Comment by LolHacksRule** [comment]
I realized as of a while, thanks so much
