### ISSUE TITLE
Current master vs 6.2.1

### ISSUE THREAD

**Issue by Da-Teach** [Perfare/Il2CppDumper#286]
Unity v24.1

I've been working on a new type of export so I used master as a starting point. But there have been some changes in the way generic functions are exported.

For example, in the current v6.2.1 release the script.json file has:
    {
      "Address": 41838464,
      "Name": "Method$Client.App.SingleInstance<AppModel>.get_Instance()",
      "MethodAddress": 21284416
    },

While the master branch has this:
    {
      "Address": 41838464,
      "Name": "Method$Client.App.SingleInstance<AppModel>.get_Instance()",
      "MethodAddress": 0
    },

It can't seem to find the MethodAddress in this case. But with some "Method$" it still finds the address. The difference was in where it was used. The foreach (var i in metadata.metadataUsageDic[3]) loop is fine (all methodDef's have a methodIndex). But the foreach (var i in metadata.metadataUsageDic[6]) is different, none of the methodDef's have a methodIndex (all -1). 

This also causes some functions to be missing (probably functions that aren't found due to the above).

**Comment by Perfare** [comment]
Now the master is not finished, so it has not been released. I am now perfecting the generic function part so that it can handle the rgctxs. In fact, il2cpp will generate a function for each generic function instance, so there is no address for the T parameter function.
