### ISSUE TITLE
(ios)- ipa  dumping UnityFramework.framework

### ISSUE THREAD

**Issue by Avatarchik** [Perfare/Il2CppDumper#289]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本

- 目标Unity版本

- 问题描述

- 上传可执行文件和global-metadata.dat

**Comment by Avatarchik** [comment]
ipa fie: https://drive.google.com/open?id=1UPCPLTCqYHYODJPg6PhYXPG1wxe__3tX

**Comment by Perfare** [comment]
ipa未解密，请使用越狱设备获取解密后的ipa.

**Comment by Avatarchik** [comment]
Thank! I noticed that this software allows you to dump, but it’s not clear how it does it if the file is encrypted
https://www.devxdevelopment.com/Download
