### ISSUE TITLE
楼主大大方便看下字符串的索引么？

### ISSUE THREAD

**Issue by ye1088** [Perfare/Il2CppDumper#29]
楼主大大方便看下字符串的索引么？因为游戏作者经常会将字符串写在代码中，如果能找到字符串的位置，那游戏就好处理了

**Comment by Perfare** [comment]
字符串在16版本以上都有，在ida运行py脚本就行

**Comment by ye1088** [comment]
sorry啦，我没有怎么看，我这就去看下，谢谢大佬~~
