### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by MxyL** [Perfare/Il2CppDumper#291]
- Il2CppDumper version: v6.2.1
- Unity version: 2017.4.35f1
- Describe the issue: Sequence contains no matching element
- Upload executable file and global-metadata.dat: uploaded here: www.mediafire.com/file/8wieil260mgl5ee/s.7z/file

Some more info:

When I tried it on the libil2cpp.so from the apk, it said the file may be protected, so I dumped the memory using game guardian. The map said the following ranges were relevant

````
08000000-08005000 r--p 00000000 08:13 308        lib/arm/libil2cpp.so
08005000-0800a000 rw-p 00005000 08:13 308        lib/arm/libil2cpp.so
0800a000-084b1000 r--p 0000a000 08:13 308        lib/arm/libil2cpp.so
084b1000-0b0bf000 rw-p 004b1000 08:13 308        lib/arm/libil2cpp.so
0b0bf000-0b4a7000 r--p 030bf000 08:13 308        lib/arm/libil2cpp.so
0b4a7000-0b4b0000 r--p 00000000 00:00 0 
0b4b0000-0b795000 rw-p 034b0000 08:13 308        lib/arm/libil2cpp.so
0b795000-0b817000 rw-p 00000000 00:00 0 
0b817000-0b824000 r--p 00000000 00:00 0 
0b824000-0b825000 rw-p 03794000 08:13 308        lib/arm/libil2cpp.so
0b825000-0b834000 r--p 00000000 00:00 0 
0b834000-0b844000 r--p 03794000 08:13 308        lib/arm/libil2cpp.so
0b844000-0b85f000 r--p 00000000 00:00 0 
0b85f000-0b8e1000 rw-p 037af000 08:13 308        lib/arm/libil2cpp.so
0b8e1000-0c000000 ---p 00000000 00:00 0 
````

And there was one big file called 08000000-0c000000 so I copied it over.
When I ran Il2CppDumper again, it said it wasn't supported.

I opened the file and did a search for ELF and noticed there were a bunch of null bytes before it, so I deleted those. This time, it detected it as a dump file and asked for the offset.

I typed 0 as the offset, and then got the error message.

**Comment by mohdali** [comment]
08000000 is the offset

**Comment by Perfare** [comment]
According to my test, if you have no problem with dumping, this protection is temporarily not supported, you can try to dump from arm64 device.
