### ISSUE TITLE
在script.json中，添加方法的结束地址。

### ISSUE THREAD

**Issue by Upfunny** [Perfare/Il2CppDumper#292]
在老版本中 script.py中会有MakeFunction(0x1001237A4, 0x10012381C)字段，可以根据方法的起始地址查询到结束地址。
而在新版script.json中，只有一个Addresses存储全部地址，
能否将结束地址直接添加到ScriptMethod对应的方法中

**Comment by Perfare** [comment]
首先这个地址并不是100%正确的地址，只是把il2cpp函数的地址排了个序，其次，script.json中的Addresses数组就是原本的MakeFunction所使用的地址，我只是把它放到了json中。
