### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by DrFer1337** [Perfare/Il2CppDumper#293]
I know they are using a 2017 version of unity, but I'm not sure about the il2cpp version, if you get it I can give you a bitcoin reward as a donation, let me know if you are interested, thanks!

- Describe the issue
ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat

[unityx.zip](https://github.com/Perfare/Il2CppDumper/files/4655961/unityx.zip)

**Comment by Perfare** [comment]
Pc game executable file is GameAssembly.dll or *Assembly.dll, not .exe file.
