### ISSUE TITLE
How to dump correct memory in game guardian to get libil2cpp.so file?

### ISSUE THREAD

**Issue by forshared22** [Perfare/Il2CppDumper#295]
-I have tried dumping with Il2CppDumper-v6.1.2 but it shows the following error

Initializing metadata...
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file is protected.

-I know the file is protected so I did a memory dump in Game Guardian

-The problem is that I get .bin extension files and I don't know how to find the .so extension file to run it in Il2CppDumper-v6.1.2

Please help I don't know what I'm doing wrong .. !!
Sorry for my English

**Comment by mohdali** [comment]
you need to look at .global-maps.txt which is generated by game guardian to see the memory address where libil2cpp.so exists, the find the corresponding bin file and cut the beginning of that file using a hex editor until the mentioned address. You can confirm you have cut properly if the first bits of the file begin with .ELF string in the hex editor.

**Comment by forshared22** [comment]
but when you run the .bin file in the car, it says that the format is not supported, do you need to convert it?
I cut the beginning of the file to what address?
game = free fire 1.47.x

**Comment by forshared22** [comment]
but when you run the .bin file in the ll2cppdumper, it says that the format is not supported, do you need to convert it?
I cut the beginning of the file to what address?
game = free fire 1.47.x

**Comment by forshared22** [comment]
but when you run the .bin file in the ll2cppdumper, it says that the format is not supported, do you need to convert it?
i cut until what address? what is the name of the address?
game = free fire 1.47.x

**Comment by forshared22** [comment]
When using the .bin file in Il2CppDumper, it says that the format is not supported, do you need to convert it to .so?

The game command generates many .bin files, when I enter the "* -maps.txt" file. I don't know how to identify a correct .Bin, which one would it be?

do I cut with the hex editor to the address "libil2cpp.so"?

**Comment by mohdali** [comment]
> When using the .bin file in Il2CppDumper, it says that the format is not supported, do you need to convert it to .so?
> 
> The game command generates many .bin files, when I enter the "* -maps.txt" file. I don't know how to identify a correct .Bin, which one would it be?
> 
> do I cut with the hex editor to the address "libil2cpp.so"?

From *-maps.txt file you can find the start address of libil2cpp.so (in hex). Then you need to find the bin file that contains that range by comparing the hex address. Then finally cut the beginning of that file till the start of the library.

**Comment by forshared22** [comment]
Ok, but When using the .bin file in Il2CppDumper, it says that the format is not supported, do you need to convert it to .so?

**Comment by mohdali** [comment]
> Ok, but When using the .bin file in Il2CppDumper, it says that the format is not supported, do you need to convert it to .so?

You can rename it if that's the issue. Just make sure it is cut properly. The first bits of the file should read as .ELF in the hex editor

**Comment by forshared22** [comment]
do I cut where it is marked in the image until the beginning?
![InShot_20200524_145616265](https://user-images.githubusercontent.com/65842010/82761182-24d5bd80-9dcf-11ea-8c50-c9ae831da29c.jpg)

**Comment by mohdali** [comment]
Cut everything before that line. keep data starting from 0005000 (Starting from 7F 45 4C 46 onwards)
![image](https://user-images.githubusercontent.com/4145465/82761420-17d2c180-9e03-11ea-9f35-0bd8a5696a36.png)

**Comment by forshared22** [comment]
unfortunately i can't get...
thanks for helping me
![IMG_20200524_162749965](https://user-images.githubusercontent.com/65842010/82763257-b697f780-9ddc-11ea-86ac-5ce51e5ce7e8.jpg)

**Comment by mohdali** [comment]
well you need to provide the dump address there as well, same that you identified from the maps.txt

**Comment by forshared22** [comment]
where is the dump address?
![IMG_20200524_170324017](https://user-images.githubusercontent.com/65842010/82763954-acc4c300-9de1-11ea-8d7d-c05f2a739bc3.jpg)

**Comment by mohdali** [comment]
![image](https://user-images.githubusercontent.com/4145465/82764374-dfd57980-9e16-11ea-8882-c0f03a380690.png)

**Comment by forshared22** [comment]
finally got it rsrsrs, thank you very much!

last doubt before closing;

how will I know which correct .bin file to use in ll2cppDumper?
![importante decompile](https://user-images.githubusercontent.com/65842010/82764854-7a6a9400-9de8-11ea-9237-4833f8255829.png)

**Comment by forshared22** [comment]
got it.
you are very good at it, thank you very much!
success to you

**Comment by RevealedSoulEven** [comment]
@mohdali can you please help me with it please?

**Comment by Barshan-Mandal** [comment]
help me please....

**Comment by Barshan-Mandal** [comment]
How to get code registration.?The code is showing that automode not supported
