### ISSUE TITLE
Il2CppDumper 

### ISSUE THREAD

**Issue by DaniloG13a** [Perfare/Il2CppDumper#296]
Initializing metadata...
Metadata Version: 23
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 23
Searching...
CodeRegistration : 313b15c
MetadataRegistration : 313b194
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) en C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:línea 72
   en Il2CppDumper.Il2Cpp.AutoInit(UInt64 codeRegistration, UInt64 metadataRegistration) en C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:línea 65
   en Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp) en C:\projects\il2cppdumper\Il2CppDumper\Program.cs:línea 174
ERROR: An error occurred while processing.
Press any key to exit...

**Comment by DaniloG13a** [comment]
could you help me?

**Comment by Perfare** [comment]
> WARNING: find .init_proc
-> ERROR: This file may be protected.
