### ISSUE TITLE
Possible il2cpp.h generation error

### ISSUE THREAD

**Issue by Rodze** [Perfare/Il2CppDumper#298]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version v6.2.1

- Target Unity version 2018.4.15.62881

- Describe the issue: I ran the il2cpp dumper on the gameassembly.dll and global_metadata.dat. Then I used the Ghidra parse c source option and it indicated error at this line when parsing il2cpp.h

line 262269:	System_Func_double__double__o* if;

- Upload executable file and global-metadata.dat
exe: https://file.io/TGmE3YKk
metadata: https://file.io/3RFzIn41

**Comment by Perfare** [comment]
There are still some parts of the header file that need to be improved, and I mainly use IDA to work. I may only check the compatibility with Ghidra after completing the header file.

**Comment by Perfare** [comment]
#287
