### ISSUE TITLE
iOS 64bits support

### ISSUE THREAD

**Issue by nicoschmitt** [Perfare/Il2CppDumper#3]
If I'm not mistaken, the current version does not support ARM 64 bits. Are you planning to do it?
I may be able to help if you point me toward the right direction.

**Comment by Perfare** [comment]
I haven't met 64 bits il2cpp file, I will go to research if someone give me these files

**Comment by nicoschmitt** [comment]
pokemongo is a Fat MachO binary containing both Arm7 and Arm64

**Comment by Perfare** [comment]
Okay, I get it, I start to work now.

**Comment by nicoschmitt** [comment]
Thanks. I've added Fat Binary support in the meantime to my code.
https://github.com/pogosandbox/Il2CppDumper/tree/dev

**Comment by nicoschmitt** [comment]
pokemongo is a fat binary for example, extracting it with 7zip gives you arm7 and Arm64 binaries.

**Comment by Perfare** [comment]
done.
