### ISSUE TITLE
麻烦解决一下，谢谢了

### ISSUE THREAD

**Issue by nnjun** [Perfare/Il2CppDumper#30]
Unable to process file automatically, try to use manual mode. 
http://pan.baidu.com/s/1mixJXfa

**Comment by Perfare** [comment]
函数符号都在，你直接在ida里搜索就行了

**Comment by nnjun** [comment]
但是我这提示这个
Unable to process file automatically, try to use manual mode.
不知道是不是版本的问题，但是下载你这个源码无法编译，麻烦一下可以发一下新版本吗 @Perfare

**Comment by Perfare** [comment]
直接在ida里搜索函数名，不需要用这个工具

**Comment by nnjun** [comment]
哎呀 原来可以这样。谢了！ @Perfare

**Comment by nnjun** [comment]
突然发现有几个问题 看半天没看到在so的偏移和返回值类型(/ □ \) @Perfare
