### ISSUE TITLE
Game was protected. But cannot dump it. Is there anyway to solve?

### ISSUE THREAD

**Issue by mrcas** [Perfare/Il2CppDumper#302]
Dear everyone,

I got a game which protected binary file. But when i use gameguardian to dump it, game crash immediately. Is there anyway to bypass this?

Please help me

**Comment by Perfare** [comment]
Please confirm that you have checked the gameguardian hidden.

**Comment by mrcas** [comment]
I tried lot of ways but still cannot do anything. Or maybe i do something wrong.

I tried to freeze the game when dump. But the dump file is not correct. I want to learn new experience to solve this case.

Here is the game
https://play.google.com/store/apps/details?id=com.puzzle.miniworld&hl=en

**Comment by Perfare** [comment]
I have tested that if check the 4 hidden options of gameguardian, can dump normally.
But for the file after dump, you need to copy the elf header from the source so file, then edit the PHT header, set the offset and vaddr values of the two Loadable Segments to 0, and set filesz and memsz to the so file size.

**Comment by mrcas** [comment]
Thanks for your help. I solved it.

**Comment by mrcas** [comment]
Dear Perfare,

Sorry for disturbing you. I noticed that after dump, i just need to edit ELF header and Il2CppDumper can dump normally. Is it any wrong? It seems this game have anti patch too. When i patched in runtime, game freezed.

**Comment by mrcas** [comment]
Thanks again Perface. I solved the problem now :D. Thanks for teaching me.

**Comment by Perfare** [comment]
Okay, I will close this issue. If you have other issues, you can open a new.
