### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by wei-bst** [Perfare/Il2CppDumper#305]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本: Il2CppDumper-v6.2.1

- 目标Unity版本:iL2Cpp版本：24.1

- 问题描述：
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.

- 上传可执行文件和global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4729463/global-metadata.zip)
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4729465/libil2cpp.zip)

**Comment by Perfare** [comment]
已经提示你文件已加壳了
