### ISSUE TITLE
Can't use auto mode to process file, try manual mode. CodeRegistration : 0. MetadataRegistration : 0

### ISSUE THREAD

**Issue by Hezzelqx1** [Perfare/Il2CppDumper#306]
> Initializing metadata...
> Metadata Version: 24
> Initializing il2cpp file...
> Applying relocations...
> Il2Cpp Version: 24
> Searching...
> CodeRegistration : 0
> MetadataRegistration : 0
> ERROR: No symbol is detected
> ERROR: Can't use auto mode to process file, try manual mode.
> Input CodeRegistration:

**Comment by Perfare** [comment]
Please use the template to submit a issue.
