### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by ntovas** [Perfare/Il2CppDumper#307]
- Il2CppDumper version : 
 Build from source 06/06/2020 [Last merged commit](https://github.com/Perfare/Il2CppDumper/commit/3ff284ee2dedc02bfb2df50e4ae45a1f003d5b36)

- Target Unity version: 24.1

- Describe the issue
   ERROR: No symbol is detected
   ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat
[Dump + Meatdata](https://drive.google.com/file/d/1e4tFg6SqlK69YvniaYYaBLz_evXYQTCi/view?usp=sharing)

-Dump Address: 7b57511000 

ps: if you need the file tell me, I believe dump is better.

**Comment by Perfare** [comment]
Please give me the store address of the game.

**Comment by ntovas** [comment]
> Please give me the store address of the game.

The app is not in app store yet. Is there any way to private contact you and send you the apk+obb?

**Comment by 276523923** [comment]
我这个也是提示这样，https://yyyue.coding.net/p/PicUploader/d/PicUploader/git/raw/master/images/game.zip
文件已经打包好了。

**Comment by Perfare** [comment]
I think this game modified the structure of il2cpp.
You can try my other project https://github.com/Perfare/Riru-Il2CppDumper
