### ISSUE TITLE
 Il2CppDumper versio new version 

### ISSUE THREAD

**Issue by anish23884** [Perfare/Il2CppDumper#309]
Il2CppDumper versio

ERROR: This file may be protected.
Il2Cpp Version: 23
Searching...
CodeRegistration : 32b74bc
MetadataRegistration : 32b74f4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) 

game free fire android

**Comment by Perfare** [comment]
> ERROR: This file may be protected.
