### ISSUE TITLE
script.json 函數 ref 參數有誤

### ISSUE THREAD

**Issue by hiloinaru** [Perfare/Il2CppDumper#310]
Il2CppDumper v6.2.1

在 Il2CppDumper 產生的 DummyDll 某個函數看起來是這樣:
`void a_func (a_obj _arg1, ref float _arg2, ref int _arg3)`

但 Il2CppDumper 產生的 script.json 文件裡該函數是這樣:
`void a_func (a_class* this, a_obj* _arg1, float _arg2, int32_t _arg3)`

兩個參數_arg2、_arg3在反組譯代碼裡無疑是個指針
或許需要修改ParseType函數，具體不是很懂
https://github.com/Perfare/Il2CppDumper/blob/3ff284ee2dedc02bfb2df50e4ae45a1f003d5b36/Il2CppDumper/Outputs/ScriptGenerator.cs#L88

**Comment by Perfare** [comment]
感谢反馈，我会去验证下。

**Comment by Perfare** [comment]
已修复
