### ISSUE TITLE
why can't dump my file

### ISSUE THREAD

**Issue by stonerey** [Perfare/Il2CppDumper#311]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.2.1
I use GameGuardian save to bin files,but It can't dump

- Describe the issue
![微信截图_20200618110002](https://user-images.githubusercontent.com/22309438/84973214-263aa180-b153-11ea-90e1-c484976ee009.png)

![234](https://user-images.githubusercontent.com/22309438/84973357-77e32c00-b153-11ea-93e9-2e8b9051f8d5.png)

- Upload executable file and global-metadata.dat

**Comment by Perfare** [comment]
You need to intercept the file until the beginning of libil2cpp.so.
