### ISSUE TITLE
麻烦版主帮忙看一下：This file may be protected. Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by fgb031102** [Perfare/Il2CppDumper#312]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.2.1
![image](https://user-images.githubusercontent.com/5464058/84997503-a54acc80-b189-11ea-8085-b6bc0fde2128.png)

- 目标Unity版本
新手，不知道如何确定版本，请版主原谅。

- 问题描述
利用版主的软件进行global-metadata.dat和libil2cpp.so文件进行dump，出现如下错误。
![image](https://user-images.githubusercontent.com/5464058/84995836-729fd480-b187-11ea-84f2-8285bf341e98.png)
尝试利用IDA分析CodeRegistration等信息，发现so文件加载的非常快。尝试检索init，registered等方法都没有返回。
![image](https://user-images.githubusercontent.com/5464058/84996304-096c9100-b188-11ea-8233-fd2fdce6417f.png)

![image](https://user-images.githubusercontent.com/5464058/84996410-315bf480-b188-11ea-8720-4772c78d638e.png)

因为两个文件比较大，已上传到网盘。希望版主给与帮助。

链接: https://pan.baidu.com/s/17b5xQTqNvq5mcfqiyKQ4-Q 
提取码: 4kce

**Comment by Perfare** [comment]
好歹看一眼README？
https://github.com/Perfare/Il2CppDumper/blob/master/README.zh-CN.md#error-this-file-may-be-protected

**Comment by fgb031102** [comment]
> 好歹看一眼README？
> https://github.com/Perfare/Il2CppDumper/blob/master/README.zh-CN.md#error-this-file-may-be-protected

谢谢版主指点！
另外我还有两个问题，麻烦版主解答一下：
1、so文件放到IDA里面很快就分析完毕了，但是并没有太多的信息，这是什么原因呢？
2、从平行空间启动游戏，手机就一直处于黑屏状态，好像不能正常加载。这种情况版主又遇到过吗？

**Comment by Perfare** [comment]
1.因为so文件已加壳
2.我不用平行空间，你应该去问平行空间

**Comment by fgb031102** [comment]
> 1.因为so文件已加壳
> 2.我不用平行空间，你应该去问平行空间

那请问一下，版主所说的用GG Dump出SO文件是指在已经root的的手机上运行的是吗？

**Comment by Perfare** [comment]
gg可以在没有root的手机上运行，不过有很多限制
