### ISSUE TITLE
Export PrivateImplementationDetails

### ISSUE THREAD

**Issue by olivierberten** [Perfare/Il2CppDumper#313]
[home.zip](https://github.com/Perfare/Il2CppDumper/files/4806652/home.zip)

No idea whether this is easy or impossible but it would be great if Il2CppDumper could export PrivateImplementationDetails to json.

**Comment by Perfare** [comment]
PrivateImplementationDetails is only used to initialize the values of some variables at runtime, you need to use ida and load the script to view the code.
This is an example, initialize an array variable in the ctor function of the class.
![QQ截图20200620053037](https://user-images.githubusercontent.com/12952226/85180904-3370a100-b2b7-11ea-8cab-8ac70cc6c3e0.png)
Then search dump.cs for 9EC851EC0DEEC9639C05D00B33ADD167340FD26E
![QQ截图20200620053207](https://user-images.githubusercontent.com/12952226/85180981-6a46b700-b2b7-11ea-8a59-71191da3208e.png)
Metadata offset tells you the offset of the data used in global-metadata.dat.

**Comment by olivierberten** [comment]
That's perfect. I knew I had missed something. Thanks!
