### ISSUE TITLE
System.IndexOutOfRangeException: 索引超出了数组界限。

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#314]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.3.0
- 目标Unity版本
2019.4.0f1
arm64-v8a
- 问题描述
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 1ee91a0
MetadataRegistration : 1ee9ad0
Change il2cpp version to: 24.3
Actual CodeRegistration : 1ee9190
Dumping...
Done!
Generate script...
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.ScriptGenerator.WriteScript(String outputDir) 位置 C:\project
s\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:行号 55
   在 Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputD
ir) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 227
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2
CppDumper\Program.cs:行号 95
Press any key to exit...

和#265一样，虽然有修正指针偏移但还是抛了，该问题在Il2CppDumper-v6.2.1版本内不存在，有空看一下吧，辛苦啦
- 上传可执行文件和global-metadata.dat
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4822947/libil2cpp.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4822956/global-metadata.zip)

**Comment by Perfare** [comment]
已修复
