### ISSUE TITLE
Need help dumping App with GameGuardian

### ISSUE THREAD

**Issue by domebat** [Perfare/Il2CppDumper#317]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
The latest version.

- Target Unity version
I didn't get this far.

- Describe the issue
I tried for hours to use this awesome tool on "Legends of Runeterra". As the Windows Version of the app is protected I tried dumping the Android App of the same Game with GameGuardian. Unfortunately I had no luck, only crashes.. I tried 3 different Android emulators: BlueStacks, Nox and Memu.
I would appreciate it very much if you could help me out. If not, I can understand.
Thanks!

- Upload executable file and global-metadata.dat
I only have the protected files.

**Comment by Perfare** [comment]
Make sure you have checked 4 hidden options of GameGuardian.
