### ISSUE TITLE
Getting the offset of classes

### ISSUE THREAD

**Issue by babbaj** [Perfare/Il2CppDumper#319]
Is there any good way to get the offset of a class? I tried to write something based off the code that outputs the "ScriptMetadata" but it only works for about half of the classes.
https://github.com/babbaj/Il2CppDumper/blob/header/Il2CppDumper/Outputs/CoolHeaderGenerator.cs#L217

**Comment by Perfare** [comment]
I think you should use byrefTypeIndex instead of elementTypeIndex, elementTypeIndex is only used for enums.
https://github.com/Perfare/Il2CppDumper/blob/dab2ce6aa9a5c87569d3445c1e2eaab7d20fdaf8/Il2CppDumper/Il2Cpp/MetadataClass.cs#L133

**Comment by babbaj** [comment]
byrefTypeIndex doesnt work but byvalTypeIndex seems to work but i get about 1000 less offsets than with elementTypeIndex and using both doesnt help

**Comment by Perfare** [comment]
Actually I don’t quite know what you want to do.
If a type is not referenced elsewhere, such as using static fields elsewhere, it will not be included in metadatausage.

**Comment by babbaj** [comment]
I simply want to be able to get the address of any class.
I'm also now running into a problem in the new rust update where the pointer that should point to BaseProjectile_c is null for some reason while other classes work fine 😢

**Comment by Perfare** [comment]
Not quite sure why the pointer is null, but I think you can get it through il2cpp exported function `il2cpp_class_from_name`, it should work.

**Comment by babbaj** [comment]
Unfortunately I'm external and can't call functions but I heard that BaseProjectile is just weird for some reason and "BaseProjectile.<>c" existing might be a hint
