### ISSUE TITLE
遇到几个有问题的,都是两种模式不能执行解决的......

### ISSUE THREAD

**Issue by loveezu** [Perfare/Il2CppDumper#32]
第一个文件:[1.zip](https://github.com/Perfare/Il2CppDumper/files/1493685/1.zip)
第二个文件:[2.zip](https://github.com/Perfare/Il2CppDumper/files/1493688/2.zip)
![image](https://user-images.githubusercontent.com/11979349/33107245-4c9feef0-cf71-11e7-882e-7504d698d284.png)
这些文件,我手头经常会遇到,如果需要一些测试的,我可以提供...

**Comment by Perfare** [comment]
已修复，下最新的release
