### ISSUE TITLE
Initialize Metadata failed

### ISSUE THREAD

**Issue by WcLyic** [Perfare/Il2CppDumper#320]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: v6.3.3

- Target Unity version: 2018.4.8f1

- Describe the issue: Initializing metadata... System.IO.EndOfStreamException

- Upload executable file and global-metadata.dat

https://i.fiery.me/gfjdT.zip

**Comment by Perfare** [comment]
It looks like this global-metadata.dat has been modified.
You can try another project I just posted https://github.com/Perfare/Riru-Il2CppDumper

**Comment by WcLyic** [comment]
It looks good, but i don't have a real android device to make a try. Maybe i should fix the modified struct of `Il2CppGlobalMetadataHeader` by myself.
