### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by kuca00** [Perfare/Il2CppDumper#322]
- Il2CppDumper 6.3.3

- Target Unity version 24.2

- Describe the issue
    ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat
[Assembly & global-metadata](https://mega.nz/file/9gxTCKBD#nAkqUmfKYbuLRuLtg2FFokPdEKBKTOYuC4r8mpxVg0s)

**Comment by HarukaMomono** [comment]
> * Il2CppDumper 6.3.3
> * Target Unity version 24.2
> * Describe the issue
>   ERROR: Can't use auto mode to process file, try manual mode.
> * Upload executable file and global-metadata.dat
>   [Assembly & global-metadata](https://mega.nz/file/9gxTCKBD#nAkqUmfKYbuLRuLtg2FFokPdEKBKTOYuC4r8mpxVg0s)

It looks like protected with Themida.

**Comment by kuca00** [comment]
and what can i do with that?

**Comment by Perfare** [comment]
This file is protected, you can try to dump GameAssembly.dll from memory, then send me the dumped file and the address of GameAssembly.dll, I will try to solve it.

**Comment by Perfare** [comment]
same as #327 , it will be supported immediately.
