### ISSUE TITLE
[Bug?] CJK characters not output/read correctly for strings

### ISSUE THREAD

**Issue by zoller27osu** [Perfare/Il2CppDumper#324]
Il2Cpp-Dumper version 6.2.1, 6.3.3
il2cpp version 24.2 (Unity 2019.3.2f1)

For the .Constant values of strings that contain CJK characters (like `CJKYearSuff` in System.Globalization.DateTimeFormatInfo), the CJK characters are output as � (\ufffd), which is incorrect. Said characters should be output as escaped unicode, e.g. `\u1234` (where 1234 are exactly 4 hex digits) (\u instead of \x to avoid ambiguity with any characters that might follow the unicode one).

**Comment by zoller27osu** [comment]
Fix in https://github.com/Perfare/Il2CppDumper/pull/325

**Comment by Perfare** [comment]
Thanks for the feedback, I will check it.
