### ISSUE TITLE
Can't use auto mode

### ISSUE THREAD

**Issue by MysticalMayhem** [Perfare/Il2CppDumper#327]
- - Il2CppDumper version : **Il2CppDumper-v6.3.3**

- Target Unity version : **2019.3.15f1**

- Describe the issue : Went through the process of selecting the GameAssembly.dll file and Metadata which provided this

_Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:_

- https://drive.google.com/file/d/1u_pEG81vWxij_uSS1EHnKEDW4STWv4jx/view?usp=sharing **.dll executable**
- https://drive.google.com/file/d/1nPNEwphnmUarRP-YgZFzZE7YzMM6sDlp/view?usp=sharing **metadata**

**Comment by MysticalMayhem** [comment]
I looked into the file through dnSpy and I think it's protected by Themida.

**Comment by Perfare** [comment]
It is now supported, download the latest version from here.
https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts
