### ISSUE TITLE
关于IDA中函数自动识别的问题

### ISSUE THREAD

**Issue by loveezu** [Perfare/Il2CppDumper#33]
-测试了一下最新的版本,之前提出的两个问题都已经解决(多谢作者的勤奋).自动Dump和识别不同的版本都没有问题的.

- -就是还有一个小问题,在IDA中的"Functions window"函数窗口,对已识别的函数,不能搜索出来.

![1](https://user-images.githubusercontent.com/11979349/33158326-0053bf8a-d044-11e7-9e17-42987f7e3288.png)

- -但是可以在"IDA View-A"通过选中从函数头到函数尾全部选中,按快捷键"P",自动识别修复.

![2](https://user-images.githubusercontent.com/11979349/33158333-11869386-d044-11e7-804c-360dc5185416.png)

- -然后就可以在函数窗口搜索了. 

![3](https://user-images.githubusercontent.com/11979349/33158336-14db8f96-d044-11e7-9c47-d601167381cd.png)

- 如果可以在代码中集成用IDAPython脚本实现自动修复不能识别的函数就完美了.

- [ ] 附上SO文件:
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/1497974/libil2cpp.zip)
global-metadata文件:
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/1497991/global-metadata.zip)

**Comment by Perfare** [comment]
在看到代码前没法判断函数的结束位置，没法实现
