### ISSUE TITLE
no function  body 

### ISSUE THREAD

**Issue by NabilSnigdho** [Perfare/Il2CppDumper#330]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version

- Describe the issue

- Upload executable file and global-metadata.dat
![ice_screenshot_20200724-055751](https://user-images.githubusercontent.com/44827701/88364506-efd0f180-cda4-11ea-9241-805f39b2624a.png)

see there is no function body and i tryed all version of unity and dumper .fix it

**Comment by pluxtore** [comment]
as far as i know, the produced dll is still native x86 which you cannot properly inspect using dnSpy. Using Ghidra with the provided ghidra.py script used to worked for me.

**Comment by Perfare** [comment]
Currently does not support restoring il code.

**Comment by 1er4y** [comment]
> as far as i know, the produced dll is still native x86 which you cannot properly inspect using dnSpy. Using Ghidra with the provided ghidra.py script used to work for me.

Hi Pluxtore, can you give more details about how exactly did you get function bodies with Ghidra? I'm getting just errors during execution ghidra.py...( It would be nice if you will write your steps starting from the beginning. Thank you in advance!

**Comment by ellislaing** [comment]
hi, did you manage to resolve this issue? i’m having the same problem.
