### ISSUE TITLE
out RaycastHit properties

### ISSUE THREAD

**Issue by afulsamet** [Perfare/Il2CppDumper#331]
Thats my RaycastHit, It dumps RaycastHit like this.
```cpp
class RaycastHit {
public:
  Vector3 Point;
  Vector3 Normal;
  std::uint32_t FaceID;
  float Distance;
  Vector2 UV;
  void* Collider;
};
```

I want to use Transform property of RaycastHit.

![](https://i.imgur.com/DbaORKW.png)

---

I just tried this and it doesn't give the correct result, i even get `nullptr`.

```cpp
static constexpr auto MAKE_RVA = [](std::uintptr_t address) -> std::uintptr_t
{
  return reinterpret_cast<std::uintptr_t>(GameAssembly) + address;
};
```

```cpp
class RaycastHit {
public:
  Vector3 Point;
  Vector3 Normal;
  std::uint32_t FaceID;
  float Distance;
  Vector2 UV;
  void* Collider;

  void* GetTransform() { // returns nullptr
    return reinterpret_cast<void* (CDECL*)(RaycastHit*)>(Memory::MAKE_RVA(0x316A0))(this);
  }
};
```

RaycastHit is actually a struct, it doesn't have any instance, it has only reference. I'm confused while using properties.

What should I do or am I making mistakes?

**Comment by Perfare** [comment]
It has nothing to do with whether it is a struct, non-static fields and methods can only be called through an instance.

**Comment by afulsamet** [comment]
> It has nothing to do with whether it is a struct, non-static fields and methods can only be called through an instance.

So, is there any alternative, to use this property?

**Comment by Perfare** [comment]
The full signature of the function should look like this
`UnityEngine_Transform_o* UnityEngine_RaycastHit__get_transform (UnityEngine_RaycastHit_o __this, const MethodInfo* method);`
The second parameter is nullptr.
You may need to use hook to get the instance of RaycastHit you want to call, or hook this function to get the transform property of all RaycastHit.

**Comment by afulsamet** [comment]
Hooked 2 samples to use GetTransform. I dont know where I made a stupid mistake. I think I have a problem with pointers.

![](https://i.imgur.com/pxgsHUT.png)

```cpp
class RaycastHit {
  public:
    Vector3 Point;
    Vector3 Normal;
    std::uint32_t FaceID;
    float Distance;
    Vector2 UV;
    void* Collider;

    static void* GetTransform(UnityEngine::RaycastHit instance, const void* method) {
      return reinterpret_cast<void* (CDECL*)(RaycastHit, const void*)>(Memory::MAKE_RVA(0x316A0))(instance, method);
    }
};
```

```cpp
if (MH_Initialize() != MH_OK)
  Utils::EXIT_FAILURE_WITH_MSG("MH Initialize Error");

if (MH_CreateHook(Offsets::Hooks::Raycast, &Hooks::Raycast, reinterpret_cast<LPVOID*>(&Hooks::Original_Raycast)) != MH_OK)
  Utils::EXIT_FAILURE_WITH_MSG("Hooks::Raycast Error");

if (MH_CreateHook(Offsets::Hooks::GetTransform, &Hooks::RaycastHit_GetTransform, reinterpret_cast<LPVOID*>(&Hooks::Original_RaycastHit_GetTransform)) != MH_OK)
  Utils::EXIT_FAILURE_WITH_MSG("Hooks::GetTransform Error");

if (MH_EnableHook(MH_ALL_HOOKS) != MH_OK)
  Utils::EXIT_FAILURE_WITH_MSG("MH Enable Error");
```

**Comment by Perfare** [comment]
I can’t tell what the reason is, you can only check the code yourself to see if it’s an offset error.
