### ISSUE TITLE
IDA python script errors

### ISSUE THREAD

**Issue by Rodze** [Perfare/Il2CppDumper#332]
- Il2CppDumper version: 6.4.1

- Target Unity version: 2018.4.24.29073

- Describe the issue: IDA warns of errors when using ida_with_struct.py

IDA Pro 7.2

They seem like syntax errors. The script is able to finish, but I'm not sure if these errors are causing any problem in IDA.  So I'm just reporting them in case it's useful.

Thanks.

[ida_errors.txt](https://github.com/Perfare/Il2CppDumper/files/4983455/ida_errors.txt)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4983460/global-metadata.zip)
[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/4983462/GameAssembly.zip)

**Comment by Perfare** [comment]
Fixed.

**Comment by Rodze** [comment]
Wow. Thx for the fast work. It seems syntax errors are indeed gone. 

Now there's just "apply_type failed".

Do you know what these errors are?

[ida_errors-6.4.2.txt](https://github.com/Perfare/Il2CppDumper/files/4991184/ida_errors-6.4.2.txt)

**Comment by Perfare** [comment]
This is an internal error of ida, basically because ida cannot apply a signature at the specified location, you can ignore it, as long as it does not pop up an error window.
