### ISSUE TITLE
Can't use auto mode

### ISSUE THREAD

**Issue by mcproj** [Perfare/Il2CppDumper#333]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本: Il2CppDumper-netcore-v6.4.1

- 目标Unity版本: 新手不知道怎么看，从可执行文件看来像2018.4.21f1

- 问题描述: 
1. iOS已解密可执行文件，从内存dump出的global-metadata.dat
2. 直接执行提示ERROR: Can't use auto mode to process file, try manual mode. 并要求输入CodeRegistration和MetadataRegistration
3. IDA分析后知il2cpp_codegen_register函数为1011e5af8，CodeRegistration=104559608，MetadataRegistration=104548e28
输入Il2CppDumper后提示System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 uiAddr) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 72
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 120
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 209
ERROR: An error occurred while processing.

- 上传可执行文件和global-metadata.dat: https://mega.nz/file/OFAnlajK#ptJ2vLJX7MWYGz7rImpus6TcIPdgU5uNxWyNPxwznGU

**Comment by Perfare** [comment]
macho的data段数据解密有误，可以尝试重新解密或者换工具提取ipa文件

**Comment by mcproj** [comment]
> macho的data段数据解密有误，可以尝试重新解密或者换工具提取ipa文件

换了两个工具解了八次，得到完全相同的可执行文件（md5/crc32/sha256都完全相同），可能是data段本身被加密了？
能否帮忙确定下是哪个部分有误，或许我可以通过hook等手段访问内存获取解密后的数据？

**Comment by Perfare** [comment]
网盘文件你删了我刚好没留档，我当时就初略看了下Il2CppMetadataRegistration的metadataUsages部分，在ida里应该能看到一片全红的脏数据，我只先看了这部分，因为我用frida-ios-dump砸壳的时候偶尔也会遇到这种情况，不过从你的报错来看types部分似乎也是有问题。

**Comment by mcproj** [comment]
我用了frida-ios-dump, dumpdecrypted, bfdecrypt解出来完全一模一样的文件，感觉不像是砸壳的问题，像是被加密了或者格式被改了
我试试看hook能不能拿到Il2CppMetadataRegistration数据，如果成功的话会将dump下来的数据跟原来的文件一起重新上传

**Comment by mcproj** [comment]
```
invoke: il2cpp_codegen_register(0x104559608, 0x104548e28, 0x103f5b600) => 0
vmaddr_slide = 0x2410000
Il2CppCodeRegistration* 		{bytes = 0xed570100 00000000 8868be06 01000000 ...  }
Il2CppMetadataRegistration* 	{bytes = 0x659c0000 00000000 70229706 01000000 ...  }
Il2CppCodeGenOptions* 		{bytes = 0x00000000 00000000 170c0000 00000000 ...  }

invoke: (global-metadata.dat) => 0x11e000000
global-metadata.dat(13.916 MB)	{bytes = 0xaf1bb1fa 18000000 10010000 b84a0100 ...  }
```

我hook了il2cpp_codegen_register函数dump了一小段数据，发现除了地址被加上了vmaddr_slide之外与ida中直接看到的数据没有区别
原来的文件已经重新上传，主楼的链接已经更新

**Comment by Perfare** [comment]
还是一样的问题，MetadataRegistration的metadataUsages数据有问题
