### ISSUE TITLE
ERROR: Metadata file supplied is not a supported version[27].

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#336]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.4.2
- 目标Unity版本
2020.2.0a15
- 问题描述
Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported v
ersion[27].
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\projects\il2cppdumper\I
l2CppDumper\Il2Cpp\Metadata.cs:行号 40
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata
& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.c
s:行号 118
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2
CppDumper\Program.cs:行号 93
Press any key to exit...

好像是Unity又有新版本了Orz..
- 上传可执行文件和global-metadata.dat
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/4999409/libil2cpp.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/4999424/global-metadata.zip)

**Comment by Perfare** [comment]
能否提供一下dump后的so，方便我测试下

**Comment by HarukaMomono** [comment]
使用GG修改器转储的32位so文件：
[GGdump.zip](https://github.com/Perfare/Il2CppDumper/files/5004621/GGdump.zip)

应用包：
链接：https://pan.baidu.com/s/13yv8bMZ4C4XD3Zlg1uhVTA 
提取码：2333

**Comment by Perfare** [comment]
已经可以处理v27的dump文件了，不过因为Unity改了逻辑，现在除了输出libil2cpp的地址外还需要输入global-metadata.dat的地址，也就是c379e000，才能正常dump

**Comment by HarukaMomono** [comment]
感谢处理！
