### ISSUE TITLE
il2cpp.h generation error

### ISSUE THREAD

**Issue by WcLyic** [Perfare/Il2CppDumper#337]
When a certain amount of error are found, ida will give up parsing the remaining content in the header file. Then many "apply_type failed" error throw. Here is a common blocking problem.

```
Error C:\Users\Sugar\Test\il2cpp.h,1204570: Field 'm_Hits' has already been defined
Error C:\Users\Sugar\Test\il2cpp.h,1204573: Syntax error near: }
Error C:\Users\Sugar\Test\il2cpp.h,1204652: Undefined type name 'UnityEngine_EventSystems_Physics2DRaycaster_Fields'
Error C:\Users\Sugar\Test\il2cpp.h,1204653: Syntax error near: }
```

```cpp
struct UnityEngine_EventSystems_Physics2DRaycaster_Fields : UnityEngine_EventSystems_PhysicsRaycaster_Fields{
	struct UnityEngine_RaycastHit2D_array* m_Hits;
};
```
```cpp
struct UnityEngine_EventSystems_PhysicsRaycaster_Fields : UnityEngine_EventSystems_BaseRaycaster_Fields{
	struct UnityEngine_Camera_o* m_EventCamera;
	struct UnityEngine_LayerMask_o m_EventMask;
	int32_t m_MaxRayIntersections;
	int32_t m_LastMaxRayIntersections;
	struct UnityEngine_RaycastHit_array* m_Hits;
};
```

Maybe the subclass's field needs to check whether its name conflicts with the parent class, and if so, it needs to be renamed.

**Comment by Perfare** [comment]
This is a confusing error. What is your version of ida? Subclasses with variables with the same name as the parent class should be allowed.
It can be loaded normally in ida 7.4
![image](https://user-images.githubusercontent.com/12952226/88963717-df57d400-d2da-11ea-9d71-20a6fe4a67bf.png)
![image](https://user-images.githubusercontent.com/12952226/88963743-e67ee200-d2da-11ea-9cfd-a89e72cbc11b.png)

**Comment by Perfare** [comment]
In addition, the apply_type failed error can be ignored, as long as it does not pop up an error window.

**Comment by WcLyic** [comment]
IDA 7.0. I also test IDA 7.2 is ok. Maybe you can point out the minimum compatible version of IDA in README for others like me.

And there are some errors when using IDA 7.2. [files.zip](https://share.dmca.gripe/3Bvji5O7l4mytEQe.zip)
```
...
apply_type failed: 0x1c3cda4L void ProtoBuf_Compiler_CompilerContext__EmitCtor (ProtoBuf_Compiler_CompilerContext_o* __this, System_Type_o* type, System_Type_array* parameterTypes, const MethodInfo* method);
The current type can not be short or long
...
apply_type failed: 0x5d7767cL void FerrPoly2Tri_Polygon__AddRange (FerrPoly2Tri_Polygon_o* __this, System_Collections_Generic_IList_PolygonPoint__o* points, int32_t windingOrder, const MethodInfo* method);
Missing brace
...
```

**Comment by Perfare** [comment]
Thanks for the feedback, the new keywords I have added will no longer have these errors.
