### ISSUE TITLE
How to use game guardian to dump?

### ISSUE THREAD

**Issue by RevealedSoulEven** [Perfare/Il2CppDumper#338]
- Il2CppDumper version : 6.4.2

- Target Unity version : 5.6.3f1

Actually it says that the file is protected so I try game guardian method.

I make GG (game guardian) scripts using dump.cs offsets for il2cpp.so and hack Garena Free Fire.

So I have good experience in it. But when I dump memory then I get .bin files and a mapping.txt file.

I find 3 files of libil2cpp.so in mapping.txt

So can you please explain how to get dump.cs from it?

Also I tried Riru-il2cppdumper but... It says that it's not a magisk flashable zip file
Please reply sir.

APK - https://www.apkmirror.com/apk/garena-international-i-private-limited/garena-free-fire/garena-free-fire-1-51-2-release/

Thank you

**Comment by Perfare** [comment]
Find the first address of libil2cpp.so from *-maps.txt, then find the file containing the address from the bin files, cut the length of the libil2cpp.so address - bin start address in the bin file, finally load with Il2CppDumper.

**Comment by RevealedSoulEven** [comment]
Ok Sir! So as you can see in the first picture that the il2cpp file is from b6b4a000 to ba2fb000. Am I right?
![Screenshot_2020-07-31-04-56-59-02_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/49313374/88984199-9871da80-d2ea-11ea-9ac6-f26d6b503eb8.jpg)


Then the file may be this one(the second picture).
![Screenshot_2020-07-31-04-59-54-78](https://user-images.githubusercontent.com/49313374/88984237-b4757c00-d2ea-11ea-9c56-a40be02a9ef1.jpg)


But how to trim it? I mean I can use hex editor easily but how much part to trim and how to know where to trim the file?

Please explain sir

**Comment by RevealedSoulEven** [comment]
@mohdali please help

**Comment by Perfare** [comment]
Cut at the beginning, size is `libil2cpp.so address - bin start address`

**Comment by Perfare** [comment]
In addition, your file does not contain libil2cpp.so, b6b4a000 is not among ba2fc000 and bc3f9000.

**Comment by RevealedSoulEven** [comment]
@Perfare leave that

I use GG from a long time and I found a way to get inly the unprotected libil2cpp.so file from GG dump😁.
I did some settings in dump memory and GG gave only a single file which started from .ELF which means it's libil2cpp.so and it doesn't need to trim wither at the beginning or at the end.

Directly getting only 2 files.
1. Bin file
2. Map.txt file

I just took the bin file without trimming anything using hex to GG and selected global-matadata.dat and put the dump address of libil2cpp.so and got all files including dump.cs and all.

Shall I share the method? @Perfare

**Comment by Perfare** [comment]
Congratulations, you can share your method here, others can search for the same problem.

**Comment by mrvizine** [comment]
Yes please share. I’d also love to learn how to correctly implement the riru-il2cppdumper. Because I can’t load that as a module either in magisk

**Comment by RevealedSoulEven** [comment]
@mrvizine actually I used game guardian method

**Comment by RevealedSoulEven** [comment]
@Perfare I will make a video tutorial. It's the simplest way to dump and get all files in one click for protected files.

But.... You will have to add the video link in the main readme.md where the protected files are mentioned. Ok?

**Comment by mrvizine** [comment]
Thanks I appreciate that!

**Comment by mrvizine** [comment]
Can you explain how to use offsets from dump.cs (I have from another game) to use in gameguardian?

**Comment by LELEOTV** [comment]
@RevealedSoulEven Poderia ensinar seu método ? Tentei fazer pelo tradicional e não achei a libil2cpp.so

**Comment by Minux0x6** [comment]
@RevealedSoulEven Hey can u please show me the way i'll really appreciate it

**Comment by Reizen115** [comment]
@RevealedSoulEven can you share the way please? I would really appreciate it bro

**Comment by Elmisa8220** [comment]
I have managed to decompile the libil2cpp.so of the New Update of Free Fire V1.56 I am a developer but I have no experience in Mods I would appreciate if someone help me create a Mod Menu

**Comment by 12349292922929** [comment]
Bro me podrias pasar la dump.cs de esta vercion ? :(

**Comment by LOLERgg** [comment]
Hello Perfare Sir,
Can U Tell Me How To Make This Libil2ccp In Which I Can Record And Never Get Banned
I Will Be So ThankFull i Can Pay Some Money After Work 
Just Send Me A Video Of Everything! 
Thanks!

**Comment by LOLERgg** [comment]
In Free Fire Plus I Am PC PLAYER

**Comment by Codexx101** [comment]
> I have managed to decompile the libil2cpp.so of the New Update of Free Fire V1.56 I am a developer but I have no experience in Mods I would appreciate if someone help me create a Mod Menu

Hello, have you gotten what you wanted yet?

**Comment by Codexx101** [comment]
> @Perfare I will make a video tutorial. It's the simplest way to dump and get all files in one click for protected files.
> 
> But.... You will have to add the video link in the main readme.md where the protected files are mentioned. Ok?

Still waiting on the video tho

**Comment by lendariosregedit** [comment]
> @Perfare farei um vídeo tutorial. É a maneira mais simples de despejar e obter todos os arquivos com um clique para arquivos protegidos.
> 
> Mas .... Você terá que adicionar o link do vídeo no readme.md principal, onde os arquivos protegidos são mencionados. OK?

?

**Comment by BrainedUp** [comment]
> > @Perfare farei um vídeo tutorial. É a maneira mais simples de despejar e obter todos os arquivos com um clique para arquivos protegidos.
> > Mas .... Você terá que adicionar o link do vídeo no readme.md principal, onde os arquivos protegidos são mencionados. OK?
> 
> ?

Any problem?

**Comment by BrainedUp** [comment]
> * Il2CppDumper version : 6.4.2
> * Target Unity version : 5.6.3f1
> 
> Actually it says that the file is protected so I try game guardian method.
> 
> I make GG (game guardian) scripts using dump.cs offsets for il2cpp.so and hack Garena Free Fire.
> 
> So I have good experience in it. But when I dump memory then I get .bin files and a mapping.txt file.
> 
> I find 3 files of libil2cpp.so in mapping.txt
> 
> So can you please explain how to get dump.cs from it?
> 
> Also I tried Riru-il2cppdumper but... It says that it's not a magisk flashable zip file
> Please reply sir.
> 
> APK - https://www.apkmirror.com/apk/garena-international-i-private-limited/garena-free-fire/garena-free-fire-1-51-2-release/
> 
> Thank you

Can I get help on how to hack Garena Free Fire?

**Comment by Cheetah1212** [comment]
> Congratulations, you can share your method here, others can search for the same problem.



> Congratulations, you can share your method here, others can search for the same problem.

Hi can you tell me how to use aimbot like rouk ff do you have any tutorial please

**Comment by BrainedUp** [comment]
@Cheetah1212 yes I have been searching for long and now I have finally gotten how to use aimbot like ruok, moro etc. If you want to know message me on my telegram here https://t.me/BrainedUp

**Comment by LOLERgg** [comment]
@BrainedUp  i have msged you in telegram but u didnt replied its like 1 day
And Anyone know how to make a aimbot like ruok ff which i can record too? 
plz u can contact me in telegram or msg here
Telegram: https://t.me/Levi 04

**Comment by ImPeekaboo** [comment]
> @Perfare leave that
> 
> I use GG from a long time and I found a way to get inly the unprotected libil2cpp.so file from GG dump😁.
> I did some settings in dump memory and GG gave only a single file which started from .ELF which means it's libil2cpp.so and it doesn't need to trim wither at the beginning or at the end.
> 
> Directly getting only 2 files.
> 
> 1. Bin file
> 2. Map.txt file
> 
> I just took the bin file without trimming anything using hex to GG and selected global-matadata.dat and put the dump address of libil2cpp.so and got all files including dump.cs and all.
> 
> Shall I share the method? @Perfare

Bro, pls share the tutorial

**Comment by houssam-12bboo** [comment]
H
