### ISSUE TITLE
某主连结某服的il2cpp.so无法auto到CodeRegistration

### ISSUE THREAD

**Issue by Songhan17** [Perfare/Il2CppDumper#339]
您好！
- Il2CppDumper版本
Il2CppDumper-v6.4.4
- 目标Unity版本
2017.4.3f1
- 问题描述
之前直接dump发现有壳，通过GG从内存中dump出了il2cpp.so，然后用Il2CppDumper-v6.4.4操作，无法dump出来，请问下如何能获得其正确的CodeRegistration呢，执行下来会有个System.InvalidOperationException: 序列不包含任何匹配元素错误
- 上传可执行文件和global-metadata.dat

[so_dat.zip](https://github.com/Perfare/Il2CppDumper/files/5015484/so_dat.zip)

**Comment by Perfare** [comment]
没给dump地址

**Comment by Songhan17** [comment]
[com.bilibili.priconne-maps.txt](https://github.com/Perfare/Il2CppDumper/files/5019569/com.bilibili.priconne-maps.txt)
根据maps的位置，dump地址是9ef7c000吗？il2cpp.so开始的位置。  但是我试了不行

**Comment by Perfare** [comment]
编辑program header将第一个可执行段的p_filesz和p_memsz的大小设置为文件大小

**Comment by Songhan17** [comment]
还是不行，我填写了字节大小75685888，依然会出现下面的情况，请问这个能找到CodeRegistration地址吗？
Input dump address or input 0 to force continue:
9ef7c000
Il2Cpp Version: 24
Searching...
CodeRegistration : 0
MetadataRegistration : a3978d64
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:

**Comment by Perfare** [comment]
[dump_fixed.zip](https://github.com/Perfare/Il2CppDumper/files/5021172/dump_fixed.zip)
第一个可执行段，你肯定编辑错位置了，这是编辑好的，你自己看看吧

**Comment by Songhan17** [comment]
emm...我用的010打开的，对比了一下。。在struct program_table_entry32_t program_table_element[1]这一行。。的确是编辑错位置了。。。谢谢dalao的耐心指点。。我再钻研钻研。。再一次，感谢您
