### ISSUE TITLE
ll2CppDumper Manual Mode 

### ISSUE THREAD

**Issue by KingKong5147** [Perfare/Il2CppDumper#34]
Hi buddy,

The new version you have released is awesome. You were are to show me how to find offset with the  last tricky binary but this one ive added is very unique do you have a solution to make your awesome tool work?
and is there another way for me to contact you??

http://iosddl.net/dd1bc7e98a687708/zaca.rar

**Comment by Perfare** [comment]
Because the important data of this file is damaged, Il2CppDumper can't work
![qq 20171129065703](https://user-images.githubusercontent.com/12952226/33348817-bfb9c6d4-d4d2-11e7-8be9-34b069ac43b4.png)

**Comment by KingKong5147** [comment]
That's a shame I need this so I can remove the jailbreak detection so no solution ?

**Comment by KingKong5147** [comment]
Looks as though the metadata is encrypted

**Comment by KingKong5147** [comment]
Is there a way to decrypt it?

**Comment by Perfare** [comment]
I'm sorry, I don't know about IOS. I can't help you
