### ISSUE TITLE
Need help, Thank you.

### ISSUE THREAD

**Issue by EndlessMISAKA** [Perfare/Il2CppDumper#340]
- Il2CppDumper版本
6.4.4

- 目标Unity版本
未知，unity资源文件被加密，hex查看不到版本号。运行时提示il2cpp版本是24.1

- 问题描述
想拆包传颂手游，但是它的assetbundle文件被加密了，所以想试试dump代码出来看看有没有解密算法。
但dump失败，metadata似乎有保护，所以想试试您的Riru，但是一直编译失败。
jdk14.02，查了一下gradle似乎要升到最新版才行我也升了，还是不行，错误提示我有截图在压缩包里。
我没学过安卓相关的，而这个编译错误似乎有很多种原因，所以搞不清楚。
大佬可以帮忙搞开吗？有偿也行。
（只想拆出立绘和语音用于收藏，非常感谢大佬之前开发的舰B的L2D和语音解包工具）

- 上传可执行文件和global-metadata.dat
[so_metadata.zip](https://github.com/Perfare/Il2CppDumper/files/5016472/so_metadata.zip)
[assets.zip](https://github.com/Perfare/Il2CppDumper/files/5016477/assets.zip)

**Comment by Perfare** [comment]
直接用Android Studio打开，运行gradle的:module:assembleRelease命令即可
global-metadata.dat可以尝试从内存中dump出来，在dump后的文件中搜索metadata开头4字节特征就行了
