### ISSUE TITLE
PS4 LL2CPP bypass protection

### ISSUE THREAD

**Issue by Damin72** [Perfare/Il2CppDumper#341]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper v6.4.4

- Unity 2017.4.8f1 PS4 (if AssetStudioGUI doesn't lie)

- Our translator team need to properly decompile Il2CppUserAssemblies.prx, but there is protection and we cant examine DLL-s fully. Is there any solutions to get libil2cpp.so for this file? Maybe with PS4-HEN-Payload help (f.e. DUMPER PAYLOAD, what decrypt and dump game files).

Files (PS4-folder):
https://drive.google.com/file/d/1tD4oBIPg9fJSO9CQehR258pBih0OdO0x/view?usp=sharing

**Comment by masagrator** [comment]
libil2cpp.so is Android file. It's not used anywhere else.

If I understand correctly this tool doesn't support PS4.

**Comment by Damin72** [comment]
> libil2cpp.so is Android file. It's not used anywhere else.
> 
> If I understand correctly this tool doesn't support PS4.

Supported since 2018.

**Comment by masagrator** [comment]
Ah, sorry. It's under ELF support... 😥

**Comment by HarukaMomono** [comment]
> Note: if you do not provide all of the following information I will directly ignore and close this issue
> 
> * Il2CppDumper v6.4.4
> * Unity 2017.4.8f1 PS4 (if AssetStudioGUI doesn't lie)
> * Our translator team need to properly decompile Il2CppUserAssemblies.prx, but there is protection and we cant examine DLL-s fully. Is there any solutions to get libil2cpp.so for this file? Maybe with PS4-HEN-Payload help (f.e. DUMPER PAYLOAD, what decrypt and dump game files).
> 
> Files (PS4-folder):
> https://drive.google.com/file/d/1tD4oBIPg9fJSO9CQehR258pBih0OdO0x/view?usp=sharing

I dumped it for you, have a try
[dump.zip](https://github.com/Perfare/Il2CppDumper/files/5033101/dump.zip)
the same as #339

**Comment by Damin72** [comment]
Or PS4 DLL not same as PC, or this DLL still protected. 0_O
PC-version (judgmentCTRL):
![image](https://user-images.githubusercontent.com/21997242/89506549-f8c5b800-d7d3-11ea-8f37-47a1a759cdb7.png)
PS4-version (judgmentCTRL):
![image](https://user-images.githubusercontent.com/21997242/89506578-ffecc600-d7d3-11ea-8564-6473cf3786cc.png)

**Comment by HarukaMomono** [comment]
> Or PS4 DLL not same as PC, or this DLL still protected. 0_O
> PC-version (judgmentCTRL):
> ![image](https://user-images.githubusercontent.com/21997242/89506549-f8c5b800-d7d3-11ea-8f37-47a1a759cdb7.png)
> PS4-version (judgmentCTRL):
> ![image](https://user-images.githubusercontent.com/21997242/89506578-ffecc600-d7d3-11ea-8564-6473cf3786cc.png)

It's just a dummy dll, does not contain any method body. You need to use ida to load elf to view.
![Snipaste_2020-08-06_16-40-16](https://user-images.githubusercontent.com/47363075/89510807-a603f480-d803-11ea-98fe-53605e723cd3.png)
![Snipaste_2020-08-06_16-40-59](https://user-images.githubusercontent.com/47363075/89510825-adc39900-d803-11ea-958d-9bd8df4156c7.png)

**Comment by Damin72** [comment]
Oh, i see. Okay, thanks. 
And one more question, if you can answer... Any way to put it back, when we manage to edit?

**Comment by HarukaMomono** [comment]
I'm not professional, try to patch memory or something better.

**Comment by Damin72** [comment]
Thanks for answer.
