### ISSUE TITLE
I get an error when I try to decompile

### ISSUE THREAD

**Issue by ShuperDark** [Perfare/Il2CppDumper#342]
- Il2CppDumper version
6.4.4

- Target Unity version
I don't know

- Describe the issue
When I try to decompile, I get an error like this:
`Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: シーケンスに、一致する要素は含まれてません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   場所 Il2CppDumper.Macho64.Search() 場所 C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:行 186
   場所 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 場所 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行 195
ERROR: An error occurred while processing.
Press any key to exit...`

- Upload executable file and global-metadata.dat
https://www.dropbox.com/s/z0ec03lrsh0m7fg/SakuraSimulator?dl=0
https://www.dropbox.com/s/w7czbsr7scfh3n3/global-metadata.dat?dl=0

**Comment by Perfare** [comment]
You have selected the wrong executable file, this file is too small.

**Comment by ShuperDark** [comment]
Does the executable file correspond to the binary file of the app?
I'm trying to decompile an iOS app.
If it's Android, I'm pretty sure it uses ".so", right?
  ##![DF30BEE4-AD90-4D61-99D9-B8300F17C3F4](https://user-images.githubusercontent.com/29055910/90312720-b291f680-df41-11ea-84e2-a9826db5b898.png)

**Comment by Perfare** [comment]
The file may be in the Frameworks folder, name is UnityFramework.

**Comment by ShuperDark** [comment]
Oh! You're the best!
Decompiled successfully!
Thank you!
