### ISSUE TITLE
ida_with_struct.py文件需要更新

### ISSUE THREAD

**Issue by SenkiTK** [Perfare/Il2CppDumper#344]
- Il2CppDumper版本
v6.4.4
- 问题描述
IDAPython可能更新过了，parse_decls和parse_decl函数现在需要四个参数。

附错误信息：

Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "D:\RE\IDA\python\ida_typeinf.py", line 2205, in parse_decls
    
TypeError: parse_decls expected 4 arguments, got 2

**Comment by Perfare** [comment]
请根据选择文件时窗口的标题选择正确的文件

**Comment by SenkiTK** [comment]
> 请根据选择文件时窗口的标题选择正确的文件

我先用il2cppdumper把gameAssembly.dll处理过了。然后用IDA PRO7.0打开GameAssembly，载入ida_with_struct的脚本，先加载了script.json再加载了il2cpp.h，然后就提示我错误了

**Comment by Perfare** [comment]
ida 7.0及以上版本都测试过肯定没问题，之前有人遇到一模一样的问题就是因为他选错文件了

**Comment by qiannianshuangxue** [comment]
我也是一样的错误,请问 @SenkiTK @Perfare 大佬们是怎么解决的,使用ida脚本恢复符号没出现问题,但在使用struct脚本出现了同样的错误
