### ISSUE TITLE
Unknown error when dumping

### ISSUE THREAD

**Issue by LaxusiC** [Perfare/Il2CppDumper#346]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: Latest (6.4.4)

- Target Unity version: 2018.3

- Describe the issue: Dump error: https://i.imgur.com/6oZhLRd.png

- Upload executable file and global-metadata.dat: https://mega.nz/file/9koBXIjJ#phHpP7hei3RzOID9_UXN4u5FV4kQ2ZSAaLCX_xL6Xj8

**Comment by Perfare** [comment]
This game should modify the format of global-metadata.dat.
If you can work on Android, you can try my other project https://github.com/Perfare/Riru-Il2CppDumper, it should be able to bypass this confusion.
