### ISSUE TITLE
Can't find code registration

### ISSUE THREAD

**Issue by chrrox** [Perfare/Il2CppDumper#347]
I managed to get a dumped dll but it can' find the code registration and metadata offset.
https://www35.zippyshare.com/v/Fzc6A0an/file.html

Unity 2018.4.18f1

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

**Comment by Perfare** [comment]
Don't do anything to dumped so files.
