### ISSUE TITLE
这不是bug，请教一个问题

### ISSUE THREAD

**Issue by ndl1302732** [Perfare/Il2CppDumper#348]
下载了最新版本的il2cppdumper.
使用il2cppdemper 反编译一个apk得到如下输出文件：
1 DummyDll 目录
2 dump.cs
3 il2cpp.h
4 script.json
5 stringliteral.json

请教下：
1 script.json文件是不是供ida.py这个脚本使用的
2 stringliteral.json和il2cpp.h 是不是供ida_with_struct.py这个脚本使用的

我是这么用的。想跟大佬再确认下。接触il2cppdumper时间不长，望大佬解答下。

**Comment by Perfare** [comment]
选择文件的时候窗口顶上有告诉你选什么文件
