### ISSUE TITLE
none of the mode works with Unity 2017.2.0p2

### ISSUE THREAD

**Issue by WindWT** [Perfare/Il2CppDumper#35]
![image](https://user-images.githubusercontent.com/1337002/33516504-d8d2ea7c-d7ae-11e7-8ca7-ce090cb4b8d7.png)

[libil2cpp.so and global-metadata.dat](https://github.com/Perfare/Il2CppDumper/files/1523870/1.zip)

**Comment by Perfare** [comment]
use Manual mode then input address of g_CodeRegistration and g_MetadataRegistration

**Comment by Perfare** [comment]
![qq 20171204033228](https://user-images.githubusercontent.com/12952226/33528923-13033b7a-d8a4-11e7-8458-8795d777d004.png)
![qq 20171204033236](https://user-images.githubusercontent.com/12952226/33528924-147ca37e-d8a4-11e7-8607-bcccaee8a87b.png)
