### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by DeQuex** [Perfare/Il2CppDumper#350]
says can't use auto mode

can you help me?

- Upload executable file and global-metadata.dat
[Fall Guys.zip](https://github.com/Perfare/Il2CppDumper/files/5114036/Fall.Guys.zip)

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-cant-use-auto-mode-to-process-file-try-manual-mode

**Comment by DeQuex** [comment]
I already sent the files needed

**Comment by Perfare** [comment]
If you choose the right file, you won't get any errors.

**Comment by DeQuex** [comment]
Am I use like this:
Il2CppDumper D:\SteamLibrary\steamapps\common\Fall Guys\FallGuys_client.exe D:\SteamLibrary\steamapps\common\Fall Guys\FallGuys_client_Data\il2cpp_data\Metadata\global-metadata.dat C:\Users\DeQuex\Desktop\VS\

**Comment by DeQuex** [comment]
Il2CppDumper "D:\SteamLibrary\steamapps\common\Fall Guys\FallGuys_client.exe" "D:\SteamLibrary\steamapps\common\Fall Guys\FallGuys_client_Data\il2cpp_data\Metadata\global-metadata.dat" "C:\Users\DeQuex\Desktop\VS\"

or like this? I tried this one before

**Comment by Perfare** [comment]
Why should you choose exe file?
https://github.com/Perfare/Il2CppDumper#error-cant-use-auto-mode-to-process-file-try-manual-mode

> Please note that the executable file for the PC platform is GameAssembly.dll or *Assembly.dll
