### ISSUE TITLE
System.ArgumentNullException: 路径不能为 null

### ISSUE THREAD

**Issue by yp05327** [Perfare/Il2CppDumper#351]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.4.12
- 目标Unity版本
2018.4.18f1
- 问题描述
运行后报错，信息如下：
Initializing metadata...
System.ArgumentNullException: 路径不能为 null。
参数名: path
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 117
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 94

- 上传可执行文件和global-metadata.dat
[libil2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/5124078/libil2cpp.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/5124081/global-metadata.zip)

**Comment by Perfare** [comment]
用的命令行模式？没有输入正确的global-metadata.dat地址，另外这个global-metadata.dat是加密的

**Comment by yp05327** [comment]
可执行文件和global-metadata.dat和Il2CppDumper放在同一目录下，然后在该目录下打开powershell 执行 
./Il2CppDumper.exe libil2cpp.so global-metadata.dat
的结果

然后这个看着也不像是加密的问题，所以就很奇怪，跑来问一下

我还有一份6.2.1版本的 进行同样的操作 结果会返回
usage: Il2CppDumper <executable-file> <global-metadata>

这样的话 因为被加密了 所以应该是正常的？

然后我又尝试了一下直接运行v6.4.12的exe，返回的结果看上去是正常的：
Initializing metadata...
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 51
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 119
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 94

**Comment by Perfare** [comment]
嗯，加密的global-metadata.dat的在命令行下会出现的bug，等我有空了修下好了
