### ISSUE TITLE
生成的.h中，继承结构可能存在变量名冲突

### ISSUE THREAD

**Issue by DKingCN** [Perfare/Il2CppDumper#353]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
v6.4.12

- 目标Unity版本
2017.4.3f1

- 问题描述
导出的的.h中，C++继承结构父子间可能出现同名变量，变量名冲突导致IDA导入.h结构失败，影响后续所有相关函数的符号设置。

- 上传可执行文件和global-metadata.dat
NSO文件，版权考虑不上传。

**Comment by WcLyic** [comment]
请参考 #337

**Comment by DKingCN** [comment]
是同一个问题，IDA低版本无法兼容。感谢解答。
