### ISSUE TITLE
[question]最新release下dump文件报错

### ISSUE THREAD

**Issue by xuzhenhuicn** [Perfare/Il2CppDumper#354]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
    Il2CppDumper-v6.4.12
- 目标Unity版本
    2018.4.2f1
- 问题描述
    `Initializing metadata...
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 51
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 119
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 94
Press any key to exit...`

- 上传可执行文件和global-metadata.dat
    包含APK：https://drive.google.com/drive/u/1/folders/1t7QrvvHs20HizqAWvDG_HZc3NUbgw9cS
    dat文件：https://drive.google.com/file/d/10T3ZK_Ze7OlEGA4oT1E0pI3FX75H2X4E/view?usp=sharing
    so文件：https://drive.google.com/file/d/1EjA16BHhJ6Rz7redFlst9iVLi_mULf0l/view?usp=sharing

- 其他
    请问这种情况是由于加密导致的嘛，如果是希望能指点下一步该怎么操作。

**Comment by HarukaMomono** [comment]
有点像ups加密过的，去试试隔壁的riru-il2cppdumper项目

**Comment by WcLyic** [comment]
鱼目混珠而已 实际 `global-metadata.dat` 是 `assets/bin/Data/Managed/Resources/Joyport.Base.dll-resources.dat`

![Snipaste_2020-09-04](https://user-images.githubusercontent.com/29097441/92229788-9b10b280-eedc-11ea-9fac-ae6089120646.png)

**Comment by xuzhenhuicn** [comment]
> 鱼目混珠而已 实际 `global-metadata.dat` 是 `assets/bin/Data/Managed/Resources/Joyport.Base.dll-resources.dat`
> 
> ![Snipaste_2020-09-04](https://user-images.githubusercontent.com/29097441/92229788-9b10b280-eedc-11ea-9fac-ae6089120646.png)

好的，这种情况是开发者对MetadataLoader.cpp做了修改吧，想请问下是截图的内容是libil2cpp.so中解析到的嘛，我在IDA中尝试没搜到loadmeta的内容。

**Comment by WcLyic** [comment]
@xuzhenhuicn 原本 `libil2cpp.so` 是没有这些符号的 我只是加上注释方便理解而已
