### ISSUE TITLE
我遇到个问题

### ISSUE THREAD

**Issue by poxin1022** [Perfare/Il2CppDumper#355]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本     
 试过三个版本4.6---6.4.12----6.4.4

- 目标Unity版本
2019.2.21f1

- 问题描述
错误提示：
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Metadata.ProcessingMetadataUsage() 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 139
   在 Il2CppDumper.Metadata..ctor(Stream stream, Single version) 位置 C:\projects\il2cppdumper\Il2CppDumper\Metadata.cs:行号 74
   在 Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 140
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 87

- 上传可执行文件和global-metadata.dat
由于不能上传so和dat类型的文件我压缩打包了一下
https://poxin.lanzous.com/iyuqSgcwwgd

**Comment by HarukaMomono** [comment]
看了一下是易盾

**Comment by poxin1022** [comment]
> 看了一下是易盾

metadata.dat是这个文件被加密了吗

**Comment by HarukaMomono** [comment]
> > 看了一下是易盾
> 
> metadata.dat是这个文件被加密了吗

so被加密了，推荐试试riru-il2cppdumper

**Comment by poxin1022** [comment]
> > > 看了一下是易盾
> > 
> > 
> > metadata.dat是这个文件被加密了吗
> 
> so被加密了，推荐试试riru-il2cppdumper

好的，谢谢
