### ISSUE TITLE
动森的so无法dump

### ISSUE THREAD

**Issue by peasshoter** [Perfare/Il2CppDumper#361]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue
Il2CppDumper-v6.4.12
Metadata Version: 24
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
动森露营的so,无法dump,安装包里找到了SymbolMap-ARM64文件，不清楚是不是缺少这个。
so https://wws.lanzous.com/iGau7ggml8d
global-metadata https://wws.lanzous.com/ihIkXggmlej

**Comment by Perfare** [comment]
尝试使用https://github.com/Perfare/Riru-Il2CppDumper
