### ISSUE TITLE
[Suggestion] Make compatible with Hopper Dissembler?

### ISSUE THREAD

**Issue by i0SH4X0R** [Perfare/Il2CppDumper#362]
Could You Make it work with hopper please?

**Comment by Perfare** [comment]
Sorry, I don’t have a Mac OSX device.

**Comment by i0SH4X0R** [comment]
I think it works for linux too

**Comment by donrodrigodelavega** [comment]
I would definitely second that suggestion, hopper supports python scripts like ghidra or IDA
