### ISSUE TITLE
ghidra.py script Line 24 "getEntryPoint" fails if no next function is found, stopping the script prematurely.

### ISSUE THREAD

**Issue by Smileynator** [Perfare/Il2CppDumper#365]
I am not 100% on what the fix has to be. (either don't change end, or change end to EOF?) But a simple "is None" check can prevent the error in the script.

**Comment by PsychoPast** [comment]
Hey. I had the same problem but I fixed it thx to the little python knowledge I have
Replace (pic 1) with (pic 2)
![Screenshot_20200921_154643](https://user-images.githubusercontent.com/33565739/93768731-7fb6de80-fc22-11ea-92ce-50e098394924.jpg)
![Screenshot_20200921_155239](https://user-images.githubusercontent.com/33565739/93768735-804f7500-fc22-11ea-889f-d83b6fac1305.jpg)

**Comment by therealchjones** [comment]
See PR #368 (thanks, @PsychoPast) [just including here to link]
