### ISSUE TITLE
Unity Changes 24.3 - UnityFramework nested executable

### ISSUE THREAD

**Issue by x-darlyn** [Perfare/Il2CppDumper#369]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.4.12

- Target Unity version
24.3

- Describe the issue
Latest Unity Version has two MACH-O files. UnityFramework is nested inside root IPA executable and launched.

Root
[Data][Managed][Metadata]Global-metadata.dat
[Frameworks][UnityFramework.framework]UnityFramework
Executable

Executable loads UnityFramework
Dumper fails

- Upload executable file and global-metadata.dat
https://wetransfer.com/downloads/20dc6ab3dc793d9dc91221eb63efc0fd20200922175144/93ee85452efe1b24b2bd880f270f0e7520200922175208/e685f7

main executable:

__int64 UnityFrameworkLoad(void)
{
  void *v0; // x0
  void *v1; // x0
  void *v2; // x19
  void *v3; // x0
  void *v4; // x20
  void *v5; // x0
  __int64 v6; // x19
  void *v7; // x0
  void *v8; // x20
  void *v9; // x0
  void *v10; // x0
  void *v11; // x0
  void *v12; // x21
  void *v13; // x0
  __int64 v14; // x22

  v0 = objc_msgSend(&OBJC_CLASS___NSBundle, "mainBundle");
  v1 = (void *)objc_retainAutoreleasedReturnValue(v0);
  v2 = v1;
  v3 = objc_msgSend(v1, "bundlePath");
  v4 = (void *)objc_retainAutoreleasedReturnValue(v3);
  objc_release(v2);
  v5 = objc_msgSend(v4, "stringByAppendingString:", CFSTR("/Frameworks/UnityFramework.framework"));
  v6 = objc_retainAutoreleasedReturnValue(v5);
  objc_release(v4);
  v7 = objc_msgSend(&OBJC_CLASS___NSBundle, "bundleWithPath:", v6);
  v8 = (void *)objc_retainAutoreleasedReturnValue(v7);
  if ( !((unsigned __int64)objc_msgSend(v8, "isLoaded") & 1) )
    objc_msgSend(v8, "load");
  v9 = objc_msgSend(v8, "principalClass");
  v10 = objc_msgSend(v9, "getInstance");
  v11 = (void *)objc_retainAutoreleasedReturnValue(v10);
  v12 = v11;
  v13 = objc_msgSend(v11, "appController");
  v14 = objc_retainAutoreleasedReturnValue(v13);
  objc_release(v14);
  if ( !v14 )
    objc_msgSend(v12, "setExecuteHeader:", &_mh_execute_header);
  objc_release(v8);
  objc_release(v6);
  return _objc_autoreleaseReturnValue(v12);

**Comment by Perfare** [comment]
I checked the file because some pointers are in the uninitialized _bss section, I will try to fix it.

**Comment by xgDebug** [comment]
else if (header.stringLiteralOffset == 272)
                {
                    Version = 24.3f;
                    header = ReadClass<Il2CppGlobalMetadataHeader>(0);
                }
