### ISSUE TITLE
Error dumping iOS version of game

### ISSUE THREAD

**Issue by kappa9999** [Perfare/Il2CppDumper#372]
I was able to dump Genshin Impact chinese version APK and extract dump.cs but I get error on iOS binary dump.
Game : https://apps.apple.com/cn/app/%E5%8E%9F%E7%A5%9E/id1467190251?uo=4&at=1010lce4

Android version has obfuscated class names so I need iOS version to inspect data properly

error for iOS version dump:

Initializing metadata...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Il2CppDumper.Metadata.ProcessingMetadataUsage()
at Il2CppDumper.Metadata..ctor(Stream stream)
at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp)
at Il2CppDumper.Program.Main(String[] args)
Press any key to exit...

Binary and metadata: https://drive.google.com/drive/u/1/folders/1P68kjIcYPASeB9sUE6QpAkTRlskC8Awa

any help would be greatly appreciated...

**Note: if you do not provide all of the following information I will directly ignore and close this issue: 

- Il2CppDumper version: Il2CppDumper-[bh3-3.8.0-All] & Latest release version both

- Target Unity version: 2017.4.30f1

- Describe the issue: See above

- Upload executable file and global-metadata.dat: See above **

**Comment by Perfare** [comment]
The global-metadata.dat of the ios version you provided is encrypted.
In addition, obfuscated class names at the c# level is the same whether in Android or ios.

**Comment by kappa9999** [comment]
> The global-metadata.dat of the ios version you provided is encrypted.
> In addition, obfuscated class names at the c# level is the same whether in Android or ios.

The class names in the iOS version do not seem to be obfuscated, I can see them when I inspect the metadata in HxD

Image:  https://i.imgur.com/yjta4UR.png

Is there no way to get around the encrypted metadata?

**Comment by Perfare** [comment]
The string segment shown in your screenshot is the file name of lua.

**Comment by kappa9999** [comment]
Oh I see... thanks for the clarification
