### ISSUE TITLE
Problem with running the script in ghidra

### ISSUE THREAD

**Issue by denis70ru** [Perfare/Il2CppDumper#373]
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:647)
	at ghidra.python.GhidraPythonInterpreter.<init>(GhidraPythonInterpreter.java:103)
	at ghidra.python.GhidraPythonInterpreter.get(GhidraPythonInterpreter.java:89)
	at ghidra.python.PythonScript.runInNewEnvironment(PythonScript.java:110)
	at ghidra.python.PythonScript.run(PythonScript.java:48)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-11
JVM Version: Oracle Corporation 11
OS: Windows 10 10.0 amd64

**Comment by therealchjones** [comment]
Can you confirm which script you're trying to run in ghidra?

**Comment by denis70ru** [comment]
```
# -*- coding: utf-8 -*-
import json

functionManager = currentProgram.getFunctionManager()
baseAddress = currentProgram.getImageBase()
USER_DEFINED = ghidra.program.model.symbol.SourceType.USER_DEFINED

def get_addr(addr):
	return baseAddress.add(addr)

def set_name(addr, name):
	name = name.replace(' ', '-')
	createLabel(addr, name, True, USER_DEFINED)

def make_function(start, end):
	next_func_start = getFunctionAfter(start).getEntryPoint()
	if next_func_start < end:
		end = next_func_start
	body = createAddressSet()
	body.addRange(start, end.subtract(1))
	functionManager.deleteAddressRange(start, end.subtract(1), getMonitor())
	func = getFunctionAt(start)
	if func is None:
		functionManager.createFunction(None, start, body, USER_DEFINED)
	else:
		func.setBody(body)

print 'Script: Edit config.json and set MakeFunction to false to speed up ghidra script execution'
f = askFile("script.json from Il2cppdumper", "Open")
data = json.loads(open(f.absolutePath, 'rb').read().decode('utf-8'))
scriptMethods = data["ScriptMethod"]
for scriptMethod in scriptMethods:
	addr = get_addr(scriptMethod["Address"])
	name = scriptMethod["Name"].encode("utf-8")
	set_name(addr, name)
index = 1
scriptStrings = data["ScriptString"]
for scriptString in scriptStrings:
	addr = get_addr(scriptString["Address"])
	value = scriptString["Value"].encode("utf-8")
	name = "StringLiteral_" + str(index)
	createLabel(addr, name, True, USER_DEFINED)
	setEOLComment(addr, value)
	index += 1
scriptMetadatas = data["ScriptMetadata"]
for scriptMetadata in scriptMetadatas:
	addr = get_addr(scriptMetadata["Address"])
	name = scriptMetadata["Name"].encode("utf-8")
	set_name(addr, name)
	setEOLComment(addr, name)
scriptMetadataMethods = data["ScriptMetadataMethod"]
for scriptMetadataMethod in scriptMetadataMethods:
	addr = get_addr(scriptMetadataMethod["Address"])
	name = scriptMetadataMethod["Name"].encode("utf-8")
	methodAddr = get_addr(scriptMetadataMethod["MethodAddress"])
	set_name(addr, name)
	setEOLComment(addr, name)
addresses = data["Addresses"]
for index in range(len(addresses) - 1):
	start = get_addr(addresses[index])
	end = get_addr(addresses[index + 1])
	make_function(start, end)
print 'Script finished!'
```

**Comment by therealchjones** [comment]
Thanks. It’s confusing that there does not appear to be an error message noting a spot in the script but rather in Ghidra’s interpreter. Can you confirm that when the script prompts you to choose a file you’re selecting the il2cppdumper script.json file? Are you able to attach that file here?

**Comment by denis70ru** [comment]
I have as soon as I run the script immediately POPs up this error

[script.zip](https://github.com/Perfare/Il2CppDumper/files/5300028/script.zip)

**Comment by therealchjones** [comment]
I apologize for the multiple questions, but I'm just not getting it. Please confirm this is the workflow:
1. Open ghidra CodeBrowser
2. Use the "script manager" tool
3. Find "ghidra.py" in the list and select it
4. Press the green "run" button
5. Before anything else happens, the above error comes up in the script console

**Comment by denis70ru** [comment]
This error occurs when running a python script, there are no problems with java scripts

**Comment by therealchjones** [comment]
Do you mean to say you’re not using the above workflow? How are you running the script?

**Comment by denis70ru** [comment]
I also ran the script

**Comment by therealchjones** [comment]
This isn’t enough information to proceed.  Please list all your steps and the outcome. Ensure other python scripts are working in ghidra.

**Comment by denis70ru** [comment]
I did everything the same way you did. Other scenarios don't work either

**Comment by therealchjones** [comment]
Stop. Write out everything you did, in order, absolutely basically, and what happened. Make a video if you want instead. Do the same with another python script. You’re not giving enough information here, and I can’t help if you won’t answer completely.

**Comment by denis70ru** [comment]
![Gif](https://user-images.githubusercontent.com/60542504/94683169-43852b80-0350-11eb-8881-f67fbd62d435.gif)

**Comment by therealchjones** [comment]
Many of those are throwing exceptions (all the red text in the console), not just the Il2Cppdumper one. It's a problem with your ghidra setup, not this program.
