### ISSUE TITLE
Dump Protected libil2cpp.so

### ISSUE THREAD

**Issue by Waliiid** [Perfare/Il2CppDumper#379]
* Il2CppDumper version : v6.4.12
* Target Unity version: 5.6.3f1 (from unity_builtin_extra)
* Issue:

I got the exact libil2cpp.so bin file from memory using gameguardian and when i tried to dump it using Il2CppDumper, i got asked to write the dump adresse, i tried the adresse from the bin file didn't work, i don't know why check the SS.

![Il2CppDumper_WjDPuLc6hG](https://user-images.githubusercontent.com/20482574/94995356-a9162980-0595-11eb-8fac-98b80293e238.png)

* Files:
[File to dump.zip](https://github.com/Perfare/Il2CppDumper/files/5321905/File.to.dump.zip)

**Comment by Waliiid** [comment]
Never mind

**Comment by lintangtimur** [comment]
> Never mind

have solution?
