### ISSUE TITLE
Dumping the protected lib using bin file from gg

### ISSUE THREAD

**Issue by Ascarre15** [Perfare/Il2CppDumper#382]
Hello there, I dumped the memory of free fire using gg and I got 500+ bin files. So i chose the biggest that is 1.02 gb but i cant get the dummy files else any offsets can anyone help me cz it showing an error...how to use the bin file properly.....the game is latest.

**Comment by Perfare** [comment]
#338

**Comment by BrainedUp** [comment]
> Hello there, I dumped the memory of free fire using gg and I got 500+ bin files. So i chose the biggest that is 1.02 gb but i cant get the dummy files else any offsets can anyone help me cz it showing an error...how to use the bin file properly.....the game is 

> Hello there, I dumped the memory of free fire using gg and I got 500+ bin files. So i chose the biggest that is 1.02 gb but i cant get the dummy files else any offsets can anyone help me cz it showing an error...how to use the bin file properly.....the game is latest.

Hello, please if you have found a solution for that do share.
