### ISSUE TITLE
Can't use auto mode, try manual mode

### ISSUE THREAD

**Issue by mbc07** [Perfare/Il2CppDumper#384]
Trying to use Il2CppDumper but the target binary contains no symbols, is there any way to deduct CodeRegistration and MetadataRegistration addresses by other means? I also got dump.cs from Riru-Il2CppDumper but it doesn't seem possible yet to generate Dummy DLLs just with it...

**Il2CppDumper version:** 6.4.12
**Target Unity version:** 2018.4.21f1
**Binary, metadata and dump.cs:**  [il2cpp_booster_131838603.7z](http://www.mediafire.com/file/660rusg8h27czro/il2cpp_booster_131838603.7z/file)

**Il2CppDumper log:**
```
Initializing metadata...
Metadata Version: 24,1
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24,1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
```

**Comment by mbc07** [comment]
I took a look at the binary of previous versions of this game and found one which seems to ship with a symbol map. Does that help in any way?

**Il2CppDumper version:** 6.4.12
**Target Unity version:** 2017.4.30f1
**Binary, metadata and symbol map:** [il2cpp_booster_107165101.7z](http://www.mediafire.com/file/tbkava8cp6klg7p/il2cpp_booster_107165101.7z/file)

**Il2CppDumper log:**
```
Initializing metadata...
Metadata Version: 24
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
```

**Comment by Perfare** [comment]
In my opinion, this game should modify the structure of il2cpp.
