### ISSUE TITLE
How calculate to decrypt Metadata encrypted?

### ISSUE THREAD

**Issue by thienha1** [Perfare/Il2CppDumper#39]
As you said "It look like Metadata has been encrypted, You should decrypt the data by yourself." But I don't know where to start...
`FF FF 00 00 00 00 FF FF FF FF 93 55 00 00 
2C 00 00 00 FF FF FF FF FF FF FF FF 00 00 
00 00 C0 00 00 06 86 00 00 00 FF FF 00 00 
F8 3F 06 00 5E 0E 00 00 DC 00 00 00 FF FF 
FF FF 00 00 00 00 FF FF FF FF 94 55 00 00 
2C 00 00 00 FF FF FF FF FF FF FF FF 00 00 
00 00 C1 00 00 06 86 00 00 00 FF FF 00 00 
04 40 06 00 5E 0E 00 00 A0 05 00 00 FF FF 
FF FF 00 00 00 00 FF FF FF FF 95 55 00 00 
04 00 00 00 FF FF FF FF FF FF FF FF 00 00 `

**Comment by Perfare** [comment]
Please go to the hacking forum and seek help instead of asking questions here
https://github.com/Perfare/Il2CppDumper#error-metadata-file-supplied-is-not-valid-metadata-file

**Comment by evildog1** [comment]
@thienha1 What game is it?

**Comment by thienha1** [comment]
@evildog1 still that game ...Honkai Impact 3

**Comment by thienha1** [comment]
@evildog1 and i still investigate that

**Comment by evildog1** [comment]
oh now i remember. I'm still unable to recover the metadata yet. let's wait until dev update the game to metadata 24 so we can see function names in .so file
