### ISSUE TITLE
Error reading wasm files.

### ISSUE THREAD

**Issue by USQREN** [Perfare/Il2CppDumper#392]
@Perfare 
Can't get dummy dll.
[Wasm&Metadata.zip](https://github.com/Perfare/Il2CppDumper/files/5469540/Wasm.Metadata.zip)

**Comment by Perfare** [comment]
Download the latest version from here https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

**Comment by USQREN** [comment]
@Perfare
Now everything works without errors. The issue has been resolved.

**Comment by USQREN** [comment]
@Perfare
Now everything works without errors. The issue has been resolved. Thanks.
