### ISSUE TITLE
Wrong addresses for .wsam assemblies

### ISSUE THREAD

**Issue by USQREN** [Perfare/Il2CppDumper#395]
@Perfare
The picture shows the assembly Assembly-CSharp-firstpass.dll (the dump was obtained from the .wasm file)
UnityEngine.Purchasing.OnEnable ()
RVA, Offset, VA have the same offset and they are too small, they are incorrect, it was tested on the game.
https://ibb.co/0fc3Sy3

**Comment by Perfare** [comment]
The method pointer in wsam should be an index. I'm sorry I haven't studied it carefully so I don't understand the mapping relationship.
