### ISSUE TITLE
[question] How do i recompile everything back to GameAssembly.dll after im done modifying everything

### ISSUE THREAD

**Issue by TheCrazyInsanity** [Perfare/Il2CppDumper#396]
I am trying to make a mod for among us and i want to know how to recompile everything back to GameAssembly.dll

**Comment by NaNraptor** [comment]
You dont... You make a dll and then you use things like Melon Loader or you inject the dll in the game yourself

**Comment by Perfare** [comment]
[MelonLoader](https://github.com/HerpDerpinstine/MelonLoader) may be what you need.
