### ISSUE TITLE
Question regarding readme and the DummyDLLs

### ISSUE THREAD

**Issue by SoftwareGuy** [Perfare/Il2CppDumper#398]
In the readme, you specify that the DummyDLLs that this program generates can be used with UTinyRipper to extract MonoBehaviours and other things from the game's asset files. I have used this tool successfully against a game that I want to analyse (and maybe mod later down the track...) and got a dump of the DummyDLLs which I thought included the code from the game, however they are just empty shells (as the name suggests, dummies).

Can UTinyRipper use the DummyDLLs to "reconstruct"/dump the scripts in the game with code, or would it just restore the MonoBehaviours as empty shells? I suppose it's probably hard to interpret the C++ that the IL2CPP part of Unity creates into usable scripts, so you can kinda get a glimpse of the game's code structure but other than that, you don't have the full source code so-to-speak.

Cheers!

**Comment by Perfare** [comment]
In the il2cpp environment, only the structure of MonoBehaviour can be restored. It is useful for viewing specific data in MonoBehaviour, such as ScriptableObject, if you need code, you can only view it through ida and write it manually.
