### ISSUE TITLE
il2cppDumper doesn't compile

### ISSUE THREAD

**Issue by MEG4-hk** [Perfare/Il2CppDumper#399]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Latest Il2CppDumper version (11/11/2020)

- Target Unity version: 2019.1.0f1

I've just cloned the repo and now I'm having an issue when compiling the repo:
`The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.`

**Comment by Perfare** [comment]
> The current .NET SDK does not support targeting .NET Core 3.1. Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
