### ISSUE TITLE
支持metadata版本20支持

### ISSUE THREAD

**Issue by germanzhu** [Perfare/Il2CppDumper#4]
能否添加metadata版本20支持？

**Comment by Perfare** [comment]
可以考虑

**Comment by Perfare** [comment]
暂时没找到20版本的游戏，能上传那两个文件给我吗

**Comment by germanzhu** [comment]
我将我找到的20版本的游戏文件，放置于百度网盘这
链接：http://pan.baidu.com/s/1nv9Howh 密码：764g

**Comment by Perfare** [comment]
你这壳都还没砸呢，砸完后用[Latest build](https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts)应该是可以跑的
