### ISSUE TITLE
README.md should be written in english

### ISSUE THREAD

**Issue by evildog1** [Perfare/Il2CppDumper#40]
Not an issue but it would be great if you can write README.md in english so everyone can read without having to translate using online tool.

**Comment by Perfare** [comment]
My English is not very good, so I also use the translation software if I want to write in English

**Comment by evildog1** [comment]
It's ok. My english is not good too but i can write english without translation tool. Do you mind if i translate README.md to english and maybe you rename chinese version of README to README.zh-cn.md?

**Comment by Perfare** [comment]
never mind, but I'm now refining new features "DummyDll", edit at least once before 100% finish, 
need to wait a moment, or I may try to do it myself.

**Comment by evildog1** [comment]
oh ok
