### ISSUE TITLE
Il2CppDumper.exe软件无法打开～直接闪退

### ISSUE THREAD

**Issue by s88101088** [Perfare/Il2CppDumper#401]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本 6.4.12

- 目标Unity版本 2017.4

- 问题描述  Il2CppDumper.exe软件无法打开～直接闪退

- 上传可执行文件和global-metadata.dat

**Comment by Perfare** [comment]
确认你的电脑运行环境，程序运行需要.net 4.7.2.
