### ISSUE TITLE
Program.cs:line 217

### ISSUE THREAD

**Issue by FuryFearless** [Perfare/Il2CppDumper#402]
- v6.4.12

- 5.3

- Doesnt dump the file i just taking Program.cs:line 217 error

- global-meta.dat i can't upload if u guys want i can upload other downlands website

**Comment by Oderjunkie** [comment]
try uploading global-matadata.dat in a .zip file

**Comment by FuryFearless** [comment]
https://www.dosya.tc/server32/0m0yv1/dat.rar.html i upload here

**Comment by Perfare** [comment]
you need to upload executable file and global-metadata.dat

**Comment by FuryFearless** [comment]
[dat.zip](https://github.com/Perfare/Il2CppDumper/files/5684263/dat.zip)

**Comment by FuryFearless** [comment]
i upload rn
