### ISSUE TITLE
System.Exception: ERROR: Can't use this mode to process file, try another mode.

### ISSUE THREAD

**Issue by Fish37** [Perfare/Il2CppDumper#404]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 5.0.4

- Target Unity version 2019.4.13

- Describe the issue it keeps telling me to try another mode but none of them work

[stuff.zip](https://github.com/Perfare/Il2CppDumper/files/5658127/stuff.zip)

- Upload executable file and global-metadata.dat file is not supported, i uploaded them inside a zip.

**Comment by Perfare** [comment]
I did not encounter any problems with the files you provided.
