### ISSUE TITLE
Can't use auto mode to process file, try manual mode. Help needed.

### ISSUE THREAD

**Issue by bignuts** [Perfare/Il2CppDumper#405]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version -> v6.4.12

- Target Unity version -> 2018.4.2f1 from online researching, could be wrong

- Describe the issue -> ERROR: Can't use auto mode to process file, try manual mode. 

```bash
Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 182191970
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 182191970
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
```

- Upload executable file and global-metadata.dat -> [files.zip](http://www.mediafire.com/file/ws5qyqxoklun301/files.zip/file)

**Comment by Perfare** [comment]
This file appears to be packed.
