### ISSUE TITLE
Structures are getting extracted, but no code is.

### ISSUE THREAD

**Issue by Oderjunkie** [Perfare/Il2CppDumper#406]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.4.12

- Target Unity version: 2017.3.0f3

- Describe the issue
Scripts don't get extracted properly. Proof using a test compilation unity file:
![image](https://user-images.githubusercontent.com/58880677/101658401-07f49500-3a56-11eb-8966-539106d407a4.png)
EDIT FOR CLARIFICATION:
These are the same unity project with "Scripting Backend" changed between "Mono" and "Il2cpp".
"Mono" is the unity project compiled without using il2cpp, and decompiled without il2cppdumper.
"Il2cpp + Il2cppdumper" is the same project compiled using il2cpp, and decompiled using il2cppdumper.
The Mono decompilation was correct, while the il2cppdumper decompilation was incorrect.

- Upload executable file and global-metadata.dat
Attached as .zip file: [dumper.zip](https://github.com/Perfare/Il2CppDumper/files/5667336/dumper.zip).

**Comment by Perfare** [comment]
DummyDll only contains structure, not code.
