### ISSUE TITLE
ida struct script load error 

### ISSUE THREAD

**Issue by w0x12ef** [Perfare/Il2CppDumper#408]
- Il2CppDumper版本
 最新版
- 目标Unity版本
2019.1.4
- 问题描述
- 从ida里面load struct.py脚本，选择il2cpp.h后ida控制台报错
apply_type failed: 0x48e174L System_Byte_array* Mono_Security_X509_X509Certificate__get_SerialNumber (Mono_Security_X509_X509Certificate_o* __this, const MethodInfo* method);
Syntax error near: System_Byte_array
apply_type failed: 0x48e218L System_Byte_array* Mono_Security_X509_X509Certificate__get_Signature (Mono_Security_X509_X509Certificate_o* __this, const MethodInfo* method);
Syntax error near: System_Byte_array
apply_type failed: 0x48d574L System_Byte_array* Mono_Security_X509_X509Certificate__PEM (System_String_o* type, System_Byte_array* data, const MethodInfo* method);
Syntax error near: System_Byte_array
apply_type failed: 0x48f3f4L bool Mono_Security_X509_X509CertificateCollection__Compare (Mono_Security_X509_X509CertificateCollection_o* __this, System_Byte_array* array1, System_Byte_array* array2, const MethodInfo* method);

**Comment by hinxx** [comment]
I wonder why this report is invalid?
I'm seeing similar errors printed for one of the Android libil2cpp.so I'm looking at in IDA.

```
Field '_caseInsensitiveTable' has already been defined
Syntax error near: }
Undefined type name 'System_Resources_RuntimeResourceSet_Fields'
Syntax error near: }
Field '_useAttribute' has already been defined
Syntax error near: }
Undefined type name 'System_Runtime_Remoting_Metadata_SoapMethodAttribute_Fields'
Syntax error near: }
Field '_useAttribute' has already been defined
Syntax error near: }
Undefined type name 'System_Runtime_Remoting_Metadata_SoapTypeAttribute_Fields'
Syntax error near: }
Field '_resourceSets' has already been defined
Syntax error near: }
Undefined type name 'System_ComponentModel_ComponentResourceManager_Fields'
Syntax error near: }
Field 'm_Hits' has already been defined
Syntax error near: }
Undefined type name 'UnityEngine_EventSystems_Physics2DRaycaster_Fields'
Syntax error near: }
Syntax error near: System_Object_array
apply_type failed: 0x247b410L System_String_o* Locale__GetText (System_String_o* fmt, System_Object_array* args, const MethodInfo* method);
...
```

**Comment by Perfare** [comment]
@hinxx What version of ida are you using? Please use version 6.4 or higher.

**Comment by hinxx** [comment]
It is `7.0.170914 Windows x64`.

**Comment by Perfare** [comment]
@hinxx Sorry, I made a typo, please use version 7.4 or above.

**Comment by hinxx** [comment]
Got it. Thanks!
