### ISSUE TITLE
Does this work on Mac and Linux?

### ISSUE THREAD

**Issue by gurrenm3** [Perfare/Il2CppDumper#409]
This is not an issue, more of a question, Does it work on mac and linux? Thanks

Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version

- Describe the issue

- Upload executable file and global-metadata.dat

**Comment by xfoxfu** [comment]
The project supports dotnet core, so it definitely can work on all platforms with dotnet core support. You may grab the source code and compile it under macOS or Linux.

**Comment by gurrenm3** [comment]
Awesome, thanks for your response
