### ISSUE TITLE
But it only shows 32-bit addresses

### ISSUE THREAD

**Issue by ShuperDark** [Perfare/Il2CppDumper#410]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- 6.4.19

- Unknown

- Describe the issue
I'm analyzing an iOS game called SakuraSchoolSimulator, but it only shows 32-bit addresses.
How can I get a 64-bit address to show up?
[https://www.dropbox.com/s/b1nlna1i9ukfm4d/2020-12-23.png?dl=0](url)

- Upload executable file and global-metadata.dat
https://drive.google.com/file/d/1S7fwTwqZ5jNwgesLNmGtH4bhxDcUMPVq/view?usp=sharing
https://drive.google.com/file/d/1sIAbjadHDZCoVLI97nHnvQAQNWxmspB-/view?usp=sharing

**Comment by masagrator** [comment]
This is relative address. 0x0 is start of executable. So until there will be  4GB executables, there is no need for 64-bit addresses

**Comment by ShuperDark** [comment]
> This is relative address. 0x0 is start of executable. So until there will be  4GB executables, there is no need for 64-bit addresses


However, it crashes when hooking a function, which is a problem.
An older version of SakuraSchoolSimulator would show the 64-bit address

**Comment by masagrator** [comment]
Check what is the start address for executable of platform you are using, add this offset to it and done.
Issue will be if your platform is using ASLR. 

This is not the IL2CPPDumper issue. Issue lays on your lack of knowledge.

**Comment by ShuperDark** [comment]
> Check what is the start address for executable of platform you are using, add this offset to it and done.
> 
> Issue will be if your platform is using ASLR.  Then each time you will need to recalculate offset.
> 
> 
> 
> This is not the IL2CPPDumper issue. Issue lays in your lack of knowledge. 

Is this what you mean by 'executable of platform'?
![image](https://user-images.githubusercontent.com/29055910/103126972-661aac80-46d3-11eb-8315-bccac5968697.png)

Or UnityFramework?
