### ISSUE TITLE
[Suggestion] Restore il2cpp VM functions

### ISSUE THREAD

**Issue by neobenedict** [Perfare/Il2CppDumper#412]
With IDA 7.5's in-built Lumina feature it is now possible to automatically restore many of the il2cpp VM functions:

![](https://i.imgur.com/5qbT7e0.png)

With pattern matching it could be possible to implement this into il2cppdumper as well for important functions (such as exception raising). Eventually this could lead to complete decompilation of code back to CIL.

In order to do, a libil2cpp.so with debug symbols should be compiled on Windows and Mac for each Unity and android NDK version of interest, and a table of symbols created similar to how IDA's Lumina function works. This is how I was able to restore 50% of the il2cpp VM functions for a game I had no debug symbols for.

Do you have any plans or ideas of how to implement this? I may get around to it at some point either way.

**Comment by Perfare** [comment]
The amount of engineering is too large, and it is necessary to compile a  executable with symbols for each version, which may also be affected by the compiler.
