### ISSUE TITLE
Requesting assistance

### ISSUE THREAD

**Issue by Ben00n** [Perfare/Il2CppDumper#413]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: Latest(6.4.19)

- Target Unity version : 2018.4.13f1

- Describe the issue: 
![image](https://user-images.githubusercontent.com/72699618/103287221-9bccd780-49ea-11eb-9088-96eb715346e1.png)

the game im working on is PokeOne if you're familiar with it.
it is apparently protected and im not sure how to get the addresses of the ini func

- Upload executable file and global-metadata.dat 
- https://ufile.io/gc9gfdrg ---- metadata
- https://ufile.io/wlabet4a ---- exec

thanks in advance

**Comment by Perfare** [comment]
Unsupported file.
