### ISSUE TITLE
[Question] Do you think a way to import names of functions to rename would be a good fit into this program ?

### ISSUE THREAD

**Issue by LelouBil** [Perfare/Il2CppDumper#414]
I am currently developing a python script to export renamed method names from Ghidra and I have edited a copy of Il2cppDumper to rename these functions to the reverse engineered names automatically, this would be very useful for obfuscated games. However I don't know if it should be a separate utility or if it would be better integrated in Il2cppDumper or Il2cppAssemblyUnhollower.

**Comment by Perfare** [comment]
You can use Il2CppInspector, it seems that he supports anti-obfuscation.
