### ISSUE TITLE
how to obtain coderegistration and metadataregistration codes for the free fire game

### ISSUE THREAD

**Issue by forshared22** [Perfare/Il2CppDumper#418]
Hello, first I'm sorry for my English
- Il2CppDumper version: v6.4.19

i'm trying to get the code registration and metadata registration but i can't, i've looked at the tutorial below but i don't understand anything, it's very different from the process i use il2cppdumper.
https://www.unknowncheats.me/forum/general-programming-and-reversing/355005-il2cppdumper-tutorial-finding-coderegistration-metadataregistration.html

but I will explain my problem below

I used the game guardian to break the protection of the game and got several .bin files, I took the .bin file and excluded it from the .ELF and it worked.

then I got the code from the file "com.dts.freefireth-maps" and it worked as shown below:
![maps txt](https://user-images.githubusercontent.com/65842010/104332557-0f80e100-54cf-11eb-82d0-0b5343f03323.png)

but now you are asking for coderegistration and metadataregistration, how can I get these codes manually?
![codematadata coderegistration](https://user-images.githubusercontent.com/65842010/104332792-5078f580-54cf-11eb-8c29-cc588f1ececc.png)

I opened this new topic because it is different from the others for the free fire game.
please help me.

**Comment by Barshan-Mandal** [comment]
why are you closing it ?Do you fear?
