### ISSUE TITLE
 "can't use auto mode to process the file, try manual mode" 

### ISSUE THREAD

**Issue by donrodrigodelavega** [Perfare/Il2CppDumper#419]
- **Il2CppDumper version**: v6.4.19

- **Target Unity version**: 2020.2.0f1

- **Describe the issue**: The GameAssembly file includes 2 CPU code, for x86 and AARCH64, but can't process the file either architecture selected.

- **Upload executable file and global-metadata.dat**: [GameAssembly.dylib.zip](https://github.com/Perfare/Il2CppDumper/files/5824311/GameAssembly.dylib.zip) / [global-metadata.dat.zip](https://github.com/Perfare/Il2CppDumper/files/5824321/global-metadata.dat.zip)

**Comment by Perfare** [comment]
Unsupported file.

**Comment by donrodrigodelavega** [comment]
It's the new universal binaries Intel/Apple Silicon, it's going to be a standard soon for every unity games.
Please consider support it.
