### ISSUE TITLE
array out of range

### ISSUE THREAD

**Issue by asymmetricg** [Perfare/Il2CppDumper#423]
- Il2CppDumper version: 6.14.9 (tested with a previous version didnt work aswell)

- Target Unity version: ?

- Describe the issue didnt create a dummy folder and anything
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 10f35e1c
MetadataRegistration : 10f365c8
Dumping...
Done!
Generate script...
System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Il2CppDumper.ScriptGenerator.AddRGCTX(StructInfo structInfo, Il2CppTypeDefinition typeDef) na C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:linha 629
   em Il2CppDumper.ScriptGenerator.WriteScript(String outputDir) na C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:linha 80
   em Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) na C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linha 241
   em Il2CppDumper.Program.Main(String[] args) na C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linha 96
Press any key to exit...

- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/5862498/files.zip)

**Comment by Perfare** [comment]
Very strange phenomenon, some data that should be uninitialized has been initialized, causing Il2CppDumper to fail to process normally.
