### ISSUE TITLE
序列不包含任何匹配元素 | v27

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#427]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper v6.4.22
- 目标Unity版本
2020.2.4f1 / v27
- 问题描述
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
7ca3981000
Il2Cpp Version: 27
Input global-metadata.dat dump address:
7ca0059000
Searching...
CodeRegistration : 0
MetadataRegistration : 7ca49db7e0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: E8BA38
Input MetadataRegistration: E8BEAC
System.InvalidOperationException: 序列不包含任何匹配元素
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predica
te)
   在 Il2CppDumper.Elf64.MapVATR(UInt64 addr) 位置 C:\projects\il2cppdumper\Il2C
ppDumper\ExecutableFormats\Elf64.cs:行号 73
   在 Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistrat
ion) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 76
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata
& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.c
s:行号 217
ERROR: An error occurred while processing.
Press any key to exit...
emmm 不知道是不是2020的u3d导致的.
- 上传可执行文件和global-metadata.dat
[dumpso&metadata.zip](https://github.com/Perfare/Il2CppDumper/files/6026221/dumpso.metadata.zip)

**Comment by zahir2000** [comment]
![image](https://user-images.githubusercontent.com/57207346/108837348-10984880-760d-11eb-93fc-e2e8657ad1c0.png)

Files: https://iosddl.net/8bdfbb173f345a99/binary+metadata.zip

**Comment by Perfare** [comment]
版本为27.1，已支持
