### ISSUE TITLE
Can't use auto mode to process file, try manual mode. (The Perfect Tower II)

### ISSUE THREAD

**Issue by Miner28** [Perfare/Il2CppDumper#428]
- Il2CppDumper version
v6.4.22 (currently newest)
- Target Unity version
2020.2.1
- Describe the issue
ERROR: Can't use auto mode to process file, try manual mode.
- Upload executable file and global-metadata.dat
https://cdn.discordapp.com/attachments/754017546558111834/814963398491111484/The_Perfect_Tower_II.zip

**Comment by Miner28** [comment]
Should have posted full log
`PS D:\Download\Il2CppDumper-netcore-v6.4.22> .\Il2CppDumper.exe 'D:\SteamLibrary\steamapps\common\The Perfect Tower II\GameAssembly.dll' 'D:\SteamLibrary\steamapps\common\The Perfect Tower II\The Perfect Tower II_Data\il2cpp_data\Metadata\global-metadata.dat' ..\output\
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 18134b310
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 18134b310
ERROR: Can't use auto mode to process file, try manual mode.`

**Comment by Perfare** [comment]
Now supported.
