### ISSUE TITLE
Can't Dumper

### ISSUE THREAD

**Issue by Sainamz1** [Perfare/Il2CppDumper#429]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.5.0
- Target Unity version
2017.4.40f1
- Describe the issue
ERROR: Can't use auto mode to process file, try manual mode.
- Upload executable file and global-metadata.dat

[libandmeta.zip](https://github.com/Perfare/Il2CppDumper/files/6059598/libandmeta.zip)

**Comment by Sainamz1** [comment]
Initializing metadata...
Metadata Version: 24
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:

**Comment by QVA0Rg** [comment]
Check lib in IDA, its is protected.
