### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Finguy1** [Perfare/Il2CppDumper#432]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: v6.5.0

- Target Unity version: 5.6.4p4

- Getting an error
![Untitled](https://user-images.githubusercontent.com/80328746/110469788-befabe00-80e2-11eb-9cff-4ec323596128.png)

 "System.InvalidOperationException: Sequence contains no matching element"
- This error occures with all versions of il2cppdumber and no matter if I use an encrypted lib that's dumped from memory and there for decrypted or if I use a known uncrypted libil2cpp.so file. This file I add have been successfully dumped by friend of mine with il2cppdumper but I dont have any success.

**Comment by Perfare** [comment]
If your file is dumped from memory, you need to enter the dump address.
