### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by PhoenixICE** [Perfare/Il2CppDumper#435]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 
6.5.0
- Target Unity version
5.x.x 2019.4.19f1
- Describe the issue
global-metadata.dat doesn't pass
`if (BitConverter.ToUInt32(file, 0) == 0xFAB11BAF)`
probably should return some error saying global-metadata.dat isn't found?
![image](https://user-images.githubusercontent.com/2542611/111099565-e7c6fb80-8599-11eb-9b50-0c49e3e2c3b6.png)
- Upload executable file and global-metadata.dat
[ArcanaTactics.zip](https://github.com/Perfare/Il2CppDumper/files/6138608/ArcanaTactics.zip)

Not sure why this global-metadata.dat doesn't work however.
Game: Arcana Tactics
https://play.google.com/store/apps/details?id=com.gamevil.arcanatactics.android.google.global.normal&hl=en_AU&gl=US

**Comment by Perfare** [comment]
The metadata file is encrypted, so it causes this problem.
