### ISSUE TITLE
2019.4.22f1 dump出错。这个版本的好像都dump不出来

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#437]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.5.0
- 目标Unity版本
2019.4.22f1 
- 问题描述
Metadata Version: 24.2
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 251e5d8
MetadataRegistration : 251ed50
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadUInt64()
   在 Il2CppDumper.BinaryStream.ReadPrimitive(Type type) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 122
   在 Il2CppDumper.BinaryStream.ReadClass[T]() 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 142
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 201
   在 Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 110
   在 Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 67
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 190
ERROR: An error occurred while processing.
Press any key to exit...
[dumpfile.zip](https://github.com/Perfare/Il2CppDumper/files/6155673/dumpfile.zip)

- 上传可执行文件和global-metadata.dat

**Comment by morelli690** [comment]
adding more info to this issue:
full link
[](https://www.unknowncheats.me/forum/rust/164256-rust-reversal-structs-offsets-320.html)
[](https://www.unknowncheats.me/forum/rust/164256-rust-reversal-structs-offsets-321.html)
https://i.imgur.com/8GmTIuA.png error point
each talk about link
[](https://www.unknowncheats.me/forum/3090837-post6382.html)
[](https://www.unknowncheats.me/forum/3090904-post6391.html)
[](https://www.unknowncheats.me/forum/3090921-post6397.html)
[](https://www.unknowncheats.me/forum/3091179-post6408.html)

**Comment by Perfare** [comment]
已支持
