### ISSUE TITLE
ERROR: Metadata file supplied is not a supported version[]

### ISSUE THREAD

**Issue by bhxm2009** [Perfare/Il2CppDumper#438]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.5.3
- 目标Unity版本
2018.4.1f
- 问题描述
未获取到版本信息，而是报throw new NotSupportedException($"ERROR: Metadata file supplied is not a supported version错误，var version = ReadInt32();返回文件长度。IDA查看global-metadata.dat头信息如下：
![image](https://user-images.githubusercontent.com/12119902/111874134-b5b8fd80-89ce-11eb-8411-89805508414e.png)

- 上传可执行文件和global-metadata.dat

[Debug.zip](https://github.com/Perfare/Il2CppDumper/files/6175812/Debug.zip)

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper/blob/master/README.zh-CN.md#error-metadata-file-supplied-is-not-valid-metadata-file
