### ISSUE TITLE
Dump Error

### ISSUE THREAD

**Issue by Arsenal88** [Perfare/Il2CppDumper#442]
when I made a dump
this message appear to me

![12](https://user-images.githubusercontent.com/51047081/112976613-62287b80-9155-11eb-871f-873e3db3bb19.PNG)

**Comment by Perfare** [comment]
![QQ截图20210421094711](https://user-images.githubusercontent.com/12952226/115485060-8ecc4080-a286-11eb-9bc9-08f7dda6e665.png)
