### ISSUE TITLE
il2cpp.h is not compatible with Ghidra 

### ISSUE THREAD

**Issue by therealchjones** [Perfare/Il2CppDumper#443]
Though Il2CppDumper has the ability to label methods and parameters in Ghidra via the ghidra_with_struct.py script, this does not work if the types from il2cpp.h are not first imported, and that does not currently work. Relevant notes are in:
- #287: il2cpp.h does not include necessary primitive types, includes Ghidra-unsupported C++-style inheritance
- #366: ghidra_with_struct.py doesn't work without il2cpp.h types defined prior to running
- #371: PR (with discussion) for these issues modified il2cpp.h generation rather than ghidra scripts, potentially negatively impacting IDA compatibility (and ruining inheritance). See [comment by @Perfare](https://github.com/Perfare/Il2CppDumper/pull/371#issuecomment-719957630).

Current (non-working) workflows:

1. Import il2cpp executable into ghidra (analysis is not needed)
2. Run script ghidra_with_struct.py without having imported il2cpp.h: this results in many errors of the type
    ```
    Could not identify type Il2CppType*(parsed as 'Il2CppType *')
    ```
    and
    ```
    Warning: Unable to parse
    void Blur__OnDisable (Blur_o* __this, const MethodInfo* method)
    Attempting to modify...
    Warning: also unable to parse
    void Blur__OnDisable (Blur_o* __thisext, const MethodInfo* method)
    Skipping.
    ```

Or:

1. Import il2cpp executable into ghidra (analysis is not needed)
2. File->Parse C Source..., then Clear (pencil eraser), Save As->il2cpp.h.prf, then add il2cpp.h and "Parse to Program": this results in an error similar to:
    ```    
    2021-03-30 17:11:08 INFO  (CParserTask$3) Parse Errors: C Parser:  Encountered errors during parse. 
         in /[redacted]/il2cpp.h near line -1
         near token: null
         Last Valid Datatype: Il2CppClass * *
         Check around CParserPlugin.out around line: 62
    ```
    (and at least in the case of the program I'm testing this on, line 62 is the first declaration of type `uint32_t`)

Unfortunately, then, at this time ghidra_with_struct.py doesn't appear to be adding any information more than ghidra.py.

I'm hoping these two issues (missing primitives and inheritance) can be worked around with a ghidra scripting solution, probably with edits to ghidra_with_struct.py. 

Question for @Perfare: Is this still worthwhile if it means losing obvious inheritance (in ghidra only)? Since ghidra is only supporting C types, I don't imagine we'd be losing anything meaningful, but am happy to discuss. 

I'll begin working on a scripted solution for ghidra and add a PR when there's something usable.

**Comment by therealchjones** [comment]
So, step 1: I think we'll consider the problem with standard types missing an issue with ghidra rather than il2cppdumper since it's noted several time in ghidra issues not associated with this program. I've posted a workaround on one of them that will work for il2cppdumper output at https://github.com/NationalSecurityAgency/ghidra/issues/716#issuecomment-811094873. This doesn't solve the C++-style inheritance issue, which I'll continue to work on (and give status updates on here, natch).

Perhaps at the end of this making a "guide" on using il2cppdumper with ghidra (rather than altering il2cppdumper to work around every limitation in ghidra) would be helpful. @Perfare, would something like that be appropriate for the main il2cppdumper repo or should I post it elsewhere?

**Comment by Kein** [comment]
Any update on this?

**Comment by therealchjones** [comment]
> Any update on this?

Sorry, what kind of update are you looking for? If you want it to work now, the il2cpp-hmaker script in #287 does what is needed and can be used. If it's the integration into the current ghidra scripts, I can't give you an idea when that'll be available. If it's the aforementioned guide, I'm definitely not going to spend time working on that unless @Perfare and others think it'll be useful to add to the project.

**Comment by Kein** [comment]
>Sorry, what kind of update are you looking for?

Any kind of workaround

**Comment by therealchjones** [comment]
Got it, see the above linked issues. The one from the ghidra repo explains how to get the base types, and the first one linked at the top of this thread includes a shell script that will convert il2cpp.h to a C-style header that can be imported.

**Comment by therealchjones** [comment]
@djkaty/Il2CppInspector already has this figured out, and based on the latest [release notes](https://github.com/djkaty/Il2CppInspector/releases/tag/2021.1), @Perfare is working to build any remaining Il2CppDumper into that, so I’m not going to spend any more time on this. There are a few minor kinks to work out in Il2CppInspector to get it to fit my needs, but they seem more doable.

**Comment by Perfare** [comment]
Yes, using Il2CppInspector is a better way.

**Comment by Real96** [comment]
> > Any update on this?
> 
> Sorry, what kind of update are you looking for? If you want it to work now, the il2cpp-hmaker script in #287 does what is needed and can be used. If it's the integration into the current ghidra scripts, I can't give you an idea when that'll be available. If it's the aforementioned guide, I'm definitely not going to spend time working on that unless @Perfare and others think it'll be useful to add to the project.

I followed the issue, used your workaround script and did what you wrote [here](https://github.com/NationalSecurityAgency/ghidra/issues/716#issuecomment-811094873). But i'm still getting this:

![image](https://user-images.githubusercontent.com/20956021/141684918-352b0c20-0ee8-44d1-a9a8-b3fb6f422216.png)

Any soultions?

**Comment by DRayX** [comment]
Seems like Il2CppInspector has died, and it still doesn't have NSO support.  Any chance we can resolve this in Il2CppDumper?  The current workaround is a total pain.

**Comment by therealchjones** [comment]
Sorry, what’s NSO? The existing Il2cppinspector, even if no longer being developed, does what I need it to instead of using the workaround you mention for il2cppdumper. I don’t foresee spending any more time on this.

**Comment by therealchjones** [comment]
No. As I mentioned above, it appears to work properly with il2cppinspector, so I’m not spending more time on this.

**Comment by DRayX** [comment]
NSO is the Nintendo Switch binary format (Nintendo Switch Object maybe, who knows, the magic number is NSO0).
The latest release of Il2CppInspector notes that it has feature parity with Il2CppDumper except for NSO and wasm support "coming soon", but now I suspect soon might be never.  I'm not sure if it would be easier to fork Il2CppInspector to add NSO loading, or tweak Il2CppDumper so that it's header can be loaded by Ghidra (for now, I did the "super" field via regex, and created a base header with some typedefs).

**Comment by Kein** [comment]
> Seems like Il2CppInspector has died, and it still doesn't have NSO support. Any chance we can resolve this in Il2CppDumper? The current workaround is a total pain.

What current workaround you use for Ghidra and NSOs?

**Comment by DRayX** [comment]
I used regex to replace `: (\w+) {` with `{\n  (\1) super;` and added

```
typedef unsigned __int8 uint8_t;
typedef unsigned __int16 uint16_t;
typedef unsigned __int32 uint32_t;
typedef unsigned __int64 uint64_t;
typedef __int8 int8_t;
typedef __int16 int16_t;
typedef __int32 int32_t;
typedef __int64 int64_t;
typedef __int64 intptr_t;
typedef __int64 uintptr_t;
typedef unsigned __int64 size_t;
```

to the top of the file

**Comment by Kein** [comment]
Which file, again?

**Comment by DRayX** [comment]
The generated il2cpp.h file

**Comment by Kein** [comment]
> No. As I mentioned above, it appears to work properly with il2cppinspector, so I’m not spending more time on this.

Just FYI Il2CPPInspecter has been dead for 2 years
