### ISSUE TITLE
Can't dump process file

### ISSUE THREAD

**Issue by MrSean666** [Perfare/Il2CppDumper#446]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
- v6.5.3

- 目标Unity版本
- 2018.4.14f1

- 问题描述
- ERROR: No symbol is detected
- ERROR: Can't use auto mode to process file, try manual mode.

- 上传可执行文件和global-metadata.dat

[资源加固.zip](https://github.com/Perfare/Il2CppDumper/files/6275996/default.zip)

**Comment by Perfare** [comment]
你都知道加固过了还问啥。。。
