### ISSUE TITLE
27.1版本以上版本无法dump出字符串信息和类typeinfo偏移地址

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#449]
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 27
Searching...
CodeRegistration : 16338a4
MetadataRegistration : 1633e5c
Change il2cpp version to: 27.1
CodeRegistration : 16338a0
Dumping...
Done!
Generate struct...
Done!
Generate dummy dll...
Done!
Press any key to exit...
[27.1.zip](https://github.com/Perfare/Il2CppDumper/files/6325785/27.1.zip)

dump后没有typeinfo信息和字符串的json文件。看了下新版源码这块字段被删掉了。P神有什么思路能获取到吗?

**Comment by Arsenal88** [comment]
@Perfare 

![1212](https://user-images.githubusercontent.com/51047081/115465214-8cd69300-a22e-11eb-958b-bf0b4b39167c.PNG)

**Comment by Perfare** [comment]
已完成，需要注意的是现在Unity改了metadataUsage的格式，如果是从内存中dump的会导致metadataUsage已经初始化无法获取
