### ISSUE TITLE
Dumping from dump file.  (Unable to read beyond the end of the stream.)

### ISSUE THREAD

**Issue by lintangtimur** [Perfare/Il2CppDumper#452]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v6.6.2
- Target Unity version
5.6.4
- Describe the issue
I dumping il2cpp.so from Gameguardian

1. Open gameguardian, select call of duty mobile, and then dump memory
2. Select memory region
![image](https://user-images.githubusercontent.com/16686825/115652651-dcfd4480-a357-11eb-8b0b-693c12a3c071.png)
3. 
![image](https://user-images.githubusercontent.com/16686825/115652734-fef6c700-a357-11eb-8ed1-89ec432a3b73.png)

- Upload executable file and global-metadata.dat
https://gofile.io/d/uxk8tK This zip contain 2 files, `bin` and `global_metadata`

**Comment by muathudaudon** [comment]
https://drive.google.com/file/d/1WoUoYWhY8xrzB89vpDAWGyqiVWgXWCMN/view?usp=drivesdk
Try this dumper

**Comment by muathudaudon** [comment]
t.me/cu8877

**Comment by muathudaudon** [comment]
> Note: if you do not provide all of the following information I will directly ignore and close this issue
> 
> * Il2CppDumper version
>   v6.6.2
> * Target Unity version
>   5.6.4
> * Describe the issue
>   I dumping il2cpp.so from Gameguardian
> 
> 1. Open gameguardian, select call of duty mobile, and then dump memory
> 2. Select memory region
>    ![image](https://user-images.githubusercontent.com/16686825/115652651-dcfd4480-a357-11eb-8b0b-693c12a3c071.png)
> 
> ![image](https://user-images.githubusercontent.com/16686825/115652734-fef6c700-a357-11eb-8ed1-89ec432a3b73.png)
> 
> * Upload executable file and global-metadata.dat
>   https://gofile.io/d/uxk8tK This zip contain 2 files, `bin` and `global_metadata`

dump done
![image](https://user-images.githubusercontent.com/82992390/115685923-e354e600-a382-11eb-9777-62066af3a78e.png)

**Comment by lintangtimur** [comment]
wow, im using gameguardian dump, but still same like above

**Comment by muathudaudon** [comment]
> can you show how u dump from gg?

![IMG_1619139238136_1619139285715](https://user-images.githubusercontent.com/82992390/115802608-6ae53800-a409-11eb-9628-9b80be4f76a6.jpg)
![IMG_1619139279964_1619139283035](https://user-images.githubusercontent.com/82992390/115802615-6e78bf00-a409-11eb-9bf3-1f6e07fcfd49.jpg)
![IMG_1619139698376_1619139702836](https://user-images.githubusercontent.com/82992390/115803035-3d4cbe80-a40a-11eb-983c-a6cd318edfc5.jpg)


Your dump file is error

**Comment by lintangtimur** [comment]
![image](https://user-images.githubusercontent.com/16686825/115810256-d8986080-a417-11eb-8c2c-b91336d7872d.png)
now i have new error, i followed ur instruction, my dump i think is correct
https://gofile.io/d/FFUmbU

**Comment by lintangtimur** [comment]
Oh that error because global_metadata not same version

**Comment by lintangtimur** [comment]
@muathudaudon any tutorial for finding esp, aimbot, recoil, etc from dummyDll?

**Comment by muathudaudon** [comment]
> @muathudaudon any tutorial for finding esp, aimbot, recoil, etc from dummyDll?

Ok
I find code from dump.cs
Ex: no recoil=recoilupbase then get offset and use gg to calcultor

**Comment by lintangtimur** [comment]
> > @muathudaudon any tutorial for finding esp, aimbot, recoil, etc from dummyDll?
> 
> Ok
> I find code from dump.cs
> Ex: no recoil=recoilupbase then get offset and use gg to calcultor

do u have example script for wallhack in codm + offset?
