### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. please help

### ISSUE THREAD

**Issue by muathudaudon** [Perfare/Il2CppDumper#453]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
4.6.0.0
- Target Unity version
Call of duty mobile game
- Describe the issue
ERROR: Can't use auto mode to process file, try manual mode.
- Upload executable file and global-metadata.dat

[global-metadata.dat.zip](https://github.com/Perfare/Il2CppDumper/files/6355406/global-metadata.dat.zip)
 thanks sir

**Comment by lintangtimur** [comment]
I downloaded CODM too, il2cpp.so is protected right? i'm trying dump il2cpp from game memory but not work

**Comment by muathudaudon** [comment]
> I downloaded CODM too, il2cpp.so is protected right? i'm trying dump il2cpp from game memory but not work


i had dumped output script.py+dump.cs with manually via gameguardian but wrong for results value
so i need dump from libil2cpp.so

**Comment by lintangtimur** [comment]
is my dump process is wrong? i had a problem too #452

**Comment by Perfare** [comment]
Il2CppDumper version too old.
