### ISSUE TITLE
 Metadata file supplied is not valid metadata file

### ISSUE THREAD

**Issue by AEROnotAYR0** [Perfare/Il2CppDumper#454]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本

- 目标Unity版本

- 问题描述

- 上传可执行文件和global-metadata.dat

**Comment by AEROnotAYR0** [comment]
Metadata file supplied is not valid metadata file

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper/blob/master/README.zh-CN.md#error-metadata-file-supplied-is-not-valid-metadata-file
