### ISSUE TITLE
System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.

### ISSUE THREAD

**Issue by zahir2000** [Perfare/Il2CppDumper#455]
- Il2CppDumper version: **6.6.2**
- Target Unity version: **2018.4.13f1**
- Describe the issue
![issue](https://i.imgur.com/fn6ZFZi.png)
- [executable file and global-metadata.dat](https://www14.zippyshare.com/v/9quVPboM/file.html)

**Comment by Perfare** [comment]
Encrypted metadata file.
