### ISSUE TITLE
How to dump internal Unity structures like GameObject and Transform?

### ISSUE THREAD

**Issue by srvasn** [Perfare/Il2CppDumper#457]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.6.2

- Target Unity version
2018.2

- Describe the issue

Il2CppDumper is currently unable to dump field information for internal Unity classes (from namespace UnityEngine) like GameObject and Transform.

API reference for GameObject class : https://docs.unity3d.com/ScriptReference/GameObject.html

Extract from header dump output for UnityEngine_GameObject

```
struct UnityEngine_Object_Fields {
	intptr_t m_CachedPtr;
};
 
struct UnityEngine_GameObject_Fields : UnityEngine_Object_Fields {
};

```

Extract from C# class dump for GameObject

```
// Namespace: UnityEngine
public sealed class GameObject : Object // TypeDefIndex: 1941
{
	// Properties
	public Transform transform { get; }
	public int layer { get; set; }
	[ObsoleteAttribute] // RVA: 0x12E6BC8 Offset: 0x12E6BC8 VA: 0xA7F69BC8
	public bool active { get; set; }
	public bool activeSelf { get; }
	public bool activeInHierarchy { get; }
	public bool isStatic { get; set; }
	internal bool isStaticBatchable { get; }
	public string tag { get; set; }
	public Scene scene { get; }
	public GameObject gameObject { get; }
}
```

How do I get the fields for objects like above?

- Upload executable file and global-metadata.dat

Not required as the game can be dumped fine, only classes under the namespace UnityEngine (like GameObject and Transform) have this problem.

**Comment by Perfare** [comment]
These properties are methods rather than fields.
