### ISSUE TITLE
Some errors in dumping

### ISSUE THREAD

**Issue by zyyzyx** [Perfare/Il2CppDumper#458]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper version=v6.6.2

- 目标Unity版本 version=2018.4.5f1

- 问题描述
- 已从内存中dump libil2cpp.so在使用il2cppDumper的时候出现以下错误。
- Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
0xbd11d000
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
CodeRegistration : c36be344
MetadataRegistration : c36be37c
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping

Done!
Generate struct...
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Il2CppExecutor.GetTypeDefinitionFromIl2CppType(Il2CppType il2CppType) 位置 C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:行号 289
   在 Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) 位置 C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:行号 99
   在 Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) 位置 C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:行号 152
   在 Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) 位置 C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:行号 870
   在 Il2CppDumper.StructGenerator.WriteScript(String outputDir) 位置 C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:行号 49
   在 Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 248
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 102

[https://drive.google.com/file/d/1Pv8_iLHpxx40BL9J64-D36RxLrOx_fc5/view?usp=sharing](url) so address

[https://drive.google.com/file/d/1XLynfV-NzDA2fpt1ncmD3SSjUepE9cWm/view?usp=sharing](url) Global Metadata address

**Comment by Perfare** [comment]
根据你的报错情况你选择的是32位的elf文件，32位的dump文件存在问题无法处理，鉴于32位已经被淘汰不打算再继续跟进
