### ISSUE TITLE
無法讀取資料流末端之外。

### ISSUE THREAD

**Issue by p84586** [Perfare/Il2CppDumper#459]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
- 6.6.2

- 目标Unity版本
2018.4.31f1
- 问题描述
Initializing metadata...
System.IO.EndOfStreamException: 無法讀取資料流末端之外。
   於 System.IO.__Error.EndOfFile()
   於 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   於 System.IO.BinaryReader.ReadUInt32()
   於 Il2CppDumper.Metadata..ctor(Stream stream) 於 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs: 行 41
   於 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 126
   於 Il2CppDumper.Program.Main(String[] args) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 100
- 上传可执行文件和global-metadata.dat

https://drive.google.com/file/d/132e3YVhxrWPnnmb07UjxVPGqtbaWcSPE/view?usp=sharing

**Comment by HarukaMomono** [comment]
> 请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue
> 
> * Il2CppDumper版本
> * 6.6.2
> * 目标Unity版本
>   2018.4.31f1
> * 问题描述
>   Initializing metadata...
>   System.IO.EndOfStreamException: 無法讀取資料流末端之外。
>   於 System.IO.__Error.EndOfFile()
>   於 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>   於 System.IO.BinaryReader.ReadUInt32()
>   於 Il2CppDumper.Metadata..ctor(Stream stream) 於 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs: 行 41
>   於 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 126
>   於 Il2CppDumper.Program.Main(String[] args) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 100
> * 上传可执行文件和global-metadata.dat
> 
> https://drive.google.com/file/d/132e3YVhxrWPnnmb07UjxVPGqtbaWcSPE/view?usp=sharing

your global-metadata.dat size is 0 byte

**Comment by p84586** [comment]
> > 请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue
> > 
> > * Il2CppDumper版本
> > * 6.6.2
> > * 目标Unity版本
> >   2018.4.31f1
> > * 问题描述
> >   Initializing metadata...
> >   System.IO.EndOfStreamException: 無法讀取資料流末端之外。
> >   於 System.IO.__Error.EndOfFile()
> >   於 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
> >   於 System.IO.BinaryReader.ReadUInt32()
> >   於 Il2CppDumper.Metadata..ctor(Stream stream) 於 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs: 行 41
> >   於 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 126
> >   於 Il2CppDumper.Program.Main(String[] args) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 100
> > * 上传可执行文件和global-metadata.dat
> > 
> > https://drive.google.com/file/d/132e3YVhxrWPnnmb07UjxVPGqtbaWcSPE/view?usp=sharing
> 
> your global-metadata.dat size is 0 byte

After what you said, I discovered that this file is 0 byte, I think the official version removes this file. Thanks
