### ISSUE TITLE
error when loading ida.py 

### ISSUE THREAD

**Issue by y0ush4** [Perfare/Il2CppDumper#461]
IDA latest 7.5 show 1:bad or ill-formed pre processor command

**Comment by y0ush4** [comment]
![Untitled](https://user-images.githubusercontent.com/39189703/119223745-b9751780-bb18-11eb-91e3-642a3dac820c.png)

script generated is not good

**Comment by masagrator** [comment]
You have in console why it's not working. You don't have IDA Python 3 installed

**Comment by masagrator** [comment]
Tl;dr it's not il2cppdumper issue

**Comment by y0ush4** [comment]
oh! i guess because i didnt ran any setup of IDA7.5 thats why its not getting the python can you point me to how to configure python3 within IDA?

**Comment by y0ush4** [comment]
Fixed thanks for the timely response it was an IDA python issue
