### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. (Last Epoch)

### ISSUE THREAD

**Issue by thekidwhousesabow** [Perfare/Il2CppDumper#463]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Il2CppDumper-netcore-v6.6.2

- Target Unity version
2019.4.23f1

- Describe the issue
Program fails with `ERROR: Can't use auto mode to process file, try manual mode.` when dumping.
<details>
<summary>Full log</summary>

```
Initializing metadata...  
Metadata Version: 24.2  
Initializing il2cpp file...  
Il2Cpp Version: 24.2  
Searching...  
CodeRegistration : 0  
MetadataRegistration : 0  
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
```
</details>

- Upload executable file and global-metadata.dat
[GameAssembly.dll and global-metadata.dat](https://www65.zippyshare.com/v/KtoehsBY/file.html)

**Comment by Perfare** [comment]
The il2cpp structure of this file has been modified.
