### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by hex999** [Perfare/Il2CppDumper#464]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Il2CppDumper v6.6.2
- Target Unity version
2019.4.23f1 (Not sure)
- Describe the issue
I get the following error
`Initializing metadata...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 183
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 100
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...`

I have another release of the same game (and same version) that this process works, and the metadata of this release doesnt seem any more obfuscated, one is considerably smaller, though, but not sure why this release doesnt work, will upload both, thanks for your help

- Upload executable file and global-metadata.dat
https://www.mediafire.com/file/dtt3wdm8t0mlsoa/libil2cppdump.zip/file

same version that is working(dont mind size diff in binaries): 
https://www.mediafire.com/file/u2w5zzxketzlv61/il2cppsoglobal.zip/file

**Comment by muathudaudon** [comment]
me too . have not dumperguid for input unity code

**Comment by hex999** [comment]
It seems metadataUsageList.count is considered 4 bytes, but in this case its 2 bytes, can be fixed please

**Comment by muathudaudon** [comment]
> It seems metadataUsageList.count is considered 4 bytes, but in this case its 2 bytes, can be fixed please

https://github.com/Perfare/Il2CppDumper/issues/130
How to get dumperguid for input unity version??

**Comment by Perfare** [comment]
Encrypted metadata file.
