### ISSUE TITLE
SMT 3 HD Remake: Manual Mode

### ISSUE THREAD

**Issue by Snivy** [Perfare/Il2CppDumper#465]
- Il2CppDumper version: 6.6.2

- Target Unity version: 2019.4.10f1

- Describe the issue: Throws an error, use manual mode; tried using the included scripts with IDA but nothing happened (says module object has no attribute ask_file, scripts.json is missing from the release.) Not quite sure how to start the program in Manual Mode either.

- [Upload executable file and global-metadata.dat](https://www.mediafire.com/file/x9xukqszgnu3n0a/SMT3HD.zip/file)

**Comment by kg** [comment]
Ran into this too. Looking at the dll it doesn't seem to be encrypted or anything, it's a valid PE with lots of sections and all the il2cpp entry points exported. The game does use Denuvo copy protection, so maybe they did something weird to it?

**Comment by Snivy** [comment]
Maybe, I've tried building an empty project with Il2CPP enabled for version 2019.4.10f1 with no real headway, trying Unity version 2019.4.9f1.

Both versions are referenced in the file headers of multiple files, hoping this is the key.

**Comment by Snivy** [comment]
I think I finally found the pointers that manual mode wanted me to find; now it's giving me the error "Array Dimensions exceeded supported range.

**Comment by Snivy** [comment]
Here's the full output:
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 182be9190
Input MetadataRegistration: 182be96dc
Change il2cpp version to: 24.4
CodeRegistration : 182be9178
System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 210
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 123
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 224
ERROR: An error occurred while processing.
Press any key to exit...

**Comment by Perfare** [comment]
This file has been protected, the data is encrypted, you cannot use Il2CppDumper to process.
