### ISSUE TITLE
Index was outside the bounds of the array... Help me

### ISSUE THREAD

**Issue by muathudaudon** [Perfare/Il2CppDumper#466]
![image](https://user-images.githubusercontent.com/82992390/119621527-6eb51180-be30-11eb-8d74-9d868f702ac7.png)
i have read all the documentation about this error,
but there is no satisfactory answer
or can be of help
please someone help me
thank you very much
im using dumper latest

**Comment by Perfare** [comment]
Encrypted metadata file.
