### ISSUE TITLE
ERROR: Metadata file supplied is not a supported version[20050336].

### ISSUE THREAD

**Issue by xoxoxxxz** [Perfare/Il2CppDumper#468]
- Il2CppDumper 6.6.2

- Target Unity version: 2017.4.30f1

- Issue: System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[20050336].

- global-metadata.dat : https://mega.nz/file/PkE0hT5J#VlCIa_GMVmoJvSxvRCDZnEn5P4O2Lk88avLsM7RoOqA
- libil2cpp.so: https://mega.nz/file/uwdiwZpD#o_gllinAoB5IJP18JYNNKcRSHvDI0QlYoS99DKsfwJ4

**Comment by Perfare** [comment]
Encrypted metadata file.
