### ISSUE TITLE
ERROR: il2cpp file is not supported on window 10

### ISSUE THREAD

**Issue by adi2k17** [Perfare/Il2CppDumper#47]
I'm running a vm window 10 on my mac and when I try to dump subway surfer it gives me this error ERROR: il2cpp file is not supported.
   at Il2CppDumper.FormGUI.A(Object , DoWorkEventArgs )
please tell me what do I need to do to fix it ASAP

**Comment by Perfare** [comment]
You select the file not ELF or Mach-O file

**Comment by adi2k17** [comment]
Ohh Thank you

**Comment by adi2k17** [comment]
Wait I selected i64 file and it gave me the same error
