### ISSUE TITLE
WASM Dumping Issue.

### ISSUE THREAD

**Issue by PappaPaj** [Perfare/Il2CppDumper#471]
- Il2CppDumper version - v6.6.2

- Target Unity version - Unknown, Metadata Version  = 27

- Describe the issue

> Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Il2CppDumper.PlusSearch.FindReference(UInt64 addr) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PlusSearch.cs:line 359
   at Il2CppDumper.PlusSearch.FindCodeRegistration2019() in C:\projects\il2cppdumper\Il2CppDumper\Utils\PlusSearch.cs:line 339
   at Il2CppDumper.WebAssemblyMemory.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\WebAssemblyMemory.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
ERROR: An error occurred while processing.

Files to reproduce 

[files.zip](https://github.com/Perfare/Il2CppDumper/files/6610666/files.zip)

**Comment by OdinVex** [comment]
I get EOF issues too but only when targetting the *Linux* build of a game versus the Windows one which works, Metadata 24.2. The Linux version will report "WARNING: find .init_proc" with CR and MR reporting 0. Looking into it on my own.

**Comment by OdinVex** [comment]
Mine is a native build though, so I'll probably just clone and work on it myself sometime.

**Comment by Brian151** [comment]
how do i even get the global-metadata.dat file from a unity webgl game?

**Comment by PappaPaj** [comment]
Any update on this?

**Comment by soyasoya5** [comment]
Have you try setting offsetEnd and addressEnd in this file to STATICTOP?
https://github.com/Perfare/Il2CppDumper/blob/185278310e5b673c13e861b1e191c94d0bbdb845/Il2CppDumper/ExecutableFormats/WebAssemblyMemory.cs#L59

According to this answer by @Perfare , you'll have to find the STATICTOP variable in the Unity framework .js file.
https://github.com/Perfare/Il2CppDumper/issues/202#issuecomment-611850987

It may look like this
```js
    GLOBAL_BASE = 1024;
    STATIC_BASE = GLOBAL_BASE;
    STATICTOP = STATIC_BASE + 4397328;
```

As for obtaining the global-metadata.dat files for Unity WebGL builds, there are hints in the issue I linked above, it should be easy enough to obtain as the data files are usually sent alongside with the .wasm file.

**Comment by me0wday** [comment]
@soyasoya5 I was experimenting with this too, I noticed for me the tool had issues finding the MetadataRegistration address, any chance you can provide some information on how you found it manually in the wasm file?

**Comment by zonya1** [comment]
so I managed to dump a WebGL game. but do anyone know if its possible to "cross-reference" the methods from the DLLs containing the method names to the WASM file (to find the method in WAT code)?
