### ISSUE TITLE
ida.py do not work with NSO

### ISSUE THREAD

**Issue by KurobaM** [Perfare/Il2CppDumper#473]
Il2CppDumper version v6.6.2

Target Unity version 2019.4.17f1

Issue:
 When using ida.py, nothing happen
 NSO is loaded with [nxo64.py](https://github.com/reswitched/loaders)

[Binary + global-metadata](https://drive.google.com/file/d/1gqRP44kb0oQ2CRzeaoBGNFddAtH7Zeob/view)

**Comment by masagrator** [comment]
This is NSO, not NRO

**Comment by KurobaM** [comment]
> This is NSO, not NRO

oops, I might be drunk or smth

**Comment by KurobaM** [comment]
For some reason, idaapi report wrong imagebase. I got the symbol after manually edit the imageBase
