### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by KarenCheat** [Perfare/Il2CppDumper#475]
![0416C168-2BCE-496E-B210-4A4D8AE6A419](https://user-images.githubusercontent.com/86381652/123164549-c53b5d00-d47b-11eb-8528-76e12f0f0224.jpeg)

- Il2CppDumper version 6.6.2

- Target Unity version 2019.4.22

- Game Standoff2

I DONT KNOW HOW TO SEARCH CODE REGISTRATION AND METADATA REGISTRATION 

Please Help Me

**Comment by Bindygames** [comment]
Metadata registration : globalgamemanagers file (or) unity default resources (ressources.assets)
You open the file with notepad and then there should be some numbers : 
![image](https://user-images.githubusercontent.com/67878460/124546337-7933d500-ddf8-11eb-8fd2-e1d76ae91328.png)
You put in the numbers.

**Comment by Perfare** [comment]
You need to upload files to me.

**Comment by KarenCheat** [comment]
[so2.zip](https://github.com/Perfare/Il2CppDumper/files/6772540/so2.zip)

link : https://oxy.cloud/d/HQXd

**Comment by KarenCheat** [comment]
> Metadata registration : globalgamemanagers file (or) unity default resources (ressources.assets)
> You open the file with notepad and then there should be some numbers :
> ![image](https://user-images.githubusercontent.com/67878460/124546337-7933d500-ddf8-11eb-8fd2-e1d76ae91328.png)
> (2018.4.10f1)
> You put in the numbers.

2019.4.22

**Comment by PashaBakhmach** [comment]
help me please
Il2CppDumper version 6.6.5

Unity target version 2019.4.22f1

Link file  https://drive.google.com/file/d/1LxpqaADh54dxE7pJbC8tBISsIfeai0D8/view?usp=sharing

Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[-1443069758].
   в Il2CppDumper.Metadata..ctor(Stream stream) в C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:строка 38
   в Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 126
   в Il2CppDumper.Program.Main(String[] args) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 100
Press any key to exit...

**Comment by KarenCheat** [comment]
You have iOS ?

**Comment by PashaBakhmach** [comment]
Нет хочу дампнуть библимотеку  андроид

**Comment by PashaBakhmach** [comment]
> У тебя iOS?

Нет хочу дампнуть библимотеку андроид

Можешь мне написать https://t.me/PashaProductionYT

**Comment by Perfare** [comment]
global-metadata.dat and executable files are not the same version.
