### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Bindygames** [Perfare/Il2CppDumper#476]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.6.2

- Target Unity version 2020.2.4(.4f1)

- Describe the issue
`Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: The sequence does not contain any matching element.
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.Search() in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 203
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 210
ERROR: An error occurred while processing.
Press any key to exit...`

The update was supposed to fix that

- Upload executable file and global-metadata.dat
[MergeMayor.zip](https://github.com/Perfare/Il2CppDumper/files/6713359/MergeMayor.zip)

**Comment by Bindygames** [comment]
Note : I tried with another binary file that worked in the past and it gave me the same exact error

**Comment by Perfare** [comment]
The executable file is too small, obviously not a Unity file.

**Comment by Bindygames** [comment]
I tried with other games and still the same error.
It is a unity file since there is the unity framework and ressources.
The file is a binary file.

**Comment by Bindygames** [comment]
Note : You were right. It was the wrong file.
