### ISSUE TITLE
Error Initializing metadata... System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[-1443069758].    в Il2CppDumper.Metadata..ctor(Stream stream) в C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:строка 38    в Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 126    в Il2CppDumper.Program.Main(String[] args) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 100 Press any key to exit...                              link file https://drive.google.com/file/d/1kMc4PNhx61ikrv0UOQyMieVVXBiTAO_L/view?usp=sharing

### ISSUE THREAD

**Issue by PashaBakhmach** [Perfare/Il2CppDumper#479]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version  v6.6.3

- Target Unity version XZ

- Describe the issue

- Upload executable file and global-metadata.dat

- Link file https://drive.google.com/file/d/1kMc4PNhx61ikrv0UOQyMieVVXBiTAO_L/view?usp=sharing

ОШИБКА: предоставленный файл метаданных не является поддерживаемой версией [-1443069758]. в Il2CppDumper.Metadata..ctor (поток потока) в C: \ projects \ il2cppdumper \ Il2CppDumper \ Il2Cpp \ Metadata.cs: строка 38 в Il2CppDumper.Program.Init (String il2cppPath, String metadataPath, Metadata & metadata, Il2Cpp & il2Cpp) : \ projects \ il2cppdumper \ Il2CppDumper \ Program.cs: строка 126 в Il2CppDumper.Program.Main (String [] args) в C: \ projects \ il2cppdumper \ Il2CppDumper \ Program.cs: строка 100 Для выхода нажмите любую клавишу ... вчер

**Comment by masagrator** [comment]
lol

**Comment by PashaBakhmach** [comment]
Примечание: если вы не предоставите всю следующую информацию, я проигнорирую и закрою эту проблему.

Il2CppDumper версия v6.6.3

Целевая версия Unity XZ

Опишите проблему

Загрузите исполняемый файл и global-metadata.dat

Ссылка на файл https://drive.google.com/file/d/1kMc4PNhx61ikrv0UOQyMieVVXBiTAO_L/view?usp=sharing

ОШИБКА: предоставленный файл метаданных не является поддерживаемой версией [-1443069758]. в Il2CppDumper.Metadata..ctor (поток потока) в C: \ projects \ il2cppdumper \ Il2CppDumper \ Il2Cpp \ Metadata.cs: строка 38 в Il2CppDumper.Program.Init (String il2cppPath, String metadataPath, Metadata & metadata, Il2Cpp & il2Cpp) : \ projects \ il2cppdumper \ Il2CppDumper \ Program.cs: строка 126 в Il2CppDumper.Program.Main (String [] args) в C: \ projects \ il2cppdumper \ Il2CppDumper \ Program.cs: строка 100 Для выхода нажмите любой другой

**Comment by Perfare** [comment]
Encrypted Metadata.

**Comment by Noobhoch12** [comment]
Have the same problem can somewone help

**Comment by masagrator** [comment]
> Have the same problem can somewone help

What you don't understand in 

> Encrypted Metadata.

**Comment by Noobhoch12** [comment]
but how i can decrypted

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mi., 22. Sept. 2021 um 16:03 Uhr schrieb MasaGratoR <
***@***.***>:

**Comment by Noobhoch12** [comment]
Yea but how i can decrypted it?
