### ISSUE TITLE
Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by luatdolphin** [Perfare/Il2CppDumper#480]
![image](https://user-images.githubusercontent.com/2277080/124540769-50d4c680-de4a-11eb-9cf3-603aaafd0d18.png)
https://drive.google.com/file/d/1eDxBLRbRhPSf5CO2v2KMWYVLAp5GiHBN/view?usp=sharing
https://drive.google.com/file/d/1UfEhb6hRzadO-7b0uWBZKUTQsSu4VhRj/view?usp=sharing
Please help me to check this error

**Comment by Perfare** [comment]
Fixed.
