### ISSUE TITLE
ERROR: il2cpp file not supported.    at Il2CppDumper.FormGUI.Init

### ISSUE THREAD

**Issue by AdindaMotirka** [Perfare/Il2CppDumper#481]
Hello,

- Il2CppDumper version:
 Il2CppDumper-v6.6.5

- Target Unity version
on "\assets\bin\Data\unity default resources" the first line contains 
  ­ 7„          2018.4.24f1 
so the version is "Unity 2018.4.24 - Unity"

- The game is  : (i added space to ignore bots)
"S h a d o w     f i g h t    a r e n a" : I downloaded the last apk from : apkmirror.com

 - Describe the issue
I got this error when, I try to dump the bin file  :

`
Initializing metadata...

Metadata Version: 24.1

Initializing il2cpp file...

System.NotSupportedException: ERROR: il2cpp file not supported.

   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124

   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100

Press any key to exit...
`

- Upload executable file and global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/6795365/global-metadata.zip)

- Upload the BIN FILE I got it with this method:

I dumped the game with "game guardian" from address 1 to 1 000 000 then I searched the first line contains  "il2cpp.so" :

**759efc5000**-**75a66e6000** r-xp 00000000 103:10 20855                         /data/app/~~S0aAoCGos_L0jpyoLr8dwA==/com.nekki.shadowfightarena-z-z5_hrK-c_8NPPZI1PuSw==/lib/arm64/libil2cpp.so

So then I re-dump second time with start "759efc5000" and end  "75a66e6000" I got the bin file :

Best regards,

**Comment by abdullahsaleem1922** [comment]
same issue
