### ISSUE TITLE
无法dump出现错误

### ISSUE THREAD

**Issue by s88101088** [Perfare/Il2CppDumper#483]
Il2CppDumper版本
6.6.5
目标Unity版本
2019.4.15F1
问题描述
出現以下錯誤訊息:
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: 序列未包含符合的項目
   於 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   於 Il2CppDumper.Macho64.Search() 於 C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs: 行 203
   於 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 於 C:\projects\il2cppdumper\Il2CppDumper\Program.cs: 行 210
ERROR: An error occurred while processing.
Press any key to exit...

 
![5555](https://user-images.githubusercontent.com/64821575/125752047-1b2644ff-2aa6-4366-a6e6-699d553c8103.png)

[可执行文件+global-metadata.dat](https://drive.google.com/drive/folders/1O1ogC9dg40FbPGs64TQr234kdgdIWfLJ?usp=sharing)

再麻烦大佬您了

**Comment by Perfare** [comment]
可执行文件选错了
