### ISSUE TITLE
[FEATURE] Show address of generic implementations

### ISSUE THREAD

**Issue by jorgschulze73** [Perfare/Il2CppDumper#485]
Hello, I would like to ask you if it's possible to get address of generic implementations inside il2cpp dump?

Example, if I have the following dump:
```
public interface ExampleInterface 
{
    // RVA: -1 Offset: -1 Slot: 0
    public abstract Out ExampleFunction<In, Out>(In arg);
    /* GenericInstMethod :
    |
    |-RVA: -1 Offset: -1
    |-ExampleInterface.ExampleFunction<int, string>      <--- is it possible to get RVA for these?
    |-ExampleInterface.ExampleFunction<object, object>   <--- 
    ...
}
```

I don't know if this information is present in metadata itself, but I think it would be a great feature for reverse-engineering.

Thank you :D

**Comment by Perfare** [comment]
What you are looking at is the abstract function of the interface, you should look for the implementation of the interface.
