### ISSUE TITLE
Does not dump the full code, only classes and function are there in the dumped filed, there is no logic code in functions

### ISSUE THREAD

**Issue by ThreeLeavesGames** [Perfare/Il2CppDumper#486]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version -- v6.6.5

- Target Unity version -- 2017.4.31f1

- Describe the issue -- the code dumped does not contain any logic inside the functions or classes

- Upload executable file and global-metadata.dat
libil2cpp.so --- https://drive.google.com/file/d/19551B75vm6HH4Ys7ChjIiY1owD5CAeiT/view?usp=sharing
global-metadata.dat ---- https://drive.google.com/file/d/1NDecEVuukEgawzPO1dKbTWuM42dYIRn8/view?usp=sharing

**Comment by masagrator** [comment]
Do I understand correctly you expect from this program to output decompiled code? This tool is not dedicated to this and decompilation process is not so easy to be done automatically by any tool.
