### ISSUE TITLE
The Survivalists 1.0.7 - ghidra with struct script deadlocks when parsing data

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#487]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.6.5

- Target Unity version: unknown, Nintendo Switch

- Describe the issue: Ghidra 9.1.1. when using ghidra_with_struct.py script to load script.json and il2cpp.h, after some time of showing that data are parsing correctly it's deadlocking and ghidra after 15-30 seconds of deadlock cancels process and all parsed data are erased. No issue with ghidra.py

- Upload executable file and global-metadata.dat
https://anonfiles.com/n5UaC88du2/Surv107_zip

**Comment by architdate** [comment]
having the same issue here too

**Comment by Perfare** [comment]
Passing #538 should solve the compatibility problem at present, you need to process il2cpp.h with il2cpp_header_to_ghidra.py first, then compile in Ghidra, and finally run ghidra_with_struct.py.

**Comment by seltix5** [comment]
> Passing #538 should solve the compatibility problem at present, you need to process il2cpp.h with il2cpp_header_to_ghidra.py first, then compile in Ghidra, and finally run ghidra_with_struct.py.

hello, is there a tutorial somewhere with those steps? I could not find any guide :s 
thanks!
