### ISSUE TITLE
dll dont dump

### ISSUE THREAD

**Issue by kingmaaxx** [Perfare/Il2CppDumper#488]
Il2CppDumper version -- v6.6.5

Target Unity version -- 2021.1.4f1

Describe the issue -- i dont get the script.json or the dll files

i get this error at the end

Generate struct...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
Press any key to exit...

Upload executable file and global-metadata.dat
libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing

**Comment by HarukaMomono** [comment]
> Il2CppDumper version -- v6.6.5
> 
> Target Unity version -- 2021.1.4f1
> 
> Describe the issue -- i dont get the script.json or the dll files
> 
> i get this error at the end
> 
> Generate struct...
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
> at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
> at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
> at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
> at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
> Press any key to exit...
> 
> Upload executable file and global-metadata.dat
> libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
> global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing

dump dlls：
[DummyDll.zip](https://github.com/Perfare/Il2CppDumper/files/6936190/DummyDll.zip)

but can not generate struct, there were something error happened

**Comment by muathudaudon** [comment]
> > Il2CppDumper version -- v6.6.5
> > Target Unity version -- 2021.1.4f1
> > Describe the issue -- i dont get the script.json or the dll files
> > i get this error at the end
> > Generate struct...
> > System.IndexOutOfRangeException: Index was outside the bounds of the array.
> > at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
> > at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
> > at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
> > at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
> > Press any key to exit...
> > Upload executable file and global-metadata.dat
> > libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
> > global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing
> 
> dump dlls：
> [DummyDll.zip](https://github.com/Perfare/Il2CppDumper/files/6936190/DummyDll.zip)
> 
> but can not generate struct, there were something error happened

Have offset bro?

**Comment by kingmaaxx** [comment]
> > > Il2CppDumper version -- v6.6.5
> > > Target Unity version -- 2021.1.4f1
> > > Describe the issue -- i dont get the script.json or the dll files
> > > i get this error at the end
> > > Generate struct...
> > > System.IndexOutOfRangeException: Index was outside the bounds of the array.
> > > at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
> > > at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
> > > at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
> > > at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
> > > Press any key to exit...
> > > Upload executable file and global-metadata.dat
> > > libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
> > > global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing
> > 
> > 
> > dump dlls：
> > [DummyDll.zip](https://github.com/Perfare/Il2CppDumper/files/6936190/DummyDll.zip)
> > but can not generate struct, there were something error happened
> 
> Have offset bro?

thanks i have that before from dump.cs
i need the struct so i can add them in IDA

**Comment by muathudaudon** [comment]
> > > > Il2CppDumper version -- v6.6.5
> > > > Target Unity version -- 2021.1.4f1
> > > > Describe the issue -- i dont get the script.json or the dll files
> > > > i get this error at the end
> > > > Generate struct...
> > > > System.IndexOutOfRangeException: Index was outside the bounds of the array.
> > > > at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
> > > > at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
> > > > at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
> > > > at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
> > > > Press any key to exit...
> > > > Upload executable file and global-metadata.dat
> > > > libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
> > > > global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing
> > > 
> > > 
> > > dump dlls：
> > > [DummyDll.zip](https://github.com/Perfare/Il2CppDumper/files/6936190/DummyDll.zip)
> > > but can not generate struct, there were something error happened
> > 
> > 
> > Have offset bro?
> 
> thanks i have that before from dump.cs
> i need the struct so i can add them in IDA

❗HOW TO FIX "System.IndexOutOfRangeException: Index was outside the bounds of the array."
I try dump Codm 1.26 but failed

**Comment by D2s848** [comment]
> > > > > Il2CppDumper version -- v6.6.5
> 
> > > > > Target Unity version -- 2021.1.4f1
> 
> > > > > Describe the issue -- i dont get the script.json or the dll files
> 
> > > > > i get this error at the end
> 
> > > > > Generate struct...
> 
> > > > > System.IndexOutOfRangeException: Index was outside the bounds of the array.
> 
> > > > > at Il2CppDumper.StructGenerator.GenerateRGCTX(String imageName, Il2CppMethodDefinition methodDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 798
> 
> > > > > at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 145
> 
> > > > > at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
> 
> > > > > at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
> 
> > > > > Press any key to exit...
> 
> > > > > Upload executable file and global-metadata.dat
> 
> > > > > libil2cpp.so --- https://drive.google.com/file/d/1EI21OG6LCo1ft2ALXq-cr4d7aF_L5JuD/view?usp=sharing
> 
> > > > > global-metadata.dat ----https://drive.google.com/file/d/1fu4AdV10iY8HUqctiK9A60nzUdGd3wv3/view?usp=sharing
> 
> > > > 
> 
> > > > 
> 
> > > > dump dlls：
> 
> > > > [DummyDll.zip](https://github.com/Perfare/Il2CppDumper/files/6936190/DummyDll.zip)
> 
> > > > but can not generate struct, there were something error happened
> 
> > > 
> 
> > > 
> 
> > > Have offset bro?
> 
> > 
> 
> > thanks i have that before from dump.cs
> 
> > i need the struct so i can add them in IDA
> 
> 
> 
> ❗HOW TO FIX "System.IndexOutOfRangeException: Index was outside the bounds of the array."
> 
> I try dump Codm 1.26 but failed

I'm having a 1.0.20 dump file u can get from it what u want my telegram @xxxsx5

**Comment by Perfare** [comment]
Version is 27.2, already supported.
