### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by den2412** [Perfare/Il2CppDumper#491]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version - 6.6.5

- Target Unity version - 2018.4.35f1

- Describe the issue
- See here - https://cloud.mail.ru/public/HNZ3/po1uDT6jv

- Upload executable file and global-metadata.dat
- See here - https://cloud.mail.ru/public/cPTK/5fk8y6S2y

**Comment by Perfare** [comment]
The dump so has some errors.
