### ISSUE TITLE
Ghidra Plugin

### ISSUE THREAD

**Issue by Kneesnap** [Perfare/Il2CppDumper#492]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v6.6.5 (.NET Framework)

- Target Unity version
Not sure.

- Describe the issue
With Ghidra v10.0.2, ghidra_with_structs.py prints hundreds of warnings, suggesting that there is an issue regarding import.
![image](https://user-images.githubusercontent.com/6562913/129293508-eed591ef-fa69-452b-8863-a7ed72ebe4b6.png)

- Upload executable file and global-metadata.dat
[game_data.zip](https://github.com/Perfare/Il2CppDumper/files/6979434/game_data.zip)

**Comment by Kneesnap** [comment]
Additionally, none of the structs were actually added to the "Data Type Manager" in Ghidra.

**Comment by Perfare** [comment]
Passing #538 should solve the compatibility problem at present, you need to process il2cpp.h with il2cpp_header_to_ghidra.py first, then compile in Ghidra, and finally run ghidra_with_struct.py.
