### ISSUE TITLE
Use ida_with_struct_py3.py with IDA 7.6 = Not responding IDA

### ISSUE THREAD

**Issue by david8557** [Perfare/Il2CppDumper#495]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.6.5

- Target Unity version: 2019.4.8f1 but I think this issue happen with all version

- Describe the issue: With IDA 7.6, if I use ida_with_struct_py3.py it will make IDA not responding. I've been waiting for 2 hours but it still not responding. My CPU is i9-9900 and 32GB RAM so I think PC is not problem. I tried with IDA 7.5 and doesn't have this issue. I don't know if this is IDA 7.6 problem or Il2cppdumper need update script to compatible with latest IDA 7.6

- Upload executable file and global-metadata.dat: https://www98.zippyshare.com/v/cpIH2Ar2/file.html

**Comment by david8557** [comment]
It seem problem at this code, when IDA has to open very big .h file so it's not responding
parse_decls(open(hpath, 'rb').read(), 0)

**Comment by Perfare** [comment]
@david8557 @xfl03 
After my research, this is not a script problem.
For a same 15mb header file, IDA 7.5 can compile it normally. 
In IDA 7.6, if a file has not been analyzed yet, it can also be compiled normally through **File**-**Load file**- **Parse C header file**, but once the file analysis is complete, loading header files through **File**-**Load file**- **Parse C header file** will also cause IDA to lose response.
So the current situation is that IDA 7.6 cannot compile header files that exceed a certain size after completing file analysis. 
This is obviously a problem with IDA 7.6. If you must use IDA 7.6, the current suggestion is to use IDA 7.5 to complete the script operation before using IDA 7.6.
