### ISSUE TITLE
Il2Cpp Version: 27 can't find Code and Metadata Registration - Paint the Town Red Nintendo Switch

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#497]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.6.5

- Target Unity version: 2020.3.3f1

- Describe the issue:
```
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
```

- Upload executable file and global-metadata.dat
https://www108.zippyshare.com/v/Ub8jQTLV/file.html

**Comment by Perfare** [comment]
Sorry to reply to you now, the file has expired, if you still have questions, you can upload it again.

**Comment by masagrator** [comment]
Yeah, my bad I didn't upload it on github directly. I will get back with files for this game 2-3 weeks from now.

**Comment by Perfare** [comment]
According to my research, #521 #519 #497 should all have the same problem, which has now been fixed.

**Comment by annalepattols** [comment]
Versão Il2CppDumper: 6.7.25

Versão do Unity de destino: 2020.3.3f1


Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
