### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. 无法读取CodeRegistration值和MetadataRegistration值

### ISSUE THREAD

**Issue by EUEUE39** [Perfare/Il2CppDumper#498]
- Il2CppDumper版本:6.6.5

- 目标Unity版本:2018.4.14f1【应该是这个

- 问题描述
Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
WARNING: find SHT_LOUSER section
ERROR: This file may be protected.
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
不知道CodeRegistration和MetadataRegistration

- 上传可执行文件和global-metadata.dat
https://drive.google.com/drive/folders/1vsY2LL8aGS4Hmx29hBO_SvVyN3C_cJ5l?usp=sharing
更新了链接

**Comment by Perfare** [comment]
> WARNING: find SHT_LOUSER section
ERROR: This file may be protected.
