### ISSUE TITLE
ERROR: Some errors in dumping

### ISSUE THREAD

**Issue by remmoo** [Perfare/Il2CppDumper#50]
im using Auto(Advanced) Mode.
i think, this file is not supported on IL2CppDumper.
please support this file.

(other mode also failed)

### Error log
```txt
Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
ERROR: Unable to get section.
Applying relocations...
Searching...
CodeRegistration : 1c42970
MetadataRegistration : 1c429e4
Dumping...
ERROR: Some errors in dumping
...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done !
Create DummyDll...
```

### Image
![image](https://user-images.githubusercontent.com/37400510/37455487-87ae9240-2880-11e8-9f8a-8cd580870323.png)

### Files
https://mega.nz/#F!nXJBhA6A!0EVslozIgpoV6f0ZPdv5Qw

### My Environment
Windows 10 64bit 1709 (16299.309)

**Comment by Perfare** [comment]
This file contains a large number of zero bytes, it must be damaged or encrypted

**Comment by lijun0326** [comment]
同krr玩家（
