### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. 

### ISSUE THREAD

**Issue by steve9112** [Perfare/Il2CppDumper#500]
Hello there, 
I keep receiving this message whenever I try to dump the libil2cpp.so :

Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
WARNING: find SHT_LOUSER section
ERROR: This file may be protected.
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:

so can you please extract the GameAssembly.dll from this file: 
https://drive.google.com/file/d/18PElnfesYsVUtOI3i3TiPK5t_0wFvj60/view

thank you

**Comment by Perfare** [comment]
WARNING: find SHT_LOUSER section
ERROR: This file may be protected.
