### ISSUE TITLE
6.6.5 Syntax Error and redefining problem with IDA Pro 7.0

### ISSUE THREAD

**Issue by NaohikoKubo** [Perfare/Il2CppDumper#502]
- Il2CppDumper version
6.6.5 and 6.2.1 

- Target Unity version
24.1

- Describe the issue
In order to analyze an iOS game with IDA, I ran ida_with_struct.py to import script.json and il2cpp.h into IDA.
The results are as follows.
1. 6.6.5
    Problem 1: I get a lot of redefinition errors.
    > Field '_caseInsensitiveTable' has already been defined
    > Syntax error near: } 

    Problem 2: All apply_type functions failed.
    > Syntax error near: World_Data_VersionMstInfo_c
    > apply_type failed: 0x1068e86c0L World_Data_VersionMstInfo_c*

2. 6.2.1
    WORKS FINE. The execution of ida_with_struct.py succeeds with no error.

As a result, il2cpp information such as function argument names and attributes were captured in IDA in 6.2.1, but in 6.6.5, almost all information is missing, making analysis difficult.
Is there anything I should do, such as modifying ida_with_struct.py?

- Upload executable file and global-metadata.dat
[zip](https://www.mediafire.com/file/csfxumjtugswnwm/il2cppdumper_issue.zip/file)

**Comment by Perfare** [comment]
Requires ida 7.3 and above.
