### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by MrSean666** [Perfare/Il2CppDumper#505]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.6.5
- 目标Unity版本
2018.4.36f1_6cd387d23174
- 问题描述
提示"Input CodeRegistration: "后面该输出什么
- 上传可执行文件和global-metadata.dat
[com.kunpo.litaibai.android.ohayoo.zip](https://github.com/Perfare/Il2CppDumper/files/7143275/com.kunpo.litaibai.android.ohayoo.zip)

**Comment by Perfare** [comment]
加密过的文件
