### ISSUE TITLE
IDA parse C header error with fixed width integer type

### ISSUE THREAD

**Issue by h3x4n1um** [Perfare/Il2CppDumper#509]
- Il2CppDumper version: 6.6.5

- Target Unity version: unknown

- Describe the issue: Parse C header error with fixed width integer type using IDA 7.6

![image](https://user-images.githubusercontent.com/8504326/135555646-794cad69-47ab-4bd0-9a1e-bf49c4702f7c.png)

~~- Upload executable file and global-metadata.dat:~~

**Comment by masagrator** [comment]
Those are not C types, those are C++ types. And IDA accepts only C types. You put it manually or they were generated by tool?

**Comment by h3x4n1um** [comment]
It generates by the tool so I don't know why it in C header file

**Comment by masagrator** [comment]
Sorry, deleted post because I was wrong. 

This error doesn't state issue with types. Only that there is syntax error near those. You should upload at least generated header file.

**Comment by h3x4n1um** [comment]
Sorry for my idiocy, I dumped the il2cpp executable and global-metadata.dat from ram but accidentally delete the file that has dumped address (might take a while to me to re-dump it)

Here is the [**il2cpp.h**](https://1drv.ms/u/s!AnAKocoSOJ0Vi_Qm961MDScNI3IwlA?e=ZIa6Nz) file

**Comment by Perfare** [comment]
I'm sorry I never encountered this problem on ida, so I can't help you anything.

**Comment by h3x4n1um** [comment]
Fixed by adding some typedef to header
```c
typedef __int8 uint8_t;
typedef __int8 int8_t;

typedef __int16 uint16_t;
typedef __int16 int16_t;

typedef __int32 uint32_t;
typedef __int32 int32_t;
typedef __int32 intptr_t;

typedef __int64 uint64_t;
typedef __int64 int64_t;
```
