### ISSUE TITLE
About the global-metadata.dat file Chinese string content ~!

### ISSUE THREAD

**Issue by he381141151** [Perfare/Il2CppDumper#51]
Excuse me, how to localize the global-metadata.dat file inside the string? Or is it extracted after the finished, how to back into the global-metadata.dat file ah?

**Comment by he381141151** [comment]
请问，怎么汉化global-metadata.dat文件里面的字符串啊？或者是提取出来后汉化，怎么回编成global-metadata.dat文件啊？

**Comment by Perfare** [comment]
应该没有工具，只能自己参照global-metadata.dat的结构写一个
