### ISSUE TITLE
索引超出了数组界限。

### ISSUE THREAD

**Issue by hx8023lan1314** [Perfare/Il2CppDumper#512]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本      6.6.5

- 目标Unity版本       2021.1.15f1

- 问题描述
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.StructGenerator.AddRGCTX(StructInfo structInfo, Il2CppTypeDefinition typeDef) 位置 C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:行号 761
   在 Il2CppDumper.StructGenerator.WriteScript(String outputDir) 位置 C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:行号 83
   在 Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 248
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 102

- 上传可执行文件和global-metadata.dat   
[main.zip](https://github.com/Perfare/Il2CppDumper/files/7309111/main.zip)

**Comment by HimekoEx** [comment]
![Snipaste_2021-10-31_16-24-29](https://user-images.githubusercontent.com/49508376/139574400-8e387615-8880-48ea-b002-7c9d5adc4b7f.png)

Il2CppGlobalMetadataHeader 结构体发生改变导致无法dump, 我目前并不清楚是哪个版本开始发生变动的
我的unity当前版本为 `2020.3.21`

**Comment by HimekoEx** [comment]
![Snipaste_2021-10-31_16-48-11](https://user-images.githubusercontent.com/49508376/139575002-901651fe-dc6a-4c38-be2c-e967f1acf478.png)

整套初始化流程都发生的变动

**Comment by Perfare** [comment]
实际版本为27.2，已添加支持
