### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Double-Lung** [Perfare/Il2CppDumper#513]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.6.5

- Target Unity version: 2017.3.0f3

- Describe the issue  
I'm trying to get the dummy dll, but the program asks me for manual input:
```
PS D:\Libraries\Downloads\Il2CppDumper-netcore-v6.6.5> .\Il2CppDumper.exe .\GameAssembly.dll .\global-metadata.dat
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
```
- Upload executable file and global-metadata.dat
[files.zip.001](https://github.com/Double-Lung/PW-Style-Prototype/raw/master/required/files.zip.001)
[files.zip.002](https://github.com/Double-Lung/PW-Style-Prototype/raw/master/required/files.zip.002)
(need to unzip together)

**Comment by Perfare** [comment]
Protected file.
