### ISSUE TITLE
Wasm & global-metadata read error

### ISSUE THREAD

**Issue by NordCoderd** [Perfare/Il2CppDumper#515]
Hello, i try to dump wasm and global metadata, but it's throw error...

Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 1dee60
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 1dee60
Input MetadataRegistration: 0
Change il2cpp version to: 27,1
CodeRegistration : 1dee5c
Dumping...

 <details><summary>errors</summary>
    <pre>
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) в C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:строка 149
   в Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) в C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:строка 880
   в Il2CppDumper.StructGenerator.WriteScript(String outputDir) в C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:строка 51
   в Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 248
   в Il2CppDumper.Program.Main(String[] args) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 102
    </pre>
   </details>

Files: https://drive.google.com/file/d/1P-nOJfwBEw0BGQ4MSzDeVr58BYXthAdQ/view?usp=sharing

**Comment by Nightshades1** [comment]
I have the same issue on il2Cpp version 27, a webassembly made from unity (wasm) i don't have the source code.

**Comment by Nightshades1** [comment]
Okay you have to disassembly the wasm and search for Il2CppCodegenRegistration, there you will see 3 constant, (from the top to bottom) you have the representation in decimal, the 1st is the codeRegistration, the second is the metadata registration, you have to convert this to hex (use windows calculator) and enter it as hexadecimal eg: 0x33121 and it will work !

Perfare software work like a charm, just that the autoscan feature got fucked up, but it's not important when we know where to search :)

**Comment by NordCoderd** [comment]
Hi, thank you very much for such helpful advice.
We got a little live hacking, I tried different tips, and over time I got into a stupor when searching, and every time I updated the page with a post, new tips appeared, and finally I did it, thanks!)
I got the class structure, can you have any ideas or advice on how to find function calls from game classes in wasm code?

**Comment by Nightshades1** [comment]
> Hi, thank you very much for such helpful advice. We got a little live hacking, I tried different tips, and over time I got into a stupor when searching, and every time I updated the page with a post, new tips appeared, and finally I did it, thanks!) I got the class structure, can you have any ideas or advice on how to find function calls from game classes in wasm code?

I suggest you to use wasm2c and genererate a full disassembly, this show function name (the name is clearly the offset) so it could be really useful for what you are doing.

Also i wanted to update the method, i just dumped a webassembly game, and i simply used the address provided by Perfare, the "CodeRegistration" address in hex, just substract "4" to it, and finally the wasm you disassembled with wasm2c you search for that address, you will land straight inside il2cppCoderegistration.

Another Technic i found is to take the same unity engine version as the game/app was made with, finally switch the build to webgl, tick "Development Build" and tick "Script Only Build", Then go into the "Player Settings" and set your settings like this
![image](https://user-images.githubusercontent.com/19496833/141171526-0e8ef06d-9c2e-4ad3-9b8b-2728053776c3.png)

Finally you will use wasm2c on your own game, amazing now we can find out how unity devs did organize the thing and the super splendid way is to search for `Z_envZ____cxa_rethrowZ_vv` 
The debug symbols revealed that the 3rd function is what we are looking for.
![image](https://user-images.githubusercontent.com/19496833/141172446-01c05a8d-8ae5-44c7-a890-efba4e75702d.png)

Also don't forget to use DnSpy on the generated DLLStub for analysis, have fun !

**Comment by Nightshades1** [comment]
You may also check https://github.com/garrettgu10/ghidra-wasm-plugin its nice
