### ISSUE TITLE
All of the code inside functions aren't there

### ISSUE THREAD

**Issue by InternalRBLX** [Perfare/Il2CppDumper#517]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v6.6.5

- Target Unity version
2021.1.14f1

- Describe the issue
All of the functions don't have anything inside of them.

- Upload executable file and global-metadata.dat
https://mega.nz/file/OQEhFQ7b#GSnqGlP6iWhMF2k2fw202YDN5qniU1FPEwHIhKElxOM

**Comment by masagrator** [comment]
You sure you didn't mistook how this program works? It doesn't decompile any program, so obviously code is not there. It's not dedicated to this.
