### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by marshpin** [Perfare/Il2CppDumper#518]
i'll attach the metadata and game assembly file below

[Error.zip](https://github.com/Perfare/Il2CppDumper/files/7464816/Error.zip)

**Comment by marshpin** [comment]
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:


The entire log ^

**Comment by Perfare** [comment]
Did not encounter any problems in the file you provided.
