### ISSUE TITLE
Auto mode fails on 2020.1.17f1 NSO

### ISSUE THREAD

**Issue by JillCrungus** [Perfare/Il2CppDumper#519]
- Il2CppDumper version
6.6.5
- Target Unity version
2020.1.17f1
- Describe the issue
When attempting to dump from the given executable (NSO), auto mode fails and Il2CppDumper prompts to use manual mode
[main.zip](https://github.com/Perfare/Il2CppDumper/files/7486134/main.zip)

**Comment by Perfare** [comment]
It has been fixed.
