### ISSUE TITLE
DUSK (Switch) Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#521]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.6.5

- Target Unity version: unknown

- Describe the issue: Can't use auto mode to process file, try manual mode.

```
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
```

- Upload executable file and global-metadata.dat
[DUSK.zip](https://github.com/Perfare/Il2CppDumper/files/7522737/DUSK.zip)

**Comment by Perfare** [comment]
According to my research, #521 #519 #497 should all have the same problem, which has now been fixed.
