### ISSUE TITLE
Add support for newer Unity versions

### ISSUE THREAD

**Issue by Symbai** [Perfare/Il2CppDumper#524]
Currently il2cppdumper rejects any version higher than 27:
https://github.com/Perfare/Il2CppDumper/blob/d6995999d08deb04374b6189110db1c6de49e980/Il2CppDumper/Il2Cpp/Metadata.cs#L49
I've now ran into several games which are version 29. I don't know which unity engine version that is but it would be nice if il2cppdumper supports them.
[Metadata.zip](https://github.com/Perfare/Il2CppDumper/files/7555342/Metadata.zip)

**Comment by SamboyCoding** [comment]
It's unity 2021.2, and depending on your use case, my Cpp2IL project (which was originally a fork of dumper) may be able to help you, as it does support v29

**Comment by Perfare** [comment]
done
