### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by iHunter69** [Perfare/Il2CppDumper#525]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version

- Describe the issue

- Upload executable file and global-metadata.dat

Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 1819dba60
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 1819dba60
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:

its crab game game assembly, not working

**Comment by Perfare** [comment]
I have tested the game you mentioned without any problems, please make sure you are using the latest version.
