### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by iHunter69** [Perfare/Il2CppDumper#528]
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 181a8dc10
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 181a8dc10
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:

**Comment by masagrator** [comment]
Without files noone will help you. Did you read issue template at all?

**Comment by iHunter69** [comment]
> Without files noone will help you. Did you read issue template at all?

i said which file it is, Crab Game GameAssembly, its free on steam.
