### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Rafa2k8** [Perfare/Il2CppDumper#529]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version : 6.6.5

- Target Unity version: 2020.3.4.703331

Gettig this error when tryig to dump.
- Upload executable file and global-metadata.dat:
-
[error.zip](https://github.com/Perfare/Il2CppDumper/files/7634593/error.zip)

**Comment by Perfare** [comment]
Wrong executable file
https://github.com/Perfare/Il2CppDumper#error-cant-use-auto-mode-to-process-file-try-manual-mode
