### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Kami-Kid** [Perfare/Il2CppDumper#531]
I added the GameAssembly.dll and global-metadata.dat but i keep getting the "can't use auto mode to process file, try manual mode." error and all i could find on the topic was people who put the exe file instead of the dll

[il2cpp error.zip](https://github.com/Perfare/Il2CppDumper/files/7653867/il2cpp.error.zip)

**Comment by Perfare** [comment]
I did not encounter any problems with the files you provided.
![屏幕截图 2021-12-06 070019](https://user-images.githubusercontent.com/12952226/144767447-bdfea372-7c71-4c2a-8a70-eac8cce95e39.png)
