### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Rafa2k8** [Perfare/Il2CppDumper#532]
Note: if you do not provide all of the following information I will directly ignore and close this issue
Il2CppDumper version : 6.6.5
Target Unity version: 2020.3.4.703331
Getting this error when trying to dump.
Upload executable file and global-metadata.dat
[error.zip](https://github.com/Perfare/Il2CppDumper/files/7654154/error.zip)
:
sorry for the last time i didnt read it :) thanks in advance

**Comment by Perfare** [comment]
I did not encounter any problems with the files you provided.
![屏幕截图 2021-12-06 065616](https://user-images.githubusercontent.com/12952226/144767392-b96ea52e-a53c-4b09-a0b8-619b48c88fab.png)
