### ISSUE TITLE
Unity v2019.4.11f1 - Il2cpp version 24.3 - Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by david8557** [Perfare/Il2CppDumper#534]
- Il2CppDumper version: 6.6.15

- Target Unity version: 2019.4.11f1

- Describe the issue: If I use the original il2cpp, it will failed with auto mode

> Initializing metadata...
> Metadata Version: 24.2
> Initializing il2cpp file...
> Applying relocations...
> Il2Cpp Version: 24.2
> Searching...
> Change il2cpp version to: 24.3
> CodeRegistration : 4084cb4
> MetadataRegistration : 0
> ERROR: No symbol is detected
> ERROR: Can't use auto mode to process file, try manual mode.
> Input CodeRegistration:

If I use the dump il2cpp with GG, will have another error:

> Initializing metadata...
> Metadata Version: 24.2
> Initializing il2cpp file...
> Detected this may be a dump file.
> Input il2cpp dump address or input 0 to force continue:
> 0x78cbc000
> Il2Cpp Version: 24.2
> Searching...
> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
>    at System.IO.__Error.EndOfFile()
>    at System.IO.MemoryStream.InternalReadInt32()
>    at Il2CppDumper.SectionHelper.FindMetadataRegistrationOld() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 226
>    at Il2CppDumper.Elf.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf.cs:line 153
>    at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
> ERROR: An error occurred while processing.
> Press any key to exit...

- Upload executable file and global-metadata.dat: https://www107.zippyshare.com/v/Q2mO4KnV/file.html
- I have tried to fix this dump il2cpp but it's still fail. Thank you for your time to look at this issue!

**Comment by Perfare** [comment]
global-metadata.dat and libil2cpp.so are not from the same version of apk.
