### ISSUE TITLE
[Help] How do I convert to ghidra?

### ISSUE THREAD

**Issue by boopxyz** [Perfare/Il2CppDumper#535]
Hey so I know there is a ghidra.py but how do I use it? Thanks!

**Comment by masagrator** [comment]
Open any binary with Ghidra so you get disassembler window.
Window -> Script manager
you will have icons in toolbar on the left of window (icon with 3 lines). Click on it
You have now list of directiories where you can put python scripts.
It should have line
```
$USER_HOME/ghidra_scripts
```
If it's there, then you can put scripts on Windows into
```
C:\Users\*your_profile_name*\ghidra_scripts
```

**Comment by boopxyz** [comment]
> 

Alright so I did that and it worked. However, most of my functions are like encrypted or something.
![image](https://user-images.githubusercontent.com/29463310/145599903-ae0352c1-2fe6-42ab-93d2-709e3a18536e.png)

**Comment by masagrator** [comment]
Well, that's not il2cppdumper issue.

**Comment by boopxyz** [comment]
Okay
