### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by somewheel** [Perfare/Il2CppDumper#537]
- Il2CppDumper版本
v6.6.15
- 目标Unity版本
2020.3.21f1
- 问题描述
大佬你好，我这边分析wasm格式就报如下错误：
ERROR: Can't use auto mode to process file, try manual mode.
麻烦帮忙看看，文件都在下面附件里，谢谢！
- 上传可执行文件和global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/7696714/files.zip)

**Comment by Deviinnnnnnnn** [comment]
Having The Same Issue
![image](https://user-images.githubusercontent.com/91716223/145749217-e86600f1-d894-49fe-b268-72f42153ca3c.png)

**Comment by Perfare** [comment]
在我看来你的可执行文件和global-metadata.dat大概率不是来自同一个版本
