### ISSUE TITLE
Initializing metadata... System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[29]

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#540]
Initializing metadata...
System.NotSupportedException: ERR
[Il2CppDumper-v6.6.15.zip](https://github.com/Perfare/Il2CppDumper/files/7709543/Il2CppDumper-v6.6.15.zip)
OR: Metadata file supplied is not a supported version[29]

**Comment by Coinswang** [comment]
大佬，这个29版本的什么时候适配

**Comment by Perfare** [comment]
基本已经完工，如果不需要头文件的话可以先去下载，我晚点再确认头文件结构的改变
https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts
