### ISSUE TITLE
6.15版本和7.2版本无法dump、6.5版本可以dump

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#541]
遇到了一个游戏，我用6.6.15，6.7.2版本都无法dump，但是用v6.6.5旧版本可以。
P神有空看看是这个是游戏魔改了文件问题还是后面版本代码问题吧~笔芯

CodeRegistration : 34e81d0
MetadataRegistration : 34e9580
Change il2cpp version to: 27.1
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadUInt64()
   在 Il2CppDumper.BinaryStream.ReadPrimitive(Type type) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs: 行号 110
   在 Il2CppDumper.BinaryStream.ReadClass[T]() 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 130
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 200
   在 Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 107
   在 Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 91
[6.15版本和7.2版本无法dump-6.5版本可以dump.zip](https://github.com/Perfare/Il2CppDumper/files/7744544/6.15.7.2.dump-6.5.dump.zip)

**Comment by Perfare** [comment]
已修复
