### ISSUE TITLE
crash on  generate dummy dll 【System.Colletions.Generic.KeyNotFoundExcepition】

### ISSUE THREAD

**Issue by jackjieYYY** [Perfare/Il2CppDumper#545]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Il2CppDumper-v6.7.3
- Target Unity version
2017.4.39f1
- Describe the issue
Input CodeRegistration : 6722d54
Input MetadataRegistration: 6722d8c
![6XT~G}(@L 78`NAA1$ QU5D](https://user-images.githubusercontent.com/53422254/147484803-2d22e18e-0e1d-4f26-bf62-c76a435d3439.png)

- Upload executable file and global-metadata.dat
- https://1drv.ms/u/s!Ar48jzKQjQlfgtRhVytJbFZ1z4pqHw?e=jUBXfJ

Hi, Perfare, kindly let me know if you need any further information

**Comment by Perfare** [comment]
Fixed
