### ISSUE TITLE
Empty all functions 

### ISSUE THREAD

**Issue by meghe2000** [Perfare/Il2CppDumper#547]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.7.5

- Target Unity version: 2019.4.13f1

- Describe the issue: 
  after convert scripts, all functions not body
  void Awake(){ //Empty }
  void Test(){ //Empty }

- Upload executable file and global-metadata.dat:
  I saw this problem in every file

**Comment by masagrator** [comment]
il2cppdumper is not disassembling files, so not having code is normal.
Header files are helping with reverse engineering executables in disassemblers.

You mistook what this tool is doing.

**Comment by meghe2000** [comment]
Which tool should I use to decompile complete scripts?

**Comment by masagrator** [comment]
Decompiling exe is not a trivial thing you can do with any tool.
For decompiling Dlls you can use dotPeek.
For decompiling assets you can use uTinyRipper.

**Comment by meghe2000** [comment]
Similar tool
  [http://www.devxdevelopment.com/IL2CPP-Convert-to-Csharp](http://www.devxdevelopment.com/IL2CPP-Convert-to-Csharp)
Do you know?

**Comment by masagrator** [comment]
This works only on ARM devices and it won't recover symbols that don't exist in the first place.

**Comment by Perfare** [comment]
First of all, Il2CppDumper does not decompile and restore the code. This program was designed from the beginning to help other decompilation tools such as ida to better decompile the code of il2cpp.
According to my observation, the program you mentioned can only restore some simple logic codes. You can try https://github.com/SamboyCoding/Cpp2IL, I think it can also do it.

**Comment by opperwopper** [comment]
my binary isnt working  my cpp2_out is empty can u help
