### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by hongjiahua** [Perfare/Il2CppDumper#549]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v6.7.5
- Target Unity version
2020.3.24f1
- Describe the issue
![2022-01-01 (2)](https://user-images.githubusercontent.com/47426264/147854436-ffbfed50-2733-4ade-90ac-3a35ea69fc5f.png)

- Upload executable file and global-metadata.dat
- [https://www21.zippyshare.com/v/08HjHoAp/file.html](url)

**Comment by Perfare** [comment]
The executable file and global-metadata.dat you provided do not seem to be from the same version.

**Comment by hongjiahua** [comment]
But they do exist in the same version of the game, or please try this, but I think the effect is the same as before
[https://www109.zippyshare.com/v/MZShjnXH/file.html](url)
