### ISSUE TITLE
CANT DUMP CODM GAME 

### ISSUE THREAD

**Issue by muathudaudon** [Perfare/Il2CppDumper#550]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 
![Screenshot_20220108-112333_Files](https://user-images.githubusercontent.com/82992390/148631241-66190e27-d9bc-4575-af2b-506f5914cb59.jpg)
Please Fix
- Target Unity version 
- 2019.4.23f1

- Describe the issue
- OUT OF ARAY...

- Upload executable file and global-metadata.dat
- [Binary file](https://linksharing.samsungcloud.com/b8jcMZxf3I4u) [Metadata file](https://linksharing.samsungcloud.com/cfZsr2cntqix)

**Comment by masagrator** [comment]
Without providing files according to last point of issue template noone can help you.

**Comment by muathudaudon** [comment]
> Without providing files according to last point of issue template noone can help you.

I update bug, pl help me, thanks

**Comment by Perfare** [comment]
Looks like the global-metadata.dat file is modified.
