### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Ferryry** [Perfare/Il2CppDumper#553]
I have tried decompiling a IL2Cpp Project and I got the following error: [see title].
I have uploaded the GameAssembly.dll file (to save bandwith I packed it into a *.7z and then in a *.zip file (because GitHub doesn't like 7z archives)).

**Comment by masagrator** [comment]
Did you even read issue template?

Beside you didn't share any link.

**Comment by Ferryry** [comment]
Yes I did and I accidentally forget the attachement. I am sorry.
[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/7846513/GameAssembly.zip)

**Comment by Perfare** [comment]
You did not provide global-metadata.dat file.
