### ISSUE TITLE
ERROR: Can't use auto mode ...

### ISSUE THREAD

**Issue by MrLoLf** [Perfare/Il2CppDumper#554]
Unity Version: 2018.4.36
Description: I used the Game Assembly.dll and the .exe and both didn't work with the global-metadata.dat.
Il2CppDumper Version: v6.7.6
[GitHub Error.zip](https://github.com/Perfare/Il2CppDumper/files/7848865/GitHUb.Error.zip)

**Comment by Perfare** [comment]
File is protected by themida.
