### ISSUE TITLE
Empty methods

### ISSUE THREAD

**Issue by ellislaing** [Perfare/Il2CppDumper#559]
i have used **il2cppdumper** to dump the dll files of crab game. when opening with **dnspy** i can see all of the methods/functions but there is _no code_ inside of them.
![B0A6BA02-5716-4BA9-8F51-04551CF9DFA0](https://user-images.githubusercontent.com/97805950/149636081-c621f474-d74e-4a5b-89f6-6928d5e13f99.png)
what is wrong?

**Comment by masagrator** [comment]
Answer didn't change

https://github.com/Perfare/Il2CppDumper/issues/330#issuecomment-665151778

**Comment by ellislaing** [comment]
> Answer didn't change
> 
> [#330 (comment)](https://github.com/Perfare/Il2CppDumper/issues/330#issuecomment-665151778)

i am not sure how to use ghidra to view the code in the methods
