### ISSUE TITLE
遇到一个没有办法反编译的

### ISSUE THREAD

**Issue by nnjun** [Perfare/Il2CppDumper#56]
错误信息：
![12](https://user-images.githubusercontent.com/26114387/40092749-983f4022-58f1-11e8-8409-d167faf98901.png)

这是两个文件
[文件.zip](https://github.com/Perfare/Il2CppDumper/files/2007288/default.zip)
麻烦作者看一下

**Comment by nnjun** [comment]
@Perfare 艾特一下

**Comment by Perfare** [comment]
这种不用看就是加固过的
