### ISSUE TITLE
script.json and stringliteral.json can not found

### ISSUE THREAD

**Issue by ruijiexie** [Perfare/Il2CppDumper#561]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version

- Describe the issue

- Upload executable file and global-metadata.dat

**Comment by masagrator** [comment]
Your description says absolutely nothing

**Comment by ruijiexie** [comment]
Il2CppDumper The project cannot find these two files
