### ISSUE TITLE
mach-o executable is encrypted and cannot be processed

### ISSUE THREAD

**Issue by estebaneas** [Perfare/Il2CppDumper#563]
- Il2CppDumper version: v6.7.6

- Target Unity version: 2018.4.30f1 (never prompted to me )

- Describe the issue :
I downloaded this game called Final Fantasy War of the visions from the app store, I unpackaged the files from the ipa and got the bin and the global-metadata files. When executing the dumper and feeding it with the files the following messages are showing:
mach-o executable is encrypted and cannot be processed
System.IndexOutOfRangeException: Index was outside the bounds of the array.
![image](https://user-images.githubusercontent.com/74024549/150678913-fb8bc033-7644-4379-96b4-7aa15e09aa26.png)

To me it seems odd because the program still tries to do something after the first error.

Binary (https://drive.google.com/file/d/1uygVzFtuRe6bgeUxM5w5_e3tI4cu4Gm4/view?usp=sharing)
Metadata(https://drive.google.com/file/d/1hTNRma8fQdJVvdXQkG7x69eUBgUfjGN8/view?usp=sharing)

I started first with android, but metadata is obfuscated, then I moved to ios and now it seems that the binary is encrypted, I really don't know but if is not one file is the other that have problems and I assume that the metadata for ios cannot be used for the android binary right?

Maybe this is not a bug and I am stupid :V

**Comment by Perfare** [comment]
You first need to obtain the decrypted macho file, please check the relevant information yourself.
