### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by yuanyan3060** [Perfare/Il2CppDumper#565]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.7.6
- 目标Unity版本
2017.4.39f1
- 问题描述
System.IndexOutOfRangeException: 索引超出了数组界限。
![dump](https://user-images.githubusercontent.com/58114805/151212146-e5c80e4c-6217-4121-a1ce-2d373a2b8281.png)

- 上传可执行文件和global-metadata.dat
下面那个压缩包实际上是7z格式，貌似不能上传7z压缩包（
[arknight 1721.zip](https://github.com/Perfare/Il2CppDumper/files/7943670/arknight.1721.zip)

**Comment by yuanyan3060** [comment]
将metadataUsageListsCount减小8之后能正常Initializing metadata。然后CodeRegistration计算正确，MetadataRegistration错误
![dump2](https://user-images.githubusercontent.com/58114805/151413342-75bfa65f-5d81-49a9-9eca-fa94a24a8925.png)

**Comment by Perfare** [comment]
推测是修改了metadata结构
