### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by liquid8796** [Perfare/Il2CppDumper#567]
Unity Version: 2021.2.3f1 or 2021.2.7f1 (I don't know which one is exactly cause I found 2 version in 2 different files in game folder, but i'm sure 1 of them should be correct version)
Description: I tried GameAssembly.dll with global-metadata.dat but not work.
Il2CppDumper Version: v6.7.6
Attachment: [files.zip](https://github.com/Perfare/Il2CppDumper/files/7960725/files.zip)

**Comment by Perfare** [comment]
file is protected.
