### ISSUE TITLE
how about this error。。。

### ISSUE THREAD

**Issue by athlan20** [Perfare/Il2CppDumper#57]
![image](https://user-images.githubusercontent.com/2987056/40228427-dbd177e6-5ac3-11e8-8a3b-821d03e69149.png)

have meet like this？

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-metadata-file-supplied-is-not-valid-metadata-file

**Comment by athlan20** [comment]
okay,thanks...
