### ISSUE TITLE
dump出来为啥没有script。py文件

### ISSUE THREAD

**Issue by fyfyfy982** [Perfare/Il2CppDumper#573]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper  6.7.5

- 未知

- dump出来为啥没有script。py文件

- 上传可执行文件和global-metadata.dat

**Comment by Perfare** [comment]
因为本来就没有script.py也不会生成script.py文件。

**Comment by thouger** [comment]
2019年的版本有的，作者去掉了，原因不知道为什么
