### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [Perfare/Il2CppDumper#574]
- Il2CppDumper版本：6.7.6

- 目标Unity版本：2017.4.39f1

- 问题描述：
apk中的global-metadata.dat、使用[global-metadata_dump](https://github.com/350030173/global-metadata_dump)和	
GameGuardian dump出来的global-metadata.dat文件完全相同且都是未加密被魔改的状态，在010 Editor中使用Template能跑出结构体，但在使用Il2CppDumper时出现以下问题：
```
Initializing metadata...
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Metadata.ProcessingMetadataUsage() 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 215
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 121
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 126
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 100
Press any key to exit...
```

- 可执行文件和global-metadata.dat：https://zhaolei2008-my.sharepoint.com/:u:/g/personal/zhaolei2008_zhaolei2008_onmicrosoft_com/EeYlsHnMkS5HsfQNOBs7ESQBDay_xMUgZt7D9PoY9CKmKQ?e=mD1HCw

**Comment by Perfare** [comment]
#565
