### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by catchra** [Perfare/Il2CppDumper#579]
[GameAssembly_and_metadata.zip](https://github.com/Perfare/Il2CppDumper/files/8229710/GameAssembly_and_metadata.zip)

I am using Il2CppDumper-v6.7.8

![image](https://user-images.githubusercontent.com/5056308/157816957-d8409dd6-2e05-4af0-b3be-5e0c37cde531.png)

**Comment by Perfare** [comment]
Encrypted file.
