### ISSUE TITLE
所有模式都失败，辛苦看下，谢谢( ios )

### ISSUE THREAD

**Issue by jhtshr** [Perfare/Il2CppDumper#58]
日志截图：
![log](https://user-images.githubusercontent.com/18548098/40816788-606c9054-6581-11e8-9222-d9c39450495a.png)

文件20M，超过10M只能网盘：
链接: https://pan.baidu.com/s/1GPwsvl1TxaRcoob-o32fVw 密码: bfe4

谢谢

**Comment by jbro129** [comment]
Did you try doing different modes? 
2, 3, 4?
You can try manual with the offsets the program already gave.

**Comment by jhtshr** [comment]
All modes have been tried and all failed
