### ISSUE TITLE
What is the name of the program?

### ISSUE THREAD

**Issue by AndreiGTA** [Perfare/Il2CppDumper#581]
What is the name of the program?
![144328845-d5abeb19-a8ca-4da2-a48a-2531b213591f.png](https://user-images.githubusercontent.com/90599898/158027182-2bbcf65a-1e09-41c8-8e15-3b116f7df8c8.png)

**Comment by AndreiGTA** [comment]
> What is the name of the program?
> ![144328845-d5abeb19-a8ca-4da2-a48a-2531b213591f.png](https://user-images.githubusercontent.com/90599898/158027182-2bbcf65a-1e09-41c8-8e15-3b116f7df8c8.png)

**Comment by masagrator** [comment]
"il2cppdumper"?

**Comment by AndreiGTA** [comment]
> "il2cppdumper"?

No, some other program

**Comment by masagrator** [comment]
Then this is not a place for asking this type of questions.
Issues is for... issues related to this program. How your post is related to this program behavior?

**Comment by AndreiGTA** [comment]
> Then this is not a place for asking this type of questions.
> Issues is for... issues related to this program. How your post is related to this program behavior? 

I want to know the name of the program

**Comment by masagrator** [comment]
And I want a cookie.
Ask elsewhere. This is not a general help site. Your question is unrelated to il2cppdumper

**Comment by AndreiGTA** [comment]
> to

What can't you ask?

**Comment by AndreiGTA** [comment]
> And I want a cookie.
> Ask elsewhere. This is not a general help site. Your question is unrelated to il2cppdumper

What can't you ask?

**Comment by Zh40Le1ZOOB** [comment]
The name of the software is "[010 Editor](https://www.sweetscape.com/010editor/)".
Image using the "[UnityMetadata.bt](https://www.sweetscape.com/010editor/repository/files/UnityMetadata.bt)" template.

**Comment by AndreiGTA** [comment]
> The name of the software is "[010 Editor](https://www.sweetscape.com/010editor/)".
> Image using the "[UnityMetadata.bt](https://www.sweetscape.com/010editor/repository/files/UnityMetadata.bt)" template.

Where can I download the template UnityMetadata.bt?

**Comment by Zh40Le1ZOOB** [comment]
You just need to create an blank .txt file. Then copy the content of that [webpage](https://www.sweetscape.com/010editor/repository/files/UnityMetadata.bt) into the .txt file. Finally change the filename extension to .bt .

**Comment by AndreiGTA** [comment]
> You just need to create an blank .txt file. Then copy the content of that [webpage](https://www.sweetscape.com/010editor/repository/files/UnityMetadata.bt) into the .txt file. Finally change the filename extension to .bt .

I created copied and saved in .bt format where you can paste?

**Comment by AndreiGTA** [comment]
> The name of the software is "[010 Editor](https://www.sweetscape.com/010editor/)".
> Image using the "[UnityMetadata.bt](https://www.sweetscape.com/010editor/repository/files/UnityMetadata.bt)" template.

He actually used the ELFTemplate.bt template and not UnityMetadata.bt
