### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Stankye** [Perfare/Il2CppDumper#582]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.7.8

- Target Unity version: 2020..3.25f

- Describe the issue: ERROR: Can't use auto mode to process file, try manual mode.

[gh-issue-7z.zip](https://github.com/Perfare/Il2CppDumper/files/8249002/gh-issue-7z.zip)

7z & zip due to 25MB limit

**Comment by Perfare** [comment]
I haven't had any problems with the files you provided.
