### ISSUE TITLE
报错: System.ArgumentException: Source array was not long enough.

### ISSUE THREAD

**Issue by rewjx** [Perfare/Il2CppDumper#583]
Il2cppdumper版本: Il2CppDumper-net5-v6.7.8

unity版本: 2020.3.25f1，是webAssembly的程序

问题:使用时抛出如下图所示的异常。
![捕获](https://user-images.githubusercontent.com/40747772/158353162-f54d7f45-1673-4b96-b027-1f0e8ebe61e3.PNG)
 抛出异常的代码位于：
`                            var rgctxDefs = new Il2CppRGCTXDefinition[rgctxRange.range.length];
                            Array.Copy(rgctxs, rgctxRange.range.start, rgctxDefs, 0, rgctxRange.range.length);
                            rgctxsDefDictionary.Add(rgctxRange.token, rgctxDefs);`

通过打印rgctxs.Length， rgctxRange.range.start以及rgctxRange.range.length，发现值分别为33，6，4165740。而且跳过该异常值，发现还会出现rgctxRange.range.start大于rgctxs.Length的情况。

这个错误大概是解析wasm的问题？wasm用Ghidra能正常反编译，应该没有加密混淆。global-metadata.dat似乎也没加密，因为搜索内存dump出来的global-metadata.dat和磁盘的一致，没任何区别。

global-metadata.dat: [https://1drv.ms/u/s!Ah3GiOCSBMjhbzCl7pc1nlV_x0k](url)
wasm文件: [https://1drv.ms/u/s!Ah3GiOCSBMjhcOSidU84AuY1jL4?e=znDfyy](url)

**Comment by rewjx** [comment]
我用unity2020.3.25f1编写了一个WebGL的demo程序进行测试，发现用il2cppdumper解析demo程序会报一样的错，因此可以排除是加密混淆之类的原因了。大概就是对wasm的解析有点bug。
希望得到大佬的帮助，谢谢大佬。

**Comment by Perfare** [comment]
指针判断值设的太大，已修复
