### ISSUE TITLE
Inyecting code on Switch main file

### ISSUE THREAD

**Issue by cualquiercosa327** [Perfare/Il2CppDumper#585]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper versión :latest

- Target Unity versión 2021.x

- Describe the issue: I would love learn how I could inyect a modded CSharp.dll file on the main file of the Nintendo Switch 

 Excuse me, could I please talk you?
I have some questions and I believe you could help me. 
Thanks again

**Comment by masagrator** [comment]
> * Describe the issue: I would love learn how I could inyect a modded CSharp.dll file on the main file of the Nintendo Switch

You can't. Period.
Author won't help you with something that is not possible to do.
