### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Hitoshura12** [Perfare/Il2CppDumper#586]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.9

- Target Unity version 2020.3.22f1

- Describe the issue ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat
[GameAssemblyandMetaData.zip](https://github.com/Perfare/Il2CppDumper/files/8309990/GameAssemblyandMetaData.zip)

**Comment by Perfare** [comment]
I haven't had any problems with the files you provided.
