### ISSUE TITLE
索引超出了数组界限

### ISSUE THREAD

**Issue by zf1147956747** [Perfare/Il2CppDumper#587]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.7.9
- 目标Unity版本
2017.4.39
- 问题描述
索引超出了数组界限
- 上传可执行文件和global-metadata.dat
- [https://wwu.lanzouq.com/ilszz01svg0h](url)
![image](https://user-images.githubusercontent.com/102012168/159210061-ab3aa47f-19fc-4db4-8af0-4404f5f9fcf1.png)

**Comment by zbx911** [comment]
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 27
Searching...
Change il2cpp version to: 27.1
CodeRegistration : ac81ea0
MetadataRegistration : ac845e0
System.OverflowException: 数组维度超过了支持的范围。
   在 Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 208
   在 Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:行号 91
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 197
ERROR: An error occurred while processing.
Press any key to exit...

**Comment by Perfare** [comment]
Encrypted file.
