### ISSUE TITLE
Crash in ProcessMetadataUsage when one of Il2CppMetadataUsage types are unused

### ISSUE THREAD

**Issue by Jasuf** [Perfare/Il2CppDumper#590]
- Il2CppDumper version: commit daeff2734

- Target Unity version: Unknown, not relevant

- Describe the issue

In function `ProcessMetadataUsage` at https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Il2Cpp/Metadata.cs#L231 there is a small mistake. If by some chance one of `Il2CppMetadataUsage` types is unused (which is the case for my game of interest), the corresponding subdictionary stays empty and therefore we end up applying `Max` to the emply collection, which raises an exception.

Probable fix would be to change
```
maxMetadataUsages = metadataUsageDic.Max(x => x.Value.Max(y => y.Key)) + 1;
```

to 
```
maxMetadataUsages = metadataUsageDic.Max(x => x.Value.Select(y => y.Key).DefaultIfEmpty().Max()) + 1;
```

to supply a default value in this case and avoid the crash.

- Upload executable file and global-metadata.dat: Sorry, no luck here.

**Comment by Perfare** [comment]
Thank you for your help!
