### ISSUE TITLE
It is unable to find the GameAssembly.dll files nor global-metadata.dat

### ISSUE THREAD

**Issue by cualquiercosa327** [Perfare/Il2CppDumper#591]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version : Il2CppDumper v6.7.8

- Target Unity version:  2020.3.12f1

- Describe the issue I have tried to dump the GameAssembly.dll from the game but i am unable to localize it .The same with the metadata from Disco Elyseum Director cut (latest version). It has no the il2 folder than the latest version had with the global-metadata.dat.
I have tried to extract the files with 

- Upload executable file and 
[Disco Elysium.zip](https://github.com/Perfare/Il2CppDumper/files/8405476/Disco.Elysium.zip)
global-metadata.dat

**Comment by masagrator** [comment]
It is not an issue with tool then, but with you.

**Comment by cualquiercosa327** [comment]
Hi.I am trying to found them as on this version they are no available (as it did on the past versions)

**Comment by Perfare** [comment]
I can't help you solve this problem.
