### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by oofsamy** [Perfare/Il2CppDumper#592]
Among Us by the way

- Il2CppDumper version
6.4.12
- Target Unity version
2020.3.22f1
- Describe the issue
Just the error as title
- Upload executable file and global-metadata.dat
[GameAssemblyAndMetadata.zip](https://github.com/Perfare/Il2CppDumper/files/8405594/GameAssemblyAndMetadata.zip)

**Comment by oofsamy** [comment]
May just mention, I got it working through the web version, still not working on the actual dumper.

**Comment by Perfare** [comment]
I haven't had any problems with the files you provided.
you are using an outdated version.
