### ISSUE TITLE
 ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by lazygabrielKSL** [Perfare/Il2CppDumper#593]
btw this game is umamusume

- Il2CppDumper version
6.7.8

- Target Unity version
2020.3.24f1

- Describe the issue
ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat
[metadata.zip](https://drive.google.com/file/d/1ed2ysYSitFhgrzCEh0cZMuh_mDJAKK1A/view?usp=sharing)

**Comment by Perfare** [comment]
Encrypted file.
