### ISSUE TITLE
Stringliterals wrong address

### ISSUE THREAD

**Issue by blackjack4494** [Perfare/Il2CppDumper#594]
- Il2CppDumper version
  - v6.7.8

~- Target Unity version~ not needed.

- Describe the issue
  - the addresses for stringliterals seems to be wrong.

~- Upload executable file and global-metadata.dat~ not needed.

![image](https://user-images.githubusercontent.com/4406639/162340766-f27a368a-7fcb-423a-a0f7-18ab41e74e5e.png)

This can be seen on the picture. I always wondered why script.json and stringliteral.json have such different addresses. ghidra.py and ghidra_with_scripts.py weren't able to apply the stringliterals but that is due to the wrong addresses and the stringliteral.json in its current form not being parsed by the scripts anyway.
The stringliterals embedded in script.json have addresses that are totally off.
![image](https://user-images.githubusercontent.com/4406639/162347073-9f44b5f6-0530-4b94-83cb-7a8d9902bc6e.png)

I will probably fork the project and open a PR regarding this issue to fix it.

**Comment by Perfare** [comment]
All relative addresses are stored in the json file, because different decompilers may use different base addresses, which will be calculated when the function address is applied in the script.
https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/ghidra_with_struct.py#L20

**Comment by Perfare** [comment]
In addition, I didn't find any problem in your screenshot, the name of stringliterals is also set normally.
