### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#598]
- Il2CppDumper 1.6.8

- Target Unity 2020.3.20f1

![Screenshot_2022-04-14-03-36-45-261_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/163248169-42fe4e57-d024-4bb7-853f-f8ca0dd28ab2.jpg)

https://www.mediafire.com/file/wzsh0el4g4aunb1/com.action.survival.craft.rpg.zip/file

**Comment by Perfare** [comment]
file is supported, you need to set `ForceDump` and `NoRedirectedPointer` to true in `config.json`

**Comment by QPLAYid** [comment]
![Screenshot_2022-04-22-15-04-02-707_bin mt plus canary](https://user-images.githubusercontent.com/102419809/164613321-8c900039-50da-4717-84a0-b74e092f414d.jpg)
add a new sentence?

**Comment by Perfare** [comment]
you need to download the new version.

**Comment by QPLAYid** [comment]
![Screenshot_2022-04-22-16-26-42-749_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/164627570-73417e8b-7270-407d-8528-f1af8852d4a1.jpg)

Now metada SUPLIED  no valid metadata file

**Comment by Perfare** [comment]
I can only guarantee that the file you provide is working fine.
