### ISSUE TITLE
error when dumping using auto advanced and auto 使用自动高级和自动转储时出错

### ISSUE THREAD

**Issue by T3rm1at0r** [Perfare/Il2CppDumper#60]
when trying to dump i get this error and the game im trying to dump is Dead effect 2 and
when i also do manual it does not dump really anything 
当我试图转储我得到这个错误，我试图转储的游戏是死亡效果2和
当我也做手动时，它不会转储任何东西

WARNING: Version 16 can only get CodeRegistration
CodeRegistration : 101bddf40
Exception of type 'System.Exception' was thrown.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 22

ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 116

警告：版本16只能获得CodeRegistration
CodeRegistration：101bddf40
抛出了类型'System.Exception'的异常。
    在C：\ projects \ il2cppdumper \ Il2CppDumper \ Program.cs中的Il2CppDumper.Program.Main（String [] args）：第22行

错误：无法使用此模式处理文件，请尝试其他模式。
    at Il2CppDumper.Program.Main（String [] args）在C：\ projects \ il2cppdumper \ Il2CppDumper \ Program.cs：第116行

when i do just auto i get this 
Initializing il2cpp file...
Searching...
Exception of type 'System.Exception' was thrown.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 22

ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 116

当我做自动我得到这个
初始化il2cpp文件...
搜索...
抛出了类型'System.Exception'的异常。
    在C：\ projects \ il2cppdumper \ Il2CppDumper \ Program.cs中的Il2CppDumper.Program.Main（String [] args）：第22行

错误：无法使用此模式处理文件，请尝试其他模式。
    at Il2CppDumper.Program.Main（String [] args）在C：\ projects \ il2cppdumper \ Il2CppDumper \ Program.cs：第116行

**Comment by Perfare** [comment]
> WARNING: Version 16 can only get CodeRegistration
CodeRegistration : **_101bddf40_**
Use this information to get the MetadataRegistration and then use the manual mode to process the file.

**Comment by T3rm1at0r** [comment]
i did but when i do the script.py does not really dump anything to Ida Pro  
我做了但是当我做脚本时，dot py并没有真正地向Ida Pro转储任何内容
