### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by Beylan** [Perfare/Il2CppDumper#600]
- Il2CppDumper version: v6.7.8

- Target Unity version: v2021.1.17f1

I'm currently trying to translate "The Mortuary Assistant" just for fun. I select GameAssembly.dll and global-metadata in il2cpp_data folder. But then it says "ERROR: Can't use auto mode to process file, try manual mode."

[GameAssemblyy.zip](https://github.com/Perfare/Il2CppDumper/files/8501581/GameAssemblyy.zip)

**Comment by Perfare** [comment]
I haven't had any problems with the files you provided.
