### ISSUE TITLE
FindCodeRegistration2019 里的偏移歪了

### ISSUE THREAD

**Issue by dlnn** [Perfare/Il2CppDumper#602]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.7.8
- 目标Unity版本
2019.4.21f1  Il2cpp版本24.5
- 问题描述

如果是为了通过Il2CppCodeRegistration.codeGenModules查找Il2CppCodeRegistration的话应该-16*sizeof(void*)才对吧
![0PNATDBF7@$~PCFX{JK@~3X](https://user-images.githubusercontent.com/22004270/164059057-40d36452-95e7-4e9f-9403-9d475881656f.png)
![LPKM4Q@_2{7VXBG_H3N7XHM](https://user-images.githubusercontent.com/22004270/164059098-d2a40629-ad1c-4255-a2e9-8fc29a4a852d.png)

- 上传可执行文件和global-metadata.dat

**Comment by Perfare** [comment]
所有小版本会在Il2Cpp.cs里进行判断
https://github.com/Perfare/Il2CppDumper/blob/daeff2734c1ef53ac54abb4c9b53ac586c46b466/Il2CppDumper/Il2Cpp/Il2Cpp.cs#L53-L84

**Comment by dlnn** [comment]
我直接强制版本24.5给我跳过这里了淦 话说你是怎那么区分小版本的 我在分类il2cpp源码 自己diff么

**Comment by Perfare** [comment]
小版本是我自己设定的，只考虑被Il2CppDumper用到的结构，实际上不同Unity版本之间其他的结构体也会有变化。
