### ISSUE TITLE
End of stream error

### ISSUE THREAD

**Issue by johnbbstv** [Perfare/Il2CppDumper#605]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version net6-6.7.18

- Target Unity version 2019.4.18f1

- Describe the issue
- Help please can't make this working !. Thanks ! 
![error unity version 2019 4 18f1](https://user-images.githubusercontent.com/104259601/164893804-1afca1dc-b3ea-46df-ab61-52e20442862a.jpg)

- Upload executable file and global-metadata.dat
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/8546879/global-metadata.zip)
[wasm.zip](https://github.com/Perfare/Il2CppDumper/files/8546881/wasm.zip)

**Comment by Perfare** [comment]
It should work fine now.

**Comment by johnbbstv** [comment]
Sir you are the best !
Thanks a lot !
