### ISSUE TITLE
Support for generating PDB file of gameassembly.dll

### ISSUE THREAD

**Issue by theraininsky** [Perfare/Il2CppDumper#606]
Il2CppDumper version: v6.7.8
Target Unity version: 5.4.0f3

I don't know if currently there's way to load generated symbols(dump.cs) to the living debugger like x64dbg, ollydbg, windbg.
I think it will be much helpful for living debug if this tool can generate a PDB file that can be load in to the debugger.

**Comment by Perfare** [comment]
script files already provide similar functionality.
