### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#607]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.19

- Target Unity version 2020

- Describe the issue

- 
![Screenshot_2022-04-25-13-15-51-763_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/165020158-21dca546-ad64-4a7e-b820-34a5b9754bc1.jpg)

File il2cpp.so and metadata  https://www.mediafire.com/file/a6lpbmj979yoi94/com.WhiteBeardGames.GEARZBOUND.zip/file

**Comment by Perfare** [comment]
Since your so file is dumped from memory, why not set `ForceDump` and `NoRedirectedPointer` to `true`

**Comment by QPLAYid** [comment]
Yea i forget thanks
