### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by MoccoU** [Perfare/Il2CppDumper#608]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version : Il2CppDumper-v6.7.19

- Target Unity version : 2018.4.36f1

- Describe the issue : ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat

[GameAssembly+global-metada.zip](https://github.com/Perfare/Il2CppDumper/files/8575519/GameAssembly%2Bglobal-metada.zip)

**Comment by Perfare** [comment]
32-bit version has been added to load normally.
