### ISSUE TITLE
Dumper version 3.3.9 not dumping but 2.1.3 does

### ISSUE THREAD

**Issue by T3rm1at0r** [Perfare/Il2CppDumper#61]
so i just tested this PLEASE look into this version 3.3.9 does not dump this game but version 2.1.3 dumps it but i still have to do manual now 3.3.9 generates a script.py but it doesn't cache the functions into Ida or it does but its nothing useful but 2.1.3 i have to do manual but it generates a script.py and its useful functions like add currency and other stuff into ida 
all of the above also goes to the game racing rivals 

所以我只是测试了这个请看看这个版本3.3.9不会转储这个游戏，但版本2.1.3转储它但我仍然需要手动现在3.3.9生成一个script.py但它不会将函数缓存到 Ida或它确实但它没有用，但2.1.3我必须做手动但它生成一个script.py及其有用的功能，如添加货币和其他东西到ida
以上所有内容也适用于赛车对手

https://itunes.apple.com/us/app/racing-rivals/id604186826?mt=8

https://itunes.apple.com/us/app/dead-effect-2/id931273204?mt=8

**Comment by Perfare** [comment]
I don’t know what you are talking about in English or Chinese.

**Comment by lijun0326** [comment]
英语还能不带标点符号（

**Comment by lijun0326** [comment]
英语还能不带标点符号（

**Comment by T3rm1at0r** [comment]
所以我只是测试了这个版本3.3.9 不转储这个游戏, 但版本2.1.3 转储它, 但我仍然要做手动3.3.9 生成脚本. 但它不会缓存的功能到 Ida 或它没有什么用处, 但2.1.3 我必须做的人但它会生成一个脚本. 和它的有用的功能, 如添加货币和其他东西到 ida 所有上述也去比赛竞争对手

**Comment by T3rm1at0r** [comment]
我用不同的应用程序翻译它

**Comment by Perfare** [comment]
Still don't know what you are talking about

**Comment by T3rm1at0r** [comment]
basically the 3.3.9 Il2cppdumper version does not dump but version 2.1.3 dumps it but i still have to do manual and 3.3.9 generates a script.py but it doesn't put the functions into Ida or it does but its nothing useful now 2.1.3 i have to do manual but it generates a script.py and its useful functions like add currency and other stuff into ida

**Comment by Perfare** [comment]
Still don't know what you are talking about, but you can consider uploading files to me.

**Comment by T3rm1at0r** [comment]
its good but the newest version of this dumper does not dump any ios game i have so please fix it

**Comment by Perfare** [comment]
@T3rm1at0r Please upload a file

**Comment by Mila432** [comment]
@T3rm1at0r you are bad then , i am dumping ios apps daily and everything works 100%

**Comment by T3rm1at0r** [comment]
@Mila432 i f**** know how to dump if you READ my description i said i have to use a older version to dump this game and other game you probably wont understand this since you dont know how to read and plus this isnt your issue so get OUT

**Comment by T3rm1at0r** [comment]
@Perfare  here are the files the binary of the game and globalmetadata.dat 
https://www69.zippyshare.com/v/wvtSdnib/file.html
https://www69.zippyshare.com/v/ldQe72nr/file.html

**Comment by Perfare** [comment]
test done, both 32-bit and 64-bit work fine, not my fault.

**Comment by T3rm1at0r** [comment]
did you use the newest version of the dumper
