### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#610]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.19

- Target Unity version 2019.4.31f1

Metada and lib https://www.mediafire.com/file/a1580woqxko35nq/samurai.zip/file

![Screenshot_2022-04-29-04-24-02-356_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/165830924-445f7bbd-83bc-4d59-a115-f2762bb346fc.jpg)

i get error after i make "ForceDump": true, "NoRedirectedPointer": true otherwise i make false then i get beyond blah bla bla

**Comment by QPLAYid** [comment]
![Screenshot_2022-04-29-04-49-12-143_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/165834139-a2733926-ca12-466d-a667-826d74358410.jpg)

**Comment by Perfare** [comment]
methodIndex is encrypted.
