### ISSUE TITLE
Help Question about this tool

### ISSUE THREAD

**Issue by rowanbean1960** [Perfare/Il2CppDumper#611]
I dumped the dll files from GameAssembly.dll for the game Ultimate Bomb Squad Demo using il2cpp, and it worked correctly making a dummy folder with all the game dll files, but the problem I having is after I mod the game dlls with dnspy is how to repack the files back to GameAssembly.dll because as far as I know a game using il2cpp will not use the dii file separated like that. Is there a tool to repack the files?

**Comment by masagrator** [comment]
il2cppdumper 's only for getting usable infornations, not to get files that can be moddable. DLL files created by this tool are not valid files to use in any game.

**Comment by rowanbean1960** [comment]
> il2cppdumper is only for getting usable informations, not to get files that can be modded. DLL files created by this tool are not valid files to use in any game.

Is there any tool to extraxt the valid dlls and repack them in a game using il2cpp?
If not then I guess the only way to mod the game is to use the dll files to access the assets
unless you know of another way to mod a game using il2cpp.

Someone should look into it and create a tool to do it if possible if there is not one.

**Comment by rewjx** [comment]
u may mod GameAssembly.dll directly.

**Comment by rowanbean1960** [comment]
@rewjx  Oh OK, thanks.
Can this thread be left open in case of any issues?
If not I will close it.

**Comment by XingGuoWuYu** [comment]
https://github.com/juanmjacobs/il2cpp-modder

**Comment by rowanbean1960** [comment]
> https://github.com/juanmjacobs/il2cpp-modder

I already had il2cppdumper but I need to download and install nodejs.
The page doesn't tell me how to use it or how I use il2cpp modder with il2cppdumper and nodejs.
I will google it but I'M guessing I won't find a tutorial on it.
@XingGuoWuYu Do you know or anyone else know?
THANKS
