### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#614]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.19

- Target Unity version 2018.4.27f1

- Unable to read beyond the end of the stream
I try  ForceDump": true ,
  "NoRedirectedPointer": true
I get same error 
Unable to read beyond the end of the stream

- this file metadata and il2cpp
https://www.mediafire.com/file/t8k73ii5x4hsbbv/metada+and+il2cpp.zip/file

![Screenshot_2022-04-30-21-06-13-277_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/166105589-942e54b8-1a4d-4fd9-8be7-800b2fcfeaf9.jpg)

**Comment by Perfare** [comment]
you didn't dump the complete file.

**Comment by Shekharmine** [comment]
i am facing the same error
![error](https://user-images.githubusercontent.com/126941898/224542208-29103ec4-9560-45f0-bf08-d2f3eba78215.png)
![error-2](https://user-images.githubusercontent.com/126941898/224542209-f8e8447f-608e-45db-9b9f-c3e8f11e5046.png)
i cannot upload a dump file, as the Read Assetes stopped there forever.
how to fix this?
