### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#615]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.19

- Target Unity version
  2019.4.34f1
- Describe the issue
Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat
- https://www.mediafire.com/file/c72uh17eqfsl0ru/metadata+and+lib.zip/file

**Comment by Perfare** [comment]
protected file.
