### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. MARVEL Strike Force: Squad RPG

### ISSUE THREAD

**Issue by tomorroisnew** [Perfare/Il2CppDumper#619]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.7.19
- Target Unity version
2020.3.18f1
- Describe the issue
I tried dumping this game, at first, it shows me Can't use auto mode to process file, so i thought it was encrypted. So i then dumped the libil2cpp.so and global-metadata.dat and now its showing me a different error
![image](https://user-images.githubusercontent.com/85917161/168017120-fab0fb68-803a-4095-980c-e4b69d480140.png)
- Upload executable file and global-metadata.dat
https://www.mediafire.com/file/3gmupkf574mc4gx/files.zip/file
I added both the dumped and the original libil2cpp.so and metadata file there

**Comment by tomorroisnew** [comment]
I finally dumped it in the 32 bit version of the game by manually finding the code registrationg  and the metadata registration. However, it still doesnt work on the 64 bit.

**Comment by tomorroisnew** [comment]
Also got it to worked with x64. I was using the wrong MetadataRegistration. Closing this now

**Comment by kourain** [comment]
> Cũng có nó để làm việc với x64. Tôi đã sử dụng sai MetadataRegistration. Đang đóng cái này

![image](https://user-images.githubusercontent.com/85356599/172625968-6ba9e14a-f784-495e-875b-793677300f75.png)
I had the same problem with another game
what should I do

**Comment by tomorroisnew** [comment]
The game is encrypted. I suggest you dump the library and the global-metadata while the app is running in the memory
