### ISSUE TITLE
System.IndexOutOfRangeException: 索引超出了数组界限。

### ISSUE THREAD

**Issue by thermos17** [Perfare/Il2CppDumper#622]
大佬，麻烦帮我看下这个问题。执行DUMPING的时候报错。
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Il2CppDumper.Il2Cpp.GetMethodPointer(String imageName, Il2CppMethodDefinition methodDef)
   在 Il2CppDumper.StructGenerator.WriteScript(String outputDir)
   在 Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir)
   在 Il2CppDumper.Program.Main(String[] args)
已经上传文件，链接：https://pan.baidu.com/s/1y7qeJJHf12CtxPduR30gVQ?pwd=lnov 
提取码：lnov

**Comment by O2C14** [comment]
好像是so太大导致的，我的so文件有81mb

**Comment by thermos17** [comment]
不会，200MB的我DUMP过都可以，问题应该在META上


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Perfare/Il2CppDumper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 凌晨0:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Perfare/Il2CppDumper] System.IndexOutOfRangeException: 索引超出了数组界限。 (Issue #622)





 
好像是so太大导致的，我的so文件有81mb

**Comment by thermos17** [comment]
没有加密，应该是结构改动过了，碰过好多个类似的，没有工具可以解决，除非手动去改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Perfare/Il2CppDumper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 凌晨0:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Perfare/Il2CppDumper] System.IndexOutOfRangeException: 索引超出了数组界限。 (Issue #622)





 
META加密？

**Comment by O2C14** [comment]
但是我用v6.6.5dump出来了，只是不知道是不是正确的

**Comment by O2C14** [comment]
Zygisk-Il2CppDumper使用方法过于繁琐，我直接放弃挣扎

**Comment by Perfare** [comment]
methodPointerIndex加密或者global-metadata.dat加密
