### ISSUE TITLE
Unable to process 2020.3.31f1

### ISSUE THREAD

**Issue by sanktanglia** [Perfare/Il2CppDumper#625]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version - Il2CppDumper-v6.7.19

- Target Unity version - 2020.3.31f1

- Describe the issue - unable to process in manual or auto version, doesnt work when dumping or using game files

- Upload executable file and global-metadata.dat - https://1drv.ms/u/s!AsgK5_qXV9lKhv8PPP5YIG5DMrNipg?e=fLyk3G offset should be 8000000
- Non dumped version - https://1drv.ms/u/s!AsgK5_qXV9lKhv8QFaNYjV-PNo9Azw?e=5aigfe

**Comment by Perfare** [comment]
Unsupported protected file.
