### ISSUE TITLE
 Error while restoring attribute Index 16797

### ISSUE THREAD

**Issue by phantom54** [Perfare/Il2CppDumper#628]
Il2CppDumper-v6.7.1
i put dll and metadata in .7z and then in .zip
[Monster Charmer 0.2.0 dll and metadata.zip](https://github.com/Perfare/Il2CppDumper/files/8824929/Monster.Charmer.0.2.0.dll.and.metadata.zip)

**Comment by Perfare** [comment]
Same as #620, fixed.
