### ISSUE TITLE
Unity好像有了新的编译模式，现在没有global-metadata.dat了

### ISSUE THREAD

**Issue by esterTion** [Perfare/Il2CppDumper#63]
[プリコネR](https://priconne-redive.jp/) 1.6.0版本里面没有global-metadata.dat了，我碰的游戏也不算是多不知道这是不是首个例子，目前确认了ios和apk都没有

程序样本：[redive_1.6.0.7z](https://estertion.win/media/redive_1.6.0.7z)

**Comment by Perfare** [comment]
明显被压缩加密了，直接从内存dump即可

**Comment by Perfare** [comment]
稍微看了下cy把metadata直接存在了libil2cpp.so的data里，还有个导出符号coneshell_global_metadata_dat
做了个简单的加密，具体算法在il2cpp::vm::MetadataLoader::LoadMetadataFile里

**Comment by esterTion** [comment]
更新一下，虽然可能你也并不关心（

按照那个函数去看了后发现是整个metadata文件取反存在程序里了，所以我后来直接搜文件头 af1bb1fa 的反 50e44e05 就搜到了，这存法也是暴力，不过也杜绝了直接搜索
还是感谢指路

**Comment by Perfare** [comment]
PC版那个我也看了，都没有任何保护措施，把Coneshell那个类拿出来就可以了直接用了。。。

**Comment by esterTion** [comment]
是，pc版啥都没有直接拖
我在服务器挂的自动数据更新直接用了他dll拿wine调用搞完了，也算是能用，猜测短期也不会再换了（
[unity-texture-toolkit/ 63fc4a9](https://github.com/esterTion/unity-texture-toolkit/commit/63fc4a9ee8dbfd068e8f945feb6773686f343dee)

**Comment by lshy1993** [comment]
大佬们，我用dnspy能看到coneshell，问题是如何将cdb提取出来啊，cy改变了数据库太难受了……

**Comment by esterTion** [comment]
你想要提取cdb的话我这有两条路：
1、自己提取：用我的 [Coneshell_call.exe](https://github.com/esterTion/unity-texture-toolkit/blob/master/redive/Coneshell_call/main.cpp)，然后`Coneshell_call.exe -cdb masterdata.cdb master.db`，参考[esterTion/unity-texture-toolkit: redive/main.php](https://github.com/esterTion/unity-texture-toolkit/blob/f28287c043e36276981399790485e0dd6bbb16a2/redive/main.php#L388): L388-416
2、直接从我的更新站里面下载提取好的 [redive.db.br](https://redive.estertion.win/db/redive_jp.db.br)，然后用brotli解压，更新检测逻辑参考 [superk589/PrincessGuide: Updater.swift](https://github.com/superk589/PrincessGuide/blob/2f380b8aa8f5e2e8f32681ed654fe1d24a883534/PrincessGuide/Common/Updater.swift)

**Comment by bgli100** [comment]
按 @esterTion 给的方法搜50e44e05提取整段后取反顺利拿到了metadata，但是丢给 Il2CppDumper 提取失败（提示版本是192不知道什么毛病）

Ultraedit看内容有大段明文估计取反没问题，文件头感觉还是不对？不知道有什么思路么

https://mega.nz/#!Hpx1Tb5C!sSXjDZgrHQARKX7piVlcH7V-6IedE03IyTD-MkDvKps

**Comment by lijun0326** [comment]
哇居然在issue里面看到了这个。。楼上大佬们对新加的壳有思路吗（@esterTion @bgli100

**Comment by esterTion** [comment]
完全没有，我cdb3看的ios版复制出来的反编译代码，没壳

**Comment by hanbim520** [comment]
加壳的各位有放出工具吗？
