### ISSUE TITLE
wierd field offset is being provided

### ISSUE THREAD

**Issue by mafusuke** [Perfare/Il2CppDumper#633]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Latest version

- Target Unity version
5.6.4

- Describe the issue
As you can see it on image below, I found fields started with "__Hotfix0_" which has weird offsets.
There is two fields that have 0x18 and same phenomena can be seen in many classes.
The name of these fields seems name of function, and I think it has something to do with xlua maybe.
When I accessed to 0x40 to check what is there, I got not String but pointer (not of function but maybe of object).
Any idea about these fields?
![image](https://user-images.githubusercontent.com/43488869/173402981-95984ffe-d091-4c41-97e6-9645d4c18ebb.png)

- Upload executable file and global-metadata.dat
send link to file later if needed

**Comment by masagrator** [comment]
In C# String is an object, so dunno what's wrong with that?

**Comment by mafusuke** [comment]
This is my explanation problem, sorry.
When I tried to read object as String using
https://github.com/frida/frida , I couldn't get meaningful one so that I thought of it as something related to Delegate Bridge , but this is my opinion and I'm not sure.

**Comment by Perfare** [comment]
1. They are static and non-static.
2. C# String is not std:string or char*, It's a struct containing Utf16 data, you can't use it directly.
