### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by xuhuanzy** [Perfare/Il2CppDumper#634]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
Il2CppDumper-v6.7.25

- 目标Unity版本
2018.4.35f1

- 问题描述
MetadataRegistration : 0
自动寻找失败，ida能够正常打开该so

- 上传可执行文件和global-metadata.dat

[so.zip](https://github.com/Perfare/Il2CppDumper/files/8894357/so.zip)

**Comment by Perfare** [comment]
如果你是dump的so文件，请不要对dump后的文件进行任何所谓的“修复”操作！

**Comment by heyacra** [comment]
Is here the right place to put my issue, or should I create a new one?

[Please.zip](https://github.com/Perfare/Il2CppDumper/files/8980312/Please.zip)
Version: Il2CppDumper-v6.4.12

![image](https://user-images.githubusercontent.com/108124353/175746994-5ebaa72d-59f9-4863-b195-728dc6a1b509.png)

**Comment by Perfare** [comment]
@heyacra Do not discuss here, please open a new issue.
