### ISSUE TITLE
The address is wrong.

### ISSUE THREAD

**Issue by melame1a** [Perfare/Il2CppDumper#635]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
5.0.4, 6.7.19

- Target Unity version
2018.4.23f1

- Describe the issue
The original libil2cpp.so is protected. So I analyzed the memory dumped libil2cpp.so and all the addresses are wrong.

- Upload executable file and global-metadata.dat
[so.zip](https://github.com/Perfare/Il2CppDumper/files/8908738/so.zip)

![00](https://user-images.githubusercontent.com/105432739/173815858-8da71b3e-67f2-45a2-bd2a-e422176d3f3c.png)
![01](https://user-images.githubusercontent.com/105432739/173815921-e967e535-949a-4582-afc9-459bd4f5912f.png)

**Comment by Perfare** [comment]
Game have obfuscation, please use https://github.com/Perfare/Zygisk-Il2CppDumper
