### ISSUE TITLE
Need help with dumping CODM

### ISSUE THREAD

**Issue by ArcyMods** [Perfare/Il2CppDumper#637]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
- v6.7.25

- Target Unity version
- 5.6.4p4

- Describe the issue
- So, i know that i can't dump CODM **v1.0.33** by auto mode because the game has all kinds of protection against dumping (refer to https://anticheatexpert.com/#/products/anti-cheat-android). I used your other project (https://github.com/Perfare/Zygisk-Il2CppDumper) and it can dump the game fine. But i was wondering, is it possible to dump the game if i have the right info? I searched through the game files in ida and found some interesting stuff:
```
qword_8D83358 is the pointer for the loaded metadata
sub_6BA81E4 is the loader function for the metadata

0x8D83340 is the metadata code registration
0x8D83348 is the metadata registration
```
If you could help me with dumping the game using the info i provided i'd gladly appreciate it. Thanks!

- Upload executable file and global-metadata.dat
(Because the zip file is bigger than 25MB i could only upload it as a link)
https://www.mediafire.com/file/hy5jrqxzjhn44st/CODM.zip/file

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected
