### ISSUE TITLE
Dumper stuck at Initializing metadata... forever

### ISSUE THREAD

**Issue by david8557** [Perfare/Il2CppDumper#638]
- Il2CppDumper version: 6.7.25

- Target Unity version: 2019.4.19f1

- Describe the issue: Dumper stuck at Initializing metadata... forever

- Upload executable file and global-metadata.dat: https://www39.zippyshare.com/v/ZqI4Jz0e/file.html

**Comment by Perfare** [comment]
I'm sorry that the file has expired and cannot be downloaded, but from your description, global-metadata.dat may be damaged or encrypted.
If you still have problems, you can consider opening a new issue and uploading the file again.
