### ISSUE TITLE
Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by acrops** [Perfare/Il2CppDumper#639]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本: Il2CppDumper-net6-v6.7.25

- 目标Unity版本: v2019.4.36f1

- 问题描述: Can't use auto mode to process file, try manual mode.

- 上传可执行文件和global-metadata.dat  libil2cpp.so+global-metadata.dat的资源大小压缩zip后超过上传限制的25MB，可否提供其他途径提交文件呢？

**Comment by Perfare** [comment]
你可以上传任何非网赚网盘然后这里贴出链接
