### ISSUE TITLE
Is it possible to dump attributes parameters?

### ISSUE THREAD

**Issue by fattakhovmarat** [Perfare/Il2CppDumper#64]
Hello. Thanks for your tool.
For example I have class like that:
```
public class Name // TypeDefIndex: 1000
{
	// Fields
	[JsonAttribute] // 0x1000A72
	public string Field1;
}
```
But [JsonAttribute] comes with parameter like [Json("f")].
Is it possible to dump attributes parameters?

**Comment by Perfare** [comment]
Goto 0x1000A72 you will find what you need, this can't be automatic, only manual.
