### ISSUE TITLE
Can't use auto mode to process file, try manual mode

### ISSUE THREAD

**Issue by edipo2s** [Perfare/Il2CppDumper#640]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
 6.7.25

- Target Unity version
 2020.3.22f1 (unity default resources file)
 2020.3.31f1 (data.unity3d file)

- Describe the issue
 With a GameGuardian dump returns a `ERROR: No symbol is detected` message followed by `Can't use auto mode to process file, try manual mode`.

- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/9011063/files.zip)

**Comment by Perfare** [comment]
Sorry to reply you now, considering that the game should have been updated, I don't know if you still have this problem. So if you still have problems, you can consider reopening an issue and uploading files to me.
