### ISSUE TITLE
错误：Index was outside the bounds of the array

### ISSUE THREAD

**Issue by lxgz12345** [Perfare/Il2CppDumper#642]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本    
v6.7.25

- 目标Unity版本    
未知

- 问题描述    
提示 Index was outside the bounds of the array

- 上传可执行文件和global-metadata.dat  
游戏是崩坏2，dat和so下载链接：https://lxgz.lanzouv.com/iJQvy079vsij

![QQ截图20220702215223](https://user-images.githubusercontent.com/51988982/177003948-e442532e-ae63-4b5f-98dc-5724005e5ee1.png)

**Comment by not-so-cool-anymore** [comment]
I am having a similar problem with my own game (I made it for research purposes). My metadata file is not obfuscated and the game is compiled with Unity 2020.1 and VS 2019 (to do the il2cpp build part). Did you find any solutions?

**Comment by Perfare** [comment]
游戏有保护
