### ISSUE TITLE
not working for fishing planet

### ISSUE THREAD

**Issue by JDNinja85** [Perfare/Il2CppDumper#647]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version == 6.4.12

- Target Unity version == not sure what this is? (i know unity but not sure what target version is or how to find it)

- Describe the issue == ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat == how/where?

**Comment by raspiduino** [comment]
> Upload executable file and global-metadata.dat == how/where?

Get the apk, unzip it, look into `lib`, then find the file `libil2cpp.so`, and drag it here into the comment box.

I don't remember exactly where I get `global-metadata.dat`, but it should be in the apk file, too.
