### ISSUE TITLE
 ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by guinhx** [Perfare/Il2CppDumper#648]
- Il2CppDumper version: 6.7.25

- Target Unity version: any

- Describe the issue: ERROR: Can't use auto mode to process file, try manual mode.

- Upload executable file and global-metadata.dat: https://drive.google.com/file/d/1CrimEZ5tlk7RGVYDLBj0i3EpPykOL7kf/view

I want to use the source code as study material to learn more about the systems used in the game above.
But I'm having this error above, I tested other tools but none could give me the complete source code.

**Comment by Perfare** [comment]
This tool does not decompile source code.
