### ISSUE TITLE
ERROR: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by MikaCybertron** [Perfare/Il2CppDumper#649]
- Il2CppDumper version: 6.7.25

- Target Unity version: 27 to 27.1

- Describe the issue:  can't dump the il2cpp, the error say was `System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.`

- Upload executable file and global-metadata.dat: https://drive.google.com/file/d/1UKToa-J6yLGmhk94D0pyG9j7W0Z-sn8n/view?usp=sharing

![image](https://i.imgur.com/GnalYTD.png)

**Comment by bluewave41** [comment]
You didn't read the output log.

`ERROR: This file may be protected.`

https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

**Comment by DarkPollux** [comment]
> You didn't read the output log.
> 
> `ERROR: This file may be protected.`
> 
> https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

How i can bypass the protection?
