### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by KingKong5147** [Perfare/Il2CppDumper#651]
Dear Perfare,

Firstly i would like to say Thank you for the awesome work you do for everybody in the community and everyone that use this marvelous tool! :)

-6.7.25 (Latest Version)

- Target Unity version is 27

- The issue im having is the following 
- Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 addr) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 71
   at Il2CppDumper.SectionHelper.FindMetadataRegistrationV21() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 256
   at Il2CppDumper.Macho64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 241
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 213
ERROR: An error occurred while processing.
Press any key to exit...

https://iosddl.net/40c13a571b64301c/Slime_Idle.7z

Thank you for your time

**Comment by thermos17** [comment]
这个问题你解决了吗，我也碰到同样的问题

**Comment by KK6684** [comment]
> 这个问题你解决了吗，我也碰到同样的问题

No, it would seem Perfare is busy. This issue still remains unsolved at this time.

**Comment by bluewave41** [comment]
https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Utils/SectionHelper.cs#L232

The value that comes out of this is wildly wrong. The sections in your file are 8 digits long and the 64 bit value located at that address is 13510798971045456 which is never going to be found.

I'll attempt some more digging and comparing to see what should happen here.

**Comment by KK6684** [comment]
I look forward to the solution.

Sent from my iPhone

On 25 Sep 2022, at 2:00 pm, Matthew Semeniuk ***@***.***> wrote:

﻿

https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Utils/SectionHelper.cs#L232

The value that comes out of this is wildly wrong. The sections in your file are 8 digits long and the 64 bit value located at that address is 13510798971045456 which is never going to be found.

I'll attempt some more digging and comparing to see what should happen here.

**Comment by thermos17** [comment]
> https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Utils/SectionHelper.cs#L232
> 
> 由此产生的价值是非常错误的。您文件中的部分长度为 8 位，位于该地址的 64 位值是 13510798971045456 永远不会被发现。
> 
> 我将尝试更多地挖掘和比较已知的好文件，看看明天会发生什么。

I will wait

**Comment by Perfare** [comment]
Closed because had the same issue.
