### ISSUE TITLE
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。

### ISSUE THREAD

**Issue by YK-hastur** [Perfare/Il2CppDumper#652]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
v6.7.25

- 目标Unity版本
未知

- 问题描述
Initializing metadata...
System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.MemoryStream.InternalReadInt32()
   在 System.IO.BinaryReader.ReadInt32()
   在 Il2CppDumper.BinaryStream.ReadPrimitive(Type type) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 95
   在 Il2CppDumper.BinaryStream.ReadClass[T]() 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 165
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 201
   在 Il2CppDumper.BinaryStream.ReadClassArray[T](UInt64 addr, Int64 count) 位置 C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:行号 209
   在 Il2CppDumper.Metadata.ReadMetadataClassArray[T](UInt32 addr, Int32 count) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 162
   在 Il2CppDumper.Metadata..ctor(Stream stream) 位置 C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:行号 89
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 126
   在 Il2CppDumper.Program.Main(String[] args) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 100

- 上传可执行文件和global-metadata.dat
[file.zip](https://github.com/Perfare/Il2CppDumper/files/9434807/file.zip)

**Comment by Perfare** [comment]
global-metadata.dat is corrupted or protected.
