### ISSUE TITLE
Problem with Crab Game

### ISSUE THREAD

**Issue by Xyndra** [Perfare/Il2CppDumper#653]
- Il2CppDumper version 6.4.12

- Target Unity version: unknown

- Describe the issue: I am trying to open the game "Crab Game" and it seems it isn't accessible
[GameAssembly and metadata](https://github.com/Perfare/Il2CppDumper/files/9452705/GameAssembly.zip)

**Comment by bluewave41** [comment]
>Il2CppDumper version 6.4.12

??? The latest version is 6.7.25. Yes, 7 not 4. Why are you using such an old version?

There are no errors in the latest version.
