### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by leonardo3dp** [Perfare/Il2CppDumper#655]
ERROR: Can't use auto mode to process file, try manual mode.

https://drive.google.com/drive/folders/1FyT1nzLOTDcwRzkJLSqxRDLmbhmBta4H?usp=sharing

**Comment by bluewave41** [comment]
So try manual mode: https://tomorrowisnew.com/posts/Finding-CodeRegistration-and-MetadataRegistration/

Open in Ghidra, auto analyze, wait for it to finish going. You can use Search > For Strings to find strings and right click, references, show references to and find references.
