### ISSUE TITLE
Enter CodeRegistration and MetadataRegistration

### ISSUE THREAD

**Issue by Venkata-sai-rishi** [Perfare/Il2CppDumper#656]
![Screenshot 2022-10-03 191533](https://user-images.githubusercontent.com/91658406/193593303-6908c8d7-fe90-4f8f-a366-35f0baad7aee.png)

Il2CppDumper version: Il2CppDumper-v6.7.25

How to find CodeRegistration and MetadataRegistration. To find Registration codes also unity_builtin_extra 
not exist in **C:\Users\Administrator\Downloads\PROClient_86\PROClient\PROClient_Data\Resources**
And I also tried so many methods from google also.

**Executable file and global-metadata.dat**
[https://drive.google.com/drive/folders/11g5m6GcM5xyIivjUGc3ydTH9Wx8Tj2TB?usp=sharing](url)

**Comment by Venkata-sai-rishi** [comment]
![Screenshot 2022-10-03 191533](https://user-images.githubusercontent.com/91658406/193593303-6908c8d7-fe90-4f8f-a366-35f0baad7aee.png)

How to find CodeRegistration and MetadataRegistration. To find Registration codes also unity_builtin_extra 
not exist in **'C:\Users\Administrator\Downloads\PROClient_86\PROClient\PROClient_Data\Resources**

Executable file and global-metadata.dat
[https://drive.google.com/drive/folders/11g5m6GcM5xyIivjUGc3ydTH9Wx8Tj2TB?usp=sharing](url)

**Comment by Perfare** [comment]
The address you provided cannot be downloaded, but I think the file is protected.
