### ISSUE TITLE
KeyNotFoundException when initializing metadata

### ISSUE THREAD

**Issue by CziterGaming** [Perfare/Il2CppDumper#657]
- Il2CppDumper version
6.7.25
- Target Unity version
unknown

I used Scylla to dump GameAssembly.dll because of obuscation. Even then Im getting KeyNotFoundException.
Looks like global-metadata.dat is not obfuscated as I see normal in-game strings inside.

![obraz_2022-10-09_031828292](https://user-images.githubusercontent.com/77675168/194733028-0fb5f002-5cdd-49ad-a013-a963143ae5c5.png)

GameAssembly + global-metadata:
[files.zip](https://github.com/Perfare/Il2CppDumper/files/9740552/files.zip)

**Comment by LabGuy94** [comment]
duplicate of my error

**Comment by DarkPollux** [comment]
same

**Comment by LabGuy94** [comment]
Metadata is obfuscated
