### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException error

### ISSUE THREAD

**Issue by DarkPollux** [Perfare/Il2CppDumper#659]
- Il2CppDumper version 6.7.25

- Target Unity version 2019.4.16f1

- Describe the issue: il2cppdumper doesn't work, I have no idea why. Please help. 

- [il2cpp and metadata](https://drive.google.com/drive/folders/1l1k09M-CJTe_ojrYSis1dpfBgEIQwRGs?usp=sharing)

`Initializing metadata...
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.ThrowHelper.ThrowKeyNotFoundException()
   в System.Collections.Generic.Dictionary2.get_Item(TKey key)
   в Il2CppDumper.Metadata.ProcessingMetadataUsage() в C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:строка 218
   в Il2CppDumper.Metadata..ctor(Stream stream) в C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:строка 124
   в Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 126
   в Il2CppDumper.Program.Main(String[] args) в C:\projects\il2cppdumper\Il2CppDumper\Program.cs:строка 100
Press any key to exit...`
`

**Comment by Perfare** [comment]
Corrupted or encrypted metadata.
