### ISSUE TITLE
Sequence contains no matching element 

### ISSUE THREAD

**Issue by KK6684** [Perfare/Il2CppDumper#661]
Hi,

I seem to having similiar issue as the topic on link below :

https://github.com/Perfare/Il2CppDumper/issues/651

Unity Version 29.

https://iosddl.net/5f53c293783b9118/Mighty_Doom.7z

Binary and Metadata have been attached.

Thanks,

**Comment by iAroc** [comment]
Any updates on this? Got the same problem on a new file. any way to contact @Perfare ? would even pay ya something for getting it bumped and fixed

**Comment by Perfare** [comment]
Closed because had the same issue.
