### ISSUE TITLE
Const fields don't have offsets

### ISSUE THREAD

**Issue by HorridModz** [Perfare/Il2CppDumper#663]
- Il2CppDumper version: 6.7.25

- Target Unity version: Unity Version 202, Il2cpp Version 27.1

- Describe the issue: I was curious why const fields don't have offsets (I'm pretty sure they can still be modified in memory, so I don't see why not). For example,
`private const int TOKEN_NONE = 0;` does not have an offset, while
`protected static int lastErrorIndex; // 0x0` does.
This probably isn't Il2cppDumper's fault, but I'm curious about it. It's also a little annoying because I believe const fields can still be modified in memory.

- Upload executable file and global-metadata.dat: The example was from Pixel Gun 3D 16.6.1, but it should occur on all games. I could not upload executable and metadata because the file size is too big.

**Comment by Perfare** [comment]
Constants have no offset, they are directly replaced with concrete values at compile time.
