### ISSUE TITLE
Dumper not working for Just Dance 2023 v1.0.1

### ISSUE THREAD

**Issue by ppng222** [Perfare/Il2CppDumper#666]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
- Using version v6.7.25

- Target Unity version
-Target Unity Version from Bundles is 2021.3.9f1

- Describe the issue
- Getting a key error when dumping to structs along with errors with dumping
<img width="783" alt="image" src="https://user-images.githubusercontent.com/76928655/203644882-1f012fc2-850c-49fa-b389-02d4e6e28d05.png">

- Upload executable file and global-metadata.dat
- https://www.dropbox.com/s/lm1j6hdvjjqz3nw/JDNext_Update_1.0.1.zip?dl=0

**Comment by tnsfk309** [comment]
girl decompress your nso

**Comment by masagrator** [comment]
> girl decompress your nso

il2cppdumer supports originally compressed files, so stop giving shitty advices

**Comment by tnsfk309** [comment]
> > girl decompress your nso
> 
> il2cppdumer supports originally compressed nso files, so stop giving shitty advices

OH really? then how in the fuck it also didnt work for me compressed but worked when it was decompressed!!! was it magic??

**Comment by masagrator** [comment]
your stupidity it seems
