### ISSUE TITLE
Cant dump League of Maidens dll

### ISSUE THREAD

**Issue by phantom54** [Perfare/Il2CppDumper#667]
- Il2CppDumper version : v6.7.25

- Target Unity version : 2021.1.0.53423 (2021.1.0.2281647)

- Describe the issue : Cant dump

- Upload executable file and global-metadata.dat :

old:
https://pixeldrain.com/u/6RhabNV2
https://mega.nz/file/P5gDwaJA#BcXdBQ11y8yEDv7bvKItTqHylzD_Q4m-djtQW-JNg1Y

new:
https://pixeldrain.com/u/Nvpsfcj6
https://mega.nz/file/PkhhhZrR#wU2tn4nuSBJ1ZrTcoYA52o7XzCzrXvkbuEsfyPov7dQ

**Comment by Perfare** [comment]
protected file.
