### ISSUE TITLE
[PC]Can't use auto mode

### ISSUE THREAD

**Issue by TheXWolf** [Perfare/Il2CppDumper#668]
Attempting to dump attached IL2Cpp DLL, tried through the exe as well as admin cmd prompt. Values given were location of GameAssembly.dll, global-metadata.dat, and the output folder per git. Game is Soulstone Survivors.
Yes, I tried the tomorrowisnew but could not find the right data, not sure I had the right tools honestly. 
[SS.zip](https://github.com/Perfare/Il2CppDumper/files/10145462/SS.zip)

**Comment by Perfare** [comment]
Did not encounter any errors on the file you provided.
