### ISSUE TITLE
Error: An error occurred while processing.

### ISSUE THREAD

**Issue by Asaki83** [Perfare/Il2CppDumper#671]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本: Il2CppDumper-v6.7.25

- 目标Unity版本: Unity 2020.3.26f1

- 问题描述: 我在unity上随便写了个代码在IOS环境下打包，出来的IPA包解压后得到无后缀的可执行文件和globalmetadata.dat，输入到il2cppdumper后显示以下结果：
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: 序列不包含任何匹配元素
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 Il2CppDumper.Macho64.Search() 位置 C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:行号 203
   在 Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) 位置 C:\projects\il2cppdumper\Il2CppDumper\Program.cs:行号 226
ERROR: An error occurred while processing.
Press any key to exit...

- 上传可执行文件和global-metadata.dat：https://drive.google.com/drive/folders/1daESAjgp9aNOo8PstUxCW7HsJ-90hxKx?usp=share_link

**Comment by zljkevin** [comment]
same problem

**Comment by Perfare** [comment]
可执行文件是UnityFramework，你觉得主程序可能只有66kb吗？
