### ISSUE TITLE
Metadata File Supplied is not supported Version 

### ISSUE THREAD

**Issue by jokerart06** [Perfare/Il2CppDumper#676]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Dumper: 6.7.19 GUI

- Target Unity version
2019.4.11f1

- Describe the issue
When i try to dump the game via gg to get the original il2cpp.so and global metadata it says the following error in il2cpp dumper metadata file supplied is not supported version. 

- Upload executable file and global-metadata.dat
![image](https://user-images.githubusercontent.com/54529030/213131832-c7102349-21f7-48ad-92a2-83fc0bac72bc.png)
https://mega.nz/file/eipShbAR#GJGXuGgHbX6rFCmeYJL-vaElSoRF1bO1BQ75wE_AkhI
https://mega.nz/file/72YDBaYA#K2m5JZ_vtvdo89JEht8b-69T12qiXqodAFra9AbxfzM

-Game Link for more info:
https://play.google.com/store/apps/details?id=com.odin.kingdomlegends.gplay

**Comment by Perfare** [comment]
This is a version 0 that does not exist, so this global-metadata.dat should be encrypted.
