### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode. 

### ISSUE THREAD

**Issue by fabian0150** [Perfare/Il2CppDumper#677]
- Il2CppDumper version: 
v6.4.12.0

- Target Unity version
v2020.3.38f1

- Describe the issue
Sadly, i tried all my best to create a dump but I always get the same error - no matter what - maybe you can help please?

- Upload executable file and global-metadata.dat
[stumble-guys-files.zip](https://github.com/Perfare/Il2CppDumper/files/10446331/stumble-guys-files.zip)

- Additional info
The unity game is called "stumble guys" 

Thanks in advance!

**Comment by Perfare** [comment]
Why are you using an older version of Il2CppDumper?
