### ISSUE TITLE
ll2Cpp binary file ????

### ISSUE THREAD

**Issue by DogancanYr** [Perfare/Il2CppDumper#679]
What is this .

**Comment by DogancanYr** [comment]
I couldn't do it . Can you post a working video of the program?

**Comment by Vex186** [comment]
bunu da yapamıyorsan

**Comment by DogancanYr** [comment]
Maybe I'm doing it right, but this is not the right program.

**Comment by AppleCanon** [comment]
What if it's Android?

**Comment by DogancanYr** [comment]
How ?
I tried using it to open the File on the computer
