### ISSUE TITLE
__mod_init_func got removed from the game, Sequence contains no matching element

### ISSUE THREAD

**Issue by iAroc** [Perfare/Il2CppDumper#681]
- Il2CppDumper version
- Il2CppDumper v6.7.25

- Target Unity version
- 29

- Describe the issue
Cant dump the game, because in the newest update, they removed the __mod_init_func 
if i bypass that and provide CodeRegistration and MetadataRegistration on my own, it still fails because it gets some really weird pointers (like pCodeRegistration.genericMethodPointers is 4503599711270136)

- Upload executable file and global-metadata.dat
- https://sx-pokego.xyz/global-metadata.dat
- https://sx-pokego.xyz/UnityFramework

CodeRegistration : 4f3f220
MetadataRegistration : 50b4e10

If i can support your work with a donation to speed up the fix, feel free to conact me, or tell me how i can contact you

**Comment by Perfare** [comment]
I have found a temporary workaround for this problem.
I'm currently doing some research to determine why this is happening.
I'll update it in a few days anyway.
same problem #651 #661

**Comment by iAroc** [comment]
Heyya. Sounds good.
if you have already a workaround, mind if you can share that or push it, so i can pull it and try it out?

If you want to contact me for some testing or otherwise help (if i can) tell me

**Comment by KK6684** [comment]
Hopefully this gets resolved soon :) are you able to show workaround in the meantime?..

**Comment by KK6684** [comment]
Just out of curiosity is the whole tool going to be updated for this?.. how do I implement this fix as the tool is auto?.

**Comment by Perfare** [comment]
@KK6684  You can download the build version here.
https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

**Comment by HTGAzureX1212** [comment]
This issue is still present with v6.7.40, which seems to contain the fix that closed this issue.
