### ISSUE TITLE
Fields have [DebuggerBrowsable(0)] not show in DnSpy

### ISSUE THREAD

**Issue by ngoalong123** [Perfare/Il2CppDumper#682]
Fields have [DebuggerBrowsable(0)] show in dump.cs only. not show in DnSpy.

**Comment by Perfare** [comment]
check the dnspy options
Decompiler - Show hidden compiler generated types and methods
Also worth mentioning that it is [CompilerGenerated] not [DebuggerBrowsable] that affects it。

**Comment by ngoalong123** [comment]
It worked thank you so much

Vào 19:12, Th 3, 7 thg 2, 2023 Perfare ***@***.***> đã viết:
