### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by 28598519a** [Perfare/Il2CppDumper#683]
- Il2CppDumper版本
Il2CppDumper-net6-v6.7.31

- 目标Unity版本
UnityFS.....5.x.x.2019.4.25f1

- 问题描述
```
Initializing metadata...
Metadata Version: 24.4
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 24.4
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
0
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 0x4BCCC7C
Input MetadataRegistration: 0x4BCCC78
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 194
```

- 上传可执行文件和global-metadata.dat
[global-metadata.dat](https://drive.google.com/file/d/1pUj5TYEX9zaVE6sWLkTeFsL4h_QQ3-rR/view?usp=share_link)
[libil2cpp.so](https://drive.google.com/file/d/1iXYHyYuI7vWemoNwrCYDxuJk7K1zV0pN/view?usp=share_link) -v7a
[APK](https://drive.google.com/file/d/1FaPGDfyTBgtZ9xSDLDQC6unykmagrriK/view?usp=share_link)

(話說有試過Zygisk-Il2CppDumper，然而什麼都沒生成。。。)

**Comment by Perfare** [comment]
请不要使用任何所谓的“修复”工具修复so，把dump后的so和地址直接丢给Il2CppDumper

**Comment by 28598519a** [comment]
> 请不要使用任何所谓的“修复”工具修复so，把dump后的so和地址直接丢给Il2CppDumper

還是不行，一樣得到Arithmetic operation resulted in an overflow

![](https://user-images.githubusercontent.com/33422418/217249237-bbf75d6e-1762-4f2b-a8a3-5e4e7ec9051b.png)

`    -r --raw(Optional)                    Output Raw Lib and Not Rebuild It`
