### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by rvpoochen** [Perfare/Il2CppDumper#684]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本 v6.7.31

- 目标Unity版本 2020.3.38f1

- 问题描述  ERROR: Can't use auto mode to process file, try manual mode.

- 上传可执行文件和global-metadata.dat
- https://pan.baidu.com/s/1oGYA4a0CEmGl831Jup0k3Q?pwd=ie95
[and_2.zip](https://github.com/Perfare/Il2CppDumper/files/10684581/and_2.zip)

**Comment by Perfare** [comment]
data部分数据应该是加密了

**Comment by akchama** [comment]
@Perfare Sorry I don't know chinese, I have a similar issue, what is the solution here?
