### ISSUE TITLE
stringliteral.json address 跟 ida offset 對不上

### ISSUE THREAD

**Issue by 28598519a** [Perfare/Il2CppDumper#685]
此問題延續自 [issues/683](https://github.com/Perfare/Il2CppDumper/issues/683)

- Il2CppDumper版本
Il2CppDumper-net6-v6.7.32

- 目标Unity版本
UnityFS.....5.x.x.2019.4.25f1

- 问题描述
Dump.cs給的offset沒問題，可是stringliteral.json的address與ida的offset對應不上
![](https://user-images.githubusercontent.com/33422418/217688421-76f7e5dc-2aab-490f-973d-4e40f61098f3.png)
![](https://user-images.githubusercontent.com/33422418/217688472-62d47436-5b3c-43cb-9d8b-a417a4ed262e.png)

- 上传可执行文件和global-metadata.dat
[global-metadata.dat](https://drive.google.com/file/d/1XP1LAxiFhNUKb3MkWiZ8UEZUm9zOL7lt/view?usp=share_link)
[libil2cpp.so](https://drive.google.com/file/d/1YiPEbAKuT-Ym1NctuX0YjHORnfIbIdMa/view?usp=share_link) -raw-v7a

**Comment by Perfare** [comment]
在Il2CppDumper和ida中都使用dump后的未修改的so
按以下步骤在ida载入dump后的so
1. 修改so的Program Header把所有段的p_offset修改为p_vaddr的值，p_filesz修改为p_memsz的值
2. ida载入时勾上“Manual load”，输入dump时的地址
