### ISSUE TITLE
What loader/debugger NSO support was tested with?

### ISSUE THREAD

**Issue by Kein** [Perfare/Il2CppDumper#686]
I successfully dumped il2cpp data for NSO with metadata. However, the python script fails to do its work properly, despite reporting finished.
I'm using IDA 7.7 and [nxo64.py](https://github.com/reswitched/loaders)

Is there something wrong or missing in the setup/chain?

**Comment by Perfare** [comment]
There is a serious problem with this script, it does not feed back the correct base address to ida, you may consider modifying it manually or find other solutions.
#114

**Comment by Kein** [comment]
Fair enough, thanks.
