### ISSUE TITLE
Support auto modes for 2022.2.7f1

### ISSUE THREAD

**Issue by AndnixSH** [Perfare/Il2CppDumper#690]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: v6.7.37

- Target Unity version: 2022.2.7f1

- Describe the issue:
Auto modes isn't supported for ARM64, x86 and x86_64 compiled with Unity 2022.2.7f1, only ARMv7 supported. Can you support it, most importantly ARM64? x86 and x86_64 are made specifically for chromebooks

- Upload executable file and global-metadata.dat
[test.zip](https://github.com/Perfare/Il2CppDumper/files/10816607/test.zip)

**Comment by Perfare** [comment]
all supported.
