### ISSUE TITLE
Unable to read beyond 

### ISSUE THREAD

**Issue by Alessakrendly** [Perfare/Il2CppDumper#692]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.38

- Target Unity version 
- 
- 2020.3.37f1

- Describe the issue

![Screenshot_2023-02-24-16-06-47-732-edit_com radinc csharpshell](https://user-images.githubusercontent.com/124020522/221115352-34d8f98b-ca9b-42e2-8c2f-0d50a6e135cc.jpg)

- Upload executable file and global-metadata.dat

https://www.mediafire.com/file/9k8ojs64opql95k/dump.zip/file

**Comment by Perfare** [comment]
Your dump file is incomplete.
