### ISSUE TITLE
新版的 Il2CppDumper.exe 不能反编译了吗

### ISSUE THREAD

**Issue by 350030173** [Perfare/Il2CppDumper#693]
能不能像之前那样可以使用如下工具反编译 Il2CppDumper.exe
https://github.com/dnSpy/dnSpy

**Comment by Perfare** [comment]
虽然我不知道你为什么要反编译Il2CppDumper.exe，但是dnSpy早在2020年就已经停止更新，并不支持selfcontained打包的.net应用，推荐使用ILSpy。
