### ISSUE TITLE
Succses dump but file dll emty

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#694]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.38

- Target Unity version 2021.3.8f1

- Describe the issue

- sussesfully dump but file dll is emty 

- Upload executable file and global-metadata.dat

[Dump file](https://www.mediafire.com/file/hx3371b2euhat49/dump1.zip/file)

**Comment by Perfare** [comment]
Dummy dll does not contain method body.
