### ISSUE TITLE
Bug with arm64 binaries

### ISSUE THREAD

**Issue by ZahirSher** [Perfare/Il2CppDumper#7]
Tried to decrypt arm64 (mach-o) and it gave me following errors:

```
Select Mode: 1. Manual 2.Auto
ERROR: Unable to process file automatically, try to use manual mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 39
Press any key to exit...
```

**Binary + MetaData for you to test:** http://www8.zippyshare.com/v/uF4e3Aa4/file.html

**Comment by Perfare** [comment]
This is not a bug, auto mode unable to work properly under all circumstances, you need to find the pointer by yourself and use manual mode.
In the file you provided, input 10199CEF8 and 1019EAC60 program will work

**Comment by ZahirSher** [comment]
@Perfare Can you give me brief instructions to find the addresses manually? Would help me a lot 👍

**Comment by ZahirSher** [comment]
Nevermind, figured it myself :) Thank you~
