### ISSUE TITLE
某Il2Cpp游戏dump提示错误

### ISSUE THREAD

**Issue by WuMe-sicx** [Perfare/Il2CppDumper#702]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
- Il2CppDumper-net6-win-v6.7.40

- 目标Unity版本 (可以不填)

- 问题描述
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
- 上传可执行文件和global-metadata.dat
[il2cpp文件下载](https://oss121.oss-cn-hangzhou.aliyuncs.com/il2cpp%E6%96%87%E4%BB%B6.zip)

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper/blob/master/README.zh-CN.md#error-this-file-may-be-protected
