### ISSUE TITLE
Dump error  given key

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#703]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 
- 6.7.40

- Target Unity version (optional)
- UnityFS5.x.x2020.3.45f1

- Describe the issue
![Screenshot_2023-03-22-09-21-41-818-edit_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/226773288-f4ad029d-9499-4241-87fd-6a3578bd234c.jpg)

- Upload executable file and global-metadata.dat
- [Dump.zip](https://www.mediafire.com/file/vhfm67xykj22k6k/dump.zip/file)

**Comment by Perfare** [comment]
global-metadata.dat is encrypted.
