### ISSUE TITLE
Cant use Auto Mode ti prosses try a manual

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#704]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
- 6.7.40

- Target Unity version (optional)
- 2017.4.3f1

- Describe the issue 
![Screenshot_2023-03-28-07-04-44-488-edit_com google alessa](https://user-images.githubusercontent.com/102419809/228078396-c6dc96d8-fb00-4eab-b221-ac115d5aa382.jpg)

- Upload executable file and global-metadata.dat
- [Dump.zip](https://www.mediafire.com/file/kf718z9v61n759c/dump.zip/file)

**Comment by Perfare** [comment]
Did not encounter any problems with the files you provided.
