### ISSUE TITLE
Cant create dummy file

### ISSUE THREAD

**Issue by QPLAYid** [Perfare/Il2CppDumper#709]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 
- 6.7.40

- Target Unity version (optional) 
- 2020.3.33f1c2

- Describe the issue
-  cant create dummy file
![Screenshot_2023-04-05-11-20-23-600_com google alessa](https://user-images.githubusercontent.com/102419809/229964933-cbcc7b3a-2d55-48f0-a4f2-9b7f159d5865.jpg)

- Upload executable file and global-metadata.dat
- https://www.mediafire.com/file/kf718z9v61n759c/dump.zip/file

**Comment by Perfare** [comment]
Which specific version are you using in the release? Or did you compile it yourself?

**Comment by QPLAYid** [comment]
> Which specific version are you using in the release? Or did you compile it yourself?

Source code (zip)

**Comment by Perfare** [comment]
So the problem is with your compilation tools,
Il2CppDumper itself does not have this error.
