### ISSUE TITLE
New file format?

### ISSUE THREAD

**Issue by CRC32EX** [Perfare/Il2CppDumper#71]
This apk does not contains `global-metadata.dat`.
I think this is new format of Unity.

Could you support new format?

[apk download](http://www.mediafire.com/file/6aweqsc6dcx2y15/com.nintendo.zaga_1.0.1.apk/file)

**Comment by Perfare** [comment]
#63

**Comment by m1m2m3mr** [comment]
@esterTion how can we mod game without global-metadata.dat?

**Comment by ForyModz** [comment]
> https://gist.github.com/esterTion/7fde10f2cb02722079d5fd9335ad5848
> 
> There's nothing about unity, but a technique from Cygames.

@esterTion how can i use this to extract the global-metadata.dat from coneshell?

**Comment by ForyModz** [comment]
@esterTion hey man im sorry im a little bit of a noob in this. Where exactly are you running this from? This looks like its being run from a linux machine but its an .exe file, im a little confused with this

**Comment by esterTion** [comment]
I'm on msys64, I think it should compile on all platform. 
And not sure how vs will handle this, not tested.

**Comment by ForyModz** [comment]
@esterTion yeah i got it working thanks :)

**Comment by 241d2** [comment]
@ForyModz can you give me compiled tool?
Mine failed to compile
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	coneshell	d:\project\c++\coneshell_extract_metadata\coneshell\coneshell\coneshell_extract_metadata.cpp.cpp	16	
Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	coneshell	d:\project\c++\coneshell_extract_metadata\coneshell\coneshell\coneshell_extract_metadata.cpp.cpp	18	

Thanks
