### ISSUE TITLE
PrincessConnectReDive (JP) 7.2.0版本

### ISSUE THREAD

**Issue by krulci** [Perfare/Il2CppDumper#710]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
v6.7.40
- 目标Unity版本 (可以不填)
2021.3.20f1
- 问题描述
公主连结DMM版今天刚从mono换成il2cpp，7.2.0暂时好像还没上线，月中应该就会正式上线
他的global-metadata.dat也是和马娘一样embed在GameAssembly.dll中
我已经用CE dump了，且去除了Header。没dumped的原档超过25mb了
- 上传可执行文件和global-metadata.dat
[GameAssembly_dump.zip](https://github.com/Perfare/Il2CppDumper/files/11162046/GameAssembly_dump.zip)
[global-metadata.zip](https://github.com/Perfare/Il2CppDumper/files/11162048/global-metadata.zip)

**Comment by Perfare** [comment]
你提供的dll的大小太小，看起来是裁剪过的。
从你的描述看原本的dll并没有加密，你应该使用原本的dll而不是这个裁减过的dll。

**Comment by krulci** [comment]
> 你提供的dll的大小太小，看起来是裁剪过的。 从你的描述看原本的dll并没有加密，你应该使用原本的dll而不是这个裁减过的dll。

原本的dll包含了global-metadata.dll
我提供的GameAssembly.dll和global-metadata.dat是启动游戏后用Cheat Engine从内存dump出来的

**Comment by krulci** [comment]
以下是使用上面提供的内存dumped的dll和dat
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (193): %1 is not a valid Win32 application.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...
```

**Comment by krulci** [comment]
以下是用原本的dll和内存dumped的dat
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (126): The specified module could not be found.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...
```

**Comment by Perfare** [comment]
上传原本的dll给我看看

**Comment by krulci** [comment]
> 

https://drive.google.com/file/d/1aJ93IekL7dk0s5D-OwfAwAC8tbyV9Nv1/view?usp=share_link

**Comment by Perfare** [comment]
dll引用了其他dll，把Il2CppDumper放到dll所在目录再运行看看

**Comment by krulci** [comment]
> dll引用了其他dll，把Il2CppDumper放到dll所在目录再运行看看

![image](https://user-images.githubusercontent.com/52474054/230703686-38c1bf26-3e0a-4b3e-93f2-587816b4279e.png)
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (1114): A dynamic link library (DLL) initialization routine failed.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...
```

**Comment by Perfare** [comment]
重新从内存中dump一份dll，大小至少要有源文件那么大（78163968字节），之前你dump的dll不完整，缺少data部分

**Comment by krulci** [comment]
> 

可是他原本游戏目录内就没有global-metadata.dll
这东西是在GameAssembly.dll内
dump出来的两个大小合起来就等于GameAssembly.dll

**Comment by krulci** [comment]
> 重新从内存中dump一份dll，大小至少要有源文件那么大（78163968字节），之前你dump的dll不完整，缺少data部分

我把dump出来的两个文件发你
确实去除CE头后
小的那个文件（就是我改成global-metadata.dat）的那个在`AF 1B B1 FA`之前是还有一大段被我去掉的
但是当我把这一段接到GameAssembly.dll后面的时候，他还是没法用这个跑
https://drive.google.com/file/d/1215fFXt82Z8RjnuEsGdclcytlw3sdUiS/view?usp=share_link

**Comment by krulci** [comment]
![image](https://user-images.githubusercontent.com/52474054/230704873-5dfda2d4-d96e-4da4-bec0-aa0317cb7fc3.png)

**Comment by krulci** [comment]
我尝试把两个文件的CE头都去了合并起来保存成GameAssembly.dll
然后把小的那个只保留AF 1B B1 FA以后的保存成global-metadata.dat
确实il2cppdumper可以跑
但是还是没法初始化DLL
错误如下
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (1114): A dynamic link library (DLL) initialization routine failed.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...
```

**Comment by Perfare** [comment]
把两个文件拼接在一起就是完整的dll了，不过因为section没有对应到内存需要手动修改下
链接: https://pan.baidu.com/s/1QZXxFQO1lli36VClaXlVeA?pwd=25nc 提取码: 25nc

**Comment by krulci** [comment]
> 把两个文件拼接在一起就是完整的dll了，不过因为section没有对应到内存需要手动修改下 链接: https://pan.baidu.com/s/1QZXxFQO1lli36VClaXlVeA?pwd=25nc 提取码: 25nc

Section这个要怎么对应至内存？
确实成功Dump了

**Comment by krulci** [comment]
有点好奇dumped的和原本的差了啥？
另外这DLL有办法修复成可以直接用游戏跑吗？
目前会得到`Failed to load il2cpp`

**Comment by Perfare** [comment]
section修改部分就是把PointerToRawData和SizeOfRawData的值改成VirtualAddress和VirtualSize的值
区别就是原本的dll是加密的，内存中是解密的状态
直接dump的肯定不能直接用，你至少需要修复iat表

**Comment by krulci** [comment]
> section修改部分就是把PointerToRawData和SizeOfRawData的值改成VirtualAddress和VirtualSize的值 区别就是原本的dll是加密的，内存中是解密的状态 直接dump的肯定不能直接用，你至少需要修复iat表

感谢，IAT不知道怎修复。
虽然是另一个库cpp2il的（因为做mod要用到这个库），但是看il2cpp的逻辑和il2cppdumper差不多
IL2Cpp.Init初始化data的时候，
可是因为这些我都是从内存dump的，他是
```
data = new Union { dummy = datapoint };
```
然后因为
```
public long klassIndex => (long)dummy;
```
所以想问下，这种情况下Il2CppTypeDefinition[]的大小就不对了
```
metadata.typeDefs[il2CppType.data.klassIndex]
```
这种在il2cppdumper是怎么处理的？

**Comment by krulci** [comment]
> section修改部分就是把PointerToRawData和SizeOfRawData的值改成VirtualAddress和VirtualSize的值 区别就是原本的dll是加密的，内存中是解密的状态 直接dump的肯定不能直接用，你至少需要修复iat表

找到个特定的x64dbg版本
虽然没法玩整加载游戏，但是GameAssembly.dll加载进来了
但是用Scylla做IAT Repair，替换原来的之后，游戏依然`Failed to load il2cpp`
