### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: 707111

### ISSUE THREAD

**Issue by RasyaDhika** [Perfare/Il2CppDumper#714]
- Il2CppDumper-win-v6.7.40

- When i put libil2cpp.so and metadata it will show this
-i think the metadata is the problem because when i put random files to Il2cpp and i put same metadata file it will give same output like this
- ![image](https://user-images.githubusercontent.com/111063178/233778467-959445b4-935b-4bc0-a1b1-ad272ea4a8b8.png)

- the files :
- https://file.io/cuj98p5lgsYe

**Comment by Perfare** [comment]
Your file has been deleted, but from your error message, global-metadata.dat has been encrypted.
