### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by WhiteZerooooo** [Perfare/Il2CppDumper#728]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
v6.7.40
- 目标Unity版本 (可以不填)
2020.3.34
- 问题描述
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
- 上传可执行文件和global-metadata.dat
[dump.zip](https://github.com/Perfare/Il2CppDumper/files/11642940/dump.zip)

**Comment by Perfare** [comment]
> ERROR: This file may be protected.
