### ISSUE TITLE
No Mode Works

### ISSUE THREAD

**Issue by Mr-Tomahawk** [Perfare/Il2CppDumper#73]
http://prntscr.com/l2spmu
what happens on manual mode

http://prntscr.com/l2spst
What happens on any auto mode

http://prntscr.com/l2soca
What I'm using in IDA for manual mode
CodeRegistration: 102FD3413
MetadataRegistration: 10015D03C

https://www.mediafire.com/file/9ee6oouupk19d8q/Binary_and_Metadata.rar/file
My files that I'm using

My friend says he's doing the exact same thing as me and it isn't working. any help?

**Comment by Perfare** [comment]
supported after e85c8bc7cfa9a3662fa7e21ebc7162b087bc0d56
