### ISSUE TITLE
SCP:SL metadata issue

### ISSUE THREAD

**Issue by Classy-paper** [Perfare/Il2CppDumper#740]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
- latest

- Target Unity version (optional)
- 2021.3.17f1

- Describe the issue
- SCP:SL's metadata file doesn't seem to be liking il2cppdumper, when you run it;  The given key 'kIl2CppMetadataUsageInvalid' was not present in the dictionary. When you view it in hexed.it you see that the first 4 bytes are fine but the fifth byte is 17, checked a UC thread and it said to change it to 18 and that actually used to work for me on SCP:SL but it doesn't rn, if it helps  they don't have an etc file like other unity games, don't think it matters though.

- Upload executable file and global-metadata.dat

metadata - https://www.mediafire.com/file/k1u3ypn9bi88o5w/global-metadata.dat/file
gameassembly.dll - https://www.mediafire.com/file/5f2ftn1337g1qx3/GameAssembly.dll/file

**Comment by CaretakerBlayze** [comment]
same problem to me

**Comment by CaretakerBlayze** [comment]
any possible solutions???

**Comment by Perfare** [comment]
It looks like the metadata is encrypted.
