### ISSUE TITLE
Metadata 解析错误

### ISSUE THREAD

**Issue by gamert** [Perfare/Il2CppDumper#744]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本 
- v6.7.4
- 目标Unity版本 (可以不填)
2018.4.36f1
- 问题描述
1. fieldDefaultValuesDic = fieldDefaultValues.ToDictionary(x => x.fieldIndex);重复的key异常；
2. parameterDefaultValuesDic = parameterDefaultValues.ToDictionary(x => x.parameterIndex);重复的key异常；x.parameterIndex出现大量-65535,；
3. ProcessingMetadataUsage中metadataUsageDic的key出现0或7，导致未初始化的值。
- 上传可执行文件和global-metadata.dat
[proj_src_il2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/12407177/proj_src_il2cpp.zip)

**Comment by Perfare** [comment]
可以认为Metadata已加密
