### ISSUE TITLE
Metadata supplied not valid

### ISSUE THREAD

**Issue by Eraea** [Perfare/Il2CppDumper#749]
- Il2CppDumper version : 6.7.40

- Unity Version: From inspecting Libunity.so, it seems the game runs on version 2018.4.16f1

- Issue:
When dumping, the error "Metadata supplied is not valid" occurs, which I think would mean the metadata file version is a newer one.

- Uploaded metadata and executable
[Uploaded Files](https://www.mediafire.com/file/72k9fdpfwtlyilv/wrdump.7z/file)

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-metadata-file-supplied-is-not-valid-metadata-file
