### ISSUE TITLE
Support for metadata 19

### ISSUE THREAD

**Issue by ZahirSher** [Perfare/Il2CppDumper#75]
![capture](https://user-images.githubusercontent.com/8087235/47978081-ad5e1180-e0f6-11e8-8152-6cde4d590d04.PNG)

Binary: https://www83.zippyshare.com/v/wd8HrimN/file.html
Metadata: https://www83.zippyshare.com/v/6wUnfPPq/file.html

**Comment by AndnixSH** [comment]
I think the first version of Il2CppDumper work with metadata 19 https://github.com/Jumboperson/Il2CppDumper
I need to complie it again

**Comment by Perfare** [comment]
This has been supported.
