### ISSUE TITLE
Original Offset Addition +/-1

### ISSUE THREAD

**Issue by ZahirSher** [Perfare/Il2CppDumper#8]
Noticed it when I decrypt iOS Binaries (v16, 23 tested), it either +/- to the original offset. 
What I mean by this is let us say,

**Original Offset is :** 11455
**The Decrypted Offset Shows the Instruction to be in :** 11456 or 11454

This causes the IDA to not rename the function names when script is loaded because its below or above the instruction. 

**Here is a v16 binary for you to test:**
http://www8.zippyshare.com/v/rrOhfBam/file.html
(fat binary)

**Comment by ZahirSher** [comment]
@Perfare I just tried the "manual" mode for the binary above and some other binaries and I confirm this error is no more the issue. It only doesnt work with Auto Mode. Ill close this issue. Thanks!

**Comment by Perfare** [comment]
I find a bug in v16 32bit macho, fixed in baaa6350c358ae359397d4a96a6ecaa78dc2f1aa
