### ISSUE TITLE
Weird offsets when dumping iOS il2cpp binary (on any Auto settings)

### ISSUE THREAD

**Issue by BowDown097** [Perfare/Il2CppDumper#80]
So the game I'm modding has both an iOS and Android version, and I'm currently trying to figure out iOS mods. I noticed that the offsets in the iOS dump.cs are quite different from those in the Android dump.cs, not because of location, but because of how they appear.

`public float GetRaceTime(); // 0x4C5A38`
Here's a float, GetRaceTime, and its offset in the Android dump.cs.

`public float GetRaceTime(); // 0x101049900`
Here's the same exact float and its offset in the iOS dump.cs.

I can modify whatever's at the Android offset perfectly, and save it, and the mod will appear in-game. This is different with iOS, though; I've tried doing the last 8, 7, 6 numbers and nothing appeared in-game, and I've tried doing everything after the "0x" and that didn't work because 0x101049900 is not a valid offset in the file in the first place. So, I believe the offsets it's displaying are either incorrect or a bit off, at least on every "Auto" setting, but I haven't tried it with Manual.

**Comment by Mila432** [comment]
offsets for ios are accurate and the game bin looks like arm64

**Comment by BowDown097** [comment]
> offsets for ios are accurate and the game bin looks like arm64

hm really? what would the real offset be then for that float?

**Comment by Mila432** [comment]
0x101049900

**Comment by Perfare** [comment]
This is something confusing. The offset in dump.cs actually is RVA(relative virtual address), if you modify the game during runtime or view binary file in ida, you need this. If you want to modify binary file with hex editor, you actually need is a file offset. In Android, RVA and file offset are the same in most cases. 
The current file offset will only be output in the dummy dll.

**Comment by BowDown097** [comment]
Ah, ya, that's what I was wondering. Maybe a possible thing to add would be to include RVA as well as the file offset?

**Comment by Perfare** [comment]
Now you can go to the dummy dll and see the file offset, I will add the file offset to dump.cs later.

**Comment by Archangel004** [comment]
Try cracking the binary and opening it with IDA, usually the offset specified is the offset for the arm64 portion of the app. 

If your binary is arm64 only, then relative position and file offset will be different by 0x100000000 (aka just remove the first 1). However, if the binary is FAT (i.e armv7 + arm64), armv7 data will cause this to 
shift.

You can fix this by thinning it with `lipo -thin arm64 binaryname -o binaryname_thinned` or you can open IDA, open the binary in it, then type G and copy paste the offset. The file offset is also shown in IDA at the bottom left (just above the output window, theres a small bar which shows your relative offset as well as file offset.

Moreover, if you are trying to modify files during runtime (such as with a debugger), you also need to take care of the ASLR slide. 
If you are using GDB, you can find the slide by "info address _mh_execute_address" or if you use LLDB, the command is "image list". In GDB, it replies with the value, in LLDB, there is a huge output, but the value you need is right at the top. It shows the location of the app you're debugging as well as an offset (in brackets usually). Make sure to remove the 1 (or subtract 0x100000000) from the slide, then add that slide to the offset from dump.cs.

This will be your address for the function for that run. If you restart the app, the slide will change and you need to change it.

If you need any more help, lemme know

**Comment by esterTion** [comment]
May be irrelevant, are you making an alternative ipa package?
I previously wrote [a ms tweak](https://gist.github.com/esterTion/9eb39738b51b85d6d7c42d769c89c071), which works fine with these offsets. 
Also that way I don't need to care about machine code modifying. 

Just a reference, if you are making patch then I don't have knowledge on those.
