### ISSUE TITLE
ERROR: The necessary section is missing.

### ISSUE THREAD

**Issue by IamSanjid** [Perfare/Il2CppDumper#83]
Idk what's the issue. Used the latest version.
Screenshot:
![image](https://user-images.githubusercontent.com/38256064/50692243-75733c00-105d-11e9-8db8-b58bbeaf5df7.png)
Files:
[Files.zip](https://github.com/Perfare/Il2CppDumper/files/2727270/Files.zip)

**Comment by Perfare** [comment]
Protected file
