### ISSUE TITLE
自己手动找CodeRegistration和MetadataRegistration

### ISSUE THREAD

**Issue by dqzg12300** [Perfare/Il2CppDumper#88]
怎么分辨自己找到的是对的呢？我找到下面这个函数，CodeRegistration吗？
如果是下面这个函数，地址那里我是不是填写0xF418
int __fastcall sub_F418(int a1, int a2)
{
  int v2; // r8
  int v3; // r7
  int (**v5)(); // [sp+0h] [bp-F0h]
  int v6; // [sp+1Ch] [bp-D4h]
  int v7; // [sp+20h] [bp-D0h]
  int v8; // [sp+2Ch] [bp-C4h]
  char dest; // [sp+30h] [bp-C0h]
  void *v10; // [sp+B0h] [bp-40h]
  int v11; // [sp+B4h] [bp-3Ch]
  int v12; // [sp+B8h] [bp-38h]
  int v13; // [sp+BCh] [bp-34h]
  int v14; // [sp+C0h] [bp-30h]

  v2 = a1;
  v3 = a2;
  __fun_a_18(0, 0);
  memset(&v6, 0, 0xB0u);
  strncpy(&dest, "libil2cpp.so", 0x7Fu);
  v10 = &unk_F14B64;
  v8 = 1;
  v12 = 2;
  v13 = 4;
  v14 = 5;
  v6 = v2;
  v7 = v3;
  v11 = dword_1900C;
  sub_F680(&v5);
  v5 = &off_18D88;
  if ( sub_F7CC(&v5, &unk_19C48, 1062) )
    __arm_a_1(&v6, &v5);
  sub_F6FC(&v5);
  return 0;
}

**Comment by Perfare** [comment]
直接在程序里输入，能跑就是对的，不能跑就是错的
