### ISSUE TITLE
处理64位Mach-O文件时出错

### ISSUE THREAD

**Issue by lijun0326** [Perfare/Il2CppDumper#9]
ERROR: Unable to process file automatically, try to use manual mode.
   在 Il2CppDumper.Program.Main(String[] args)
使用的是已经脱壳的il2cpp编译的某u3d游戏的二进制文件（定语好多啊2333）
链接: http://pan.baidu.com/s/1c2IkPPY 密码: cyyn

**Comment by Perfare** [comment]
请使用手动模式
#7

**Comment by lijun0326** [comment]
手动模式的话，如何找坐标呢？
刚才试了下IDA里面搜MetadataCache::Register，但是没东西诶qwq

**Comment by lijun0326** [comment]
刚才按照 #7 找到了地址，顺便放个64位iOS的教程方便后人查看
丢进IDA，搜索名叫InitFunc_1的函数，在他的正上面的那个函数里面就有你要找的地址了
![qq 20170629195054](https://user-images.githubusercontent.com/17663689/27686199-4d3235c4-5d04-11e7-81db-e5db7b5887a1.png)

**Comment by Perfare** [comment]
fd72d51d7c6e98a22f4ff106df4afda621594a52 已添加自动模式

**Comment by KingKong5147** [comment]
@https://github.com/Perfare how do you fully use this in manual mode? I know from the translation you have to find a pointer in the init_funct address but not all unity games has the 3 different addresses in that function are you able to help ?
