### ISSUE TITLE
所有模式都失败，so和.dat都没有加密，麻烦看一下谢谢！

### ISSUE THREAD

**Issue by Coinswang** [Perfare/Il2CppDumper#90]
PlusSearch.FindCodeRegistration方法中
我下载源码调试了一下：发现
 if (il2Cpp.ReadUInt32() == methodCount)这个判断，读取的值和方法数量不一致，导致无法dump
[资源.zip](https://github.com/Perfare/Il2CppDumper/files/2790750/default.zip)

**Comment by Perfare** [comment]
global-metadata.dat文件有问题

**Comment by Perfare** [comment]
提供一下Unity的版本号我确认一下，不过我猜测global-metadata.dat本身是加密的，可能是dumper有误，或者本身global-metadata.dat就是修改过的

**Comment by Coinswang** [comment]
https://rexdl.com/android/antistress-relaxation-toys-apk.html/

我现在在外面，不是太方便发送给您，这个是apk的下载链接。麻烦您了

**Comment by Perfare** [comment]
已修复，现在载入后会询问是否2018.3以上版本，选是即可正常dump
