### ISSUE TITLE
Some errors in dumping

### ISSUE THREAD

**Issue by LaxusiC** [Perfare/Il2CppDumper#91]
Same ios game, it worked 3 days ago but they updated the game and now I can't dump the game anymore. I tried all modes, none of them work and i'm using latest version v3.6.0

https://imgur.com/tP68F9D

Binary and metadata file: https://1drv.ms/u/s!Au2Ksx_NGkHWjlV-_QWhr1kdOEZv

**Comment by Perfare** [comment]
This game Unity version should greater than or equal to 2018.3 .When asked "Is the Unity version greater than or equal to 2018.3?", please select yes.

**Comment by LaxusiC** [comment]
I did select yes, but still can't dump?
