### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by GUDROIDBR** [Perfare/Il2CppDumper#92]
Initializing il2cpp file...
Applying relocations...
CodeRegistration : 27bb018
MetadataRegistration : 27bb050
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   em Il2CppDumper.Program.Main(String[] args) na C:\projects\il2cppdumper\Il2CppDumper\Program.cs:linha 151
Press any key to exit...

**Comment by Perfare** [comment]
Need files
