### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by WezXBL** [Perfare/Il2CppDumper#93]
This tool has never actually worked. For me atleast anyway. I open the correct files, Binary, then metadata.dat and the tool errors everytime after selecting any mode. & When it does create some dll files, they are obfuscated extremely making editing impossible & long.

This tool should be to the standards of the APK Multitool for android users but seems like people are creating tools for the easy to abuse OS`s than for IOS.  This tool has been updated quit often but the issues from 1.0 still remain.

**Comment by Mila432** [comment]
dont tell me you load the encrypted bin..

**Comment by WezXBL** [comment]
> dont tell me you load the encrypted bin..

Actually i think i may have lol. How do i decrypt it? When i tried this before with a jailbreak tweak it didnt work.
