### ISSUE TITLE
Latest version of tool doesn't work anymore

### ISSUE THREAD

**Issue by ColdMeekly** [Perfare/Il2CppDumper#96]
Heya!

Version 3.4 of your tool works flawlessly for the binaries that I use, however when I tried to use the latest version I got the same issue as referenced in #94. I can confirm the file is not corrupt because version 3.4 correctly parses everything and it does its job.

I will do some testing later to see at which exact version it stopped working.

**Comment by Thorusus** [comment]
Same for me, however, this is the first time I'm using the dumper so I don't know about previous versions.

https://drive.google.com/file/d/1KGx7yrP2Zv0jfrXuk39GzwBXVirxtCWp/view?usp=sharing

Press 2 then 4

**Comment by Perfare** [comment]
@Thorusus one bug in 64 bit, has been fixed.

**Comment by Thorusus** [comment]
I confirm that it works now. You're awesome 🥇
